### ISSUE TITLE
How could I get humidity with MQTT 

### ISSUE THREAD

**Issue by uzumaki20398** [kiwi-cam/homebridge-broadlink-rm#100]
could I use MQTT to get humidity?

As air-condition type I can get temp
but with Humidifier Dehumidifier type
I can't get humidity

this is my code of air-condition 
"name": "AC",
"type": "air-conditioner",
"maxTemperature": 32,
"minTemperature": 16,
"defaultCoolTemperature": 27,
"defaultHeatTemperature": 22,
"mqttURL": "mqtt://192.168.1.50",
"mqttUsername": "username",
"mqttPassword": "password",
"mqttTopic": "mytopic"
"data": {
                        "off": "code",
                        "cool16": {code},
},

**Comment by kiwi-cam** [comment]
The humidity functionality is very new. I have plans to add MQTT and file based readings - like the AC accessory.  I'll update this issue when I get it progressing.

**Comment by kiwi-cam** [comment]
I've just added MQTT support in homebridge-broadlink-rm-pro@4.3.6-beta.7.

Any chance you could update the BETA and test for me?  I don't have an MQTT source to test with.

**Comment by uzumaki20398** [comment]
Sorry I’m busy last week. 

I’ve update the BETA. 
and add MQTT username, password,topic
But nothing to chance
My humidity still show 0%.

My code
`{ `
`"name": "Humidifier Dehumidifier",`
`"type": "humidifier-dehumidifier",`
`"mqttURL": "mqtt://192.168.1.51",`
`"mqttUsername": "username",`
`"mqttPassword": "password ",`
`"mqttTopic": "HumidityTopic",`
`"showLockPhysicalControls": false,`
`......`
`}`

**Comment by kiwi-cam** [comment]
That's surprising.  Could you add `"debug": true, ` to your config too and share the logs?

You should see something like `[Broadlink RM] Dehumidifer onHumidity (70)` posted frequently with other logs around it too.

**Comment by uzumaki20398** [comment]
I add “debug”:true,
And Publish 60 to my humidity Topic. 

Still showing 0
Log
`[11/9/2020, 8:58:11 AM] [Broadlink RM] [ERROR] Humidifier Dehumidifier No MQTT value could be found for topic with identifier "humidity".`
`[11/9/2020, 8:58:11 AM] [Broadlink RM] Humidifier Dehumidifier onHumidity (0)`
`[11/9/2020, 8:58:11 AM] [Broadlink RM] Humidifier Dehumidifier getCurrentState: 0`

**Comment by uzumaki20398** [comment]
I noticed that if I publish something to Topic
appear something woring in Log
`TypeError: this.updateTemperatureUI is not a function
    at HumidifierDehumidifierAccessory.onMQTTMessage (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/humidifier-dehumidifier.js:340:10)`
    `at MqttClient.<anonymous> (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/accessory.js:342:12)`
    `at MqttClient.emit (events.js:315:20)`
    `at MqttClient._handlePublish (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/mqtt/lib/client.js:1162:12)`
    `at MqttClient._handlePacket (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/mqtt/lib/client.js:351:12)`
    `at work (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/mqtt/lib/client.js:283:12)`
    `at Writable.writable._write (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/mqtt/lib/client.js:294:5)`
    `at doWrite (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/readable-stream/lib/_stream_writable.js:428:64)`
    `at writeOrBuffer (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/readable-stream/lib/_stream_writable.js:417:5)`
    `at Writable.write (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/readable-stream/lib/_stream_writable.js:334:11)`

**Comment by uzumaki20398** [comment]
I change humidifier-dehumidifier.js
  remove "null"
and success
 // Read humidity from mqtt
    ` if (config.mqttURL) {` 
     `  const humidity = this.mqttValueForIdentifier('humidity');` 
     `  this.onHumidity(null,humidity || 0);` 
`  ` 
      ` return;` 
   `  }`

after
 // Read humidity from mqtt
    ` if (config.mqttURL) {` 
     `  const humidity = this.mqttValueForIdentifier('humidity');` 
     `  this.onHumidity(humidity || 0);` 
`  ` 
      ` return;` 
   `  }`

**Comment by uzumaki20398** [comment]
I change "humidifier-dehumidifier.js" something 
line 340
` this.updateTemperatureUI();`
after 
 ` this.updateHumidityUI ();`

then I publish new humidity.
Finally,  succeed.

**Comment by kiwi-cam** [comment]
Nice catch. Obviously I manipulated the temperature code to work with Humidity... and missed one reference.

I've just pushed homebridge-broadlink-rm-pro@4.3.6-beta.8. Could you just confirm I've got the fix right in there and I'll push a new release?

**Comment by uzumaki20398** [comment]
I update 4.3.6-beta8
After testing , humidity is normal with MQTT. 
Thank you.

**Comment by kiwi-cam** [comment]
Fixed in 4.3.6
