### ISSUE TITLE
rf code

### ISSUE THREAD

**Issue by hassman12** [kiwi-cam/homebridge-broadlink-rm#101]
hi,
due to the issue that RF signals can't be viewed via the "learn frequency" I'm trying to sniff the codes from and arduino with 433 receiver.
what code type can i use?
can i use are data like :4532,868,336,264...
or binary: 10100101101011000100101100001011
or decimal: 2779532043

thank you

**Comment by ben-callaway** [comment]
What 433 receiver are you using, I've been tempted.

**Comment by hassman12** [comment]
A regular rf 433 arduino receiver like this one:
https://randomnerdtutorials.com/rf-433mhz-transmitter-receiver-module-with-arduino/

And does anybody know a library thats capable of parsing the correct form?

This plugin documents specify “hex code”. But I can’t find a library which output hex code (and converting the binary to hex is not the same)

Thanks!

**Comment by kiwi-cam** [comment]
RF Learning should now be fixed in 4.3.8
