### ISSUE TITLE
Disable Speed on Fan, Just Turn ON/OFF

### ISSUE THREAD

**Issue by masterfordev** [kiwi-cam/homebridge-broadlink-rm#103]
Hello @kiwi-cam, i have a vocolinc outlet which i selected that it is a fan in the Home app (screenshot 1). The curious about this is that it doesn't show the speed, it only allows you to “on/off” (screenshot 3) you know if is possible to do that also on the fan devices of your plugin? But keeping the swing mode and rotation direction. 

![image](https://user-images.githubusercontent.com/29960705/97936293-510b4800-1d38-11eb-9ead-3960b697d575.jpeg)

![image](https://user-images.githubusercontent.com/29960705/97936314-63858180-1d38-11eb-894f-df3bd774e3de.jpeg)

![Screen](https://user-images.githubusercontent.com/29960705/97936119-cfb3b580-1d37-11eb-878f-bd17de7db701.png)

**Comment by Faisalthe01** [comment]
Hey @masterfordev, I think that is one of the limitation in Home app. The way is to touch on the tile to make it turn on/off and touch and hold for more controls, i guess that's how fan accessory work in HomeKit

**Comment by masterfordev** [comment]
Maybe the fan should be set as outlet. Will check that. Thanks!

**Comment by Faisalthe01** [comment]
I got myself a fan with remote 

With Swing Mode enabled and Direction Mode Off, that swing button sure looks ugly 😀 

![9FF67716-3786-4538-88FA-DD02F12847F0](https://user-images.githubusercontent.com/62862684/99870654-04c17280-2c29-11eb-9c35-95f2ecf5a69a.png)

**Comment by masterfordev** [comment]
Haha i dont like that oscillate button, so i used the rotate direction button for enable/disable the swing mode 😅 ![Fan](https://user-images.githubusercontent.com/29960705/99871043-bebacf00-2b94-11eb-8937-441e0ad016a6.png)

**Comment by Faisalthe01** [comment]
Lol, does it ever used to look like this? Dyson Fan Homebridge Screenshot, they are using FanV2 like this Broadlink.

![EDD11436-B7ED-44A9-B7CF-656357D68079](https://user-images.githubusercontent.com/62862684/99871243-f1180b00-2c2c-11eb-8b74-72bc80ea5507.jpeg)

**Comment by masterfordev** [comment]
Omg no. But that looks better 😅

**Comment by Faisalthe01** [comment]
That screenshot is from iOS 13, maybe it got changed to ugly in iOS 14

**Comment by Faisalthe01** [comment]
@masterfordev 

This is the Dyson’s fan file
https://github.com/joe-ng/homebridge-dyson-link/blob/master/DysonLinkAccessory.js

Let me know if you figure it out. I’m a bit busy with my newborn baby

**Comment by masterfordev** [comment]
> @masterfordev
> 
> This is the Dyson’s fan file
> https://github.com/joe-ng/homebridge-dyson-link/blob/master/DysonLinkAccessory.js
> 
> Let me know if you figure it out. I’m a bit busy with my newborn baby

When you said "newborn baby" you are talking literally or you mean the new fan? 😅

**Comment by Faisalthe01** [comment]
lol no an actual baby and the fan is for the baby

**Comment by masterfordev** [comment]
Haha congrats for the new member of the house. I want one too, but I mean the fan. Lol 😂

I was looking here where I live but I didn't find someone to sell them.

**Comment by newt10** [comment]
If you have a fan connected to a smart outlet, then you will not be able to get the swing and rotation direction functionality. This plugin does support them if you have a fan with IR remote and the broadlink IR blaster

**Comment by masterfordev** [comment]
> If you have a fan connected to a smart outlet, then you will not be able to get the swing and rotation direction functionality. This plugin does support them if you have a fan with IR remote and the broadlink IR blaster

I know that. I think you dont understood what I was asking for. I want the button with just turn on/off (without speed).

**Comment by newt10** [comment]
Ah! What is the "type" of your accessory under config.json?
If you are using fan then this is natively supported in the plugin, you need to 
set "hideRotationDirection": true, "hideSwingMode": true

**Comment by newt10** [comment]
@masterfordev - if this is resolved, let us know and we can close the issue.

**Comment by masterfordev** [comment]
Nope. If i disable that options in the config, the speed still enable. I want just turn on/off. With no speed.

**Comment by Faisalthe01** [comment]
Use it as a switch and then change the icon to fan

**Comment by masterfordev** [comment]
> Use it as a switch and then change the icon to fan 

Great idea! 😂 but i want swing mode too lol 😂

**Comment by Faisalthe01** [comment]
Wait until iOS 15, Apple might realise their mistake 😜

**Comment by masterfordev** [comment]
> Wait until iOS 15, Apple might realise their mistake 😜 

Lol will ask that exclusive option for me 🤣
