### ISSUE TITLE
Error code received on Aircondition

### ISSUE THREAD

**Issue by Spanishu** [kiwi-cam/homebridge-broadlink-rm#104]
I have just seen on my logs on Homebridge the following error message
`node:11563) UnhandledPromiseRejectionWarning: AssertionError: [CONFIG ERROR]  You need to provide a hex code for the following temperature:
        { "temperature30": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
        or provide the default temperature:
         { "temperature30": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
    at AirConAccessory.getTemperatureHexData (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:308:7)
    at AirConAccessory.sendTemperature (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:268:48)
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:245:14
(node:11563) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)`

Here is my config.json
`{
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "accessories": [
                {
                    "name": "Learn IR",
                    "host": "192.168.1.155",
                    "mac": "78:0f:77:87:f0:b8",
                    "type": "learn-code"
                },
                {
                    "name": "Aire Despacho",
                    "type": "air-conditioner",
                    "host": "192.168.1.155",
                    "mac": "78:0f:77:87:f0:b8",
                    "turnOnWhenOff": false,
                    "ignoreTemperatureWhenOff": true,
                    "pseudoDeviceTemperature": 27,
                    "autoCoolTemperature": 26,
                    "autoHeatTemperature": 23,
                    "autoSwitch": "A/C Auto Switch",
                    "temperatureUpdateFrequency": 300,
                    "minTemperature": 10,
                    "maxTemperature": 28,
                    "disableLogs": true,
                    "data": {
                        "on": "26004c0271380e290d2a0e0e0e0d0d0f0d2a0d0e0e0e0e290e290e0d0f280e0e0e0e0e290e290e0d0f280e290e0e0e0e0e290d0e0f0d0f280e0d100c0f0c0e0e0e0d0f0d0e0d0f0d0e0d0f0d0e0d0e0e0e0d0f0d0e0d0f0d0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f0d0e0d0f0d0e290e290e0d0f0d0e0e0e290d0e0e290e0e0e0d0f0d0e0d0e0e0e0d0e290e290e0e0e290e290e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e290e0e0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f280d0f0e290e0e0e290e0001aa71380e290e290e0e0e0d0e0e0e290e0d0f0d0e290e290e0e0e290e0d0e0e0e290e290e0d0f280e2a0e0d0e0e0e290d0e0f0d0e290e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d100c100b100c0f0c100c0f0c0e0e0d0e0e0e0d0e0e0e0d0e0d0f0d0e0d0f0d0e0d0f0d2a0f28100c0f0c0e0e0d2a100c0c2a100c100b0d0f0d0e0d0f100c0c2b0f28100b10271027100c0f0d0f0c0f0c100c100b100c0f0d0f27100c100c0f0c0f0d0f0c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0c100c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0c100c0f0d0f0c0f0d0f0c0f0c100c100b100c100c0f0c100b100c0f0d0f0c0f0d0f0c0f0c100c0f0c100c100b100c0f0d0f0c100b100c0f0d0f0c0f0c10280f0c1027100c0f2810000d0500000000000000000000",
                        "off": "26004c0272360f280f290f0c0f0c100c0f280f0d0f0c0f280f28100c0f280f0c100c0f280f280f0d0f280f280f0c100c0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f290f0c0f0c100c0f0c100c0f280f280f0d0f0c0f0d0f0c0f0d0f280f280f0c10280f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f2810280f280f280f0c0f28100c0f280f0001a973360f2810280f0c0f0d0f0c0f280f0d0f0c0f280f28100c0f280f0d0f0c0f280f280f0d0f280f280f0d0f0c0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f2810280f0c0f0d0f0c0f0d0f0c0f280f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0f280f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f280f0c0f0d0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c10280f280f280f280f0c0f290f0c0f280f000d0500000000000000000000",
                        "cool21": {
                            "data": "2600bc0170390e2b0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d0f0e2b0d0f0e2b0d2b0e0e0e2b0d2c0d2b0d2c0d2b0e0e0e0f0d2b0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d2b0e2b0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d2b0e0e0e0f0d0f0d0f0e0e0e0f0d0003cc71390d2c0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d2c0d0f0d2b0e2b0d0f0e2b0d2b0e2b0d2b0e2b0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d2c0d2b0e0e0e0f0d0f0d2b0e0f0d2b0e0f0d2b0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d0f0e2b0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e2b0d2b0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e2b0d0f0e2b0d2b0e2b0d0f0e2b0d2b0e000d0500000000000000000000"
                        },
                        "cool22": {
                            "data": "2600bc0170390e2b0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d0f0e2b0d0f0d2c0d2b0e0e0e2b0d2c0d2b0d2c0d2b0e0e0e0f0d2b0e0e0e0f0d0f0e0e0e0e0e0f0d2b0e2b0d2b0e2b0d0f0f0d100d0f0d0d0f0f0d100d0d0f0d0f0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0d100d0f0d0d0f0f0d100d0f0d0f0d0f0e0f290f0d100d0f0d0f0d0f0d100d0f0003ca73370f2a0f0d0f0d0f0d0f2a0f0d0f0d100d0f0d0f2a0f0d0f290f2a0f0d0f2a0d2b0f2a0f290f2a0f0d0f0d0e2b0f0d0e0e0e0f0f0d0f0d0f0d100d0d0f0f0d0e0e0e0f0d0f0f0d0e0f0d0f0d0f0f0d0f0e0d2b0e0e0e0f0d0f0d2c0d2b0d0f0e0f0d0f0d0f0e2b0d2b0e0e0e2b0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d2b0e2b0d0f0d2c0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d2c0d2b0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0d0f0e2b0d2b0e2b0d2c0d2b0d0f0e2b0d2b0e000d0500000000000000000000"
                        },
                        "cool23": {
                            "data": "2600bc0170390e2b0d0f0d0f0e0f0d2b0d0f0e0f0d0f0d0f0e2b0d0f0d2b0e2b0d0f0e2b0d2b0e2b0d2b0e2b0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d0f0e0f0d2b0e2b0d2b0e2b0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d0f0e0e0e0003cc71390d2b0e0f0d0f0d0f0e2b0d0f0d0f0e0e0e0f0d2b0e0f0d2b0e2b0d0f0d2c0d2b0d2c0d2b0d2c0d0f0d0f0e2b0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d2b0e2b0d0f0e0e0e0f0d2b0e2b0d2b0e0f0d2b0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d0f0e2b0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e2b0d2b0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d2c0d2b0e2b0d000d0500000000000000000000"
                        },
                        "cool24": {
                            "data": "26004c0271370f280f280f0d0e0d0e0e0e290e0e0e0d0e290e290e0e0e290e0d0e0e0e290e290e0e0e290e290e0d0e0e0e290f0d0e0d0e290e0e0e0d0e0e0f0c0e0e0e0d0f0d0f0c0e0e0e0d0f0d0e0d0f0d0e0d0e0e0f0c0f0d0f0c0f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0e0d0f0d0e0d0f0d0e0d0f280f0d0f0c0f0d0f0c0f0d0f280f280f0c0f290e290f0c0f0d0f0c0f0d0f0c0f280f280f0d0f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0d0e0d0f0c0f0d0e0e0e0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0d0e0d0f0c0f0d0f0d0e0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f290e290f0c0f0d0e0d0e290f280f290f0001a971380e290e290e0e0e0d0e0e0e290e0d0e0e0e290e290e0d0e2a0e0d0e0e0e290e290e0d0e2a0e290e0d0e0e0e290e0d0e0e0e290e0d0e0e0e0d0e0e0e0e0d0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e290e0d0e0e0e0e0d0e0e0d0e2a0e290e0d0e0e0e0d0e0e0e0d0e0e0e290e0d0e0e0e0d0e0e0e0d0e290e2a0e0d0e290e290e0e0e0d0e0e0e0d0e0e0e290e290e0e0e290e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0e0d0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0f0d0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0e0d0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e290e290e0e0e0d0e0e0e290e290e290e000d0500000000000000000000"
                        },
                        "cool25": {
                            "data": "26004c027236102710280f0c100b100c0f28100c0f0c10271027100c0f28100b100c0f281027100c0f281027100b100c0f28100c0f0c1027100c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0c1027100c0f0c100c0f0d0f0c0f281027100c0f0c100c0f0c100c0f0c1027100c0f0c100c0f0c100c0f281027100b10280f28100b100c0f0d0f0c0f0d0f271027100c0f28100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f280f28100b100c0f0d0f2710280f280f0001a973360f281027100c0f0c100c0f28100b100c0f281027100b10280f0c100c0f281027100b102710280f0c100c0f28100b100c0f28100b100c100b100c0f0c100c0f0d0f0c0f0c100c0f0d0f0c0f0c100c100b100c100b100c100b100c1027100b100c100b100c100b10280f280f0c100c0f0c100c0f0c100c0f28100b100c0f0c100c0f0c102710280f0c10271027100c0f0c100c0f0c100c0f281027100c0f280f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c10271027100c0f0c100c0f281027102710000d0500000000000000000000"
                        },
                        "cool26": {
                            "data": "26004c0271370f280f290e0d0f0c0f0d0f280f0d0f0c0f280f280f0d0f280f0c0f0d0f280f280f0d0f280f280f0c0f0d0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0e0d0f0d0e0d0f280f0d0f280f0c0f0d0f0c0f0d0f0c0f280f290e0d0f280f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0e290f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0e0e0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0e0e0f280f0d0e290f280f0c0f0d0f280f280f0001a972370f280f290e0d0f0d0f0c0f280f0d0f0c0f280f280f0d0f280f0d0f0c0f280f280f0d0f280f280f0c100c0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0f0c0f0d0f0c0f280f0d0f280f0c0f0d0f0c0f0d0f0c0f290f280f0c0f280f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f290f0c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f280f0d0f280f280f0c0f0d0f280f280f000d0500000000000000000000"
                        },
                        "cool27": {
                            "data": "26004a0270390d2a0e292a0c0e0e0e2a0d0f0c0f0d2a0d2a0d0f0c2b0d0e0d100d290e290d100c2a0d2a0d0f0d0f0d290d0f0d0f0c2a0e0e0d0e0d0f0d0f0c100d0e0c0f0d0e0c100d0f0c0f0d0f0d0e0d0e0d0f0e0e0d0f0c0e0d0f0d0f0d290d0f0e0d0d0f0d0f0c100d290d2b0d0e0d0e0c100d0e0d2a0d0f0c2b0d0e0d0f0c0f0d100c0e0d2a0d2b0d0f0d290d2a0d0f0c100d0f0d0e0d0f0c0f0d0f0c0e0d2a0d100c0f0c100c0f0c100d0e0d0e0c0e0e0f0d0f0d0f0c0f0d0f0d0e0d0f0c0c100f0c0e0d0f0d0f0c0f0d0f0d0e0d0e0e0f0c0f0d0e0d0f0e0e0c0e0d100c0e0d0f0d0f0d0e0d0e0d100c0f0d0e0d0e0d0f0d0e0d0f0d0e0d100d0d0d100c0e0c100d0e0d0f0d0f0c0e0e0f0d0f0d0e0c100d290d0f0d2a0d2a0d0e0d0f0d2a0c2b0d0001ab71380d2a0d2a0d100c0f0c100b2b0d0f0e0d0d2a0e290d0e0e2a0d0e0d0f0c2b0d2a0d0f0c2b0d2a0d0e0d0f0d2a0d0f0c0f0d2a0d100c0f0c0f0d0e0d100d0d0d0f0d0f0c0f0d0e0d0f0d0e0d0f0d0e0d100c0e0d0f0d0e0c110c0e0d2a0d0f0d0e0d100d0d0c100d2a0d2a0d0f0d0e0d0e0e0e0d2a0d100d290d0e0d0f0d0e0d0f0d0f0d290d2b0d0e0d2a0d2a0d0f0d0e0d0f0d0e0c100d0e0d0f0d0e0d2a0d0f0d0e0d100c0f0c0f0d0e0d100d0d0d0f0d0e0d0f0d0f0d0e0d0e0d0f0d0e0d0f0d0f0c0f0d0e0d0f0d0e0d0f0d0f0c100c0e0d0f0d0f0c0f0d0e0d0f0d0f0c100c0f0d0e0d0e0d0f0d0f0d0e0d0f0c100d0d0d0f0d0e0d0f0d0e0e0e0d0e0d0f0d0e0d0f0e0d0d0f0d0e0e0e0d0e0d0f0d2a0e0e0c2b0d2a0d0e0d100c2a0e290d000d05000000000000000000000000"
                        },
                        "cool28": {
                            "data": "26004c0272370e290e290f0c0e0e0e0d0e290e0e0f0c0f290e290f0c0e290f0d0e0d0f280f290e0d0e290f280f0d0e0d0e290f0d0e0d0f290e0d0e0e0e0d0e0e0e0d0e0d0f0d0e0d0f0d0e0d0f0d0e0e0e0d0f0d0e0d0e0e0e0d0e0d0f0d0f0c0f290f0c0f0d0e0d0e0e0e0d0e290f280f0d0f0c0f0d0e0d0e0e0f280f280f0d0f0c0e0e0e0d0e0e0f280f280f0c0e2a0e290f0c0f0d0f0c0f0d0e0d0f0d0f0c0e0e0f280f0c0f0d0f0c0e0e0f0c0e0e0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0e0e0f0c0e0e0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f290e290f280f0c0f0d0f280f280f0001a972370f280f280f0d0f0c0f0d0f280f0d0f0c0f280f280f0d0f280f0c0f0d0f280f280f0d0f280f280f0c0f0d0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0f0c0f0d0f0c0f0d0f280f280f0c0f0d0f0c0f0d0f0c0f280f290f0c0f280f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f28100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0d0f0c0f0c100c0f280f280f280f28100c0f0c10280f280f000d0500000000000000000000"
                        },
                        "heat22": {
                            "data": "26004c0273360f280f28100c0f0c100c0f27100c0f0d0f2710280f0c1027100c0f0d0f271027100c10271027100c0f0d0f27100c0f0c1027100c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c100c0f0c100c0f0c0f0d0f0c100b100c100c0f0c0f0d0f280f0c100c0f0c100c0f0c1027100c0f0c100c0f0d0f0c0f281027100b100c0f0c100c100c0f0c100c0f0c100c0f280f28100b100c0f0d0f0c0f0d0f271027100c0f28100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f280f28100c0f27100c0f0c10280f280f0001a9733610271027100c0f0c100c0f28100c0f0c0f281027100c0f280f0c100c0f281027100c0f2710280f0c100c0f28100b100c1027100b100c0f0c100c0f0d0f0c0f0c100c0f0c100c0f0c100c100b100c0f0c100c100c0f0c100b100c0f28100b100c0f0d0f0c0f0d0f280f0c100c0f0c100c0f0c10271027100c0f0c100c100b100c0f0d0f0c0f0d0f0c0f281027100c0f0c100c0f0d0f0c0f281027100c0f27100c0f0c100c0f0c100c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0c100c100b100c100b100c100c0f0c100b100c100b100c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0c100c100b100c0f0c100c100b100c100b100c100b100c100b100c0f0c100c0f281027100c0f28100b100c0f28102710000d0500000000000000000000"
                        },
                        "heat23": {
                            "data": "26004c0271370e290e2a0d0e0f0d0d0e0f280d0f0d0e0d2a0e290e0e0d2a0f0d0d0e0d2a0f280e0e0d2a0d2a0d0f0d0e0d2b0c0f0d0e0d2a0e0e0d0e0e0e0d0e0d0f0d0e0e0e0d0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0d2a0f0d0d0e0e0e0d0e0e0e0d2a0d0f0d0e0d0f0d0e0d2a0d2b0e280e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d2a0d2a0d0f0d0e0f0d0d0e0d0f0d2a0d2a0d0e0e2a0d0e0d0f0d0e0f0d0d0e0d0f0d0e0f0d0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0e0d0d0f0d0e0d0f0d0e0d0e0f0d0d0f0d0e0d0e0e0e0d0f0e0d0d0f0d0e0d0f0e0d0d0f0d0e0d0f0d0e0d0f0d0e0f0d0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0f0d0d0e0d0f0d0e0d2a0d2a0f0d0d0e0e290e290e0001ab70390d2a0d2a0d0f0d0e0d0f0d2a0d0e0d0f0d2a0d2a0d0e0e2a0d0e0d0e0e2a0d2a0e0d0d2a0d2a0f0d0d0f0d2a0e0d0d0f0d2a0f0c0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0f0e0d0d0e0d0f0d0e0d0f0d0e0d0f0d2a100b0d0f0d0e0d0f100c0c2a100c0d0e0d0f0e0e0d2a10271027100c0f0c0d0f0f0c100c0c0f0d0f0f0c0d0f0f280f28100b100c100b100c0d0e10280f27100c0d2a100c0c0f0d0e0d0f0d0f0f0c100c0c0f0e0e0f0c0d0f0c0f0d0f0e0d0d0e0d0f100b0d0f0d0f0f0c100c0c0f100b0d0f0d0e0d0f100c0f0c0e0e0f0c0e0e0d0e0d0f0e0d100c0f0c0e0e0e0d0e0e0f0c0e0e0f0c0e0d100c100c0f0c100c0e0d0e0e0f0c100c0f0c100c0e0d100c0f0c0e0e0f0c100c0f281027100b100c1027102710000d0500000000000000000000"
                        },
                        "heat24": {
                            "data": "260010021007573b0b620a10100f0715092b0c120a100a300c2d08100a2d08130a4d0a430d2b082f0d7d0a150a2b07110b140b0d0a1509100c2b0a130a2c0b13091208130a130b460a0f0c120b120a2f07100717081408100913092d0d1108b70c2c0c0909190b100a150a0d0c2a07170b100b2c0b2b0c130b0c091709150a0d0b2c084b0b2f09130a0e0b11082e0b1009160a0c0d13091209140a0e0c1609280c0f0b110c110a100912081607120c0f071a0a120a0c0b120a1008180a2c08100b150b07124a0a0e0b0f08160b130a0e06150b110b0f0c30080f0e0e08140916090e0c2e0b110a2d0a0e09140a300b280a150912072e072f0b0001af0a075d3d0b280d2b071309140b0f0c2f091007140a2f0a2e090f0d2b0b2e09300a280c110c2a0c2c0b2c08300b2b0c2c0a0e0e120813071509110b1308140b0d0c2c0b100b110b2b08140b110b140a280c100a2e0b13090811130a120a100a2c0d0f0b110a1307130d2a0d290d2c0b110c0d0d140b0a0e0c110f0b1008150815082c0b310b0d0c100a2a051709300c280e460d100b0f09130b110b100b110b1209110b100b100c100b100b1307140a12081008150b1208120c0d0b130b120514091307140c120a120a0d0b190a0d05170d110a1004140d0e0a150b0b0e1007150c1209100a1208130a14090f0d0e0d100b110c0f09120c100c10091308130912091508110b1106160a2c092f0b100a120b2d0a2c0a000d05000000000000"
                        }
                    }`

**Comment by kiwi-cam** [comment]
Looks like something is trying to set the target temperature to 30 - and there's no hexCode provided for this temperature.  This is interesting given you've got maxTemperature set to 30.

Any idea what was happening when this error was thrown?

**Comment by Spanishu** [comment]
Hi, 
I have run 
`node --trace-warnings ...`
with the following output 
`internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/pi/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`
it happens when I try to change the temeperature

**Comment by kiwi-cam** [comment]
Hmmm... this looks like something with your deployment rather than this specific module.  Maybe [try re-installing](https://www.reddit.com/r/raspberry_pi/comments/59a18r/error_cannot_find_module_nodejs_help/d97s5b8/?utm_source=reddit&utm_medium=web2x&context=3) the module(s), being sure to use the -g switch?
