### ISSUE TITLE
Rm3 mini + rm4c mini broadlink bestcon

### ISSUE THREAD

**Issue by ciberknibal** [kiwi-cam/homebridge-broadlink-rm#105]
Hi.  I have been working with an rm3 without problem and now I want to add a broadlink bestcon r4mc in the living room.  the rm3 mini works without problem but when I launch the r4mc an error appears in the log indicating that it cannot find the device.  You both have a static ip and are defined in host.  is r4mc comptible bestcon compatible with the plugin?  thanks

` "hosts": [
                {
                    "address": "192.168.0.21",
                    "mac": "C8:F7:42:76:xx:xx",
                    "isRFSupported": true
                },
                {
                    "address": "192.168.0.150",
                    "mac": "24:df:a7:34:xx:xx",
                    "isRFSupported": false,
                    "isRM4": true
                }
            ],
            "accessories": [
                {
                    "host": "192.168.0.21",
                    "name": "RM3",
                    "type": "learn-code"
                },
                {
                    "host": "192.168.0.150",
                    "name": "RM4",
                    "type": "learn-code"
                },
                {
                    "host": "192.168.0.21",
                    "name": "Roombarm3",
                    "type": "switch",
                    "data": {
                        "on": "2600c60..",
                        "off": "0000 .."
                    },
                    "enableAutoOff": true,
                    "onDuration": 7200
                },
                {
                    "host": "192.168.0.21",
                    "name": "Aire dormitorio",
                    "type": "switch",
                    "data": {
                        "on": "26002a..",
                        "off": "26002a018b901235.."
                    }
                },
                {
                    "host": "192.168.0.21",
                    "name": "television",
                    "type": "switch",
                    "data": {
                        "on": "260054...",
                        "off": "2600.."
                    }
                },
                {
                    "host": "192.168.0.150",
                    "name": "Roombarm4",
                    "type": "switch",
                    "data": {
                        "on": "2600..",
                        "off": "0000 0.."
                    },
                    "enableAutoOff": true,
                    "onDuration": 7200
                },
                {
                    "host": "192.168.0.150",
                    "name": "Aire salon",
                    "type": "switch",
                    "data": {
                        "on": "26002a..",
                        "off": "26002a.."
                    }
                }
            ],
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideLearnButton": false,
            "plugin_map": {
                "plugin_name": "homebridge-broadlink-rm-pro"
            }

**Comment by masterfordev** [comment]
Hello, try adding the option `"isRM4": true,` in your RM4 device.

``
..
{
"host": "192.168.0.150",
"name": "RM4",
"isRM4": true,
"type": "learn-code"
},
..
``

**Comment by kiwi-cam** [comment]
The other thing to check is how you setup the device on your network. If you went through the setup process all the way the device will be registered with the cloud and won't respond to our local requests.  Try resetting it, reconfiguring, and aborting the setup process when prompted for a room.

**Comment by ciberknibal** [comment]
Hi.
I have tried adding isrm4 to no avail.
I actually have the device added in the application until the end. connected to the cloud. I tried to cancel the installation process. Thanks @kiwi-cam and @masterfordev

**Comment by ciberknibal** [comment]
i haved tried to reconfigure rm4 and rm3. Neither of them appears already connected to the broadlink application. The two devices have a static ip. The rm3 works perfectly but the rm4 does not work, it gives an error in homebridge as not found. responds to a ping without problem

**Comment by masterfordev** [comment]
The plugin cant auto-discover the device ? (Rm4)

**Comment by kiwi-cam** [comment]
So you've got RM3 support but not RM4? What version of the plugin are you running?

`npm -g list --depth=0` should tell you.

**Comment by ciberknibal** [comment]
it is the latest version.  It is already working ok.  I have simply removed the hosts part and let the plugin discover the broadlinks only.  Thank you so much for everything.
