### ISSUE TITLE
" sendData (no device found)"

### ISSUE THREAD

**Issue by bondskin** [kiwi-cam/homebridge-broadlink-rm#107]
All,

When I am sending an action (turn on/off Receiver), I get the following error message and nothing happens
```
[14/11/2020, 19:48:09] [Broadlink RM] Receiver On/Off setSwitchState: true
[14/11/2020, 19:48:09] [Broadlink RM] [ERROR] Receiver On/Off sendData (no device found)
[14/11/2020, 19:48:18] [Broadlink RM] Receiver On/Off setSwitchState: false
[14/11/2020, 19:48:18] [Broadlink RM] [ERROR] Receiver On/Off sendData (no device found)

```
This is my json section
```
{
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": true,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "accessories": [
                {
                    "name": "Receiver On/Off",
                    "type": "switch",
                    "data": {
                        "on": "HEX26006000000123951213123712131213123811131238123811131213123812371213123812371213123812371213123812180d1212381238121212131238121312371238121312121200051e0001254b12000c4d0001254b12000c4d0001254b12000d05000000000000",
                        "off": "HEX2600580000012692141114361311141114361411133614361411131114361436131114361436141014361436141014361411141114351436141114101436141114361336141114111400051b0001274914000c4c0001264a13000d050000000000000000000000000000"
                    }
                }
            ]
        },
```

I also replaced "switch" by "TV" but this prevents homebridge to start with the following error message
"[Broadlink RM] homebridge-broadlink-rm-pro is taking a long time to load and preventing Homebridge from starting."

**Comment by masterfordev** [comment]
The code learned include "HEX"? Try just with the numers and not including "HEX".

**Comment by bondskin** [comment]
> The code learned include "HEX"? Try just with the numers and not including "HEX".

Same effect.
Adding a TV appliance (type="TV") I get again the starting issues.

Is "switch" the right category?

**Comment by kiwi-cam** [comment]
`no device found` suggests the plugin hasn't connected to your Broadlink device.  Is it on your network and **not** [connected to the cloud](https://github.com/kiwi-cam/homebridge-broadlink-rm#documentation)?

**Comment by bondskin** [comment]
> `no device found` suggests the plugin hasn't connected to your Broadlink device. Is it on your network and **not** [connected to the cloud](https://github.com/kiwi-cam/homebridge-broadlink-rm#documentation)?

thanks for your swift reply, the Broadlink is connected to my network.
During initial setup (as you recommended above) I cancelled the assistant and did not assign a room, etc
I learned the codes.
Once done, I finished the setup, assigned a room and created remotes/appliances in the iOS app. 
Could this be the issue?

**Comment by kiwi-cam** [comment]
That'll be it. Once the device is setup in the cloud it can't be used locally. It's one or the other unfortunately.

You'll need to reset and reconfigure your device for it to work with homebridge.

**Comment by kiwi-cam** [comment]
I was playing around with firmware versions yesterday and found that there is another option.  I've updated my documentation here: https://github.com/kiwi-cam/homebridge-broadlink-rm/tree/kiwi-cam-beta-1#documentation (first part of the "Documentation" section).

**Comment by masterfordev** [comment]
> I was playing around with firmware versions yesterday and found that there is another option. I've updated my documentation here: https://github.com/kiwi-cam/homebridge-broadlink-rm/tree/kiwi-cam-beta-1#documentation (first part of the "Documentation" section).

So.. with that now we can use the RM in both platforms? with the App and homekit?

**Comment by kiwi-cam** [comment]
I only changed the setting 24 hours ago but so far it does appear that way. The setting description matches what we were experiencing so it should work.

**Comment by masterfordev** [comment]
Nice. Broadlink got friendly with us. It is a good option for when we want to update the firmware of the devices.

**Comment by bondskin** [comment]
All,

I just disabled the option in the app, as advised above, and it does not work as expected.
So I have restarted homebridge and that fixed it. Now it is working!
Awesome!
