### ISSUE TITLE
Humidifier Dehumidifier can't send HexCode

### ISSUE THREAD

**Issue by uzumaki20398** [kiwi-cam/homebridge-broadlink-rm#109]
It's difficult to set fanSpeed exactly with Home APP .

As Fan type.
My code
`"data": {`
`"on": "code_ON",`
`"fanSpeed10": `"code_10",`
`"fanSpeed40": "code_40",`
`"fanSpeed80": "code_80",`
`"fanSpeed100": "code_100",`
`}`
I want to set my fanSpeed to 80.
With Home APP , I only set fanSpeed close to 80.

If I want to set fanSpeed to 80 ,but I will set it to 75 with Home APP .
It can send close to FanSpeed80 HEXCode.

My log
`[Broadlink RM] My Fan setFanSpeed: 75`
`[Broadlink RM] My Fan setFanSpeed: (closest: 80)`

But Humidifier Dehumidifier type can't to do as fan type.

Thanks

**Comment by kiwi-cam** [comment]
The Humidifier-Dehumidifier should work exactly the same - it actually inherits the Fan functions from the Fan accessory type:
```
Nov 16 07:16:20 homebridge[21006]: [Broadlink RM] Dehumidifer setFanSpeed: 74
Nov 16 07:16:20 homebridge[21006]: [Broadlink RM] Dehumidifer setFanSpeed: (closest: 70)
Nov 16 07:16:20 homebridge[21006]: [Broadlink RM] Dehumidifer sendHex (192.168.1.xx; 24:df:a7:xx:xx:xx) 2600580000000129961214111512131a21312381213111312131239113912381238121312381239113812000001000070
```

What do you see in the logs when you adjust the fan speed of your Humidifier-Dehumidifier?

**Comment by uzumaki20398** [comment]
My code:
`{`
`"name": "Humidifier Dehumidifier",`
`"type": "humidifier-dehumidifier",`
`"mqttURL": "mqtt://192.168.0.51",`
`"mqttUsername": "Username",`
`"mqttPassword": "Password",`
`"mqttTopic": "MQTT/hum",`
`"showLockPhysicalControls": false,`
`"debug": true,`
`"data": {`
`           "on":'"code_ON",`
`           "off":`"code_OFF",
`           "fanSpeed100": "code_fanSpeed100",`
`           "fanSpeed94":  "code_fanSpeed94",`
`           "fanSpeed88": "code_fanSpeed88",`
`           "fanSpeed82": "code_fanSpeed82",`
`           "fanSpeed76": "code_fanSpeed76",`
`           "fanSpeed71": "code_fanSpeed71",`
`           "fanSpeed65": "code_fanSpeed65",`
             ......
             `}`
`}`

- -

if I set dehumidifier to 78%.
show 
`[Broadlink RM] [DEBUG] Humidifier Dehumidifier onMQTTMessage (raw value 2: 75.7)`
`[Broadlink RM] [DEBUG] Humidifier Dehumidifier onMQTTMessage (parsed temperature: 75.7)`
`[Broadlink RM] Humidifier Dehumidifier onHumidity (75.7)`
`[Broadlink RM] Humidifier Dehumidifier setDehumidifierThreshold: 78`
`[Broadlink RM] Humidifier Dehumidifier setDeumidifierThreshold: currently undefined to 69, changing to undefined to 78`
`[Broadlink RM] [DEBUG] Humidifier Dehumidifier setCurrentState: requested update from 3 to 1`
`[Broadlink RM] Humidifier Dehumidifier setCurrentState: currently 3, changing to 1`
`[Broadlink RM] Humidifier Dehumidifier sendHex (192.168.1.206;  **:**:**:**:**:**) code_OFF`
`[Broadlink RM] Humidifier Dehumidifier getCurrentState: 1`
- -
if I set dehumidifier to 72%.

show 
`[Broadlink RM] [DEBUG] Humidifier Dehumidifier onMQTTMessage (raw value: 77.0)`
`[Broadlink RM] [DEBUG] Humidifier Dehumidifier onMQTTMessage (raw value 2: 77.0)`
`[Broadlink RM] [DEBUG] Humidifier Dehumidifier onMQTTMessage (parsed temperature: 77)`
`[Broadlink RM] Humidifier Dehumidifier onHumidity (77)`
`[Broadlink RM] Humidifier Dehumidifier setDehumidifierThreshold: 72`
`[Broadlink RM] Humidifier Dehumidifier setDeumidifierThreshold: currently undefined to 78, changing to undefined to 72`
`[Broadlink RM] [DEBUG] Humidifier Dehumidifier setCurrentState: requested update from 1 to 3`
`[Broadlink RM] Humidifier Dehumidifier setCurrentState: currently 1, changing to 3`
`[Broadlink RM] Humidifier Dehumidifier sendHex (192.168.10.206; **:**:**:**:**:**) code_OFF`
`[Broadlink RM] Humidifier Dehumidifier getCurrentState: 3`
- -
if I set dehumidifier to 82%.

show only
`[Broadlink RM] [DEBUG] Humidifier Dehumidifier onMQTTMessage (raw value: 77.0)`
`[Broadlink RM] [DEBUG] Humidifier Dehumidifier onMQTTMessage (raw value 2: 77.0)`
`[Broadlink RM] [DEBUG] Humidifier Dehumidifier onMQTTMessage (parsed temperature: 77)`
`[Broadlink RM] Humidifier Dehumidifier onHumidity (77)`
`[Broadlink RM] Humidifier Dehumidifier setDehumidifierThreshold: 82`

**Comment by kiwi-cam** [comment]
Ah. You're adjusting the humidity - not the fanspeed. FanSpeed is set to round to the nearest configured fanSpeed (to save you learning 100 different Hex codes.

I'll look into adding a "stepSize" like option for the humidity.
