### ISSUE TITLE
Second RM4 mini 51da not discovered

### ISSUE THREAD

**Issue by kiwi-cam** [kiwi-cam/homebridge-broadlink-rm#11]
I have two RM4 mini 51da, and I am using homebridge-broadlink-rm-pro v4.2.6. Both RM4 are on the network with static IPs, and both are seen by Broadlink app.

RM4-34-a7-be : Discovered Broadlink RM Mini 4 (51da)
RM4-34-a5-8b : (Not Discovered)

Pls advise.

_Originally posted by @deeloke in https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/10#issuecomment-643729680_

@deeloke, This doesn't seem to be related to the other issue. I hope you don't mind but it seems more appropriate to continue the discussion here.

Could you help isolate the issue?
1. Is it related to finding that device - is there any configuration that it does find that device?
2. Is it related to have two devices - do both devices work when they're the only ones on the network?

**Comment by deeloke** [comment]
Thanks. Answers:
1. No. I have added a hosts entry to my config but this additional measure does not help.
2. Yes, the issue appears to be related to having two  RM Mini 4 (51da) devices. Both work when it is the only 51da  on the network. This version of the plugin only finds one device and does not find the other if both are powered on and on the network at the same time. Note that I also have a Broadlink RM2 Pro Plus (272a) on the network, this device does not seem  affected by this issue.

**Comment by deeloke** [comment]
FYI I am running homebridge-broadlink-rm-pro v4.2.6 and this issue persists. Is there anything I can do to help?

**Comment by kiwi-cam** [comment]
Do you get any errors in the logs?

I've got a second device on its way to me which should help investigating this issue.

**Comment by deeloke** [comment]
The logs do not present any error messages. 

__________________
Deeloke

**Comment by deeloke** [comment]
FYI I established a second homebridge on a second server, and configured it with the host option:
 "hosts": [
                {
                    "address": "192.168.X.XX",
                    "mac": "24:df:a7:XX:XX:X",
                    "isRFSupported": false
                } 
I also included the host option in accessories:  "host": "192.168.X.XX",
(the mac address is read incorrectly, this error is mentioned on another thread, so using a static IP address instead)

Unfortunately, the RM4 is incorrectly detected and does not respond to commands sent from home app:
Discovered Broadlink RM2 (2712)

Logs:
[8/12/2020, 10:44:49 PM] [Broadlink RM] Initializing BroadlinkRM platform...
[8/12/2020, 10:44:49 PM] [Broadlink RM] [INFO] Automatic Broadlink RM device discovery has been disabled as the "hosts" option has been set.
[8/12/2020, 10:44:49 PM] [Broadlink RM] Fan Accessory Ready
[8/12/2020, 10:44:49 PM] [Broadlink RM]  Light White Accessory Ready
[8/12/2020, 10:44:49 PM] [Broadlink RM]  Light Yellow Accessory Ready
[8/12/2020, 10:44:49 PM] [Broadlink RM]  Light OffWhite Accessory Ready
[8/12/2020, 10:44:49 PM] [Broadlink RM]  Light toggle Accessory Ready
[8/12/2020, 10:44:49 PM] Initializing platform accessory 'Learn'...
[8/12/2020, 10:44:49 PM] Initializing platform accessory ' Fan'...
[8/12/2020, 10:44:49 PM] Initializing platform accessory ' Light White'...
[8/12/2020, 10:44:49 PM] Initializing platform accessory ' Light Yellow'...
[8/12/2020, 10:44:49 PM] Initializing platform accessory ' Light OffWhite'...
[8/12/2020, 10:44:49 PM] Initializing platform accessory 'Light toggle'...
[8/12/2020, 10:44:49 PM] Homebridge is running on port 51826.
[8/12/2020, 10:44:49 PM] [Broadlink RM] [INFO] Discovered Broadlink RM2 (2712) at 192.168.X.XX (24::d:f::a7::X:X::XX::X:X)

**Comment by fparrav** [comment]
> Thanks. Answers:
> 
> 1. No. I have added a hosts entry to my config but this additional measure does not help.
> 2. Yes, the issue appears to be related to having two  RM Mini 4 (51da) devices. Both work when it is the only 51da  on the network. This version of the plugin only finds one device and does not find the other if both are powered on and on the network at the same time. Note that I also have a Broadlink RM2 Pro Plus (272a) on the network, this device does not seem  affected by this issue.


I have the same problem in version 4.3.3, when I configure the option 'hosts' it recognizes them as an RM2, and does not send the commands, and if I remove the hosts option it only detects one of my 2 RM4 mini

**Comment by BChap327** [comment]
Hi everybody. I had the same issue but figured out a workaround. I have two Broadlink RM 4 Pros (both are model 649b). Automatic detection only discovers one of the RM 4 Pros when they are both on the network at the same time. 

When manually using the "hosts" entry to force the plugin to discover the RM 4 Pros, the plugin sees them as Broadlink RM2 (2712). However, neither device responds to commands.

This seems to happen because of line 130 in the platform.js. - const deviceType = isRFSupported ? 0x279d : 0x2712; 

If the value of isRFSupported is "true", it discovers the device as an RM Pro+. If the value is "false", it discovers the device as an RM2.

To fix the issue, I used Terminal to nano into the platform.js file on my Raspberry Pi 4 running Hoobs and changed 0x279d : 0x2712 to 649b : 649b. This forces the plugin to properly detect my RM 4 Pros. They now both respond to commands.

Please keep in mind that I don't have any coding experience. I just figured this through trial and error. Hopefully this workaround helps others who are having this same problem.

**Comment by kiwi-cam** [comment]
Brilliant thanks @BChap327, I'll take a look at the logic behind that statement and see if I can improve it.

P.S. I'd argue that I also don't have coding experience. It's things like this that get us experience 😀

**Comment by BChap327** [comment]
Thank you. Just trying to help in any way I can. I truly appreciate your work on the plugin!

**Comment by kiwi-cam** [comment]
I've just pushed a new Beta version 4.3.4-beta.3. It should help with the device type issue.

Set your hosts section as:
```
                   "hosts": [{
                                        "address": "192.168.1.5",
                                        "mac": "24:df:a7:xx:xx:xx",
                                        "isRM4": true,
                                        "isRFSupported": true
                                }],
```

Use the applicable isRM4 and isRFSupported based on your device (RM4 devices use different headers on messages to the device).

Let me know how it goes.

It should find the device as:
`[Broadlink RM] [INFO] Discovered Manual RM4 Pro Device (2227) at 192.168.1.5 (24:df:a7:xx:xx:xx)`

**Comment by fparrav** [comment]
> I've just pushed a new Beta version 4.3.4-beta.3. It should help with the device type issue.
> 
> Set your hosts section as:
> 
> ```
>                    "hosts": [{
>                                         "address": "192.168.1.5",
>                                         "mac": "24:df:a7:xx:xx:xx",
>                                         "isRM4": true,
>                                         "isRFSupported": true
>                                 }],
> ```
> 
> Use the applicable isRM4 and isRFSupported based on your device (RM4 devices use different headers on messages to the device).
> 
> Let me know how it goes.
> 
> It should find the device as:
> `[Broadlink RM] [INFO] Discovered Manual RM4 Pro Device (2227) at 192.168.1.5 (24:df:a7:xx:xx:xx)`

I tried this with my 2 RM4 mini and it works perfectly! Thank you very much!!

**Comment by deeloke** [comment]
> I've just pushed a new Beta version 4.3.4-beta.3. It should help with the device type issue.
> 
> Set your hosts section as:
> 
> ```
>                    "hosts": [{
>                                         "address": "192.168.1.5",
>                                         "mac": "24:df:a7:xx:xx:xx",
>                                         "isRM4": true,
>                                         "isRFSupported": true
>                                 }],
> ```
> 
> Use the applicable isRM4 and isRFSupported based on your device (RM4 devices use different headers on messages to the device).
> 
> Let me know how it goes.
> 
> It should find the device as:
> `[Broadlink RM] [INFO] Discovered Manual RM4 Pro Device (2227) at 192.168.1.5 (24:df:a7:xx:xx:xx)`

Yes, both my RM4 Minis are recognised and working. Thanks! 

[10/24/2020, 3:43:32 PM] [Broadlink RM] [INFO] Discovered Manual RM4 Device (2225) at 192.168.1.XX (24::d:f::a7::XXXXX)
[10/24/2020, 3:43:32 PM] [Broadlink RM] [INFO] Discovered Manual RM4 Device (2225) at 192.168.1.XX (24::d:f::a7::XXXXX)
[10/24/2020, 3:43:32 PM] [Broadlink RM] [INFO] Discovered Manual RM Pro Device (2223) at 192.168.1.XX (34::e:a::34::e:7:XXXXX)

However, both these devices have the humidity/temperature cable connected. 

On the first, both temperature and humidity are reported correctly. 
On the second device, only humidity is reported correctly. Temperature is reported a 0.0 degrees. Any ideas?

**Comment by masterfordev** [comment]
Hello. What is your config? I have 3 devices RM Mini 4 (62bc) and they work fine. 

This is my config for the humidity/temperature sensor. 

```

{
                    "name": "Sensor Sala",
                    "type": "humiditySensor",
                    "host": "192.165.1.130",
                    "humidityUpdateFrequency": 300,
                    "disableLogs": true
                },
                {
                    "name": "Sensor Oficina",
                    "type": "humiditySensor",
                    "host": "192.165.1.131",
                    "humidityUpdateFrequency": 300,
                    "disableLogs": true
                },
                {
                    "name": "Sensor Cuarto",
                    "type": "humiditySensor",
                    "host": "192.165.1.132",
                    "humidityUpdateFrequency": 300,
                    "disableLogs": true
                },

```

**Comment by deeloke** [comment]
Hi thanks for sharing your config. I just figured it out, I forgot to remove the pseudo-mode after adding the second cable. Both RM4s are remorting temperature perfectly now.  Wonderful work peeps!

**Comment by masterfordev** [comment]
Great!

> Hi thanks for sharing your config. I just figured it out, I forgot to remove the pseudo-mode after adding the second cable. Both RM4s are remorting temperature perfectly now. Wonderful work peeps!
