### ISSUE TITLE
Replace pseudoDeviceTemperature with actual Temperature readings

### ISSUE THREAD

**Issue by Spanishu** [kiwi-cam/homebridge-broadlink-rm#111]
Right now I have in my Hombebridge Config "pseudoDeviceTemperature": 27 set for one of my AC. It would be nice however to be able to have there the real value which is being read from a Xiaomi temperature sensor which is also linked in Homebridge (homebridge-hue) plugin or if it helps directly with Deconz. If anybody has figured this out / good idea on how to do this would be highly welcome.

**Comment by kiwi-cam** [comment]
Does your Xiaomi temperature sensor write to the logs with the current temperature?

I have a cron job grab the most recent log and pulls the temperature out to dump to a file. You could then use temperatureFilePath to grab that file.

**Comment by Spanishu** [comment]
Hi I have taken a look at the REST-API I have for the sensor. When I go a get request

This is what I get in return 
`{
    "config": {
        "battery": 95,
        "offset": 0,
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "7e8c9a798d78cae31665c2cefbec2528",
    "lastseen": "2020-11-18T11:23Z",
    "manufacturername": "LUMI",
    "modelid": "lumi.weather",
    "name": "Living Room",
    "state": {
        "lastupdated": "2020-11-18T11:23:26.174",
        "temperature": 2168
    },
    "swversion": "20191205",
    "type": "ZHATemperature",
    "uniqueid": "xxxxxx"`

Since I am a total noob, i only got this far. Question would be:
- How do I get the Temperature value out into a file from this REST-API
I believe that I could do it from there. Many thanks for the support upfront!

**Comment by kiwi-cam** [comment]
I'm sure someone smarter than me could come up with a nice regex expression to get this, but I find the concept of awk a lot easier.

You should be able to extract that part of the text using: 
`echo $TEXT | awk -F '"temperature": ' '{print $2}' | awk -F ' ' '{print $1}'`
Basically awk is splitting the text on `"temperature": ` and printing the second half, then splitting on a space and printing the first half.

Stick it in a script and you're away:
```
#!/bin/sh

data=$(curl your REST-API call)
temp=$(echo $data  | awk -F '"temperature": ' '{print $2}' | awk -F ' ' '{print $1}'`)
#insert the decimal point
temp=$(echo ${temp:0:2}.${temp:2:2})
#data validation before writing to file
if echo $temp | egrep -q '^-*[[:digit:]]+.*[[:digit:]]*$'; then
        echo "$temp" > /var/tmp/temperature.txt
fi
```

**Comment by Spanishu** [comment]
Thanks a lot !!! Much appreciated
I have tried and made some small change
`temp=$(echo $data | awk -F '"temperature":' '{print $2}' | awk -F '}' '{print $1}')`

the result I get is
`2092`

There seems to be an error in line 6 with the decimal point.  I get "bad substitution", step by step... 

EDIT:
I found that running it as bash instead of ./ solved the issue. All working fine now ! Thanks!
