### ISSUE TITLE
TV not showing up in Home App

### ISSUE THREAD

**Issue by esttorhe** [kiwi-cam/homebridge-broadlink-rm#112]
Hi, this is similar to #87

I can't add the TV because when I do the steps:

>Add accesory / i have not a code or i cant scan / selec the tv / insert your PIN of homebridge

I can't get to "select tv" as nothing shows. It just keeps showing a spinner and the TV never appears in the prompt to be added.

I have tried removing the `homebridge` entirely and re-adding it, reconfiguring multiple times the plugin, etc
no combination has worked so far unfortunately

Any help is appreciated. thanks :)

**Comment by esttorhe** [comment]
Aaaaaaaaaaaaaaand nevermind. It seems at some point one of the attempts actually added the tv to homebridge but it was not showing in Home.

I had to remove the identifier from homebridge settings
```
/var/lib/homebridge/persist/AccessoryInfo.<id>.json
/var/lib/homebridge/persist/IdentifierCache.<id>.json
```

That's where they are if you are trying to remove manually instead of from the WebUI settings. 
Leaving this here in case someone faces a similar issue

**Comment by Stichoza** [comment]
Helped me re-adding TV to home app. I think it would be good to link this issue somewhere in readme
