### ISSUE TITLE
Support sending cloud ping packets (packet type 0x01)

### ISSUE THREAD

**Issue by kiwi-cam** [kiwi-cam/homebridge-broadlink-rm#113]
As discussed in: https://github.com/mjg59/python-broadlink/issues/458

Add a function to send keep alive packets to devices to prevent reboots.

**Comment by masterfordev** [comment]
This only happens on RM 3 devices? Or also in RM 4?

And, it seems useful because we can make use of this if we want the devices to be automatically restarted, for example, every 24 hours. Maybe something could be implemented for that to happen 🤔

**Comment by kiwi-cam** [comment]
> 
> 
> This only happens on RM 3 devices? Or also in RM 4?
> 
> And, it seems useful because we can make use of this if we want the devices to be automatically restarted, for example, every 24 hours. Maybe something could be implemented for that to happen 🤔

In my experience I'm only seeing it on the RM3.  But there's no harm in implementing it on all devices regardless of types.

I'm not sure an auto restart is practical - there are too many variables. This mechanism only restarts the device if it is blocked from the cloud - so noob users will really struggle to get this working. Also, we can't guarantee that the device will restart - or reliably confirm that it has.

**Comment by kiwi-cam** [comment]
This should now be fixed in 4.3.8
