### ISSUE TITLE
no response when adding "nohumidity" to humidifier

### ISSUE THREAD

**Issue by hassman12** [kiwi-cam/homebridge-broadlink-rm#116]
hi,
i added a humidifier-dehumidifier,
all worked well, but then...
i added "humidifieronly" and there was no change in the accessory.
then i added "nohumidity" and the accessory went unresponsive.

thanks

**Comment by hassman12** [comment]
"name": "diffuser1",
                    "type": "humidifier-dehumidifier",
                    "humifierOnly": true,
                    "host": "aa:...",
                    "data": {
                        "on": "260058000...
                        "off": "2600580000012...

**Comment by kiwi-cam** [comment]
This should be fixed in the latest BETA (4.3.8-beta.1). [Please test](https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions) and confirm if you're able to.

**Comment by kiwi-cam** [comment]
This should now be fixed in 4.3.8
