### ISSUE TITLE
can i send more then 1 hex code?

### ISSUE THREAD

**Issue by hassman12** [kiwi-cam/homebridge-broadlink-rm#117]
hi,
I'm trying to send 2 (or even 3) ir hex codes to a humidifier accessory,
i want it to turn on and then send another ir code to change its timer,
is it possible?
thanks

**Comment by masterfordev** [comment]
Like [this](https://lprhodes.github.io/slate/#advanced-setup) ?

![Screenshot](https://user-images.githubusercontent.com/29960705/99887080-9f588c00-2bfe-11eb-8a79-235ada539079.jpeg)

**Comment by hassman12** [comment]
yes!
thank you!
