### ISSUE TITLE
[ERROR] Learn Code (Couldn't learn code, device not found)

### ISSUE THREAD

**Issue by CapWaldmeister** [kiwi-cam/homebridge-broadlink-rm#118]
My Broadlink RMmini3 can not be found. I'm using Raspi 3.
When I click on the learn button in the home app, I get these messages:
[22/11/2020, 14:32:03] [BroadlinkRM] Learn getSwitchState: undefined
[22/11/2020, 14:32:03] [BroadlinkRM] Scan Frequency getSwitchState: undefined
[22/11/2020, 14:32:10] [BroadlinkRM] [INFO] Learn Code initializing (undefined)
[22/11/2020, 14:32:10] [BroadlinkRM] [ERROR] Learn Code (Couldn't learn code, device not found)

I tried it with this code in the configuration as recommended:
"hosts": [
  {
    "address": "192.168.1.76",
    "mac": "34:ea:34:e7:d7:28",
    "isRFSupported": true
  }
],
(replaced with adress and Mac of my RMmini3)
But it doesn't help...
It would be great, if you could help me.

**Comment by kiwi-cam** [comment]
Usually this happens when you've completed the setup of the device in the Broadlink app. Did you add the device to a room?

**Comment by CapWaldmeister** [comment]
Yes, I did. Shouldn't I do that? I'll try without adding the device...

**Comment by kiwi-cam** [comment]
Unfortunately if you add the device to a room it gets registered with Broadlink cloud and stops responding to local requests.  You need to use either Broadlink's cloud or local tools... you can't have both.

**Comment by CapWaldmeister** [comment]
Thanks a lot! Now it works.

**Comment by kiwi-cam** [comment]
I was playing around with firmware versions yesterday and found that there is another option.  I've updated my documentation here: https://github.com/kiwi-cam/homebridge-broadlink-rm/tree/kiwi-cam-beta-1#documentation (first part of the "Documentation" section).
