### ISSUE TITLE
broadlink aircondition default temperature

### ISSUE THREAD

**Issue by kircuvaloglu** [kiwi-cam/homebridge-broadlink-rm#119]
/var/tmp/inside.txt I made this txt and whatever degree I put it shows as default at the air condition's panel. My question is: my temperature sensor which is connected to home bridge via zigbee (my zigbee gateway is conbee 2) how could I set the temperature sensor to write the degrees every 30 seconds in this txt. Please keep in mind that I am new to this.

I tried from home bridge.local/swagger UI but I was not able to do it. Thank you in advance for your help.

**Comment by kiwi-cam** [comment]
I'm going with... probably.  Some people have done similar things (me included and #111) using a bash script and cronjob to write the file.  Is there a command line to retrieve the temperature?
