### ISSUE TITLE
Unknown Broadlink device with type code 653c

### ISSUE THREAD

**Issue by josephpoon0506** [kiwi-cam/homebridge-broadlink-rm#120]
Hi kiwi-cam, the script reported that seems the script is not fully supported. please check the log. thanks

[11/25/2020, 9:28:31 AM] Homebridge v1.2.3 is running on port 52124.
[11/25/2020, 9:28:31 AM] [BroadlinkRM4Pro] 
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "653c". The device is connected to your network with the IP address "192.168.1.24".

**Comment by kiwi-cam** [comment]
I can't see any references to a 653c - it must be new. Could you let me know what type of device you have?

**Comment by josephpoon0506** [comment]
I just brought a broadlink RM4 Pro with HTS2 Temperature and Humidity Sensor Cable from taobao 
[https://item.taobao.com/item.htm?spm=a1z09.2.0.0.34962e8dd9qPAp&id=522092850687&_u=pae55146d56](url)

**Comment by kiwi-cam** [comment]
I've just added this to the beta of kiwicam-broadlinkjs-rm (0.9.4-beta.2). If you [install the Beta plugin](https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions) it should pull this dependency and add support.

**Comment by josephpoon0506** [comment]
Hi Kiwi-cam, it work. thank you for your support. 

[11/25/2020, 10:10:03 AM] [BroadlinkRM4Pro] No accessories have been added to the "BroadlinkRM4Pro" platform config.
[11/25/2020, 10:10:03 AM] Initializing platform accessory 'Learn'...
[11/25/2020, 10:10:03 AM] Initializing platform accessory 'Scan Frequency'...
Setup Payload:
X-HM://0023ISYWYED36
