### ISSUE TITLE
problems on RM4 pro

### ISSUE THREAD

**Issue by platini76** [kiwi-cam/homebridge-broadlink-rm#121]
hello this evening I change an RM2mini with RM4 Pro

I have two errors and it seems not recognizing device:

[27/11/2020, 02:46:12] [Broadlink RM] Initializing BroadlinkRM platform...
[27/11/2020, 02:46:12] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
[27/11/2020, 02:46:12] [Broadlink RM] Condizionatore Soggiorno Accessory Ready
[27/11/2020, 02:46:12] [Broadlink RM] A/C Switch Accessory Ready
[27/11/2020, 02:46:12] [Broadlink RM] McIntosh Accessory Ready
[27/11/2020, 02:46:12] One of your plugins incorrectly registered an external accessory using the platform name ([object Object]) and not the plugin identifier. Please report this to the developer!

[27/11/2020, 02:47:14] [Broadlink RM] Condizionatore Soggiorno getTargetTemperature: undefined
[27/11/2020, 02:47:14] [Broadlink RM] Condizionatore Soggiorno getTargetHeatingCoolingState: 0
[27/11/2020, 02:47:14] [Broadlink RM] Condizionatore Soggiorno getCurrentHeatingCoolingState: 0
[27/11/2020, 02:47:17] [Broadlink RM] A/C Switch setSwitchState: 1
[27/11/2020, 02:47:17] [Broadlink RM] [ERROR] A/C Switch sendData (no device found)
[27/11/2020, 02:47:25] [Broadlink RM] A/C Switch getSwitchState: 1
[27/11/2020, 02:47:25] [Broadlink RM] Condizionatore Soggiorno getTargetHeatingCoolingState: 0
[27/11/2020, 02:47:25] [Broadlink RM] Condizionatore Soggiorno getTargetTemperature: undefined
[27/11/2020, 02:47:25] [Broadlink RM] Condizionatore Soggiorno getCurrentHeatingCoolingState: 0
[27/11/2020, 02:47:26] [Broadlink RM] McIntosh getSwitchState: 0
[27/11/2020, 02:47:28] [Broadlink RM] McIntosh setSwitchState: 1
[27/11/2020, 02:47:28] [Broadlink RM] [ERROR] McIntosh sendData (no device found)

my config:

{
    "platform": "BroadlinkRM",
    "hideWelcomeMessage": false,
    "hideScanFrequencyButton": true,
    "hideLearnButton": true,
    "name": "Broadlink RM",
    "accessories": [
        {
            "name": "Condizionatore Soggiorno",
            "type": "air-conditioner",
            "data": {
                "temperature16": {
                    "data": "260044010F0E110C120A100E120A12000336753710280F0E120A130C1029110A100E120A120B1228100D12270F2A120A122910280F2A12270F2A120A120B1228100D120A130A130A0F0F110C110B100F110B120A120B0F0F110C0F0E120A1B0A120B110D12270F0E120A120B0F2B1129110A130A120B1228102912270F0E12270F0E120A100E120A130A100E120A120B120B110D120A130A120B0F0F110C12270F0E12270F0E120A120C120A100E120A130A100E120A130A120B120B110D120A130A120B120B110D120B130F120A100E120A120B110D120A130A100E120A120B120B110E110A130A120B120B110D12270F0E120A120B120B110D120A130A120B0F100E0F1129110A13270F0E120A100E12270F2A120A100E120A130A0F0F110C120A130A130A110D120B120A130A110D120A130A130A102A12270F0E11281128102A112710000D0500000000",
                    "pseudo-mode": "cool"
                },
                "temperature30": {
                    "data": "26004401100B110D120A130C110A11000337733812270E0F110C110B102A120B120A130A120B0F2B110C11281029120A13270F2A11280E2B1129100B100E12270F0E120A120B120B110D120A130A130A120C110B110D120B120A130A100E120A130A120B1228100D120A130A130A100E12270F0E120A112912270F2A120A1229100B110D120A130A120B0F0F110C120A100E120A130A120C120A130A130A102A120A13270F0E110B120B110D120B120D0F0E120A100F110A130A110D120A130A130B120A120B120B110D120A130A130A100E120A130A100E120A120B120B110D120A130B110B110D120A130A120B1228100F100A110E110A130A120B130C110A130A130A112A110A13270F0E120A100E12270F2A120A120B120B110D120A130A120B120B110D120A130A130B120A130A100E120A130A12291028100E110A130A140A100E11000D0500000000",
                    "pseudo-mode": "heat"
                },
                "on": "26004401100C120A130A110D120A1100033775361128110C120A130A13270E0F110C120A120B1228100D12270F2A120A12280E2B112911271129100B100E12270F0E120B120A130A120B130A130B130A130A130A100E120A130A100E120A120B0F0F110C12270F0E120C110A100E120A120B0F0F110C12270F2A12270F0E12270F0E120A120B100E120A130A110D120A130A130A100E120A120C110B100F11270F0E12270F0E110B120B110D120A130A120B120B100E110B120B110D120A130A120B0F0F100D120A130A120B0F0F110C120A100E120A130A110D120A130A120B120B110D120B120A130A100E120A1228110B110D120A130A120B0F0F120A130A110D120A13270F0E11280E0F110C110B102A12270F0E120A120C110B100E110B0F0F110C120A130A120B120B110D120A130A120B120B112A11270F0E120A120B1228102A0C000D0500000000",
                "off": "26004401110A110D120A130B120A1200033675360E2B100D110B100F11270F0E120A120C120A13270F0E12270E2B110C11280F2A12270F2A12270F0E110D102A110C110A130A100E120B120A110D120A130A130A120B120B110D120A130A120B120D110B100E120A130A100E120C110A100F110A130A12291028100D12270F2A120C110A100F110A130A120B0F0F100D120B0F0E110C110B100F110A130A12280E0F102A110C110A130A110D120A130A130A120C110B100F110B120A120B120C120A100E120A130A100F110B120A120B0F0F110C110B100F110A130A110D120A130B120A130A130A110D120A130A1228110B110D120A130A130A100E120A130A100E120A1228110B1129120A130A130A102A12270F0E110C0F0E120A120B120B1129120A130A130A100F110B120A120B130B120A12280E0F112911270F0E120A130B120A12000D0500000000"
            }
        },
        {
            "name": "A/C Switch",
            "type": "fan",
            "data": {
                "off": "26004401110A110D120A130B120A1200033675360E2B100D110B100F11270F0E120A120C120A13270F0E12270E2B110C11280F2A12270F2A12270F0E110D102A110C110A130A100E120B120A110D120A130A130A120B120B110D120A130A120B120D110B100E120A130A100E120C110A100F110A130A12291028100D12270F2A120C110A100F110A130A120B0F0F100D120B0F0E110C110B100F110A130A12280E0F102A110C110A130A110D120A130A130A120C110B100F110B120A120B120C120A100E120A130A100F110B120A120B0F0F110C110B100F110A130A110D120A130B120A130A130A110D120A130A1228110B110D120A130A130A100E120A130A100E120A1228110B1129120A130A130A102A12270F0E110C0F0E120A120B120B1129120A130A130A100F110B120A120B130B120A12280E0F112911270F0E120A130B120A12000D0500000000",
                "on": "26004401100C120A130A110D120A1100033775361128110C120A130A13270E0F110C120A120B1228100D12270F2A120A12280E2B112911271129100B100E12270F0E120B120A130A120B130A130B130A130A130A100E120A130A100E120A120B0F0F110C12270F0E120C110A100E120A120B0F0F110C12270F2A12270F0E12270F0E120A120B100E120A130A110D120A130A130A100E120A120C110B100F11270F0E12270F0E110B120B110D120A130A120B120B100E110B120B110D120A130A120B0F0F100D120A130A120B0F0F110C120A100E120A130A110D120A130A120B120B110D120B120A130A100E120A1228110B110D120A130A120B0F0F120A130A110D120A13270F0E11280E0F110C110B102A12270F0E120A120C110B100E110B0F0F110C120A130A120B120B110D120A130A120B120B112A11270F0E120A120B1228102A0C000D0500000000"
            }
        },
        {
            "name": "McIntosh",
            "type": "tv",
            "data": {
                "volume": {
                    "up": "2600900000012694131312381313113912131313123813371337131312381213133812131337131312131337131313131213131312381213133713131337133713371239121313371300050F000127941213133713131337131312141237133812381213133713131337131312381312131312381313111413131213133713131337131312381238133712381313133713000D050000000000000000",
                    "down": "2600900000012794121313381213123813131213133811391238121312391213123813131238121412381238121312141312131312381313111413131139123812381337131313371300050F000127941213133713131238131312131337133812381213133812131337121411391313123812381213131313121313123813131213131312381238133614381114133713000D050000000000000000"
                },
                "inputs": [
                    {
                        "name": "CD",
                        "type": "other",
                        "data": "2600900000012794121313381213133713131213133812381238121313381213133713131139131312131214121312141238121312141213133812381238123813131238123812381300050F000127941213133812131238131312131337133812381114133812131337121412381214121313131114121412381213131312131338123812381238131311391238133713000D050000000000000000"
                    },
                    {
                        "name": "CD2",
                        "type": "other",
                        "data": "2600900000012694131312381213123912131313123812381337121412381213133812131337131312381213131312131338121313131213131312381139133713131238133713371300050F000127941213123912131337131312131338123812381213123912131337131312381313123812131313121312391114121412131313113912381337131312381337133713000D050000000000000000"
                    },
                    {
                        "name": "DVD",
                        "type": "other",
                        "data": "2600900000012695121312381214123714131213123812391238121313381213133713131238121412381213123813381213121412131313121313371313121411391238123813371300050F000127941313113912131337131312131239123812381313123812131238131312381214113912131338123812131313111413131214123812131313113912381337133713000D050000000000000000"
                    },
                    {
                        "name": "AUX",
                        "type": "other",
                        "data": "26009000000127931313123813131139111412141139123812381313123813131238121313381213123813371338121312381313121313131114121412131239121313371337133812000510000126951213133713131238131311141337133812381213123912131238121411391213123912381238131311391213131312131214121312141337131312381238133713000D050000000000000000"
                    },
                    {
                        "name": "SERVER",
                        "type": "other",
                        "data": "2600900000012694121412381213133812131214123811391337131311391213133812131238121411141338121313371313121313131213133713131337131312381238133713371300050F000127941313123812131337131312141238123812381313123812131337131312381313121313371313123813131213131312131337131312381313123812381238133713000D050000000000000000"
                    }
                ],
                "on": "26006801000127921511103A111513371214101512391237143614121337111511391312153514121139143614121436141210151139131412130F16103A1214133712381015123A1200050E000125961213123A12121436151115101437103A103A1115113A121214361313103A1115133712381015113A121314121238141111151115123912121337103A1115113912000511000128921510133710161139111512131239113914370F16113A10151338131214370E16113912391118153515112A1212371213101611141338131213371337101611391300050F000126941115113911151238141214111535153515361412103911151238131412370F16113A103A1213123913121412123810151214131215361213143614361511133710000513000127931511103A1115123813130F16103A133813361412153515111436161014361016113911391314133614120F161139111515111411103A1115113A12381312103A11000D05",
                "off": "2600B00100012693151116341511143613121214163416341536121313371710163415111237121415351634153513381337151016341610141213121511160F16101437121212381600050C0001279511131634161015351313131215351634153712121238161016341512123712131535163515351337133715111634160F141213121214160F16101437121312381A00050A00012992160F1536131213371511160F163414371337160F16341412123816101634151112381337153516341535131313371511160F16101411131315101634161014361300050F0001299113131337151016341412131215361634163414111338121316341610133713121536163416341437123712141634160F1512121216111213170F1536121313371300050E0001299213131238160F1634151212121238173416341511133715101634151113371313153516341634143712371214163416101511121312131610160F1536121313371500050D000127931313153516101535131213131238163416341412133712131634161015361213133715351634153513381213163416101412121312131610160F15351512123712000D050000000000000000"
            }
        }
    ]
}

**Comment by kiwi-cam** [comment]
The only error of concern is: `[ERROR] McIntosh sendData (no device found)`

Have you looked at: #107 ?

**Comment by platini76** [comment]
are you saying that I cannot use the app?  maybe I understood bad...

**Comment by platini76** [comment]
oh sorry I found solution!

https://github.com/kiwi-cam/homebridge-broadlink-rm/tree/kiwi-cam-beta-1#documentation

thanks!

it is possible to make a triple switch for 3 RF command? or also single..

**Comment by masterfordev** [comment]
Like [#117](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/117) ?

**Comment by platini76** [comment]
I found solution, adding a window-covering
now I am trying to learn RF code from my rm pro and see that there is no solution for now..

**Comment by kiwi-cam** [comment]
We’ve had some success on that this week. Take a look at #45
