### ISSUE TITLE
Add Garage Door accessory

### ISSUE THREAD

**Issue by kiwi-cam** [kiwi-cam/homebridge-broadlink-rm#130]
Today my RM4 arrived. Everything works brilliantly. Thanks so much, Cam, for all the great work. Donation is on the way. Last question: I want to operate a garage gate (433 code already grabbed). I use the switch type to operate this. Is there any other kind of type I could use so I could say "Open garage door" and "Close garage door"? Thanks!

_Originally posted by @mkuerten in https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45#issuecomment-739336066_

It shouldn’t be too hard to add basic garage door support. I’ll take a look next week.

**Comment by mkuerten** [comment]
Thank so much, Cam, highly appreciated

**Comment by kiwi-cam** [comment]
Actually... you can tell I did that while on my phone putting the kids to bed. There is a Garage Door accessory already: https://lprhodes.github.io/slate/#garage-door-opener

Do you have any issues using `"type": "garage-door-opener"`?

**Comment by mkuerten** [comment]
Sorry, I overlooked this in the documentation. Works great. Can^t thank you enough to make this all happen!
