### ISSUE TITLE
HDMI Switch Setup

### ISSUE THREAD

**Issue by fratinize** [kiwi-cam/homebridge-broadlink-rm#135]
I have a HDMI Switch that allows me to switch any of 4 inputs to a choice of 2 outputs. Is there a "type" that fits? I guess technically it's a switch
But how do I show 2 groups of 4 switches? I'm guessing it's similar to a fan/ac or even lites
Is there a smililar that I am missing?
Thanx for any guidance you can offer

**Comment by masterfordev** [comment]
Hello, maybe you can just add the inputs (of your HDMI Switch) to the TV and set the IR Codes of the switch. I did something similar with the channels of my TV receiver, homekit does not allow inserting control numbers, then I added each channel as input:

![Screenshot](https://user-images.githubusercontent.com/29960705/101393222-f8bded80-3883-11eb-89a5-7b932a86cdd5.jpeg)

So just add the ir codes of your hdmi switch to the inputs of your tv.

**Comment by fratinize** [comment]
K will try this ty

**Comment by fratinize** [comment]
Would you mind sharing your code, little confused
Thanx

**Comment by masterfordev** [comment]
Sure: 

```
"inputs": [
                            {
                                "name": "1202 FOX Channel",
                                "type": "other",
                                "data": [
                                    {
                                        "data": "260050000001219312381237121211141138123711131237121311131238113712131212123812121114113812121213113811131114123711381212123712371213113811381213110005140001234a12000d05000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "260050000001229311371238121211141237113812121237111411131237123712131113123712131138123712131212123712131212123712131212123712371213113811381212120005140001234a12000d05000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "260050000001229212371238111311141237123712121237121311131138123712131113123811131138113812381014111311141114113810141212121311381138123711381113130005120001234b12000d05000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "260050000001229311371238121211141237113812121237111411131237123712131113123712131138123712131212123712131212123712131212123712371213113811381212120005140001234a12000d05000000000000"
                                    }
                                ]
                            },
                            {
                                "name": "1204 FX",
                                "type": "other",
                                "data": [
                                    {
                                        "data": "260050000001219312381237121211141138123711131237121311131238113712131212123812121114113812121213113811131114123711381212123712371213113811381213110005140001234a12000d05000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "260050000001229311371238121211141237113812121237111411131237123712131113123712131138123712131212123712131212123712131212123712371213113811381212120005140001234a12000d05000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "260050000001229212371238111311141237123712121237121311131138123712131113123811131138113812381014111311141114113810141212121311381138123711381113130005120001234b12000d05000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "260050000001219312371138121312121237123713121138121311131138123712131212113811141212123711381237121311131312113812371114121211141237123712371212120005140001234a12000d05000000000000"
                                    }
                                ]
                            }
]
```

My code send the rm code of each "number" (with that i can change channels), so you can use the rm code of each "hdmi in, In 1, In 2, In 3..." of your HDMI Switch.

**Comment by fratinize** [comment]
Hello Cam,
I am missing Something, here is my Code, I do not see this Device?

{
            "name": "HDMI Switch",
            "type": "tv",
            "host": "192.168.1.117",
            "data": {
                "inputs": [
                    {
                        "name": "A1",
                        "type": "other",
                        "data": [
                            {
                                "data": "2600680000012294103812131114111312131114111312131114113811381238103811381238113810151038111411141113111411131213113812131138123711381138123811381000050f0001264a11000c2b0001224b11000c2e0001224b11000c2c0001254a11000d050000000000000000000000000000",
                                "pause": 0.3
                            }
                        ]
                    }
                ]
            }
        }


I have more to Add to it, But I am not seeing this at all
Thank You again for all your help.
I do have 2 Others working just fine.

**Comment by fratinize** [comment]
Hey Cam,
I see this tv shows Up in the Logs, but it does not show in Homekit, What Am I missing?
Thanx

{
	"name": "HDMI Switch",
	"type": "tv",
	"subtype": "receiver",
	"host": "192.168.1.117",
	"data": {
		"on": "2600760106190a3a071c0a18091a053f0a180919073d0b3a063e0b390a17081d0918070005a10b17063f0918071c081a0a19053f093b081b061c0a19051c093c0a3a073d0a00059f08190a3b051d0919061d083c0a18061c093b083d083c0a3b061c09190a19050005a20919093b0a19061c0919071c093b093c051d09190919071c093b063e0a390a00059f0a19053f09190a19051d093b061c09190a39083e0a3a0a3b081a0a19051d0900059f071a093c061c09190a19051d093b073e09190a19051d0919093c073c0a3b060005a1091a083c0a19051d0919093b071b091a063e093b0a3b053f0a18091a061c0900059d0a1a083c081a091a061c0919093c053f0a18061d071b0919063e093c093b080005a1051c0a3a091a071b0919063e091a0919063e093b073e0a3a0a19051d0919080005a00a18063e0a18081b081a091a063e0a3a0a19061c0919061c083d093b063e0a00059f09180a3b051d0919081b073d0919061c093b0a3b073d0a3a071c09190a1905000d05",
		"off": "2600ee000519073d061c071c071b0919073d0a190a3a073c0b3b0a3a091a081a081a060005a20919093b0a18071c0a18093b061c0a3b091909190a19061c0a3a0a3b073d0a00059e0a180a3a071b0a19061c0a180a3b051d0a3a083d073d0a3a09190a190a18060005a407190a3a0a19051d0a18063f0a180a3a061c0a18071c081a0a3b053f0a3a0a00059e0b17063e0a190a18061c0a18073e0a180a3b053f0a3a083d071b0a18061c0a00059e09190a3b081a0a180a19053f0a18063e09190b18061c0a18073e083c0a3a070005a4051b073c0b18061d09180a19053f0a18073e0a3a0a3b053f0a18081a081b0a000d050000000000000000",
		"volume": {
			"up": "2600ba0104180b390a190b170a19083c0a18071c09190a3a083c0b3a0a3a09190b180800059f0a19093b0a18091a0a180919083c0b390a3b0a180b18081a0a18093c083c0a00059d0b170b3a081a0b18081a093b0a19081a0a18083c093b0b3a083c0b170b18080005a108190a3a0a19071b0a18061c0a3a0b3a083c0b170a1909190a19083c0a3a0a00059d0c17093b0b170b18081a0a3a091a0a180a19083c0a3a093b093b0b18081a0b00059d0a180a3b081a0a18091a071b0a3a063e0b390b18081a0b17091a093b0a3b0800059f09190a3a0b18081a0b170a3b081a0a19051d093b0a3a083c0b3a091909190b00059d0a180a3b09190a19081a0a18093b083c0b3a081a0b170b18081b093a093c080005a0081a0a3a0919091a0a18083c0a180b18081a0a3a063f093b0a3a081a0b180800059f0b18083c0a180a1909190a19083c0a3a0a3a081a0b18061c0a180a3b083c0a00059e0a180a3a081a0b18081a093a0c18081a0b170a3b053e0b3a063c0c190a18060005a2061c0b390b18081a0a18091a083c0a3b083b0b180a18061c0b18053f093b0b00059e0918063f09190a18061c0b39091a081a0b18053f093b1332053f0a18061d09000d05000000000000000000000000",
			"down": "2600460204000a2d051b0b39071c071b0a19051d093b081a071c093b063e073d093c081a081a070005a50519093b091a061c071b083d081a073d093c081a071c051d071b073d093b070005a1071b083d0919071b061d061c073d0919071c083c0a3a073e053f071b071c0900059e0919083d071b0a18071b073e0a18073e083c09190a190919071b063e0a3a0900059f071c053f0a18071c081a071b063e0a19071b063e0a3a0a3b0a3a091a051d0a00059e0a18073d061c0919071c093c0819073e0a3a091a051d0a18091a093b083c060005a209190a3a071c051d0919071c083c0919061d093b073d063e0a3a0a190a180900059f09190a3b0919071b061c093b091a093b0a3a071c0a18071c051d093b093b0a00059e09190a3a0a190a18071c051d073d071c081a083c063e0a3a093c09190a180900059f071c083c081a091a0919073d061c0a3a093c0a180919071c0a19063e053f0a00059d0b17083d0a180a180a190a18073e051d0a18073e083c093b063e0a18091a060005a2061c0a3a091a051d0919093b0a19083c083c0a18091a09190919073e0a3a0a00059e071b063e0a18071c061c0a18093c0a18071c053f0a3a093b093b0a19061c0a00059e0a18073d071c0a18071c053f0919093b0a3a091a061c0a18091a093b0a3a070005a1071b0a3b071b061d061b071c063e09190a19093b073e053f083c071c0918080005a30619093c081a0919071c073d081a063e073e081a071b0a19061c073d083d080005a1071a093b0919071c0c17051c073d081b051d073d0a3b083c073e081a071b07000d05"
		},
		"inputs": [{
			"name": "A1",
			"type": "other",
			"data": [{
				"data": "2600680000012294103812131114111312131114111312131114113811381238103811381238113810151038111411141113111411131213113812131138123711381138123811381000050f0001264a11000c2b0001224b11000c2e0001224b11000c2c0001254a11000d050000000000000000000000000000",
				"pause": 0.3
			}]
		}]
	}
}

**Comment by fratinize** [comment]
Im Good Now Well At least I can See it in Home, I apparently Must have had an Old one as I upraired an Existing and was able to re pair.
Thank You

**Comment by fratinize** [comment]
Since This isn't really a Switch How do we leave the icon to Just think it is ON always?
alwaysOn:true?
