### ISSUE TITLE
About temperatureupdatefrequency

### ISSUE THREAD

**Issue by burakcankose** [kiwi-cam/homebridge-broadlink-rm#137]
Hello,

I added an air conditioner with Broadlink. I'm reading the temperature over the temp file, but it only updates the degrees every 10 minutes even though I added the temperatureupdatefrequency. What should I do for it to update every 30 seconds?

**Comment by kiwi-cam** [comment]
Can you share the config?

**Comment by burakcankose** [comment]
"name": "Air Conditioner",
				"type": "air-conditioner",
                                 "temperatureFilePath": "/var/tmp/inside.txt",
                                 "temperatureUpdateFrequency": 150,
				"noHumidity": true,
				"data": {
					"off": "2600500000012...",
					"temperature30": {
						"pseudo-mode": "heat",
						"data": "2600500000012..."
					},
					"temperature16": {
						"pseudo-mode": "cool",
						"data": "2600500000012..."
					}
				}
			},

**Comment by kiwi-cam** [comment]
That looks fine - very similar to my own.  How do the logs look? You'll see a line `Dec 09 07:18:08 homebridge[12096]: [Broadlink RM] Air Conditioner onTemperature (21.23)` whenever the temperature is updated. Is this what you're seeing every 10 minutes?

**Comment by burakcankose** [comment]
Yes it looks like you said every 10 minutes i shared a screenshot.

![09AAAFD0-5F0D-46BE-84BC-2D5775D63FD5](https://user-images.githubusercontent.com/67308405/101540390-d61cf900-3997-11eb-9a89-996254dbe3da.jpeg)

**Comment by kiwi-cam** [comment]
Hang-on.... what version are you running. There was a recent change in the BETA to remove a 10 minute default on file and w1device sources.  That'd explain why mine is behaving differently.

Try installing the BETA and confirming... or hang tight and it should be updated in the latest release soon.

**Comment by burakcankose** [comment]
I did a beta update.  this works very well!  Thank you for your effort.  It provides control in 1 minute with the following form.  

"temperatureUpdateFrequency": 60,

**Comment by burakcankose** [comment]
Hi, sometimes it gives such error what could be the reason?
![B12094D6-8A9D-41B8-B669-6D47914176A9](https://user-images.githubusercontent.com/67308405/101835130-62701d00-3b4c-11eb-9fba-af0d025de21c.jpeg)

**Comment by kiwi-cam** [comment]
That looks like an access error. How are you updating the file? Could they be conflicting? Try getting your process to update the file without deleting and recreating it.
