### ISSUE TITLE
Group of devices

### ISSUE THREAD

**Issue by imtitanic** [kiwi-cam/homebridge-broadlink-rm#139]
Hey, hi!

Is there a way to group devices with this plugin? Something like this:

![homekit](https://user-images.githubusercontent.com/68301159/101586436-2a77a700-399f-11eb-82c3-283ab253f71a.jpg)

**Comment by obs945** [comment]
This is the same as what I mean in issue #126 
https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/126 
Looking forward for the enhancement.

**Comment by newt10** [comment]
This would require significant modification of how the plugin initializes and is loaded by homebridge. I can investigate this however it would be lower on the priority list.

**Comment by newt10** [comment]
@imtitanic can you share more details on which company outlet triggers this UI? This is a different type of switch compared to what I have seen in other grouped accessory implementations like LG TV so I this would help in understanding how to make this happen.

**Comment by Write** [comment]
Would love this too. At least multi switch in one UI (Like Homebridge messenger) would be awesome. 


![image](https://user-images.githubusercontent.com/541722/133744013-3383486a-9a43-47c0-90ff-5c8e08b7da5a.png)
Example of Homebridge Messenger
