### ISSUE TITLE
Tag releases on GitHub too

### ISSUE THREAD

**Issue by Cyberbeni** [kiwi-cam/homebridge-broadlink-rm#140]
The last release in the GitHub releases is at 3.5.7 from last year while it's at 4.3.8 on NPM.

It has at least 1 useful feature: showing how many commits are on the default branch since then. And you can also check the diff between the release and HEAD. Example can be seen here: https://github.com/Cyberbeni/install-swift-tool/releases

**Comment by kiwi-cam** [comment]
Nice tip. Obviously I'm learning as I go.  I'll do this in future - including today's BETA
