### ISSUE TITLE
Consider removing the fork link

### ISSUE THREAD

**Issue by Cyberbeni** [kiwi-cam/homebridge-broadlink-rm#141]
Since the source of the fork is discontinued (and links to this repository as a successor), I think it would be better to remove the fork link to avoid people thinking that this fork has only been created to pull request some changes to the original repository.

I've done this to a couple of my repositories (one of them was a fork of a template when I just wanted to use the template, the other one is a similar story to this), you can just message GitHub support and they will usually respond in a couple minutes: https://support.github.com/contact

(As far as I know you can also rename the repository to match the NPM package name and the old name will still redirect but I'm not 100% sure that it works in every use case, so if you want to do that, I would advise double checking everything first)

**Comment by masterfordev** [comment]
I don't see any problem with that. On the contrary, I think it is a recognition to the main creator of the plugin. On other case, it would perhaps be more useful to remove the previous plugin from npm because many people install that plugin without knowing that it no longer has support.
