### ISSUE TITLE
Getting SIGTERM and plugin kills HOOBS

### ISSUE THREAD

**Issue by amitmargalit** [kiwi-cam/homebridge-broadlink-rm#144]
![Broadlink sigterm](https://user-images.githubusercontent.com/75795671/101785623-a7249580-3b05-11eb-9308-5228a0c6ed9c.PNG)
This happens minutes after plugin starts running, I am also running EWE, TUYA, and electra smart.
Please help me find out what's wrong.

**Comment by kiwi-cam** [comment]
Duplicate of #115 

This should really be fixed in 4.3.9-beta.2.
