### ISSUE TITLE
Dependency on platform helper

### ISSUE THREAD

**Issue by newt10** [kiwi-cam/homebridge-broadlink-rm#146]
@kiwi-cam, I realized that the homebridge-platform-helper is usually a pain to maintain while doing development on this plugin. I was planning on bringing the work from that package into this plugin itself to make it easier to maintain and update the code for accessories/platform. What are your ideas on this? Will you be able to help with reviewing the changes?

**Comment by kiwi-cam** [comment]
I think that's a great idea. Coincidentally I created a fork of homebridge-platform-helper last week to fix a error in the MQTT code which has obviously always been there.  I think this is a great idea and I'd be happy to help.

The other question would be... should we (you 😄) do the same for the more complex broadlinkjs-rm module - now kiwicam-broadlinkjs-rm?

**Comment by newt10** [comment]
@kiwi-cam , let me get started with homebridge-platform-helper for now and then I will look into the broadlinkjs-rm module. I see that you have made quite a few changes there for supporting RM4.
