### ISSUE TITLE
Allow splitting window-coverings duration to 2 parts

### ISSUE THREAD

**Issue by Cyberbeni** [kiwi-cam/homebridge-broadlink-rm#149]
I have blinds that look like this: https://tamas-ablak.hu/wp-content/uploads/2019/07/muanyag-redony-.jpg
So when it completely closes, the separate parts will stack up together and when I start opening it, the first couple seconds will mean that the parts will start to separate but the bottom of the blinds will remain at the bottom. What I want is that if I set the blinds from 1-10% open, they should always stop when the parts are completely separated (based on the duration I set up for that part). And when I set the blinds from 11-99%, that should translate to 1-99% (based on total duration minus the other duration), so 55% will mean that my blinds are half open IRL.

Or maybe just making that the 1% would be fine instead of 1-10%

**Comment by newt10** [comment]
@Cyberbeni - can you share a video/gif of how this currently works?

**Comment by Cyberbeni** [comment]
https://youtu.be/3LasZWJkHeY
