### ISSUE TITLE
Move all documentation into this fork

### ISSUE THREAD

**Issue by kiwi-cam** [kiwi-cam/homebridge-broadlink-rm#151]
Currently documentation in this fork only holds customisations made from the original. To make things easier for noobs (feels like I was one not that long ago) it'd be better to have everything in one location.

**Comment by masterfordev** [comment]
Great! If you need help with that, I can help too.

**Comment by kiwi-cam** [comment]
I'm thinking of using the Wiki in Github, seems a good option for collaboration and structure.  Anyone got any other thoughts? 

@newt10 has created .md files in a docs folder for the heatercooler accessory, extending this is the obvious other option. 
Lastly we could use github pages [like the original fork](https://lprhodes.github.io/slate/) but I'm not sure how collaboration works there and it feels like more work getting the look/feel right.

**Comment by masterfordev** [comment]
I was reading the information about github pages and if it is possible to add contributors to the page, the page is developed in a branch of the plugin where you can give collaborator access. So it's a good option to consider.

**Comment by masterfordev** [comment]
And use a free template, like this one: https://jekyllthemes.io/theme/carte

**Comment by newt10** [comment]
@kiwi-cam - this would be a great idea, I like the idea of wiki as it provides more flexibility and less overhead in formatting the content. One thing I realize about this plugin is that config here has more flexibility than others and this is where formatting flexibility helps.
With wiki, I like the idea of easier management and creation of hierarchical docs.

**Comment by masterfordev** [comment]
Or if you prefer to keep the lprhodes design, the same template can be used: https://slatedocs.github.io/slate/

Or duplicate repository with the code and add the new options: https://github.com/lprhodes/slate

**Comment by masterfordev** [comment]
> @kiwi-cam - this would be a great idea, I like the idea of wiki as it provides more flexibility and less overhead in formatting the content. One thing I realize about this plugin is that config here has more flexibility than others and this is where formatting flexibility helps.
> With wiki, I like the idea of easier management and creation of hierarchical docs.

I think that an interface like the main plugin is more pleasant for the users. For the reason of being able to order the menu options and all the accessories, I don't have problems with the Wiki, both seem fine to me, but thinking about the users, I think they would find a page more friendly.
