### ISSUE TITLE
Broadlink BestCon device RM4C mini not discovered (type 62be)

### ISSUE THREAD

**Issue by karamkraz** [kiwi-cam/homebridge-broadlink-rm#16]
I've tried 4.2.6 and latest 4.6.7-beta.2 without success. There are no errors in log but device has not been discovered. Added host entry in config - no luck.
Using homebridge-broadlink-rm 3.6.22 I've got this:
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "62be". The device is connected to your network with the IP address xxx

**Comment by kiwi-cam** [comment]
The device 62be is included in the latest release 4.6.7
