### ISSUE TITLE
RM3 Mini D Code Sending Header Incorrect

### ISSUE THREAD

**Issue by jordan-wirth** [kiwi-cam/homebridge-broadlink-rm#161]
Hi there,

Looks like Device.code_sending_header is incorrect for RM3 Mini D 5f36. By default, the device is discovered but does not respond to learn or IR send commands. Previously, the modification [here](https://github.com/lprhodes/homebridge-broadlink-rm/issues/551) worked before today's release, but I'm assuming that wasn't supposed to happen since this isn't an RM4 or RM4+ device, it's RM3. So, the following change restores functionality for me in the new release:

`this.code_sending_header = this.rm4Type ? new Buffer([0xda, 0x00]) : new Buffer([0xd0, 0x00]);`

That's probably incorrect for other tested devices, but in the case of RM3 Mini D it works starting the buffer with [0xd0, 0x00]. I have no other Broadlink devices to test with, but I'd be happy to make a PR for a conditional exception for this specific device (better than my band-aid above) if you think it's a one-off for this model.

**Comment by kiwi-cam** [comment]
I spotted that 5f36 was setup as both an RM3 and an RM4 device - clearly this had some unexpected results. RM3 devices use an empty header, while RM4 devices use 0xda. 

What you're saying is that 5f36 is a third case that uses a 0xd0 header? Easy enough to add it as another case but I'm curious if there are other device types that need this header.

I've just pushed a new BETA version of the broadlinkjs-rm module with an exception for the 5f36. Could you try installing the BETA version of this plugin (which will pull the other module down) and see if this resolves the issue for you?

**Comment by jordan-wirth** [comment]
Yes, that works out of the box now. Ran `npm i kiwicam-broadlinkjs-rm@0.9.6-beta.0`, and I verified this overwrote my change with yours.

Very odd exception, but maybe it'll come up in newer firmware for RM3 devices? I ordered mine end of November from Amazon, found that other thread doing research as to why I couldn't get it talking. Seems like an odd thing for them to just change. 

If it helps to pin anything down here's the device's model info:
![IMG_7370](https://user-images.githubusercontent.com/20449792/102410137-1bf04780-3fbe-11eb-9a98-8528e9c706e8.jpg)

Thanks for looking into this so quick!

**Comment by kiwi-cam** [comment]
Thanks for testing so quickly. I'll push a new release now - it sounds like it could help a few people in https://github.com/lprhodes/homebridge-broadlink-rm/issues/551.

**Comment by jordan-wirth** [comment]
Just realized the learning no longer works for 5f36 either. Looks like it uses the RM4 request header:


    if (deviceType == 0x5f36) {
            this.code_sending_header = new Buffer([0xd0, 0x00]);
            this.request_header = new Buffer([0x04, 0x00]);
    }

This fixes learning for me, and control still works. I [made a PR](https://github.com/kiwi-cam/broadlinkjs-rm/pull/11) if you think it looks good. Sorry for the version headache - should've tested this too!

**Comment by kiwi-cam** [comment]
All merged and published. Thanks for your troubleshooting
