### ISSUE TITLE
Trouble with ceiling fan that has the light On/Off/Dimmer all in the same button

### ISSUE THREAD

**Issue by mwgoff75** [kiwi-cam/homebridge-broadlink-rm#162]
I've got the fan speeds and off working, but I'm having trouble getting the correct hex codes for the light.  The fan remote has a single button for the light.  Click once it turns on, click again it turns off, click and hold and it cycles from bright to dim and back again on a loop.  When the hex generated is acting like the click and hold function.  Is there a way to generate the hex code without holding the button down for more than a second or two?  I'm not sure if there are 2 discrete hex codes or if it's all about the length of the button press.  Any idea?  Thanks in advance.

Matt

**Comment by mwgoff75** [comment]
RM4 Pro.  Homebridge 1.2.4 running on an RPi4 with 4GB ram.

**Comment by newt10** [comment]
Have you checked out the advanced hex structure where you can also do repeats?

**Comment by aster1man** [comment]
I had the same problem.  I found that the broadlink cli (part of https://github.com/mjg59/python-broadlink) was able to generate the correct codes, which were then pasted into the homelink config.

If you are not familiar with working with a command line interface (cli) it is a bit intimidating and can be a bit of a learning curve.  I see you are using a Raspberry Pi 4 so maybe no problem.

My fan controller is from Home Depot its about 5 years old and has a hand held remote with 5 buttons (fan high, med, low, off, and light), seems similar.  My on/off (its a toggle so same code for both) is:
78c0720278ce04000f1c100d1f1c101c101c101d0f1d0f0e1e0e1e0f1d1d0f1e0e1e0e0f1e1d0f1d0f1d0f0f1d1d0f0f1d1e0e0f1e1d0d0001800f1f0f1d100e1e1c101c101d0f1d0f1d0f0e1e0e1e0f1d1d0f1d0f1e0f0e1e1d0f1d0f1d0f0f1d1d0f0f1d1e0f0e1e1d0d0001800f1f0f1d0f0e1f1c101c101d0f1d0f1d0f0e1e0e1e0f1d1d0f1d101c100e1e1d0f1d0f1d0f0e1e1d0f0f1d1d0f0f1d1e0d0001800f1f0f1d0f0e1e1d101c101c101c101c100e1e0e1e0e1e1d0f1d0f1d0f0f1e1d0f1d0f1d0f0e1e1d0f0f1d1d0f0f1d1e0d0001800f1f0f1d0f0e1e1d0f1d101c101c101d0f0e1e0e1e0e1e1d0f1d0f1d0f0f1d1e0f1d0f1d0f0e1e1d0f0f1d1d0f0f1d1e0d0001800f1f0f1d0f0e1f1c101c101c101d0f1d0f0e1e0e1e0f1d1d0f1d101d0f0e1e1d0f1d0f1d0f0e1e1d0f0f1d1e0e0f1e1d0d0001800f1f0f1d0f0f1e1c101d0f1d0f1d0f1d0f0e1e0e1e0f1d1d0f1e0f1d0f0e1e1d0f1d0f1d0f0f1d1d0f0f1e1d0f0e1e1d0d0001800f1f101c100e1e1c101d0f1d0f1d0f1d0f0f1d0f1d0f1d1e0f1d0f1d0f0e1e1d0f1d0f1d0f0f1d1e0e0f1d1e0f0e1e1d0d0001800f1f0f1d100e1e1d0f1d0f1d0f1d0f1d0f0e1e0f1d0f1d1e0e1e0f1d0f0e1e1d0f1d0f1d0f0f1d1e0f0e1e1d0f0e1e1d0e00017f0f1f101c100e1e1d0f1d0f1d0f1d0f1d0f0f1e0e1e0e1e1d0f1d0f1d0f0e1e1e0e1d0f1d0f0f1e1d0f0e1e1d0f0e1e1d0d0001800f1f101d0f0e1e1d0f1d0f1d0f1d101c100e1e0e1e0e1e1d0f1d0f1d0f0f1d1d0f1d0f1e0f0e1e1d0f0f1d1d0f0f1d1d0e00017f0f200f1d0f0e1e1d0f1d0f1d101c101c100e1e0e1e0e1e1d0f1f0d1d0f0f1d1d101d0f1d0f0e1e1d0f0f1d1d0f0f1d1e0d0005dc00000000"

**Comment by mwgoff75** [comment]
> Have you checked out the advanced hex structure where you can also do repeats?

Thanks for the suggestion, I am using that for the fan speeds settings to make sure it is received, but this is different.

M@

**Comment by mwgoff75** [comment]
> I had the same problem. I found that the broadlink cli (part of https://github.com/mjg59/python-broadlink) was able to generate the correct codes, which were then pasted into the homelink config.

That was a winner.  I had to learn how to install a python egg or whatever it is, but I was able to capture the on/off for the light and it works perfectly now.  Thanks for the help.

Now if I can figure out how to combine the fan speed and light into one HomeKit device.

M@
