### ISSUE TITLE
Broadlink HTS2 Temperature sensor readings shown within Aircon accessory

### ISSUE THREAD

**Issue by edugrt** [kiwi-cam/homebridge-broadlink-rm#165]
Hello, guys

I’m not quite sure if this behavior is intended or an issue or something I’ve done the wrong  way but my HTS2 temperature sensor readings are being shown within one of my Aircon accessories. Is there any way to show it separately as a sensor accessory?

I’ve tried to setup a temperature accessory with MQTT but I’ve failed all the times, it seems I can’t setup the MQTT broker properly. Would you guys recommend a comprehensive tutorial for this? Something made for dummies (LOL).

Thank you all. 

![76B04D5E-BAB4-4460-B21A-B12AFC92371A](https://user-images.githubusercontent.com/73726734/102710679-c4d6c500-4292-11eb-9fd4-b445b33f579a.jpeg)

**Comment by kiwi-cam** [comment]
This should all be supported. What would you like the temperature sensor and Aircon to display as a temperature value? Share your config and I'll help you get it the way you're after.

These accessories will use the HTS2 readings by default. If you specify another source (pseudo, mqtt, or file) it'll use that instead.
