### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by AlexMaghen** [kiwi-cam/homebridge-broadlink-rm#167]
Hi. I'm excited about this plugin but I'm kind of lost on initial setup. Here's what I've done so far:
1. I have set up BroadLink RM4 Pro & the associated iOS App (and I've tested that it controls a TV, for example, just fine)
2. I have turned off the "Lock" setting, which your docs say is required to auto-discover, etc.
3. I have a RaspberryPi configured and working properly with Homebridge on the same WiFi network as the RM4 Pro
4. I have installed this plug-in (first I did it by installing through the Homebridge Plugins UI and then I installed it again using the command line with -g, just in case, as your docs recommend). Install was successful.
5. Now that that's done, though, I'm STUCK. The install of the Plugin doesn't seem to have made any changes to the Homebridge config file (no new "platform" was created or anything). 

I looked at your deeper documentation on the homebridge config file and I'll admit I'm a little lost. How can I get this one RM4 Pro setup in Homebridge so that I can then use Homebridge to learn remote signals and create Accessories accordingly? Your docs seem to say it does that, but I'm a little lost as to how.

I am blown away that the community (you) do wonderful work like this and I'd really appreciate ($ :)) any detailed help you can provide!

Thanks!

Alex

**Comment by kiwi-cam** [comment]
Unfortunately one problem we haven't been able to crack is the complexity of our configuration. With all the different accessory configuration options, nested inside the platform getting it to display in the UI is incredibly complex... so for now at least you'll need to modify your config.json manually.  Start simple with the platform and a switch, then extend (creating a backup each time so you can roll back if needed): https://broadlink.kiwicam.nz/#installation

**Comment by AlexMaghen** [comment]
@kiwi-cam - YES, got it. Played with it and got it to work. This thing is f'ing impressive! :) Thank you.
