### ISSUE TITLE
Some Help - Reverse Cycle Aircon

### ISSUE THREAD

**Issue by mrblack7** [kiwi-cam/homebridge-broadlink-rm#168]
First of all, thanks for continuing the great work on this plugin! 

I recently upgraded from a RM Pro to a Pro 4 and also got some split system (reverse cycle aircons) put in so I am trying to configure this to work with them.

I'd like to know what the difference is between 'heater-cooler' and 'airconditioner' accessory types? Or possibly a better question, which one should I use for control of this type of Mitsubishi reverse cycle aircon?

I have tried both, but I can't seem to get the thing to turn on, but the off command seems to work.....

**Comment by newt10** [comment]
air-conditioner is a representation of a thermostat device which controls traditional whole house ACs (similar to ones found in USA). Heater-cooler represents any heater or ac typically the standalone devices like split ACs, tower heaters, portable or window ACs. 
Can you share more details on your device type and also share a config.json

**Comment by mrblack7** [comment]
Ok, so I just added a heater-cooler type with the following config.json

Good news is at least now I am getting it to turn ON. I learned the IR code from the remote by selecting the appropriate temperature and mode, then turning OFF the remote, then learning the ON command which would set it to the last temp that was set on the remote...

Question is, how or where does it get the current room temp from? I see this `[Broadlink RM] Aircon getCurrentTemperature: 24` in the logs. Is it getting it from the sensor cable?

> {
>                     "name": "Aircon",
>                     "type": "heater-cooler",
>                     "data": {
>                         "cool": {
>                             "on": "26004c026c390e281027100c0f0c100c0f280f0c100c0f280f280f0c0f280f0d0f0c0f280f280f0c0f281027100c0f0c0f28100c0f0c0f280f0d0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c0f0d0e0d0f0d0f0c0f0d0f0c0f0c1027100c0f0c100c0f0c100c0f280f280e0d0f0d0f0c0f0d0f280f270f0d0f0c100c0e0d0f0d0f0c10280f27100c0f280f0c0f28100c0f27100c0f280f0c100c0f0c1027100c0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c0e0d100c0e0d100c0f0c100c0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c1027100c0f0c100c0f0c100c0f0c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c102710270e290e0d100c0f0c100c0f0001726d380e280f28100c0f0c100c0f280d0e100c0f280f280f0c10270d0f0f0c102710270f0c102710270f0d0f0c1027100c0e0d10270d0e100c0f0c0f0d0e0d0f0d0e0d0e0e0f0c100c0e0d0f0d0e0d0f0d0e0d0f0d0e0d0d0f0e0d0e0d0e29100c0e0d0f0d0e0d0f0d0e290d2a0d0e0f0d0e0d0f0d0e280f280e0e0e0d0e0e0e0d0e0e0e0d0f280e29100c0e290e0d0f280d0e0f280f0d0e290d0e0f0d0d0e0f280d0f0e0d0f0d0e0d0e0e0e0d0f0d0d0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0d0e0f0d0d0e0f0d0e0d0f0d0e0d0d0f0e0d0d0e0f0d0d0e0f0d0d0e0e0e0d0e0e0e0d0e0e0e0e0d0f0d0d0e0e290d0f0d0e0e0d0e0e0d0e0e0e0d0e0e0e0e0d0e0e0d0e0f0d0e0d0e0e0e0d0f0d0e0d0e0e0d0e0d2a0d2a0e290f0c0f0d0e0d0e0e0e000d0500000000000000000000",
>                             "off": "26004c026c390c2b0d2a0d0e0c0f0d0f0c2b0c100c100d290d2a0d0e0d2a0d0f0c0f0d2a0d2a0c0f0d2a0d2a0d0f0c0f0d2a0e0e0c0f0d2a0d0f0c0f0d0f0c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0c100c0f0c100c0f0c100d0e0c0f0d2a0d2a0d0f0d0e0d0f0c0f0d2a0d2a0e0e0c0f0c100c0f0c0f0d0f0c2b0c2b0c0f0e290d0f0d2a0e0d0c2b0c0f0d2a0e0f0b100e0e0b2b0c0f0d0f0c100e0d0d0e0d0f0e0d0d0f0c100e0d0c0f0f0c0e0f0b0f0d100e0c0d0f0e0c0e0f0e0d0d0f0e0e0c0f0e0d0d0f0e0d0e0e0c100e0a0f0f0f0a100e0f0c0d0f0c0f0f0d0d0e0f0d0c2b0f0c0e0e0e0d0e0e0e0d0e0e0e0e0e0c0d0f0c0f0f0d0c0f0f0d0e0d0e0e0f0c0f0d0d0e0e0e0c2b0e290e280f0d0f280f280f280f0001716d380e290f280e0e0f0c0e0e0c2a100d0e0d0e280f280f0e0e280f0c0e0e0c2b10270f0d0e290e280e0e0e0e0e280d0f0d0e0f280f0d0e0d0f0d0e0d0d0f0d0e0e0e0d0e0d0f0e0b0f0e0f0d0e0e0e0d0d0e0d0f0d0e0d0e0f0d0e0d0e0e0f0d0e0d0f0d0e0d0d0f0d290f28100c0e0e0e0d0e0e0e280e290e0d0e0e0e0e0e0d0d0f0e0d0f270f280f0d0e29100b0f280f0d0e290f0d0e28100c0e0e0e0e0d280f0d0f0d0e0d0e0e0e0d0d0f0e0d0f0d0e0d0f0d0e0d0f0d0e0e0d0d0e0e0e0d0f0c0f0d0d0e0f0e0e0d0e0d0d0f0e0d0d0f0e0d0f0d0e0d0e0d0f0d0d0f0e0d0d0f0d0e0e0d0e0d0f0d0f0d0e280f0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0e0e0d0e0e0e0d0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e290e280f280f0d0f270f2810270f000d0500000000000000000000",
>                             "heat": {
>                                 "on": "26004c026f3610271027100c0f0d0e0d0f270f0d0f0d0e281027100c0f280f0d0e0d0f280f280f0c0f281027100b0f0e0e28100c0e0d0f280f0c0f0d0f0d0e0d0f0d0e0d0f0d0e0e0d0e0e0e0d0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0d0f0d0e280f0d0f0d0e0d0f0d0e0d0f270f0e0e0d0e0d0f0d0e0d0f28100b0f0d0f0d0e0e0e0d0e0e0e0d0e0d0e0e0e0e0d280f0e0e280f0d0e280f0d0f281027100c0e0d0f27100c0f0d0f0c0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0d0f0d0e0e0e0d0e0d0f0d0e0e0e0d0e0d0f0d0e0d0e0e0e0d0e0d0f0d0e0d0f0d0e0e0e0d0e0d0f0d0e0d0f0d0e0d0f0d0e0e0e0d0e0e0d0e0e0e0d0d0f0d0e0e0e0d0e0e0e0e0d0d0f0d0e0e0e0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0e0e0e0d0e280f281027100c0f280f280f0001726f360f281027100b0f0d0f0d0e280f0d0f0d0e280f28100c0e280f0d0f0d0e281027100c0f271027100d0e0d0e28100c0f0d0e280f0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0e0d0e0e0d0e0e0e0d0e0e0e0d0e0d0f0d0e0e0e28100b0f0d0f0d0e0c100c0f28100b0f0e0e0d0e0d0f0d0e280f0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e280f0d0e280f0d0f28100c0e280f28100c0f0d0e280f0d0f0d0e0d0e0e0e0e0d0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0d0f0d0e0e0e0d0e0d0e0e0e0d0f0c0f0d0e0e0e0d0e0e0e0e0d0e0e0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0e0d0e0e0e0d0e0e0d0e0e0e0d0e0e0e0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0e0e0e0d0e0e0e280f281027100c0e280f280f000d0500000000000000000000",
>                                 "off": "26004c026c390c2b0d2a0d0e0c0f0d0f0c2b0c100c100d290d2a0d0e0d2a0d0f0c0f0d2a0d2a0c0f0d2a0d2a0d0f0c0f0d2a0e0e0c0f0d2a0d0f0c0f0d0f0c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0c100c0f0c100c0f0c100d0e0c0f0d2a0d2a0d0f0d0e0d0f0c0f0d2a0d2a0e0e0c0f0c100c0f0c0f0d0f0c2b0c2b0c0f0e290d0f0d2a0e0d0c2b0c0f0d2a0e0f0b100e0e0b2b0c0f0d0f0c100e0d0d0e0d0f0e0d0d0f0c100e0d0c0f0f0c0e0f0b0f0d100e0c0d0f0e0c0e0f0e0d0d0f0e0e0c0f0e0d0d0f0e0d0e0e0c100e0a0f0f0f0a100e0f0c0d0f0c0f0f0d0d0e0f0d0c2b0f0c0e0e0e0d0e0e0e0d0e0e0e0e0e0c0d0f0c0f0f0d0c0f0f0d0e0d0e0e0f0c0f0d0d0e0e0e0c2b0e290e280f0d0f280f280f280f0001716d380e290f280e0e0f0c0e0e0c2a100d0e0d0e280f280f0e0e280f0c0e0e0c2b10270f0d0e290e280e0e0e0e0e280d0f0d0e0f280f0d0e0d0f0d0e0d0d0f0d0e0e0e0d0e0d0f0e0b0f0e0f0d0e0e0e0d0d0e0d0f0d0e0d0e0f0d0e0d0e0e0f0d0e0d0f0d0e0d0d0f0d290f28100c0e0e0e0d0e0e0e280e290e0d0e0e0e0e0e0d0d0f0e0d0f270f280f0d0e29100b0f280f0d0e290f0d0e28100c0e0e0e0e0d280f0d0f0d0e0d0e0e0e0d0d0f0e0d0f0d0e0d0f0d0e0d0f0d0e0e0d0d0e0e0e0d0f0c0f0d0d0e0f0e0e0d0e0d0d0f0e0d0d0f0e0d0f0d0e0d0e0d0f0d0d0f0e0d0d0f0d0e0e0d0e0d0f0d0f0d0e280f0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0e0e0d0e0e0e0d0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e290e280f280f0d0f270f2810270f000d0500000000000000000000"
>                             }
>                         }
>                     }
>                 }

**Comment by newt10** [comment]
Right now, it is not getting it from the sensor cable. We are working on an enhancement to get it from a sensor cable or a temperature file. We will keep you posted.

**Comment by mrblack7** [comment]
At this point all I get is a switch to turn it On/Off in the Home App......

How do I get it so I can select a temperature?
