### ISSUE TITLE
TV Not showing up in Homekit

### ISSUE THREAD

**Issue by korgoth** [kiwi-cam/homebridge-broadlink-rm#169]
Hello, 

i am trying to setup the TV configuration for home kit as follows:

        {
            "name": "TV LivingRoom",
            "type": "tv",
            "host": "xxx.xxx.xxx.xxx",
            "subType": "TV",
            "data": {
                "on": "HEX...",
                "off": "HEX...",
                "remote": {
                    "select": "HEX...",
                    "arrowUp": "HEX...",
                    "arrowDown": "HEX...",
                    "arrowLeft": "HEX...",
                    "arrowRight": "HEX...",
                    "exit": "HEX...",
                    "back": "HEX..."
                },
                "volume": {
                    "up": "HEX...",
                    "down": "HEX..."
                }
            }
        }
        
The TV shows in HomeBridge web interface and i am able to turn it on/off, but it never reaches the Home app on my iPhone. 
All other accessories added to the RM are there - lights, ACs, plugs - but tv doesn't show up. 
I have tried to follow the documentation and examples for the required parameters - it seems that there are none, but i can't get this to work. 

Does anyone have any idea?

**Comment by masterfordev** [comment]
You added the tv in the home app?
(Add device/i dont have a code/select your tv/use your homebridge code).

**Comment by masterfordev** [comment]
@kiwi-cam you forget add that information to the documentation?

**Comment by korgoth** [comment]
Oh, that did it. Thank you @masterfordev

I only see the on/off button - how can i see the other buttons i have setup for this device - directional, volume etc? I tried accessability options -> apple tv remote -> show directional buttons (though i don't think it has something to do with) but that doesn't help

**Comment by masterfordev** [comment]
Yes. You have to use the "Control Remote" app, and for volume, open that app and use the physical buttons for volume.

**Comment by masterfordev** [comment]
See this: [tutorial](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/102#issuecomment-720813760)

**Comment by korgoth** [comment]
Got it, thanks again @masterfordev

Closing this now.
