### ISSUE TITLE
Unable to detect RM4 in Homebridge

### ISSUE THREAD

**Issue by bmpreston** [kiwi-cam/homebridge-broadlink-rm#172]
I am unable to detect the RM4 in Homebridge with the device CONFIRMED as unlocked.  Can you manually add the RM4?  Also, where do you get the device Hex codes?  Or is that not necessary once the device is set up in the app, then allowed to load into Homebridge.

Thanks

**Comment by Edsonytic** [comment]
I would recommend reading this: [https://broadlink.kiwicam.nz](https://broadlink.kiwicam.nz)

**Comment by bmpreston** [comment]
I did which is why I posted for assistance. The document states to post for assistance. But thanks anyways. I returned the device.
