### ISSUE TITLE
Feature Request:  Update Status without sending IR/RF data

### ISSUE THREAD

**Issue by flipoidix** [kiwi-cam/homebridge-broadlink-rm#177]
Hi, 

Thank you very much for this plugin, 

I am updating the status of the device using the Rest API of the homebridge, but this triggers the sending of the hex code.
Is it possible to update the status in a similar way that the option "pingIPAddressStateOnly" works? In this case I dont have an IP to ping to, so I would like to have another alternative way of changing the status without sending the code.

PS: this is the payload I'm using:

    {
        characteristicType = "Active",
        value = 1
    }

Would this be usefull to someone?
Thank you!

**Comment by darrenkhu** [comment]
Interested to hear peoples workaround on this as well,

**Comment by newt10** [comment]
Can you share more information on how you have this setup and configured?

**Comment by flipoidix** [comment]
sure, no problem. 

I have a Fibaro Gateway ( Z-wave ) and have power monitoring for the plug where the tv is connected.
I can make a routine that sends a json using the Rest api of the homebridge ( [https://github.com/oznu/homebridge-config-ui-x/wiki/API-Reference](url) ) when the power changes.

If I send the payload 
{
    characteristicType = "Active",
    value = 1
} for the id of the TV it changes to active, but it also triggers the sending of the command ( as i I have pressed the button on homekit ).

Since the ping option to change the status of the device does not send the hex command, I would like a similar option just by changing a variable on the TV switching it off or on

Maybe if we have a vitrual on / off button for the tv just to update its status without sending it is easier to implement? ( i could trigger it using homekit automation for example

this would be great not only for the TV but for other appliances since they can be operated locally bypassing homekit


> Can you share more information on how you have this setup and configured?

**Comment by newt10** [comment]
I believe this would require changes in the API itself, the API is asking the plugin to turn the device on by setting its active property. Since broadllink is stateless device there is no way for the plugin to know the true state of the device and accordingly decide to turn it on using the command or skip it.
Let me know if this makes sense.

**Comment by flipoidix** [comment]
> I believe this would require changes in the API itself, the API is asking the plugin to turn the device on by setting its active property. Since broadllink is stateless device there is no way for the plugin to know the true state of the device and accordingly decide to turn it on using the command or skip it.
> Let me know if this makes sense.

what if we dont use the api? can you make a virtual on/off accessory button to work as the ping command works when it cannot ping or ping successfully? ( just updating the status? )
