### ISSUE TITLE
Adjusting the sound in the TV

### ISSUE THREAD

**Issue by paurus70** [kiwi-cam/homebridge-broadlink-rm#178]
Good day to all. Just started learning this plugin. Managed to add a lot of devices. Faced a problem regarding TV. I use it to control the receiver. Managed to add input switching and on/off button. I can't add sound adjustment. The volume control button does not appear in HomeKit. Am I missing something? Here is an example of my configuration. Thank you for any help.
 {
                    "name": "Усилитель",
                    "type": "tv",
                    "subType": "Receiver",
                    "data": {
                        "volume": {
                            "up": "260...000",
                            "down": "2600........000"
                        },
                        "remote": {
                            "select": "SELECT_HEX_CODE",
                            "arrowUp": "UP_HEX_CODE",
                            "arrowDown": "DOWN_HEX_CODE",
                            "arrowLeft": "LEFT_HEX_CODE",
                            "arrowRight": "RIGHT_HEX_CODE",
                            "playPause": "PAUSE_HEX_CODE"
                        },
                        "on": "2600d80...000000000",
                        "off": [
                            {
                                "data": "2600d800000...00000000000000",
                                "pause": 0.3
                            },
                            {
                                "data": "b1c02403009f0......080005dc0000",
                                "pause": 0.3
                            }
                        ],

**Comment by paurus70** [comment]
P.S. The "Remote" buttons also don't appear in HomeKit.

**Comment by fratinize** [comment]
Check your control
Center on your iPhone u will c your devise and use your phones buttons

**Comment by paurus70** [comment]
Thanks for the answer. Could you elaborate?. I have now so.
![IMG_6026](https://user-images.githubusercontent.com/76495931/102934835-fda2b400-44b5-11eb-95c5-6f52e6c0d063.PNG)

**Comment by masterfordev** [comment]
https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/102#issuecomment-720813760

**Comment by paurus70** [comment]
Thank you very much! It really works as expected!
