### ISSUE TITLE
TV subtype - doesnt seem to expose different icons to homebridge / homekit

### ISSUE THREAD

**Issue by steverae68** [kiwi-cam/homebridge-broadlink-rm#182]
I have a Pioneer AMP which i have exposed in homebridge as a TV to be able to access the other functions such as volume / input etc.
I have the subtype set to receiver yet it still shows an icon as a TV

Are other icons available as my TV (pioneer) has no external speakers so all audio is controlled through this AMP.

Thanks - also love the plugin btw, only recently discovered these broadlink devices and they are fab.

**Comment by masterfordev** [comment]
https://broadlink.kiwicam.nz/#tv there have the info about tv & subs.

**Comment by steverae68** [comment]
Hello, this is exactly the information I have followed - hence raising the issue that it doesn't work as expected.

My Receiver still shows as a tv no matter what subtype i set

**Comment by masterfordev** [comment]
You removed it and added it again?

**Comment by steverae68** [comment]
Yes, I've tried every option listed in the docs.

Here is my config section.

        {
                    "name": "Pioneer Amp",
                    "type": "tv",
                    "subType": "receiver",
                    "data": {
                        "on": "HEXCODE",
                        "off": "HEXCODE",
                        "volume": {
                            "up": "HEXCODE",
                            "down": "HEXCODE"
                        },
                        "inputs": [
                            {
                                "name": "Apple TV",
                                "type": "hdmi",
                                "data": "HEXCODE"
                            },
                            {
                                "name": "Game",
                                "type": "hdmi",
                                "data": "HEXCODE"
                            }
                        ]
                    }
                },

**Comment by ddudau** [comment]
@steverae68 the code you've put here... it works well for you? Do you see the volume buttons?
because I can only see on/off and inputs :(
But I see the receiver image :)

**Comment by masterfordev** [comment]
> @steverae68 the code you've put here... it works well for you? Do you see the volume buttons?
> 
> because I can only see on/off and inputs :(
> 
> But I see the receiver image :)

[#102](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/102#issuecomment-720813760)

**Comment by ddudau** [comment]
> > @steverae68 the code you've put here... it works well for you? Do you see the volume buttons?
> > because I can only see on/off and inputs :(
> > But I see the receiver image :)
> 
> [#102](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/102#issuecomment-720813760)

Wow, it works, thanks a lot.

**Comment by fratinize** [comment]
Hmm I still see a tv
In both the remote and inside hk

**Comment by steverae68** [comment]
I decided to apply the first rule of IT to this problem - turned it all off and completely reset everything and boom - its now showing the receiver icon as id hoped - i also took the chance to update to the latest version of this plugin
issue for me is now resolved
