### ISSUE TITLE
Lost my tv in control center

### ISSUE THREAD

**Issue by fratinize** [kiwi-cam/homebridge-broadlink-rm#185]
I updated my Apple TV the other day and all of a sudden I no longer see my tv in my control center
Shows and Works fine in home app, but it's not in my control center 
I have restarted homebridge didn't help restarted my phone and all of a sudden it's there and works as expected, however, if I come back later it's no longer there
Did Apple break something?

**Comment by fratinize** [comment]
Update
Turned off updated Apple TV and used my back up which has not been updated 
Was able to add my tv worked once then gone
Again works in home kit but not showing in control center remote
I can remove them re add but then it disappears 
Thoughts?

**Comment by masterfordev** [comment]
You have a screenshot of your Control App?

**Comment by fratinize** [comment]
So today I went to take a screenshot of my missing hb tv 
I actually have 2 hb tv 
I looked at my control center and wow they are there I even checked that it worked it did changed the volume, it responded correctly, 
then all of a sudden I got a message saying my device was unavailable choose ...
Neither was available only the native so I am guessing it’s not apples update since I have disabled it being a hk hub. I have a second which I did not update which is my current hub
Any ideas ?

**Comment by masterfordev** [comment]
No idea. I have 3 tvs and 2 STB and all work fine. 

![image](https://user-images.githubusercontent.com/29960705/103573917-49793400-4e8c-11eb-858b-07ea07c543d8.jpeg)

They appear there even if the TVs are off.

**Comment by masterfordev** [comment]
You can share your config please?

**Comment by fratinize** [comment]
Honestly it was very Consistent up until a week or so ago

{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": false,
    "hideWelcomeMessage": true,
    "accessories": [
        {
            "host": "192.168.1.117",
            "name": "Inside Learn",
            "type": "learn-code"
        },
        {
            "name": "Cool Zone Fan",
            "type": "fan",
            "host": "192.168.1.118",
            "data": {
                "on": "26006c01240f290e0d2b290f290e0d2b0d2b0d2a0e2a0d2b290e0d000107290e290f0d2b290e290f0c2c0d2a0e2a0d2b0d2a290f0d000107280f290f0d2a290f290f0c2c0d2a0d2b0d2a0e2a290f0d000107280f290e0d2b2810290f0c2b0e2a0d2b0d2a0e2a290f0c000107290f290e0d2b290f290e0d2b0d2b0d2a0e2a0e2a2b0d0c000107290e290f0d2b290f290e0d2b0d2b0d2a0e2a0d2b290f0d000106280f290f0d2b2810290e0e2a0d2b0d2a0e2a0d2b290e0d000107290e2a0e0d2b290f290e0d2b0d2b0d2a0e2a0d2b290f0c000107290e290f0d2b2810290e0d2b0d2b0d2a0e2a0d2b290f0c000107290f290e0d2b290f290e0d2b0d2b0d2b0d2a0d2b290f0c000107290f280f0d2b290f280f0d2b0d2b0d2a0e2a0d2b290f0c000107290e290f0d2b290f290e0d2b0d2b0d2a0e2a0d2b290e0d000107290e290f0c2c280f290f0c2c0d2a0e2a0d2b0d2a290f0d000106290f290f0c2b290f290f0c2b0e2a0d2b0d2b0d2a290f0c000d0500000000000000000000",
                "off": "2600b201240f290e0e2a290f290e0d2b0d2b0d2a0e2a0d2b0d2a29ec290f290f0c2b290f290f0c2b0e2a0d2b0d2a0e2a0d2b29ec290f280f0d2b280f290f0d2b0d2a0e2a0d2b0d2a0e2a28ed290f290e0d2b290f290e0d2b0e2a0d2b0d2a0d2b0d2b29eb290f290f0d2b280f28100c2c0d2a0e2a0d2b0d2a0e2a28ed290f290e0d2b290f290e0d2b0d2b0d2b0d2a0d2b0d2a29ec290f28100d2a290f290f0c2b0e2a0d2b0d2a0e2a0d2b29ec280f290f0d2b290e290f0d2b0d2b0d2a0d2b0d2b0d2a29ec290f290f0d2a2810290f0c2b0e2a0d2b0d2a0e2a0d2b28ed290e290f0c2c280f290f0c2c0d2a0e2a0d2b0d2a0e2a29ec2810290e0e2a290f280f0d2b0d2b0d2b0d2a0e2a0d2b29ed280e290f0d2b290e290f0d2b0d2a0e2a0d2b0d2a0e2a29ec290f290e0d2b290f280f0e2a0d2b0d2a0e2a0d2b0d2b29eb2a0e290f0d2b290e290f0d2b0d2a0e2a0d2b0d2a0e2a29ec2810280f0d2b290f290e0e2a0d2b0d2a0e2a0d2b0d2b29eb290f290f0c2b2b0d2a0e0d2b0e290e2a0d2b0e290f2928ed290f290e0d2b2a0e2a0d0f290d2b0d2a0e2a0e2a0e292aeb2a0e2a0e0e292a0e2a0e0c2b0f290e2a0e290f290d2b28000d0500000000",
                "swingtoggle": "2600a001250d2a0e0e2a2a0d2b0d0f290e292b0d0f290e290f290f0001062a0e2a0d0f292a0e2a0e0e290f292a0e0e290f290f290e0001072a0d2b0d0f292a0d2b0d0f290f292a0d0f290f290e290f0001062a0e2a0e0e292a0e2a0e0e290f292a0e0e290f290f290f0001062a0d2a0e0f29290f290e0f290f29290e0f290f290e2a0e000107290e290f0d2b290e2a0e0e2a0e292a0e0e2a0e2a0e290f000107290d29100d2a290f28100d2b0d2a290f0c2c0d2a0e2a0e000107281028100c2b290f28100c2b0d2b290f0c2c0c2b0d2b0d000108281028100c2b290f28100c2c0c2b290f0c2c0c2b0d2b0d000108281028100c2b290f28100c2b0d2b28100c2c0c2b0d2c0c0001082810280f0d2b281028100c2b0d2b28100c2c0c2b0d2b0c0001092810280f0d2b281028100c2b0d2b28100c2b0d2b0d2b0c0001092810280f0d2b2810280f0d2b0d2b28100c2b0d2b0d2b0c000109280f290f0d2b2810280f0d2b0d2b280f0d2b0d2b0c2c0c000109280f290f0c2c280f290f0d2b0c2c280f0d2b0d2b0c2c0c000109280f28100c2c280f290f0c2c0c2b290f0d2b0c2b0d2b0d000d05000000000000"
            }
        },
        {
            "name": "Outside TVs",
            "type": "tv",
            "subtype": "receiver",
            "host": "192.168.1.118",
            "data": {
                "on": "26007800000125951314113a103a1115101511141114113a11391115113912141114111411151114113a1139113a113911151114111411151114111411151114113a1139113a113a110005ad00012a4c11000c870001284c11000c870001284c11000c8500012a4d10000c8400012a4c12000c850001294c12000d050000000000000000000000000000",
                "off": "26007800000125951314113a103a1115101511141114113a11391115113912141114111411151114113a1139113a113911151114111411151114111411151114113a1139113a113a110005ad00012a4c11000c870001284c11000c870001284c11000c8500012a4d10000c8400012a4c12000c850001294c12000d050000000000000000000000000000",
                "volume": {
                    "up": "2600ba0104180b390a190b170a19083c0a18071c09190a3a083c0b3a0a3a09190b180800059f0a19093b0a18091a0a180919083c0b390a3b0a180b18081a0a18093c083c0a00059d0b170b3a081a0b18081a093b0a19081a0a18083c093b0b3a083c0b170b18080005a108190a3a0a19071b0a18061c0a3a0b3a083c0b170a1909190a19083c0a3a0a00059d0c17093b0b170b18081a0a3a091a0a180a19083c0a3a093b093b0b18081a0b00059d0a180a3b081a0a18091a071b0a3a063e0b390b18081a0b17091a093b0a3b0800059f09190a3a0b18081a0b170a3b081a0a19051d093b0a3a083c0b3a091909190b00059d0a180a3b09190a19081a0a18093b083c0b3a081a0b170b18081b093a093c080005a0081a0a3a0919091a0a18083c0a180b18081a0a3a063f093b0a3a081a0b180800059f0b18083c0a180a1909190a19083c0a3a0a3a081a0b18061c0a180a3b083c0a00059e0a180a3a081a0b18081a093a0c18081a0b170a3b053e0b3a063c0c190a18060005a2061c0b390b18081a0a18091a083c0a3b083b0b180a18061c0b18053f093b0b00059e0918063f09190a18061c0b39091a081a0b18053f093b1332053f0a18061d09000d05000000000000000000000000",
                    "down": "2600460204000a2d051b0b39071c071b0a19051d093b081a071c093b063e073d093c081a081a070005a50519093b091a061c071b083d081a073d093c081a071c051d071b073d093b070005a1071b083d0919071b061d061c073d0919071c083c0a3a073e053f071b071c0900059e0919083d071b0a18071b073e0a18073e083c09190a190919071b063e0a3a0900059f071c053f0a18071c081a071b063e0a19071b063e0a3a0a3b0a3a091a051d0a00059e0a18073d061c0919071c093c0819073e0a3a091a051d0a18091a093b083c060005a209190a3a071c051d0919071c083c0919061d093b073d063e0a3a0a190a180900059f09190a3b0919071b061c093b091a093b0a3a071c0a18071c051d093b093b0a00059e09190a3a0a190a18071c051d073d071c081a083c063e0a3a093c09190a180900059f071c083c081a091a0919073d061c0a3a093c0a180919071c0a19063e053f0a00059d0b17083d0a180a180a190a18073e051d0a18073e083c093b063e0a18091a060005a2061c0a3a091a051d0919093b0a19083c083c0a18091a09190919073e0a3a0a00059e071b063e0a18071c061c0a18093c0a18071c053f0a3a093b093b0a19061c0a00059e0a18073d071c0a18071c053f0919093b0a3a091a061c0a18091a093b0a3a070005a1071b0a3b071b061d061b071c063e09190a19093b073e053f083c071c0918080005a30619093c081a0919071c073d081a063e073e081a071b0a19061c073d083d080005a1071a093b0919071c0c17051c073d081b051d073d0a3b083c073e081a071b07000d05"
                },
                "inputs": [
                    {
                        "name": "Apple TV",
                        "type": "hdmi",
                        "data": [
                            {
                                "data": "260070000001279513121338133713131312131213131337133813121338131213121313131213121312141213121338133713131312131213381337143713121313133713381337140005a800012d4a13000c8300012c4a13000c8400012b4a14000c8200012c4a13000c8400012b4a13000d05000000000000",
                                "pause": 0.5
                            },
                            {
                                "data": "260070000001279513121338133713131312131213131337133813121338131213121313131213121312141213121338133713131312131213381337143713121313133713381337140005a800012d4a13000c8300012c4a13000c8400012b4a14000c8200012c4a13000c8400012b4a13000d05000000000000",
                                "pause": 0.3
                            }
                        ]
                    },
                    {
                        "name": "Roku TV",
                        "type": "hdmi",
                        "data": "260070000001279513121338133713131312131213131337133813121338131213121313131213121312141213121338133713131312131213381337143713121313133713381337140005a800012d4a13000c8300012c4a13000c8400012b4a14000c8200012c4a13000c8400012b4a13000d05000000000000",
                        "pause": 0.3
                    }
                ]
            }
        },
        {
            "name": "Tiki Tunes",
            "type": "tv",
            "subtype": "receiver",
            "host": "192.168.1.117",
            "data": {
                "on": "260042020418073d0a190a18071c053f093b09190a3a093c093b0a3a0a1909190a18060005a20a1805400918061c091a0919061c0a3a071c071b0a19051d083c0a3a073d0a00059d0a190a3a061c0a18071c093b0a3b051d0a3a083c083c0a3b061c09190a19060005a20819093b0a19061c0919071c071b093b061c081a071c071b093c063e083c0a00059d0a19053f0919091a051d083c063e09190a3b063e093b093c09190919061c080005a0081a0a3a061c081b0919061c081b053f081a091a051d081a073d0a3a093c060005a20819093b0a19061c081a093c063e0919073e083c0a3a063e081a081b071b080005a00819083d0919091a051d081a0919063f081a061c0919091a063e083c093c0900059e0919083c091a071b0a18063e093b0a19063e083c0a3a093c0a19051d081a0800059f0a19053f081a071b071b091a061c083c0a19051d081a071c083c093b063e080005a008190b3a061c0919071c073d0a3b051d083c0a3a073d093b0a19081a0a19060005a50518093c0a19051d0919071c061c0a3a061c081a0a19061c093b0a3b093b0a0005a106180a3b09190a18061c093c063e09190a3b063e093b0a3b061c0919061c0900059e091a0a3a09190a180a19061c0919073e081a0a19051d09190a3a063e0a3a0a00059e0919093b0a18071c0a180a3b053e0a19063e093b0a3b063e0a180a19051d0a00059e0918073e0919071b061c091a071b063e0a18091a0a18071c053f093b083c0a00059e081a0a3a0a18081a0b18083c0a3a0b18083c0a3a093c093a0b18081a0b170a000d0500000000",
                "off": "260076010918083c0a18091a071b091909190a3b093b093c083b093c081a0a18091a0900059d0a190a3a0a1909190919093c093a0b1809190919091a081a093b0a3b093b0a00059d0a18093b0b180919081a09190a19093b093b0a3b0a3a0a3a09190b1809190900059e09190a3a0a1909190c17073d0a3a0a18081a0b18091909190a3b083c0a3a0a00059d0a19073d0a180a19081a0919061c0a3a0b3a083c0a3a0a3b09190a18081a0a00059e09190a3a081a0b170a19093b0a3a091a0a180919081a0a19063e093b0b3a0800059e0b18093b0a19081a0a180919081b093b083c0a3a0b3a083c0a18091a09190a00059d0a18093b09190b18081a0a3a0b3a09190a19081a09190919083c0b390a3b090005a007190b390a1909190a19081a0919093b083c0b39093c0a3a0b18081a0a180900059e0b18083c0a18081a091a0a3a083d0a170b18081a0a19081a093b0a3b073c0b00059e09170b3a09190b170a1909190a19073d0a3a0a3a093b0b39091a0a180a1908000d05",
                "volume": {
                    "up": "2600420204180b18053f0a3a0a19073c0b18093b093b0b18081a0a180a3b09190a19050005a10a1809190b3a083c0a180b18083c0a180a19093b0a3a083c0b170b3a093b0a00059d0a180a19093b0a3a091a0a3a0a18083c0b390a1909190a19083c0a18091a0800059f071b0a18093b093c0a18081a093b0a19081a093b0a3b093a0b18083c0b390b00059d0a18081a0a3a0a3b081a0a3a09190b390b3a081a0b17091a093b0a19081a0900059e09190a19073c0b390b1809190b39091a0a180a3b083c0a3a0919093b0b3a0800059e0a1909190b3a083c0a180a3b081a0a3a063e0a180b18081a0a3a0a19081a0a00059d0a18091a083b0b3a081a0b18093b081a0b18083c093b0a3b081a0a3a093b0800059f09190b17093c093b0b18083c0a180a3b073d0a18061c0a180a3b081a0a180900059f0a18081a0a3a093c081a0a18083c0b170a19083c0a3a093c0a180a3b073c0b00059d0a180a18083c0b390a19083b0c18083c0a3a0a18081a0b18063e091a0a18070005a009190a180b3a083c0a18091a083b0b18081a0a3a0b3a083c0a18073e093b0a00059d0a18091a0a390b3a081a0b390a19083c0a3b081a0a180919063e0b18061c0900059f08190b17073e0a3a0a19081a0a3a0919081b0a3a083c0a3a0b18063e093b070005a00a19081a0a3a083c09190b3a081a0b390a3b081a0a19081a093b0a18081b0a00059c0b180a18093b0a390a1a0919093c09190919093b0a3b093b0919093b0a3b0a00059d0a180919093c093b0a18083c0b170a3b093b0a180a190919093c071b0a1809000d0500000000",
                    "down": "2600760104190a18063e0b390b18081a0a3a0a3b093b0a19071a0b18093b09190b180800059e0b1809190a3b073d0a180a3a09190b180919093b0b3a073d0a180a3b083c0a00059c0b180a18093b0b39091a0a180a3b083c0a3b08190a190a18083c0a180a19090005a0061a0a180a3b093b0a19073c0b180a18081a0a3a093c13310a19073d0a3a0a00059e0918081a0b390b3a09190b18053f0a3a0a3a09190b180919093b0b18081a0a00059d0a180b18073d0a3a0a19083b0b18061c0a180a3b093c0a390a19093b0a3a080005a008190a180a3b093b0a18091a093b0a3a083c0b18091909190a3a0a1909190a00059d0a180a19093b093b09190a3b0a180919091a083c093b0a3b0919093b093b0a00059d0a180b18093b0a3a0a190919093b0a3b093b0a18081a0a19093b091909190900059e0a1909190a3a0a3b09190a3a081a0b170a19093b0b39083d0a180a3a083c0b00059c0b180a18083c0a3a0a1909190a3b083c0a3a0a1809190b18083c0a180b1808000d05"
                }
            }
        },
        {
            "name": "Stereo",
            "type": "tv",
            "subtype": "receiver",
            "host": "192.168.1.117",
            "data": {
                "on": "2600760106190a3a071c0a18091a053f0a180919073d0b3a063e0b390a17081d0918070005a10b17063f0918071c081a0a19053f093b081b061c0a19051c093c0a3a073d0a00059f08190a3b051d0919061d083c0a18061c093b083d083c0a3b061c09190a19050005a20919093b0a19061c0919071c093b093c051d09190919071c093b063e0a390a00059f0a19053f09190a19051d093b061c09190a39083e0a3a0a3b081a0a19051d0900059f071a093c061c09190a19051d093b073e09190a19051d0919093c073c0a3b060005a1091a083c0a19051d0919093b071b091a063e093b0a3b053f0a18091a061c0900059d0a1a083c081a091a061c0919093c053f0a18061d071b0919063e093c093b080005a1051c0a3a091a071b0919063e091a0919063e093b073e0a3a0a19051d0919080005a00a18063e0a18081b081a091a063e0a3a0a19061c0919061c083d093b063e0a00059f09180a3b051d0919081b073d0919061c093b0a3b073d0a3a071c09190a1905000d05",
                "off": "2600ee000519073d061c071c071b0919073d0a190a3a073c0b3b0a3a091a081a081a060005a20919093b0a18071c0a18093b061c0a3b091909190a19061c0a3a0a3b073d0a00059e0a180a3a071b0a19061c0a180a3b051d0a3a083d073d0a3a09190a190a18060005a407190a3a0a19051d0a18063f0a180a3a061c0a18071c081a0a3b053f0a3a0a00059e0b17063e0a190a18061c0a18073e0a180a3b053f0a3a083d071b0a18061c0a00059e09190a3b081a0a180a19053f0a18063e09190b18061c0a18073e083c0a3a070005a4051b073c0b18061d09180a19053f0a18073e0a3a0a3b053f0a18081a081b0a000d050000000000000000",
                "volume": {
                    "up": "2600ba0104180b390a190b170a19083c0a18071c09190a3a083c0b3a0a3a09190b180800059f0a19093b0a18091a0a180919083c0b390a3b0a180b18081a0a18093c083c0a00059d0b170b3a081a0b18081a093b0a19081a0a18083c093b0b3a083c0b170b18080005a108190a3a0a19071b0a18061c0a3a0b3a083c0b170a1909190a19083c0a3a0a00059d0c17093b0b170b18081a0a3a091a0a180a19083c0a3a093b093b0b18081a0b00059d0a180a3b081a0a18091a071b0a3a063e0b390b18081a0b17091a093b0a3b0800059f09190a3a0b18081a0b170a3b081a0a19051d093b0a3a083c0b3a091909190b00059d0a180a3b09190a19081a0a18093b083c0b3a081a0b170b18081b093a093c080005a0081a0a3a0919091a0a18083c0a180b18081a0a3a063f093b0a3a081a0b180800059f0b18083c0a180a1909190a19083c0a3a0a3a081a0b18061c0a180a3b083c0a00059e0a180a3a081a0b18081a093a0c18081a0b170a3b053e0b3a063c0c190a18060005a2061c0b390b18081a0a18091a083c0a3b083b0b180a18061c0b18053f093b0b00059e0918063f09190a18061c0b39091a081a0b18053f093b1332053f0a18061d09000d05000000000000000000000000",
                    "down": "2600460204000a2d051b0b39071c071b0a19051d093b081a071c093b063e073d093c081a081a070005a50519093b091a061c071b083d081a073d093c081a071c051d071b073d093b070005a1071b083d0919071b061d061c073d0919071c083c0a3a073e053f071b071c0900059e0919083d071b0a18071b073e0a18073e083c09190a190919071b063e0a3a0900059f071c053f0a18071c081a071b063e0a19071b063e0a3a0a3b0a3a091a051d0a00059e0a18073d061c0919071c093c0819073e0a3a091a051d0a18091a093b083c060005a209190a3a071c051d0919071c083c0919061d093b073d063e0a3a0a190a180900059f09190a3b0919071b061c093b091a093b0a3a071c0a18071c051d093b093b0a00059e09190a3a0a190a18071c051d073d071c081a083c063e0a3a093c09190a180900059f071c083c081a091a0919073d061c0a3a093c0a180919071c0a19063e053f0a00059d0b17083d0a180a180a190a18073e051d0a18073e083c093b063e0a18091a060005a2061c0a3a091a051d0919093b0a19083c083c0a18091a09190919073e0a3a0a00059e071b063e0a18071c061c0a18093c0a18071c053f0a3a093b093b0a19061c0a00059e0a18073d071c0a18071c053f0919093b0a3a091a061c0a18091a093b0a3a070005a1071b0a3b071b061d061b071c063e09190a19093b073e053f083c071c0918080005a30619093c081a0919071c073d081a063e073e081a071b0a19061c073d083d080005a1071a093b0919071c0c17051c073d081b051d073d0a3b083c073e081a071b07000d05",
                    "mute": "26003201041a083d061c0a18091a051e0819091a061c083d053e093c093b061c081a070005a10a19063e0919061c0919093c063e093b093c081a091a051d081a093c053f0900059f08190a3b061c0919071c0919091a051d081a083c083c093c063e0a18091a060005a2081a093b0a18061d081a063e093b093c063e0919091a081a091a053f093b0900059f0919063e0919091a051d081a071c081a0919063e093c083c083c081b061c080005a00919083d051d081a0919063e093c063e0a390a1a061c081a091a073d093c0800059f09190a3a091a061c081a091a051d0919071c083c093b063e093c081a0a18090005a00918093c081a0919061d083c093b063e093b0a190919091a051d083c093c0900059f051c0a3a081b071b091a061c0919091a051d083c063f083c093b061c091909000d0500000000"
                },
                "inputs": [
                    {
                        "name": "Music",
                        "type": "tuner",
                        "data": "2600ee000419073d0a190919071b061c0a19083c0a18091a061c0a3a0a3b09190a18060005a20a18063e0a18071c0a180a3b053f0a18073e083c0a3a061c0b180a3a063e0a00059e0a180a3b051d0a18061d09190a18063e0a19061c071b0a3b063e09190a19050005a3081a0a3a0a18061c0a19063e0a3a0a19063e0a3a093c09190a19053f093b0a00059d0b18093b0a180a19061c0a18071c0a3a0a19051d0a18063e073d0a19061c0a00059e0a180a3b051d0a18091a053f0a3a061c0a3a0a3b063e0a18091a093b0a3b0900059f0919093b081a061c0a18091a061c093b0a190a18091a053f0a3a091a081a09000d050000000000000000",
                        "pause": 0.3
                    },
                    {
                        "name": "TV",
                        "type": "hdmi",
                        "data": "2600320104190b39071c0a180a19053f0a18081a083c0b18061c0a3a0b3a051d0a18060005a20a18073d081a071c071b0a19053f083c081b063e093b061c071c083c083c080005a00919093b061d0919061c073d0a19061c073d091a071b083d053f071b081a0900059f0919073d091a071b081a071c073d083d081a073d083c0919091a063e073c0a00059f0a18063e071c0919071b093b071c071b093c051d071b093c073d081a061c080005a0071b0a3b081a071b091a051d083c063e071c093b093c061c0919073d073e090005a00719073e0919061c09190a3b071b0919073e071b091a053f073d0919071c0900059f071a0a3b071b091a051d071b093b063f081a063e073d091a061c083c093c0800059f091a093b081a071b0a19063e081a091a053f081a071c073d093b0919081b08000d0500000000",
                        "pause": 0.3
                    },
                    {
                        "name": "DVD",
                        "type": "other",
                        "data": "2600760104180b39081b0a18091a073d0a3a09190a180b18083c0b390b3a09190a19070005a00b17093b0b18081a0b170a19081a0a3a0a3b0a3a0a19071b0a18093b093b0b00059e0a170b3a09190a19081a093b0a3b081a0a18081a0a3a0b3a083c0b180a180900059f081a0a3a0a1909190a19071a0a19093b093b0b390a1909190b18083c0a3a0a00059e0a19073d0a180a1809190a3a093c0a180b18081a0a3a0a3b093b0a18081b0a00059e09180b3a081a0b170a1909190a19083c0a3a0a3b081a0a18081a0a3b0a3a0800059f0b180a3a0a19081a0a18093c083c0a18081a0a19093b093b0b39091a09190a00059e0a18093c09190a18081a0a190919093b0b390a3b0a180b18081a093b0a3b0900059e09190b3a091909190b18083c0a3a0b1809190a19073d0a3a0a3b08190b180800059f0b18093b0a18091a09190a19071b093b0a3a093c0a18081b0a170a3b083c0a00059f09180a3b081a0a18091a093b0a3a081a0b170a19093b0b390a3b0a180a1908000d05",
                        "pause": 0.3
                    }
                ]
            }
        },
        {
            "name": "HDMI Switch",
            "type": "tv",
            "subtype": "hdmi",
            "alwayson": true,
            "host": "192.168.1.117",
            "data": {
                "on": "2600760106190a3a071c0a18091a053f0a180919073d0b3a063e0b390a17081d0918070005a10b17063f0918071c081a0a19053f093b081b061c0a19051c093c0a3a073d0a00059f08190a3b051d0919061d083c0a18061c093b083d083c0a3b061c09190a19050005a20919093b0a19061c0919071c093b093c051d09190919071c093b063e0a390a00059f0a19053f09190a19051d093b061c09190a39083e0a3a0a3b081a0a19051d0900059f071a093c061c09190a19051d093b073e09190a19051d0919093c073c0a3b060005a1091a083c0a19051d0919093b071b091a063e093b0a3b053f0a18091a061c0900059d0a1a083c081a091a061c0919093c053f0a18061d071b0919063e093c093b080005a1051c0a3a091a071b0919063e091a0919063e093b073e0a3a0a19051d0919080005a00a18063e0a18081b081a091a063e0a3a0a19061c0919061c083d093b063e0a00059f09180a3b051d0919081b073d0919061c093b0a3b073d0a3a071c09190a1905000d05",
                "off": "2600ee000519073d061c071c071b0919073d0a190a3a073c0b3b0a3a091a081a081a060005a20919093b0a18071c0a18093b061c0a3b091909190a19061c0a3a0a3b073d0a00059e0a180a3a071b0a19061c0a180a3b051d0a3a083d073d0a3a09190a190a18060005a407190a3a0a19051d0a18063f0a180a3a061c0a18071c081a0a3b053f0a3a0a00059e0b17063e0a190a18061c0a18073e0a180a3b053f0a3a083d071b0a18061c0a00059e09190a3b081a0a180a19053f0a18063e09190b18061c0a18073e083c0a3a070005a4051b073c0b18061d09180a19053f0a18073e0a3a0a3b053f0a18081a081b0a000d050000000000000000",
                "volume": {
                    "up": "2600ba0104180b390a190b170a19083c0a18071c09190a3a083c0b3a0a3a09190b180800059f0a19093b0a18091a0a180919083c0b390a3b0a180b18081a0a18093c083c0a00059d0b170b3a081a0b18081a093b0a19081a0a18083c093b0b3a083c0b170b18080005a108190a3a0a19071b0a18061c0a3a0b3a083c0b170a1909190a19083c0a3a0a00059d0c17093b0b170b18081a0a3a091a0a180a19083c0a3a093b093b0b18081a0b00059d0a180a3b081a0a18091a071b0a3a063e0b390b18081a0b17091a093b0a3b0800059f09190a3a0b18081a0b170a3b081a0a19051d093b0a3a083c0b3a091909190b00059d0a180a3b09190a19081a0a18093b083c0b3a081a0b170b18081b093a093c080005a0081a0a3a0919091a0a18083c0a180b18081a0a3a063f093b0a3a081a0b180800059f0b18083c0a180a1909190a19083c0a3a0a3a081a0b18061c0a180a3b083c0a00059e0a180a3a081a0b18081a093a0c18081a0b170a3b053e0b3a063c0c190a18060005a2061c0b390b18081a0a18091a083c0a3b083b0b180a18061c0b18053f093b0b00059e0918063f09190a18061c0b39091a081a0b18053f093b1332053f0a18061d09000d05000000000000000000000000",
                    "down": "2600460204000a2d051b0b39071c071b0a19051d093b081a071c093b063e073d093c081a081a070005a50519093b091a061c071b083d081a073d093c081a071c051d071b073d093b070005a1071b083d0919071b061d061c073d0919071c083c0a3a073e053f071b071c0900059e0919083d071b0a18071b073e0a18073e083c09190a190919071b063e0a3a0900059f071c053f0a18071c081a071b063e0a19071b063e0a3a0a3b0a3a091a051d0a00059e0a18073d061c0919071c093c0819073e0a3a091a051d0a18091a093b083c060005a209190a3a071c051d0919071c083c0919061d093b073d063e0a3a0a190a180900059f09190a3b0919071b061c093b091a093b0a3a071c0a18071c051d093b093b0a00059e09190a3a0a190a18071c051d073d071c081a083c063e0a3a093c09190a180900059f071c083c081a091a0919073d061c0a3a093c0a180919071c0a19063e053f0a00059d0b17083d0a180a180a190a18073e051d0a18073e083c093b063e0a18091a060005a2061c0a3a091a051d0919093b0a19083c083c0a18091a09190919073e0a3a0a00059e071b063e0a18071c061c0a18093c0a18071c053f0a3a093b093b0a19061c0a00059e0a18073d071c0a18071c053f0919093b0a3a091a061c0a18091a093b0a3a070005a1071b0a3b071b061d061b071c063e09190a19093b073e053f083c071c0918080005a30619093c081a0919071c073d081a063e073e081a071b0a19061c073d083d080005a1071a093b0919071c0c17051c073d081b051d073d0a3b083c073e081a071b07000d05"
                },
                "inputs": [
                    {
                        "name": "Kitchen TV Music",
                        "type": "other",
                        "data": [
                            {
                                "data": "2600680000012294103812131114111312131114111312131114113811381238103811381238113810151038111411141113111411131213113812131138123711381138123811381000050f0001264a11000c2b0001224b11000c2e0001224b11000c2c0001254a11000d050000000000000000000000000000",
                                "pause": 0.3
                            }
                        ]
                    },
                    {
                        "name": "Kitchen Xfinity",
                        "type": "other",
                        "data": [
                            {
                                "data": "2600580000012391143514111312131114111213141014111213133612371435133612371435143513361411123714351411141013121411141112371411121214351336143613361200050e0001264913000c2b0001264913000d050000000000000000000000000000",
                                "pause": 0.3
                            }
                        ]
                    },
                    {
                        "name": "Kitchen Photos",
                        "type": "other",
                        "data": [
                            {
                                "data": "2600580000012391143514111312131114121212131114121212133613361436133513361436133612131336121313351312141014121213123613121336121313361236143613361200050e0001274913000c2b0001264913000d050000000000000000000000000000",
                                "pause": 0.3
                            }
                        ]
                    },
                    {
                        "name": "Kitchen DVD",
                        "type": "other",
                        "data": [
                            {
                                "data": "2600500000012491133614111213131114111213131114111213133513361436133612371435133612131336121313111435141014121212133612131336123714111236143613361200050e0001274913000d05000000000000",
                                "pause": 0.3
                            }
                        ]
                    },
                    {
                        "name": "Main TV Apple TV",
                        "type": "other",
                        "data": [
                            {
                                "data": "260070000001258e143613111411121313111410131213111411133614351435133614361335133614111336143613351312131114121113133612131311141112361436133612371400050c0001284812000c2b0001294713000c2c0001274812000c2c0001294713000c2c0001284713000d05000000000000",
                                "pause": 0.3
                            }
                        ]
                    },
                    {
                        "name": "Main TV Xfinity",
                        "type": "other",
                        "data": [
                            {
                                "data": "2600580000012390143613111411141113111411141113111411143514351336143514361335143514111411133613361312131212121312133613361311141113361336133614351400050c0001274813000c2c0001264813000d050000000000000000000000000000",
                                "pause": 0.3
                            }
                        ]
                    },
                    {
                        "name": "Main TV Photos",
                        "type": "other",
                        "data": [
                            {
                                "data": "2600580000012391143413121411141112121311141113121311143613361237143513361336143613351336143613361213131114111213131114111213131114351435133614361300050d0001274814000c2c0001264814000d050000000000000000000000000000",
                                "pause": 0.3
                            }
                        ]
                    },
                    {
                        "name": "Main TV DVD",
                        "type": "other",
                        "data": [
                            {
                                "data": "2600600000012391143512131311141112131311141112131311143514351336143613361236143613361213131114361311141112131311141112361436131114361336123714351300050d0001274814000c2b0001264814000c2b0001274714000d05000000000000",
                                "pause": 0.3
                            }
                        ]
                    }
                ]
            }
        }
    ]
}

**Comment by masterfordev** [comment]
Yours tvs arent smart? You can add the `pingIPAddress ` maybe that can help you.

https://broadlink.kiwicam.nz/#tv

**Comment by fratinize** [comment]
Actually the TVs are my stereo/received. One for each of the 2 zones no ip except the bean

**Comment by kiwi-cam** [comment]
I've had occasional "quirks" like this too. I usually find that if I quick jump in to the Home app and let the accessories update then I can use the Control again. My theory is that is the TV's status is off or "not responding" then it won't allow you to control the TV.

You could try updating Homebridge to see if that improves things (there's been [A LOT of work recently](https://github.com/homebridge/homebridge/issues/2765) on accessory responsiveness and "not responding" status)
