### ISSUE TITLE
Not working No errors

### ISSUE THREAD

**Issue by xkyle22x** [kiwi-cam/homebridge-broadlink-rm#186]
As the tittle says I have no errors in the logs, everything starts as it should and when I do something in the home app it tells me in the logs that the hex code has been sent but nothing happens. 
Not sure where to look at this point because everything looks fine. 
I've been using your plugin for around 6 months without any issues at all until this point. 
Any ideas? 
Thanks

**Comment by xkyle22x** [comment]
I rolled the plugin back to 4.3.7 to see if it would change anything and it didn't work so I updated back to 4.4.0 and now it is working again. 
I can't explain it but happy it's working again so this issue can be closed. 
Thanks

**Comment by kiwi-cam** [comment]
Thanks for the update @xkyle22x. I'll assume this is an environmental issue... unless I hear from others
