### ISSUE TITLE
[FEATURE REQUEST] Send Input signal after a while when turning on a TV/STB

### ISSUE THREAD

**Issue by tasbarba** [kiwi-cam/homebridge-broadlink-rm#188]
With native HomeKit TV’s it is possible to turn on the device in a specific input (for example HDMI 1).
Is it possible to have this behavior in the plugin? It would be handy when creating a scene or automation.
At now, when I select a TV in a scene, I can choose the input, but the doesn’t makes difference, because it only sends the “ON” IR code.

Thank you!

**Comment by masterfordev** [comment]
To do that, i added the ir code for set the channel/input. Like this:

```

"on": [
                            {
                                "data": "260050000001219313361238111311131238113812121237121311131138113812131113123713121113121311381237123712131138123711381138121212131212123712131212120005130001234b12000d05000000000000",
                                "pause": 7
                            },
                            {
                                "data": "260050000001219312381237121211141138123711131237121311131238113712131212123812121114113812121213113811131114123711381212123712371213113811381213110005140001234a12000d05000000000000",
                                "pause": 0.3
                            },
                            {
                                "data": "260050000001229311371238121211141237113812121237111411131237123712131113123712131138123712131212123712131212123712131212123712371213113811381212120005140001234a12000d05000000000000",
                                "pause": 0.3
                            },
                            {
                                "data": "260050000001219312381237121211141138123711131237121311131238113712131212123812121114113812121213113811131114123711381212123712371213113811381213110005140001234a12000d05000000000000",
                                "pause": 0.3
                            },
                            {
                                "data": "260050000001229311371238121211141237113812121237111411131237123712131113123712131138123712131212123712131212123712131212123712371213113811381212120005140001234a12000d05000000000000"
                            }
                        ],

```

As you can see, i send the code for turn on, after that wait 7 secs, and send the ir code for set the channel that i want set. You can do that but using the code of your input.

**Comment by masterfordev** [comment]
The 7 secs are for wait until my STB load the system.

**Comment by tasbarba** [comment]
Thank you for your help. Yes, I it's a workaround, but I'll be restricted to the input I set. If I want to have to two scenes, one for each input, it will not work.

**Comment by kiwi-cam** [comment]
This isn't something I'm able to easily reproduce. I can set a scene and specify an input - I assume you can too.  Could you set `"debug": true` and capture what happens when you configure this?
![image](https://user-images.githubusercontent.com/32912464/104533736-d637a500-5677-11eb-873f-664056165ac8.png)

I wonder if both commands are being sent but the TV is still powering up when the input code is sent.
