### ISSUE TITLE
Fan Type "fanv1" not working

### ISSUE THREAD

**Issue by tasbarba** [kiwi-cam/homebridge-broadlink-rm#190]
Hi, I'm trying to create a Fan accessory using the "fanv1" type, but it's not working. Here is my code:

`                {
                    "name": "Ventilador",
                    "type": "fanv1",
                    "hideSwingMode": true,
                    "stepSize": 17,
                    "data": {
                        "on": "260050000001229213361337123712121213121212131237121212371237133613361312123712131237121212371213121212131212121312121237141112371435143515341435150004ec0001244a12000d05000000000000",
                        "off": "260050000001229213361337123712121213121212131237121212371237133613361312123712131237121212371213121212131212121312121237141112371435143515341435150004ec0001244a12000d05000000000000",
                        "clockwise": "260050000001229213361337123712121213121212131237121212371237133613361312123712131237121212371213121212131212121312121237141112371435143515341435150004ec0001244a12000d05000000000000",
                        "counterClockwise": "26005TESTE",
                        "fanSpeed17": "260050000001229213361337123712121213121212131237121212371237133613361312123712131237121212371213121212131212121312121237141112371435143515341435150004ec0001244a12000d05000000000000",
                        "fanSpeed34": "260050000001229213361337123712121213121212131237121212371237133613361312123712131237121212371213121212131212121312121237141112371435143515341435150004ec0001244a12000d05000000000000",
                        "fanSpeed51": "260050000001229213361337123712121213121212131237121212371237133613361312123712131237121212371213121212131212121312121237141112371435143515341435150004ec0001244a12000d05000000000000",
                        "fanSpeed68": "260050000001229213361337123712121213121212131237121212371237133613361312123712131237121212371213121212131212121312121237141112371435143515341435150004ec0001244a12000d05000000000000",
                        "fanSpeed85": "260050000001229213361337123712121213121212131237121212371237133613361312123712131237121212371213121212131212121312121237141112371435143515341435150004ec0001244a12000d05000000000000",
                        "fanSpeed100": "260050000001229213361337123712121213121212131237121212371237133613361312123712131237121212371213121212131212121312121237141112371435143515341435150004ec0001244a12000d05000000000000"
                    }
                }`

**Comment by kiwi-cam** [comment]
What error(s) are you getting in the logs? That looks fine (except the invalid characters in the counterClockwise code ).

**Comment by uzumaki20398** [comment]
Your counterClockwise code is 26005TESTE?`"counterClockwise": "26005TESTE", `

**Comment by tasbarba** [comment]
Sorry for the delay to answer. Yes, I just wrote some useless code to the counter clock wise. But I assumed that this was not a problem to create the acessory.
