### ISSUE TITLE
homebridge-broadlink-rm Learn Button problem

### ISSUE THREAD

**Issue by mradeanu** [kiwi-cam/homebridge-broadlink-rm#192]
Hello, everyone!
First of all, please excuse my lack of consistence in addressing the issue. I have zero knowledge in programming, therefore I might say stupid things. Long story short, I have installed homebridge-broadlink-rm 4.40 to work with my new RM4mini. Unfortunately, when I try to Learn some of the buttons, I get nothing. I attach the screenshot. What do you think might be the problem. Thank you very much for your patience and support.

<img width="1280" alt="Screenshot 2021-01-08 at 23 14 45" src="https://user-images.githubusercontent.com/77172940/104065143-eda20880-5207-11eb-80ce-ca82d940d49e.png">

**Comment by masterfordev** [comment]
share config.

**Comment by mradeanu** [comment]
This is my config. I have tried to use Learn button to confirm myself that the HEX found by me in the econtrol.db that I have saved from the Broadlink app are ok. Technically, as you see, I have added a TV button there. It appears in Accessories, but even though it says it sends the HEX code, nothing happens. That is why I wanted to try the hard method of using the learn button. But it doesn't work for me :( 

{
    "bridge": {
        "name": "Homebridge 7D19",
        "username": "0E:23:CD:DD:43:C1",
        "port": 51382,
        "pin": "713-63-840"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "platform": "BroadlinkRM",
            "name": "BroadlinkRM",
            "debug": true,
            "hideScanFrequencyButton": true,
            "hideLearnButton": false,
            "hosts": [
                {
                    "address": "192.168.0.144",
                    "mac": "A0-43-B0-31-F4-84",
                    "isRFSupported": false
                }
            ],
            "accessories": [
                {
                    "accessory": "Broadlink RM Learner",
                    "name": "Learn IR",
                    "type": "learn-code",
                    "host": "192.168.0.144"
                },
                {
                    "name": "tv",
                    "type": "switch",
                    "data": {
                        "on": "JgDMAHI5Dw4MLQ4ODw4MEA4PDBANEA4ODg4PDg4ODw4OKw4ODw4ODg8ODg4NEA4ODyoODw4rDg4NEA4rDisOKw4ODRAODg8qDw4MLQ4rDisOKw4ODw4OKw4ODw4ODg0QDBAODw4rDgAJdnM4Dw4OKw4ODw4ODg8ODBAPDg4ODw4ODg4ODw4OKw4ODw4MEA8ODw0PDg4ODyoPDg4rDg4PDg4rDisNLA4ODw4ODg8qDw4OKw4rDisOKw4ODw4OKw4ODw4ODg8ODg4ODwwtDgANBQAAAAAAAAAAAAAAAA==",
                        "off": "JgDMAHI5Dw4MLQ4ODw4MEA4PDBANEA4ODg4PDg4ODw4OKw4ODw4ODg8ODg4NEA4ODyoODw4rDg4NEA4rDisOKw4ODRAODg8qDw4MLQ4rDisOKw4ODw4OKw4ODw4ODg0QDBAODw4rDgAJdnM4Dw4OKw4ODw4ODg8ODBAPDg4ODw4ODg4ODw4OKw4ODw4MEA8ODw0PDg4ODyoPDg4rDg4PDg4rDisNLA4ODw4ODg8qDw4OKw4rDisOKw4ODw4OKw4ODw4ODg8ODg4ODwwtDgANBQAAAAAAAAAAAAAAAA=="
                    }
                }
            ]
        }
    ]
}

**Comment by masterfordev** [comment]
Replace the host section with this please:

```

"hosts": [
{
"address": "192.168.0.144",
"mac": "A0:43:B0:31:F4:84",
"isRFSupported": false;
"isRM4": true;
}
],

```

**Comment by masterfordev** [comment]
Sorry, nevermind the msg above, use this:
```
"hosts": [
{
"address": "192.168.0.144",
"mac": "A0:43:B0:31:F4:84",
"isRFSupported": false,
"isRM4": true
}
],
```

**Comment by mradeanu** [comment]
I ve updated it. Restarting and trying to use the Learn Button. I ll get back with feedback. Thank you very much!

**Comment by mradeanu** [comment]
Thank you, from the bottom of my heart. For almost a week I am trying to solve this by myself. I am stubborn. The Learn button worked, I have read the HEX and put it in config, and now that switch works (ex. TV on/off). Strange enough, it seems that the code was good, except the fact I had no == at the end of it. Does it mean anything in your programmers language? 😇

Once again, thank you very, very much! I have the feeling I will annoy you some time soon,  again 😇.

**Comment by masterfordev** [comment]
They are IR codes, if they are not 100% identical, they simply do not work.

Pleasure to help you. You can close the thread now. Greetings.
