### ISSUE TITLE
Unable to turn off AC - setup as Heater-Cooler

### ISSUE THREAD

**Issue by akkiankur** [kiwi-cam/homebridge-broadlink-rm#194]
I'm able to switch off and change temperature of my AC using both SIRI and Home app. However, I can't turn off the AC. Below are the logs I see when I try to switch off the AC - 
[Broadlink RM] Living Room AC setActive: 0
[Broadlink RM] Living Room AC setCurrentHeaterCoolerState: 0
[Broadlink RM] Living Room AC setCurrentHeaterCoolerState: already 0 (no data sent - B)

Below is portion of my config file where I have defined the off button - 

"name": "Living Room AC",
                    "type": "heater-cooler",
                    "host": "xx.xx.xx.xx",
                    "coolingThresholdTemperature": 21,
                    "minTemperature": 18,
                    "maxTemperature": 25,
                    "defaultRotationSpeed": 50,
                    "fanStepSize": 50,
                    "data": {
                        "cool": {
                            "off": {
                                "data": "260050020e0e0e,
                                "sendCount": 2,
                                "interval": 0.2
                            },
                            "on": "260050020",
                            "temperatureCodes": {
                                "18": {
                                    "rotationSpeed50": "260050020e0e0"}

**Comment by newt10** [comment]
@akkiankur can you share logs with debug enabled (i.e. homebridge -D if using command line)

Based on the log, it appears that broadlink thinks the device is already in an off state so it is not sending the command

**Comment by akkiankur** [comment]
@newt10 - it is working now on its own. I will close this for now. Will let you know if again stops working. Thanks for the help,
