### ISSUE TITLE
Broadlink RM4C Mini not recognised by the plugin

### ISSUE THREAD

**Issue by JacVid** [kiwi-cam/homebridge-broadlink-rm#195]
Hello,

As advised in in the log, here is the message I get.

"_We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "6539". The device is connected to your network with the IP address "10.0.1.58"._

The Device is the latest BestCon works with Broadlink RM4C Mini. Is this device compatible with this Plug-in ?

Thanks

Jack

**Comment by ghost** [comment]
#83 Maybe you can have a look on it.

**Comment by JacVid** [comment]
Thanks 

I tried to add host with RM4 in true, but it doesn't help me. My device is still not recognised.

**Comment by kiwi-cam** [comment]
I've updated the broadlinkrm-js module to include the "6539" in the latest beta. Could you update to the latest beta and confirm this works?

**Comment by JacVid** [comment]
Thanks a lot,

with that beta version, the device is correctly detected...
