### ISSUE TITLE
Learn Code not working. 

### ISSUE THREAD

**Issue by vitaliy-kozlov** [kiwi-cam/homebridge-broadlink-rm#2]
Hi, I having issue with the Learn code. Device was successfully discovered but when I tap on Learn Code noting happen. I Got Learn Code time out error. The light on the RM also not blinking.Any suggestions? I tried both RM4C and RM4 Pro.

**Comment by vitaliy-kozlov** [comment]
[2020-6-9 14:10:59] [Broadlink RM] Learn getSwitchState: undefined
[2020-6-9 14:11:02] [Broadlink RM] Learn Code (ready)
[2020-6-9 14:11:12] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[2020-6-9 14:11:12] [Broadlink RM] [INFO] Learn Code (stopped)

**Comment by kiwi-cam** [comment]
Hi @utester123123bb. There has been a lot of changes recently around device support and issues with Learning. Could you confirm that you're running the latest version of this plugin (or at least 4.8.4)?

**Comment by fratinize** [comment]
Kiwi you mentioned version 4.8.4? I only see 4.3
I have the same problem timeout-10s
Any ideas?

**Comment by kiwi-cam** [comment]
Haha. Sorry, you're right, 4.3.0 is the latest: https://www.npmjs.com/package/homebridge-broadlink-rm-pro

Not sure what I was thinking there ¯\_(ツ)_/¯

Timeout suggests it's not picking up your code.  Are you learning IR or RF?

**Comment by fratinize** [comment]
Ir it's a mini 3 shows as rm2?
Should I remove hosts? I saw a user resolved the rm2 with that

It also appears if I add the rm3 mini to the BroadLink app, when HomeBridge is restarted it no longer sees the mini
Why is that ?
Thanx
