### ISSUE TITLE
About heater-cooler

### ISSUE THREAD

**Issue by burakcankose** [kiwi-cam/homebridge-broadlink-rm#200]
Hello, 

TemperatureFilePath feature does not work when I select the device type heater-cooler, but if I do air-conditioner it works.  is there a solution to this?

**Comment by masterfordev** [comment]
I think that option is not supported in that accessory. Because the [documentation](https://broadlink.kiwicam.nz/#heatercooler) does not refer to that option. Maybe @kiwi-cam would have to add the support.

**Comment by burakcankose** [comment]
Hi, Can you add this if it won't be difficult for you? @kiwi-cam

**Comment by newt10** [comment]
We are working on that enhancement and will keep you posted!

**Comment by burakcankose** [comment]
Thank you.  I am waiting for information from you.  Good luck.

**Comment by uzumaki20398** [comment]
I consulted the Aircon.js and made some changes.
It's OK with MQTT. but others I'm not sure.
https://github.com/uzumaki20398/homebridge-broadlink-rm/blob/kiwi-cam-beta-1/accessories/heater-cooler.js

**Comment by burakcankose** [comment]
Hİ,

Is there any progress on this subject? Thanks !  @newt10 @kiwi-cam
