### ISSUE TITLE
Unknown Broadlink device RM4C mini - Device type code: 6539

### ISSUE THREAD

**Issue by Makestudio20** [kiwi-cam/homebridge-broadlink-rm#203]
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "6539". The device is connected to your network with the IP address

**Comment by kiwi-cam** [comment]
I've just pushed a new version of the module with the device definitions. If you reinstall the latest release (or the BETA) you should have support now.

**Comment by kiwi-cam** [comment]
With the release of 4.4.1 this should be resolved now.
