### ISSUE TITLE
Cycling through inputs

### ISSUE THREAD

**Issue by spud** [kiwi-cam/homebridge-broadlink-rm#204]
I have a Samsung TV and a separate Samsung Soundbar. Each one of them has multiple input/source options (HDMI, HDMI2, TV, and HDMI, Bluetooth, TV, Digital In, etc) but neither one of them allows direct selection of a given input. In other words, there is no single command for "Switch to HDMI" on the television. Only "Change Input, Next, Next, Next" until the desired input is selected.

Clearly, humans are good at that, at least visually, recognizing when the correct input is selected...but Broadlinks, not so much.

If the TV or soundbar is shut off, the current input is retained, so when turned back on, the input is set to whatever it was when turned off. So there is no canonical "default state."

Has anyone found a solution for handling these sorts of devices, which only work by cycling through inputs?

I've tried creating each possible input, with an interval and a different sendCount for each input, but of course those counts are only relative to the current input, which is unpredictable, so they invariably get out of sync. 

(To make matters more complicated, the first command sent to the TV merely _opens_ the source-switching panel, which then requires a second click to switch inputs, but that can probably be handled with a pause. And, worse, _sometimes_ "Screen Mirroring" appears as an input option for the TV, and sometimes it doesn't. I haven't even figured out what toggles that option.)

**Comment by dnschnur** [comment]
I was trying to answer the same question for my Samsung TV, whose remote only allows cycling through inputs. As far as I can tell there's no good way to do this. However, while searching for answers I discovered (via some old forum posts containing pronto codes that I had to convert to Broadlink hex) that my TV at least *does* support switching directly to a specific input, even if that isn't exposed on the remote. Try this in your TV configuration:

```
"inputs": [
    {
        "name": "HDMI 1",
        "type": "hdmi",
        "data": "26004600949312381238123812131213121312131213123812381238121312131213121312131238121312131238121312381238123812131238123812131238121312131213120005a40d05"
    },
    {
        "name": "HDMI 2",
        "type": "hdmi",
        "data": "26004600949312381238123812131213121312131213123812381238121312131213121312131213123812381238123812381213123812381213121312131213121312381213120005a40d05"
    },
    {
        "name": "HDMI 3",
        "type": "hdmi",
        "data": "26004600949312381238123812131213121312131213123812381238121312131213121312131213123812131213121312131238123812381213123812381238123812131213120005a40d05"
    },
    {
        "name": "HDMI 4",
        "type": "hdmi",
        "data": "26004600949312381238123812131213121312131213123812381238121312131213121312131238121312381213121312131238123812131238121312381238123812131213120005a40d05"
    }
]
```

**Comment by agencybcg** [comment]
@dnschnur Thanks for posting those! I finally got a chance to try them out. Unfortunately, my inputs are "TV", "HDMI1", "HDMI2", and "Screen"(?), so they don't correspond correctly.

However, it seems like your HDMI2 and HDMI3 _do_ map to my HDMI1 and HDMI2, so if only I could find the magic number for "TV," I'd be in business!

If you know where you found those codes, perhaps I could find the one perfect variation for my TV input? Any chance you remember the forum (though the Google results for these things are pretty thin; I may happen upon them myself).

**Comment by dnschnur** [comment]
I found them here: http://www.remotecentral.com/cgi-bin/mboard/rc-custom/thread.cgi?39045

There was no TV input code, although a comment further down links to http://www.hifi-remote.com/forums/viewtopic.php?t=16222, which claims to show a TV input code. I don't know offhand how to convert that to Broadlink hex format, though.

I converted the Pronto codes from the first thread to Broadlink by piping them through http://tomeko.net/online_tools/hex_to_base64.php?lang=en and then the "cleaned input" through https://www.jdoodle.com/embed/v0/eBD (scroll past the source to the bottom of the page).

**Comment by jat80** [comment]
> I was trying to answer the same question for my Samsung TV, whose remote only allows cycling through inputs. As far as I can tell there's no good way to do this. However, while searching for answers I discovered (via some old forum posts containing pronto codes that I had to convert to Broadlink hex) that my TV at least _does_ support switching directly to a specific input, even if that isn't exposed on the remote. Try this in your TV configuration:
> 
> ```
> "inputs": [
>     {
>         "name": "HDMI 1",
>         "type": "hdmi",
>         "data": "26004600949312381238123812131213121312131213123812381238121312131213121312131238121312131238121312381238123812131238123812131238121312131213120005a40d05"
>     },
>     {
>         "name": "HDMI 2",
>         "type": "hdmi",
>         "data": "26004600949312381238123812131213121312131213123812381238121312131213121312131213123812381238123812381213123812381213121312131213121312381213120005a40d05"
>     },
>     {
>         "name": "HDMI 3",
>         "type": "hdmi",
>         "data": "26004600949312381238123812131213121312131213123812381238121312131213121312131213123812131213121312131238123812381213123812381238123812131213120005a40d05"
>     },
>     {
>         "name": "HDMI 4",
>         "type": "hdmi",
>         "data": "26004600949312381238123812131213121312131213123812381238121312131213121312131238121312381213121312131238123812131238121312381238123812131213120005a40d05"
>     }
> ]
> ```

Thanks so much for this!!!  Works great for my Samsung!!!!  AMAZING!
