### ISSUE TITLE
Broadlink RM4 Mini cannot learn

### ISSUE THREAD

**Issue by Sujovian** [kiwi-cam/homebridge-broadlink-rm#210]
I reviewed the thread from June regarding RM3 where you seem to have resolved this issue on that platform. I also noticed that RM4 Mini appears to have been added. I'm running the latest version (4.4.0). Autodiscover didn't work for me, but I had no issue adding it by manually entering Host info. everything appears to be set up properly, but Learn Code doesn't work. when I turn on the Learn IR device and try to teach it, I just see this in the log:

Learn IR getSwitchState: undefined
[1/26/2021, 2:49:05 PM] [BroadlinkRM4 Mini] Learn Code (ready)
[1/26/2021, 2:49:15 PM] [BroadlinkRM4 Mini] [INFO] Learn Code (stopped - 10s timeout)
[1/26/2021, 2:49:15 PM] [BroadlinkRM4 Mini] [INFO] Learn Code (stopped)
[1/26/2021, 2:56:26 PM] [BroadlinkRM4 Mini] Learn IR getSwitchState: undefined

**Comment by masterfordev** [comment]
share your config please.

**Comment by Sujovian** [comment]
{
            "platform": "BroadlinkRM",
            "name": "BroadlinkRM4 Mini",
            "hosts": [
                {
                    "address": "192.168.1.168",
                    "mac": "a0:43:b0:15:77:66",
                    "isRFSupported": false
                }
            ],
            "accessories": [
                {
                    "name": "Samsung TV",
                    "type": "tv",
                    "data": {
                        "on": "ON_HEX_CODE",
                        "off": "OFF_HEX_CODE",
                        "remote": {
                            "select": "SELECT_HEX_CODE",
                            "arrowUp": "UP_HEX_CODE",
                            "arrowDown": "DOWN_HEX_CODE",
                            "arrowLeft": "LEFT_HEX_CODE",
                            "arrowRight": "RIGHT_HEX_CODE",
                            "playPause": "PAUSE_HEX_CODE"
                        },
                        "volume": {
                            "up": "VOLUP_HEX_CODE",
                            "down": "VOLDOWN_HEX_CODE"
                        },
                        "inputs": [
                            {
                                "name": "INPUT 1",
                                "type": "hdmi",
                                "data": "HEX_CODE"
                            }
                        ]
                    }
                }
            ]
        }

**Comment by Sujovian** [comment]
btw, moments after I posted that, 4.4.1 dropped into my available updates. I updated and an now running 4.4.1.

the issue persists, but the log changed slightly. Now it says:


[1/26/2021, 3:57:27 PM] [BroadlinkRM4 Mini] Learn getSwitchState: false
[1/26/2021, 3:57:27 PM] [BroadlinkRM4 Mini] Scan Frequency getSwitchState: false
[1/26/2021, 3:57:32 PM] [BroadlinkRM4 Mini] Learn Code (ready)
[1/26/2021, 3:57:42 PM] [BroadlinkRM4 Mini] [INFO] Learn Code (stopped - 10s timeout)
[1/26/2021, 3:57:42 PM] [BroadlinkRM4 Mini] [INFO] Learn Code (stopped)

**Comment by kiwi-cam** [comment]
The RM4 devices use different headers to the RM3. You'll need to add "isRM4": true to your host config. i.e.:
```
        "hosts": [
            {
                "address": "192.168.1.168",
                "mac": "a0:43:b0:15:77:66",
                "isRFSupported": false,
                "isRM4": true
            }
        ],
```

Let us know if that resolves it for you.

**Comment by Sujovian** [comment]
Brilliant! thanks so much

**Comment by guussie** [comment]
I am having exactly the same issue. In my config file I have set RM4 to TRUE. But Learn still doesn't work. At some point Hoobs even crashed but I can't find that event any more in the log. If it happens again I will try to catch it.

{
            "platform": "BroadlinkRM",
            "plugin_map": {
                "plugin_name": "homebridge-broadlink-rm-pro"
            },
            "name": "Broadlink RM",
            "hosts": [
                {
                    "address": "192.168.1.59",
                    "mac": "XX:XX:XX:XX:XX:XX",
                    "isRFSupported": false,
                    "isRM4": true
                }
            ]
        }


09/02/2021, 11:17:02 [Broadlink RM] Learn Code (ready)
09/02/2021, 11:17:12 [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
09/02/2021, 11:17:12 [Broadlink RM] [INFO] Learn Code (stopped)

**Comment by necccc** [comment]
Same issue here, about to set up the device, but cannot scan RF/IR accessories, the toggle button can't even set to active

Config
```json
{
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "debug": true,
            "accessories": [],
            "hosts": [
                {
                    "address": "192.168.0.15",
                    "mac": "A0:43:B0:54:54:C0",
                    "isRFSupported": true,
                    "isRM4": true
                }
            ]
        }
```

Update:
IR learning seems OK

**Comment by masterfordev** [comment]
> Same issue here, about to set up the device, but cannot scan RF/IR accessories, the toggle button can't even set to active
> 
> 
> 
> Config
> 
> ```json
> 
> {
> 
>             "platform": "BroadlinkRM",
> 
>             "name": "Broadlink RM",
> 
>             "debug": true,
> 
>             "accessories": [],
> 
>             "hosts": [
> 
>                 {
> 
>                     "address": "192.168.0.15",
> 
>                     "mac": "A0:43:B0:54:54:C0",
> 
>                     "isRFSupported": true,
> 
>                     "isRM4": true
> 
>                 }
> 
>             ]
> 
>         }
> 
> ```
> 
> 
> 
> Update:
> 
> IR learning seems OK
> 
> 
> 
> 

For RF maybe you want take a look on [#45](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45)
