### ISSUE TITLE
Change Input via Siri

### ISSUE THREAD

**Issue by boehser-enkel** [kiwi-cam/homebridge-broadlink-rm#212]
Hi,

is it possible to change the configured input via Siri? I can't find the right command.

kind regards

**Comment by CyberMrProper** [comment]
@kiwi-cam it would be great to have the channels as button list separated from the inputs as webos plug-in does https://github.com/merdok/homebridge-webos-tv/blob/28c7e6b85b5646110a872e2787a2ef7e4b3494bc/index.js#L651. Do you think it would be possible?

**Comment by boehser-enkel** [comment]
> @kiwi-cam it would be great to have the channels as button list separated from the inputs as webos plug-in does https://github.com/merdok/homebridge-webos-tv/blob/28c7e6b85b5646110a872e2787a2ef7e4b3494bc/index.js#L651. Do you think it would be possible?

It is. But why are you postin in this issue??
