### ISSUE TITLE
Mute option is missing in TV accessory 

### ISSUE THREAD

**Issue by CyberMrProper** [kiwi-cam/homebridge-broadlink-rm#213]
I saw that in other TVs plug-ins the mute characteristic is configured, but it is missing in broadlink tv.

**Comment by kiwi-cam** [comment]
I started playing with this, but I'm not clear on where the Mute option should appear. It's not in the GUI that I can see - is it a quirky one like the volume buttons?

**Comment by masterfordev** [comment]
I think this option is not native to iOS control (only from homebridge ui x). Maybe you have to add an external switch that sends the mute command.

**Comment by masterfordev** [comment]
Or add an option to use the (i) button to send the mute. Like the webos plugin does.

**Comment by cattastrophe0** [comment]
I was looking into this and found the UI element when you are looking at a native Apple TV. Not sure what implementing it would look like.

![IMG_ED965762DCED-1](https://user-images.githubusercontent.com/57551805/212516592-e07f3c0e-642a-4e7e-b25b-cd9de7e37167.jpeg)
