### ISSUE TITLE
Device not added to HomeKit

### ISSUE THREAD

**Issue by eliteladen** [kiwi-cam/homebridge-broadlink-rm#215]
Configured my AC with codes for on, off and all available temps, but still device doesn't get added to Homekit at all. Would appreciate any tips since this is my first time doing it.

Console:
[28/01/2021, 17:30:19] [BroadlinkRM] No accessories have been added to the "BroadlinkRM" platform config.
[28/01/2021, 17:30:20] [BroadlinkRM] [INFO] Discovered Broadlink RM3 Mini D (5f36) at 192.168.68.133 (24:df:a7:7a:49:9a)

Config:
{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": true,
    "hideWelcomeMessage": true,
    "accesories": [
        {
            "name": "Ar do Quarto",
            "type": "air-conditioner",
            "data": {
                "on": "hex",
                "off": "hex",
                "temperature30": "hex",
                "temperature29": "hex"
            }
        }
    ]
}

**Comment by kiwi-cam** [comment]
Accessories has two S's 😊 (three if you count the last one)
`"accessories": [`

**Comment by eliteladen** [comment]
Oh my God lol, sorry, English is not my native language. Thank you!
