### ISSUE TITLE
RM3 Pro (279d) not working nor learning

### ISSUE THREAD

**Issue by fizulnizam** [kiwi-cam/homebridge-broadlink-rm#217]
Title. I have tried resetting it and repairing it with Broadlink app but to no avail. I noticed that when running a command through the homebridge log, it appears to send the request to the device but nothing from the device side (as in the RF command was not being transmitted). The plugin works well with my RM Mini 3 and RM 4c Mini but it stopped working with my RM 3 Pro ever since the 4.4.1 update. 
Hope to get it fixed soon.

**Comment by kiwi-cam** [comment]
There was an issue in kiwicam-broadlinkjs-rm@0.9.9 which stopped RM3 devices. Could you run `npm list -g --depth=1` and make sure you see **kiwicam-broadlinkjs-rm@0.9.10** or a later version

```
├─┬ homebridge-broadlink-rm-pro@4.4.1 
│ ├── chai@4.2.0 
│ ├── compare-versions@3.6.0 
│ ├── find-key@2.1.3 
│ ├── github-version-checker@2.2.0 
│ ├── kiwicam-broadlinkjs-rm@0.9.10 
│ ├── mqtt@4.2.6 
│ ├── node-arp@1.0.6 
│ ├── node-persist@2.1.0 
│ ├── ping@0.3.0 
│ ├── semver@7.3.4 
│ └── uuid@8.3.2
```

**Comment by fizulnizam** [comment]
I am running your plugin on HOOBS version 3.3.2. When I try to run `npm list -g --depth=1` in Terminal it wouldn't respond with anything..

**Comment by fizulnizam** [comment]
So I've uninstall and reinstalled the plugin again but still it doesn't work.. My other RM 3 Minis works well..

**Comment by kiwi-cam** [comment]
Could you install the latest BETA and retest? I've done a bit of work/learning about the RF learning process and I'm interested in hearing the results: https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45#issuecomment-772093495

**Comment by fizulnizam** [comment]
Would love to test the Beta for you but just am not very sure how do I install the Beta... Can you point me to how do I install it then I'd be happy to tell you how does it work for me?

**Comment by kiwi-cam** [comment]
Sorry @fizulnizam

From the shell you can do so using: `npm install -g homebridge-broadlink-rm-pro@beta`
To revert to latest stable release: `npm install -g homebridge-broadlink-rm-pro@latest`

If you're using the Web UI you can follow these steps: https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions.

**Comment by kiwi-cam** [comment]
@fizulnizam Any updates on this?

I've just pushed a new version of the module that fixes RM4 RF Learning. If you just re-install/update homebridge-broadlink-rm-pro you should now get the updated version. I'd love to hear if this resolves the issue, and if not I'd love to see the Debug logs.

**Comment by fizulnizam** [comment]
Very sorry for the late reply. I was not able to install the beta however, the latest update of 4.4.1 actually did fix it for me! Now my RM Pro device can be used again, as well as learning IR and RF. Huge thanks to you @kiwi-cam!
