### ISSUE TITLE
Heater Cooler never sends "on" code

### ISSUE THREAD

**Issue by malwcal** [kiwi-cam/homebridge-broadlink-rm#223]
Hello,

As far as I can tell, heater cooler never sends the **on** code.   I am trying to control a split system air conditioner where the remote on/off key is a toggle switch.  When you press it the air conditioner will turn off if it is on, or on if it is already off.  Which is never great for this type of automation, but anyway...

With the air conditioner already off, asking HomeKit  to turn it **on** makes it beep and quickly shows a number on the display.  But it does not turn on.  If next I use homekit to turn it **off** it will then turn on.  (And now the state is completely wrong in homekit vs reality).

Looking at the logs shows it is sending the temperature code, but never the **on** code.

I am guessing heater cooler needs something like "turnOnWhenOff" which is implemented for air-conditioner but not heater cooler.

(Air-conditioner is a NEC model, and if anyone knows stateful "on" or "off" codes feel free to send them through!)

**Comment by malwcal** [comment]
Any progress with this?  Is there anything I can do to help?

**Comment by malwcal** [comment]
@kiwi-cam Is there anything to do here?  I don't know if I have just set this up incorrectly, or if this is an issue with Heater Cooler.  But as previously mentioned I have never seen a log indicating that the "on" code is actually sent.

**Comment by lamatuzzi** [comment]
@malwcal, I'm facing the same problem as you with my split air conditioner. The plugin never sends the "on" code. 

I'm using stateless switches to turnaround this situation. 

If you have some news about, please let me know.

Tks !

**Comment by benjabustamante** [comment]
i have a same problem ! never send "ON" code

**Comment by kiwi-cam** [comment]
The latest BETA adds turnOnWhenOff support to the HeaterCooler Accessory. Just add `"turnOnWhenOff": true,` to the accessory Config and either Heat.On or Cool.On will be sent first when the accessory is first turned on.

Let me know how you get on.

**Comment by malwcal** [comment]
Hi,

I will try this tonight.

But I do wonder: without turnOnWhenOff, in what circumstance will the On code actually be sent? 

In other words: isn’t the fact that someone has gone to the trouble of providing an On code reason enough to send it?  It would certainly be less confusing.

**Comment by kiwi-cam** [comment]
I had the same thought @malwcal. My reason for going this way was to be consistent with how the aircon accessory operates and to utlise the same config options: https://broadlink.kiwicam.nz/#air-conditioner

If I was building this again, from the ground up, I'd certainly do things differently but I felt that changing this (or having two similar accessories behave differently) could cause more disruption than it was worth.

**Comment by malwcal** [comment]
Ah yes @kiwi-cam, I understand where you are coming from.

Maybe a warning: "you have defined an ON code but this won't be used unless you enable turnOnWhenOff"?

Or perhaps: if an ON code is defined default "turnOnWhenOff" to true AND log "ON code defined, setting turnOnWhenOff to true, set this to false if this is not required", so the user can set it to false if thats really what they want.

I guess my point is that even with this option now available this is hardly intuitive.  (Although of course documentation can help!)

Thanks for looking at this!
