### ISSUE TITLE
RM pro (2223) stops responding on 4.4.1 

### ISSUE THREAD

**Issue by deeloke** [kiwi-cam/homebridge-broadlink-rm#224]
After upgrading to 4.4.1, my rm pro (2223) stopped responding. No error reported, the rm simply didn’t send the codes to my devices. I rolled back to 4.4.0 and normal operation resumed. My other RM4 devices worked properly on both versions..

**Comment by kiwi-cam** [comment]
Are you able to adjust your config to enable debugging and share what you see?
```
{
   "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "debug": true,
    "accessories": [{
```
I'd also love to confirm what version of the kiwicam-broadlinkrm-js module you're using. Can you also run `npm list -g --depth=1` and share the resuts?

**Comment by xwteoh** [comment]
Hello kiwi-cam,

I'm facing similar issue where my rm pro+ stopped responding for my fan control. It was working fine before.
Right now, I can see the Fan control in home app and I'm able to change the fan speed too. However, it doesn't seem to sent any signal to my fan. Looking at home bridge log, I did not see any errors and it just indicate signal sent
<img width="1236" alt="Screenshot 2021-02-14 at 10 45 12 AM" src="https://user-images.githubusercontent.com/63406185/107867069-52f5b300-6eb2-11eb-9f77-7327d36c2f88.png">

my "npm list -g --depth=1" looks like below: 
<img width="1294" alt="Screenshot 2021-02-14 at 10 44 40 AM" src="https://user-images.githubusercontent.com/63406185/107867088-82a4bb00-6eb2-11eb-95d1-6f988d150ca5.png">

For my case, I tried to roll back to 4.4.0 doesn't work too. :(
I'm able to ping my Broadlink RM Pro from homebridge server without issue. Also able to control thru Broadlink App. I've also unlock the device in Broadlink app.

Appreciate if you could help on this.

Thank you.

**Comment by mitch7391** [comment]
I am facing the same issue @kiwi-cam i thought with the hex code being sent but nothing happening was an issue with the receiver in the fan or the broadlink rm pro getting old... Now I am glad to hear it might be plug-in related!

**Comment by mitch7391** [comment]
@kiwi-cam is there any idea what might be causing this, I have actually realise that a bunch of my broadlink controlled devices are not working (send hex code in Homebridge but does nothing). This plug-in is the foundations of my home automation and I am losing a lot of ground work I put in to get my wife using it all lol...

**Comment by mitch7391** [comment]
Commenting to keep this one alive.
