### ISSUE TITLE
Editing automation with air conditioner stuck when use plugin 

### ISSUE THREAD

**Issue by sanychonline** [kiwi-cam/homebridge-broadlink-rm#225]
Editing automation with air conditioner stuck when use plugin 
Issue reproduces each time until remove AirConditioner from automation script.

**Comment by kiwi-cam** [comment]
Could you give more information? What are you trying to do, what happens, and what are you expecting to happen.  Also try to include in relevant logs or screen shots.

**Comment by kiwi-cam** [comment]
This appears to be a HomeKit issue:

- https://forums.macrumors.com/threads/home-app-edit-scene-freeze-lockup.2255310/
- https://www.reddit.com/r/HomeKit/comments/ive784/ios14_home_app_freezing_when_editing_scene/
