### ISSUE TITLE
Changing Aircon temperature

### ISSUE THREAD

**Issue by fallyg** [kiwi-cam/homebridge-broadlink-rm#23]
Hi, the Air conditioner that I have is using only + and - to change temperature.

Just wondering, how can I set change temperature? i have only 2 Hex codes one for + and one for -

Thanks

**Comment by Edsonytic** [comment]
I would suggest checking the [original documentation's air-conditioner section](https://lprhodes.github.io/slate/#air-conditioner), specifically the paragraph about "Adding autoHeatTemperature and autoCoolTemperature can help automatically maintain a temperature…".

If you do not have a device with temperature sensor then my suggestion would be to just setup two switches.
