### ISSUE TITLE
Homekit not finding TV

### ISSUE THREAD

**Issue by fmpmsilva** [kiwi-cam/homebridge-broadlink-rm#232]
Hi,

I have made all the configuration but i can't make Homekit find the TV, it doesn't show.

Any idea?

**Comment by masterfordev** [comment]
Did you add it in the home app?

**Comment by fmpmsilva** [comment]
That’s the problem. When I try to ad it, it doesn’t show.

**Comment by masterfordev** [comment]
Share your config please.

**Comment by fmpmsilva** [comment]
{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "hideWelcomeMessage": false,
    "hosts": [
        {
            "address": "IPADRESS",
            "mac": "MACADRESS",
            "isRFSupported": false,
            "isRM4": true
        }
    ],
    "acessories": {
        "name": "TVHisense",
        "type": "tv",
        "data": {
            "on": "2600600000012391131113111411131113111411131113111435143513361335143513361311133613351411133613351411131113111411131113361311131114351336133613351400053e0001254813000c3b0001254813000c3b0001254813000d05000000000000",
            "off": "2600680000012490141113111311141113111411131113111435133613351435143513361311133613361311133613351411131113111411131114351311141113351435133613361300053f0001254813000c3b0001274615000c3a0001254616000c380001254813000d050000000000000000000000000000",
            "remote": {
                "select": "260080000001239014111311131114111311131213111311143515341533143514351336131113361534131113361311133613111311141113111435150f143513111435153413361300053e0001254813000c3a0001254813000c3b0001244913000c3b0001254813000c3b0001254813000c3b0001254813000c3c0001264616000d05000000000000",
                "arrowUp": "2600800000012391131113111411131113111411131113121335143513361336133514351311143513111435133613111435131114111311133613111411133514111335143513361300053b0001254813000c370001254813000c370001254813000c370001254813000c370001254813000c370001244814000c350001264714000d05000000000000",
                "arrowDown": "2600b8000001239014111311131114111311131114111311143513361335143513361336131114351335143513361311143513111411131113111411131113361311133613361335140005380001254813000c350001254813000c350001254813000c350001254813000c350001254813000c350001254813000c350001254813000c350001254813000c350001254813000c350001244814000c350001254813000c350001254813000c360001244814000c350001254813000d050000000000000000000000000000",
                "arrowLeft": "2600c80000012391141113111311141113111311141113111435133613351435133613361311133613351411131113361336131113111411131113361335141113111435133613351400053d0001254814000c3a0001244814000c3a0001244813000c3a0001254813000c3a0001254813000c3a0001254813000c3a0001254813000c3a0001254813000c3a0001254814000c390001254813000c3a0001254813000c3a0001254813000c3b0001244813000c3a0001254813000c3a0001254813000c3a0001254813000d050000000000000000000000000000",
                "arrowRight": "2600f00000012391141113111311141113111311141113111336133613351435133613361311133613111311141113351534141113111311143513361336131113111435133613351400053c0001254813000c380001254813000c390001254813000c380001254814000c380001254913000c380001254913000c380001254818000c340001254813000c3a0001244813000c390001254813000c390001254813000c390001244814000c380001254813000c380001254813000c380001254813000c390001254813000c390001254813000c390001254814000c380001254813000c390001254813000c380001254814000d05000000000000",
                "playPause": "2600700000012391131114111311131114111311131114111335143513361336133514351311143513111411131114351311143513111435133613361335141113351411133514111300053c0001254813000c380001254813000c390001254813000c380001254814000c380001244814000d05000000000000"
            },
            "volume": {
                "up": "2600c00000012391141113111311141113111311141113111336133613351435133613351411133613111311133613111411131113361311133613351411133613351435131114351300053b0001254813000c360001254814000c370001254813000c370001254813000c360001254814000c360001254814000c370001244814000c370001254813000c380001244813000c370001254813000c380001254814000c370001254813000c380001254813000c380001254813000c380001244814000d05000000000000",
                "down": "260098000001249014111311131114111311141113111311143513361336133514351336131113361336133514111311131213111336131113111411133514351435133613111336130005390001254813000c350001254814000c350001254813000c350001254814000c350001254813000c360001254813000c350001254814000c350001254814000c350001254813000c350001254813000d050000000000000000000000000000"
            },
            "inputs": [
                {
                    "name": "INPUT 1",
                    "type": "hdmi",
                    "data": "learned hex code: 2600980000012391131114111311131114111311131114111335143513361336133514351311143513111435131213111336131113111411133514111335143513121335143513361300053c0001254813000c380001254814000c380001254813000c390001254814000c380001254813000c390001254813000c390001244814000c390001244813000c390001254813000c390001254813000d050000000000000000000000000000"
                }
            ]
        }
    }
}

**Comment by masterfordev** [comment]
You used your homebridge pin for add it on homekit?

**Comment by fmpmsilva** [comment]
Yes. It ads the bridge again.

Im getting this all the time
[2/10/2021, 7:36:43 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 7:39:48 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 7:39:48 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 7:42:44 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 7:42:44 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 7:49:27 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 7:49:27 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 7:50:20 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 7:50:20 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 7:50:29 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 7:50:29 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 7:53:01 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 7:53:01 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 7:56:06 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 7:56:06 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 7:56:48 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 7:56:48 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 7:57:48 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 7:57:48 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 7:58:53 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 7:58:53 AM] [BroadlinkRM] Learn getSwitchState: false
[2/10/2021, 8:01:55 AM] [BroadlinkRM] Scan Frequency getSwitchState: false
[2/10/2021, 8:01:55 AM] [BroadlinkRM] Learn getSwitchState: false

**Comment by fmpmsilva** [comment]
Any idea?

**Comment by kiwi-cam** [comment]
> "acessories": {

There are two c's in accessories 😊

**Comment by fmpmsilva** [comment]
Nice catch 😀Unfortunately got this:
(node:30657) UnhandledPromiseRejectionWarning: TypeError: config.accessories.forEach is not a function
    at BroadlinkRMPlatform.addAccessories (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/platform.js:71:24)
    at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/base/platform.js:28:16)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:415:24
    at new Promise (<anonymous>)
    at Server.loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:414:12)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:402:28
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30657) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30657) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fmpmsilva** [comment]
Hi. Still nothing. I have the learn buttons but can’t add the tv to HomeKit.

**Comment by fmpmsilva** [comment]
Working now. Thanks you all.

**Comment by vladtsit** [comment]
@fmpmsilva could you please share working config, I'm having same issue as you had.

**Comment by vladtsit** [comment]
I'm getting following error [TV C584@TV@Active] characteristic value expected number and received undefined
with config 
                {
                    "name": "TV",
                    "type": "tv",
                    "data": {
                        "on": "123",
                        "off": "123",
                        "volume": {
                            "up": "123",
                            "down": "123"
                        },
                        "inputs": [
                            {
                                "name": "AppleTV",
                                "type": "hdmi",
                                "data": "123"
                            },
                            {
                                "name": "AirTV",
                                "type": "hdmi",
                                "data": "123"
                            }
                        ]
                    }
                }

**Comment by masterfordev** [comment]
> I'm getting following error [TV C584@TV@Active] characteristic value expected number and received undefined
> 
> with config 
> 
>                 {
> 
>                     "name": "TV",
> 
>                     "type": "tv",
> 
>                     "data": {
> 
>                         "on": "123",
> 
>                         "off": "123",
> 
>                         "volume": {
> 
>                             "up": "123",
> 
>                             "down": "123"
> 
>                         },
> 
>                         "inputs": [
> 
>                             {
> 
>                                 "name": "AppleTV",
> 
>                                 "type": "hdmi",
> 
>                                 "data": "123"
> 
>                             },
> 
>                             {
> 
>                                 "name": "AirTV",
> 
>                                 "type": "hdmi",
> 
>                                 "data": "123"
> 
>                             }
> 
>                         ]
> 
>                     }
> 
>                 }

That is not an error. Its just a warning. And its because you are not using a ping IP Address. Just wait until next release (no ETA).

**Comment by vladtsit** [comment]
> That is not an error. Its just a warning. And its because you are not using a ping IP Address. Just wait until next release (no ETA).

but TV does not appear in homekit

**Comment by fmpmsilva** [comment]
This is my config:


"name": "Televisão",
            "type": "tv",
            "pingIPAddress": "xxx.xxx.x.xx",
            "pingUseArp": true,
            "pingIPAddressStateOnly": true,
            "pingFrequency": 5,
            "pingGrace": 15,
            "data":

**Comment by vladtsit** [comment]
> "name": "Televisão",
> "type": "tv",
> "pingIPAddress": "xxx.xxx.x.xx",
> "pingUseArp": true,
> "pingIPAddressStateOnly": true,
> "pingFrequency": 5,
> "pingGrace": 15,
> "data":

Coud you please share full config? Still cannot get it working. Homekit do not see TV.

**Comment by masterfordev** [comment]
> This is my config:
> 
> 
> 
> 
> 
> "name": "Televisão",
> 
>             "type": "tv",
> 
>             "pingIPAddress": "xxx.xxx.x.xx",
> 
>             "pingUseArp": true,
> 
>             "pingIPAddressStateOnly": true,
> 
>             "pingFrequency": 5,
> 
>             "pingGrace": 15,
> 
>             "data":

Your tv dont support "normal ping"? Or why are you using Arp Ping?

**Comment by mrmaster1** [comment]
Hi All,
First of all, thank you for you hard work with this plugin!
I'd like to ask for some hints, how to set up a Samsung tv, because when I add it into the config and try to add it as new accessory, it **asks for the 8 digit HomeKit setup code**.
How can I predefine that?

my config is:
{
                    "name": "TV",
                    "type": "tv",
                    "subType": "tv",
                    "pingIPAddress": "192.168.1.40",
                    "pingFrequency": 5,
                    "pingIPAddressStateOnly": true,
                    "pingUseArp": false,
                    "pingGrace": 15,
                    "data": {
                        "on": "xx",
                        "off": "xx",
                        "remote": {
                            "select": "xx",
                            "arrowUp": "xx",
                            "arrowDown": "xx",
                            "arrowLeft": "xx",
                            "arrowRight": "xx",
                            "back": "xx",
                            "playPause": "xx",
                            "exit": "xx",
                            "info": "xx"
                        }
                    }
                }

Thank you,
Zoltan

**Comment by masterfordev** [comment]
The pin code is the pin of your homebridge.

**Comment by mrmaster1** [comment]
thank you, somehow first time it did not work, but later it is working well.

**Comment by lamatuzzi** [comment]
> This is my config:
> 
> "name": "Televisão",
> "type": "tv",
> "pingIPAddress": "xxx.xxx.x.xx",
> "pingUseArp": true,
> "pingIPAddressStateOnly": true,
> "pingFrequency": 5,
> "pingGrace": 15,
> "data":

@fmpmsilva are you Brazilian? I am 😊
 I have the same issue as you had. How do you fix?

My TV doesn't show to add in Home App. When I use "switch" accessory, it adds in Home App, but when I use "tv" accessory, Home App keeps looking for the accessory and doesn't appear to put PIN code. I attached my Home App's preview.

Thanks !
![IMG_2510](https://user-images.githubusercontent.com/80293045/115500251-4e999d80-a247-11eb-89dd-84bf76304deb.jpg)

**Comment by fmpmsilva** [comment]
Hi. I’m Portuguese. Can you share your config?

**Comment by lamatuzzi** [comment]
> Hi. I’m Portuguese. Can you share your config?

I found the solution! Here in my home, I have 2 Apple TVs as Home Central. This situation causes a bug in Homebridge that we can't add an accessory. When I disabled the 2nd Apple TV as Home Central, the accessory appeared in Home App.

If someone has this problem, I hope that this solution can help! 😊

Thanks (obrigado!)
