### ISSUE TITLE
IR learning not working after RF was resolved with beta 

### ISSUE THREAD

**Issue by necccc** [kiwi-cam/homebridge-broadlink-rm#233]
**Describe the bug**
IR learning not working since #45 

**To Reproduce**
1. Go to Accessories
2. Click on Learn
3. Go back to Status, check logs
4. IR learn did not start

**Expected behavior**
When I start IR learning, it starts to wait for IR signals

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 88

**Additional context**
In #45 we're testing a fix for RF learning, seems like that patch broke IR learning?

**Comment by kiwi-cam** [comment]
Hi @necccc. Are you able to enable debugging and share the logs? IR Learning is working in the current version for myself and others so we need to find what is different.  What Broadlink device do you have?

**Comment by captaincat25** [comment]
I am having this issue as well. My RM4 Mini works fine to control devices that I have already set up. However, for some reason it is not picking up IR codes when I try to learn new ones.
