### ISSUE TITLE
Broadlink RM4 Pro not displaying Humidity/Temperature in HomeKit

### ISSUE THREAD

**Issue by ghost** [kiwi-cam/homebridge-broadlink-rm#234]
I am new to HomeBridge (I am using HOOBS on a Raspberry Pi with a Broadlink RM4 Pro). 

I am having issues getting the Temperature/Humidity displayed in HomeKit. The Temperature/Humidty is displayed correctly in the Broadlink app so I know that the device is working as expected.

Any ideas what I am doing wrong?

Here is the HOOBS configuration:
{
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "hideWelcomeMessage": false,
    "accessories": [
        {
            "name": "Humidity",
            "type": "humiditySensor"
        },
        {
            "name": "Temperature",
            "type": "temperatureSensor"
        }
    ]
}

Screenshots
![IMG_0418](https://user-images.githubusercontent.com/78934051/107698616-ad0f4080-6d19-11eb-9ef9-73b903ed060e.PNG)
![IMG_0417](https://user-images.githubusercontent.com/78934051/107698623-aed90400-6d19-11eb-9edf-2b69138102ed.PNG)

**Comment by kiwi-cam** [comment]
Can you share your logs?  You should see something like this when the device is queried:
```
Feb 12 10:10:23 homebridge[604]: [Broadlink RM] Bedroom Humidity onHumidity (52.03)
Feb 12 10:10:23 homebridge[604]: [Broadlink RM] Bedroom Temperature onTemperature (18.24)
```

**Comment by ghost** [comment]
Thanks. I don't see any reference to onHumidity or onTemperature:

12/02/2021, 9:50:19 am [Broadlink RM] Initializing BroadlinkRM platform...
12/02/2021, 9:50:19 am [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
12/02/2021, 9:50:19 am [Broadlink RM] Humidity Accessory Ready
12/02/2021, 9:50:19 am HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
12/02/2021, 9:50:19 am HAP Warning: Characteristic 00000036-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
12/02/2021, 9:50:19 am [Broadlink RM] Temperature Accessory Ready
12/02/2021, 9:50:19 am [Ring] Configuring cached accessory db584819-63b5-4b8e-be62-2ae3ab22e1c3 Side
12/02/2021, 9:50:19 am [Ring] Configuring cached accessory d75b7c29-94a7-452a-bb61-04ef07cc93ed Front Door
12/02/2021, 9:50:19 am Initializing platform accessory 'Learn'...
12/02/2021, 9:50:19 am Initializing platform accessory 'Scan Frequency'...
12/02/2021, 9:50:19 am Initializing platform accessory 'Humidity'...
12/02/2021, 9:50:19 am Initializing platform accessory 'Temperature'...
12/02/2021, 9:50:21 am [Broadlink RM] 
12/02/2021, 9:50:21 am [Broadlink RM] **************************************************************************************************************
12/02/2021, 9:50:21 am [Broadlink RM] ** Welcome to version 4.4.1 of the Homebridge Broadlink RM Plugin!
12/02/2021, 9:50:21 am [Broadlink RM] ** 
12/02/2021, 9:50:21 am [Broadlink RM] ** Find out what's in the latest release here: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/CHANGELOG.md
12/02/2021, 9:50:21 am [Broadlink RM] ** 
12/02/2021, 9:50:21 am [Broadlink RM] ** If you like this plugin then please star it on GitHub or better yet
12/02/2021, 9:50:21 am [Broadlink RM] ** buy me a drink using Paypal https://paypal.me/kiwicamRM.
12/02/2021, 9:50:21 am [Broadlink RM] **
12/02/2021, 9:50:21 am [Broadlink RM] ** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
12/02/2021, 9:50:21 am [Broadlink RM] **
12/02/2021, 9:50:21 am [Broadlink RM] **************************************************************************************************************
12/02/2021, 9:50:21 am [Broadlink RM] 
12/02/2021, 9:50:24 am [Ring] Found the following locations:
12/02/2021, 9:50:24 am [Ring]   locationId: rbsmyy-1uncu-0 - My Location
12/02/2021, 9:50:24 am [Ring] Configuring 2 cameras and 2 devices for location "My Location" - locationId: rbsmyy-1uncu-0
12/02/2021, 9:50:26 am [myQ] myQ API: Successfully connected to the myQ API.
12/02/2021, 9:50:26 am [Nest Protect] initing protect "Office": deviceId: 18B4300000A63262 structureId: 1108b144-1d46-11ea-ae74-12d8cf60863a
12/02/2021, 9:50:26 am [Nest Protect] initing protect "Hallway": deviceId: 6416660000D23F7A structureId: 1108b144-1d46-11ea-ae74-12d8cf60863a
12/02/2021, 9:50:26 am Initializing platform accessory 'Office'...
12/02/2021, 9:50:26 am Initializing platform accessory 'Hallway'...
12/02/2021, 9:50:26 am Bridge is running on port 51826.
12/02/2021, 9:50:29 am [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: CG08114002BB, gateway: GWA1000006C7).
12/02/2021, 9:50:29 am [myQ] myQ API: Discovered device family gateway: Home (serial number: GWA1000006C7).
12/02/2021, 9:50:32 am [Broadlink RM] Learn getSwitchState: false
12/02/2021, 9:50:32 am [Broadlink RM] Scan Frequency getSwitchState: false
12/02/2021, 9:50:45 am [Broadlink RM] Learn getSwitchState: false
12/02/2021, 9:50:45 am [Broadlink RM] Scan Frequency getSwitchState: false
12/02/2021, 9:51:18 am [Broadlink RM] Learn getSwitchState: false
12/02/2021, 9:51:18 am [Broadlink RM] Scan Frequency getSwitchState: false
12/02/2021, 9:52:47 am [Ring] Front Door Detected Motion
12/02/2021, 10:00:21 am [Broadlink RM] Learn getSwitchState: false
12/02/2021, 10:00:21 am [Broadlink RM] Scan Frequency getSwitchState: false
12/02/2021, 10:05:43 am [Broadlink RM] Learn getSwitchState: false
12/02/2021, 10:05:43 am [Broadlink RM] Scan Frequency getSwitchState: false
12/02/2021, 10:08:13 am [Broadlink RM] Learn getSwitchState: false
12/02/2021, 10:08:13 am [Broadlink RM] Scan Frequency getSwitchState: false
12/02/2021, 10:08:56 am [Broadlink RM] Learn getSwitchState: false
12/02/2021, 10:08:56 am [Broadlink RM] Scan Frequency getSwitchState: false
12/02/2021, 10:14:58 am [Broadlink RM] Learn getSwitchState: false
12/02/2021, 10:14:58 am [Broadlink RM] Scan Frequency getSwitchState: false
12/02/2021, 10:16:08 am [Broadlink RM] Scan Frequency getSwitchState: false
12/02/2021, 10:16:08 am [Broadlink RM] Learn getSwitchState: false

**Comment by kiwi-cam** [comment]
Looks like it's not finding your device, there should also be a line:
`
Feb 12 11:09:40 homebridge[7204]: [Broadlink RM] [INFO] Discovered Broadlink RM4 Pro (6026) at 192.168.x.x (24:df:a7:xx:xx:xx)
`

Have you "unlocked" your device so it can be access locally: https://broadlink.kiwicam.nz/#requirements?

**Comment by ghost** [comment]
Apologies (I'm an idiot). I had removed the Broadlink device from the app and re-added it and forgot this very important step.
