### ISSUE TITLE
RM3 Mini goes offline for a few minutes every hour at the same time.

### ISSUE THREAD

**Issue by realdannys** [kiwi-cam/homebridge-broadlink-rm#245]
I've been seeing this (with two different plugins now) in my Homebridge logs.

```
[12/8/2020, 2:59:13 PM] [Broadlink RM] [ERROR]  Broadlink RM device at 192.168.0.145 (77:0f:78:32:04:29) is no longer reachable after three attempts.
[12/8/2020, 3:06:47 PM] [Broadlink RM] Broadlink RM device at 192.168.0.145 (77:0f:78:32:04:29) has been re-discovered.
```
Any ideas why this would happen? It happens at the exact same time very hour almost like the device is doing an hourly reboot. I've seen one other person mention this, which strikes me as meaning not everyone has it. It's not wifi related, obviously it's exactly the same time every hour so it's something the device itself is doing for whatever reason.

**Comment by masterfordev** [comment]
Plugin & homebridge versions?

**Comment by realdannys** [comment]
Well i'm running the latest version of the plugin and 1.3.1 of Homebridge. However it's been happening for months now with all versions of Homebridge and also with the plugin this is forked from.

It's once an hour at the same time it goes offline for 3 minutes. I can see mention of other people saying this happens too, but no answers and I don't know if it's caused by plugin communication or some kind of bug in the RM Mini firmware itself.

**Comment by MaJoHo** [comment]
i have the same issue is there any progress?
