### ISSUE TITLE
 One of your plugins incorrectly registered an external accessory using the platform name ([object Object]) and not the plugin identifier. Please report this to the developer!

### ISSUE THREAD

**Issue by CaldenMig21** [kiwi-cam/homebridge-broadlink-rm#246]
I am receiving this message in the log: "One of your plugins incorrectly registered an external accessory using the platform name ([object Object]) and not the plugin identifier. Please report this to the developer!"
I just want to report the issue (as requested by the message). I am not sure if this is limiting the accesories functionality in homekit

LOG:
22/2/2021 18:31:21 [Broadlink RM] Initializing BroadlinkRM platform...
22/2/2021 18:31:21 [Broadlink RM] [INFO] Automatic Broadlink RM device discovery has been disabled as the "hosts" option has been set.
22/2/2021 18:31:21 [INFO] Adding RF Support to device a0:43:b0:18:ed:e0 with type 2227
22/2/2021 18:31:21 [INFO] Adding RF Support to device a0:43:b0:19:0f:49 with type 2227
22/2/2021 18:31:21 [Broadlink RM] [INFO] Running Homebridge Broadlink RM Plugin version 4.4.1
22/2/2021 18:31:21 [Broadlink RM] TV Oficina Accessory Ready
22/2/2021 18:31:21 [Broadlink RM] Forzar HDMI ON en Oficina Accessory Ready
22/2/2021 18:31:21 [Broadlink RM] Forzar TV OFF en Oficina Accessory Ready
22/2/2021 18:31:22 [Broadlink RM] Aire Oficina Accessory Ready
22/2/2021 18:31:22 [Broadlink RM] Cortina Cuarto Principal Accessory Ready
22/2/2021 18:31:22 [Broadlink RM] TV Principal Accessory Ready
22/2/2021 18:31:22 [Broadlink RM] Forzar HDMI ON en Principal Accessory Ready
22/2/2021 18:31:22 [Broadlink RM] Forzar TV OFF en Principal Accessory Ready
22/2/2021 18:31:22 [Broadlink RM] Aire Cuarto Principal Accessory Ready
22/2/2021 18:31:22 One of your plugins incorrectly registered an external accessory using the platform name ([object Object]) and not the plugin identifier. Please report this to the developer!
22/2/2021 18:31:22 External port pool ran out of ports. Fallback to random assign.
22/2/2021 18:31:22 External port pool ran out of ports. Fallback to random assign.
22/2/2021 18:31:22 [Broadlink RM] 
22/2/2021 18:31:22 [Broadlink RM] **************************************************************************************************************
22/2/2021 18:31:22 [Broadlink RM] You added TVs in your configuration!
22/2/2021 18:31:22 [Broadlink RM] Due to a HomeKit limitation you need to add any TVs to the Home app by using the Add Accessory function.
22/2/2021 18:31:22 [Broadlink RM] There you'll find your TVs and you can use the same PIN as you using for this HomeBridge instance.
22/2/2021 18:31:22 [Broadlink RM] **************************************************************************************************************
22/2/2021 18:31:22 [Broadlink RM]

**Comment by masterfordev** [comment]
No much to do [#26](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/26)
