### ISSUE TITLE
 "switch-repeat"  shall be removed in the future. 

### ISSUE THREAD

**Issue by EltuZ** [kiwi-cam/homebridge-broadlink-rm#248]
Hi,

The "switch-repeat" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm

Are there any new accessories for the "switch repeat"?
{
                    "name": "Sony HW45",
                    "type": "switch-repeat",
                    "sendCount": 1,
                    "offSendCount": 2,
                    "interval": 1,
                    "disableAutomaticOff": true,
                    "data": {
                        "on": "xxxxx",
                        "off": "xxxxx"
                    }
                }

I couldn't find the switch documentation. 
I'm looking forward to help :-)

**Comment by kiwi-cam** [comment]
Sorry, I'm not sure what you're referring to. That repo and documentation haven't been updated in more than 14 months and don't mention any deprecation.

**Comment by EltuZ** [comment]
The protocol say me this: 
[25/02/2021, 09:32:07] [BroadlinkRM] **[Warning]** Sony HW45: **The "switch-repeat" accessory is now deprecated and shall be removed in the future.** Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm
[25/02/2021, 09:32:08] [BroadlinkRM] Learn getSwitchState: false
[25/02/2021, 09:32:08] [BroadlinkRM] Scan Frequency getSwitchState: false
[25/02/2021, 09:32:08] [BroadlinkRM] Leinwand getSwitchState: false
[25/02/2021, 09:32:08] [BroadlinkRM] Sony HW45 getSwitchState: false

**Comment by kiwi-cam** [comment]
Haha, I haven't used these accessories before so haven't noticed that before.  I think these accessory types were added before the ["Advanced Hex Structure"](https://broadlink.kiwicam.nz/#advanced-hex-structure) options were added.

It's probably a good idea to implement any repeats using these options instead - but I've got no plans to remove these from this fork anytime soon.

**Comment by EltuZ** [comment]
The new Switch-off :
                {
                    "name": "Sony HW45",
                    "type": "switch",
                    "data": [
                                    {
                       "data": "xxxxx",
                        "sendCount": 2,
                        "interval": 0.5
                                       }
                                    ]
                }
Is it correct that way? Thank you for your help.
