### ISSUE TITLE
Unable to discover RM4 PRO

### ISSUE THREAD

**Issue by darrenkhu** [kiwi-cam/homebridge-broadlink-rm#25]
I am having some challenge getting this to work. 

I installed homebridge using the official homebridge imageee.
https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started

Then I installed homebridge-broadlink-rm-pro v4.2.8. However it doesn't seems like it discovered my broadlink eventho connected to the same wifi network.

Things I have tried:
1. Using Broadlink App - Able to use it ok and able to add both IR and RF functions
2. Reset Broadlink App - to only connect to wifi but not choose a room. Nothing seem to happen

Would appreciate some help in getting this resolved.

Thank you

**Comment by Faisalthe01** [comment]
Delete your device from Broadlink app, add it again using AP Mode, kill the app after the Broadlink connects to your Wifi and do not complete the setup then you will see your Broadlink RM 4 discovered in logs

**Comment by enishoca** [comment]
> Delete your device from Broadlink app, add it again using AP Mode, kill the app after the Broadlink connects to your Wifi and do not complete the setup then you will see your Broadlink RM 4 discovered in logs

I had a similar issue with RM4 mini - this worked like a charm - @kiwi-cam  would you be kind enough to put this in the Readme.md.  I had virtually given up, until I came across this.
@Faisalthe01  Eid Mubarak... :)

**Comment by Faisalthe01** [comment]
> > Delete your device from Broadlink app, add it again using AP Mode, kill the app after the Broadlink connects to your Wifi and do not complete the setup then you will see your Broadlink RM 4 discovered in logs
> 
> I had a similar issue with RM4 mini - this worked like a charm - @kiwi-cam would you be kind enough to put this in the Readme.md. I had virtually given up, until I came across this.
> @Faisalthe01 Eid Mubarak... :)

Glad you got it working. Eid Mubarak to you too.

**Comment by darrenkhu** [comment]
Need to clarify a few things:
1. Is this referring to the latest broadlink app (blue icon with a letter B)? I've actually tried the step proposed but it didn't work out.
2. Anyway to troubleshoot if my network is somehow restricting auto adding of the broadlink rm4 pro?

Edit: Works! Turns out in all the resetting i've been doing i've accidentally resetted my config file. Thank you so much
