### ISSUE TITLE
Can’t get temperature from the AC built in sensor

### ISSUE THREAD

**Issue by fmpmsilva** [kiwi-cam/homebridge-broadlink-rm#251]
![69044863-8F08-48A3-8867-A7ADE80B44B7](https://user-images.githubusercontent.com/78658064/109188865-482cff00-778b-11eb-8efa-ef0a5104fe6f.png)

Hi there. Can’t get temperature from the AC built in sensor. Any help?

**Comment by kiwi-cam** [comment]
Can you share your config and logs?

**Comment by fmpmsilva** [comment]
{
            "name": "AC",
            "type": "air-conditioner",
            "preventResendHex": true,
            "turnOnWhenOff": true,
            "pseudoDeviceTemperature": 19,
            "minTemperature": 16,
            "maxTemperature": 30,
            "defaultHeatTemperature": 23,
            "defaultCoolTemperature": 21,
            "temperatureUpdateFrequency": 20,
            "replaceAutoMode": "heat",
            "data": {
              

…………………………

**Comment by fmpmsilva** [comment]
[2/25/2021, 6:32:51 PM] [BroadlinkRM] AC getCurrentHeatingCoolingState: 0
[2/25/2021, 6:32:51 PM] [BroadlinkRM] AC getTargetTemperature: 25
[2/25/2021, 6:32:51 PM] [BroadlinkRM] AC getTargetHeatingCoolingState: 0

**Comment by fmpmsilva** [comment]
I have a temperature and humidity sensor from Shelly. Can I add it to the config has ac sensor?

**Comment by kiwi-cam** [comment]
This line will stop the plug-in attempting to get the temperature from the Broadlink:
`"pseudoDeviceTemperature": 19,`

It should instead be fixed at 19 degrees.  Could you remove that line and see if you're able to get readings?

This plug-in supports text file and MQTT sources for temperature and humidity. If you can get the reading from the Shelly via either of those you'll be able to get them.
