### ISSUE TITLE
Does not work on RM mini 4

### ISSUE THREAD

**Issue by huongminh** [kiwi-cam/homebridge-broadlink-rm#254]
**Describe the bug**
I am not sure this is a bug or new feature request so excuse me if this post is in the wrong category. I use this plug in very well with my 3 RM Pros and 3 RM mini 3. Recently one of my RM mini 3 stopped working. So I bought a RM mini 4 and replaced it. After setting it up and test with the Broadlink app successfully I set it in the plugin (change the IP and Mac address of the old one to this new one). However, the RM mini 4 did not work. Please help!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kiwi-cam** [comment]
Can you share your config and logs? I'm using an RM4 Mini myself without issue
