### ISSUE TITLE
Suppress Learn & Scan getSwitchState: logging

### ISSUE THREAD

**Issue by mishakim** [kiwi-cam/homebridge-broadlink-rm#255]
**Describe the solution you'd like**
Whenever I look at my homebridge logs, they're full of 
`[2/27/2021, 10:07:07 AM] [Broadlink RM] Learn getSwitchState: false
[2/27/2021, 10:07:07 AM] [Broadlink RM] Scan Frequency getSwitchState: false`
every few min, all day. Since I don't generally use those once things are set up, they don't need such verbose logging.

**Describe alternatives you've considered**
Having a setting to not deploy those switches until needed would be a nice enhancement, but just not logging their idle state is all I really want

**Comment by soulcook** [comment]
This feature already exists. Just set

“disableLogs”: true

for each accessory.

**Comment by mishakim** [comment]
but there's no accessory entry for the Learn and Scan accessories

**Comment by soulcook** [comment]
I've got this in my config, and it works...

```
    "accessories": [
        {
            "type": "learn-code",
            "disableLogs": true
        },
```

**Comment by mishakim** [comment]
Thanks - that did it!  I think I has missed that entry in the documentation, and wouldn't have appreciated that it was useful when there was no other reason to explicitly define that accessory.
