### ISSUE TITLE
LG window mount air conditioner

### ISSUE THREAD

**Issue by hpstephens** [kiwi-cam/homebridge-broadlink-rm#256]
I was looking for a way to add a Portable LG window air conditioner. The unit has six buttons; POWER, Temp up, Temp down, fan speed, timer and mode.

**Comment by masterfordev** [comment]
What's the problem?

**Comment by hpstephens** [comment]
I'm sorry for not responding. When configuring the settings I haven't been able to get the plugin the control the air conditioner.
