### ISSUE TITLE
A stateless switch option would be VERY useful

### ISSUE THREAD

**Issue by soulcook** [kiwi-cam/homebridge-broadlink-rm#257]
**The problem**
I think this plugin is great. and use it all the time to control the projector in my home cinema.

The problem is, there's no feedback from the projector. It switches on when it gets an "on" signal, and off when it gets an "off" signal. But there's no way for homebridge-broadlink-rm to detect what state it's in. This must be a pretty common situation.

As a result, it's easy for the projector to get out of sync with the plugin, for example if it's turned on or off using its own remote, or if it misses a command. (To protect the bulb, it ignores commands when it has only just turned on or off).

As it stands, the plugin won't let you send on "off" signal if it thinks the device is already off, or an "on" signal if it thinks it's on. So if the projector is on, but homebridge-broadlink-rm doesn't happen to know that it's on, and you say "Hey Siri, turn off the projector", nothing happens. This is particularly inconvenient when running a "good night" automation that's supposed to turn everything off – you have no way of knowing whether it actually sent an off signal to the projector as instructed. 

**The solution**
The ideal solution would be to have homebridge-broadlink-rm provide the option of a stateless Homekit switch, like the ones in the [homebridge-dummy](https://github.com/nfarina/homebridge-dummy) plugin for example. The switch would function like a button, and would automatically turn itself off a second or two after being turned on. 

You could then have one switch for "off" and another one for "on". The on and off commands would be stateless, and you could happily issue them at any time without having to take pot-luck with the state that the plugin happens to think the accessory is in.

**Describe alternatives you've considered**
A possible workaround for some devices would be to always send "off" followed by "on" when you mean "on", and "on" followed by "off" when you mean "off". That way you should hopefully end up in the right state.

But that wouldn't work with my projector, because if it was already off, and you wanted to make sure it was off (remotely, say), sending "on" would switch it on, and it would then ignore the following "off' signal while it was warning up.

Any other ideas for workarounds gratefully received. But I wouldn't have thought my suggestion would be hard to implement.

**Comment by masterfordev** [comment]
The only way to get a feedback from the devices is with a Ping. In other case, maybe you can create automatizations in combination with the "dummy" plugin. 

And about your alternative fix, this can be do it manually with an [Avanced Hex Structure](https://broadlink.kiwicam.nz/#advanced-hex-structure), just send Multiple Hex Codes. 

I hope this has been useful to you.

**Comment by soulcook** [comment]
Sorry, but I think you're missing my point.

I'm not asking for a way to get feedback from the device. **There is no way to get feedback from the device** – it just responds to IR commands. This must surely usually be the case with IR controlled devices. There is no feedback.

I described the alternative fix because your template asked for one. But it's not really much use, as I explained. And certainly not a good substitute for a stateless switch.

Do you really not think that stateless switches – so you could have one switch for 'on', another switch for 'off' – would be really useful? It means that the plugin doesn't have to pretend to be aware of the state of the device when it really isn't.

**Comment by soulcook** [comment]
PS -- unfortunately there's no way of emulating statelessness using the homebridge-dummy plugin to control broadlink-rm switches. It would have to be implemented in the broadlink-rm plugin.

**Comment by soulcook** [comment]
I've now realised that you can in fact achieve what I'm asking for with the plugin as it stands, by using the `enableAutoOff` and `onDuration` properties. 

So I'm closing this issue.
