### ISSUE TITLE
Plugin Not Starting After Updating JSON Config

### ISSUE THREAD

**Issue by 20mailchump** [kiwi-cam/homebridge-broadlink-rm#258]
Hi,

I'm new to Homebridge/JSON so I may have done something wrong here. But I added a few of my devices to JSON Config and the editor did not suggest any errors, so I restarted the server and I keep getting the below error message upon restart. Any thoughts on what I need to adjust? Thanks in advance!

**homebridge-broadlink-rm-pro is taking a long time to load and preventing Homebridge from starting**.

OS: Raspbian GNU/Linux Buster (10)
Device: Raspberry Pi Zero W

JSON Config for Broadlink Plugin:
{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "hideWelcomeMessage": false,
    "accessories": [
        {
            "name": "Soundbar",
            "type": "switch",
            "data": {
                "Power On/Off": "2600...",
                "Volume Up": "2600...",
                "Volume Down": "2600...",
                "Mute": "2600...",
                "Bluetooth": "2600...",
                "Optical": "2600..."
            }
        },
        {
            "name": "TV",
            "type": "TV",
            "data": {
                "Power On/Off": "2600...",
                "Back": "2600...",
                "Exit": "2600...",
                "Guide": "2600...",
                "Up": "2600...",
                "Down": "2600...",
                "Left": "2600...",
                "Right": "2600...",
                "OK": "2600..."
            }
        }
    ]
}

**Comment by masterfordev** [comment]
If that is your config file, read the [documentation](https://broadlink.kiwicam.nz/#switch). You have to config like the documentation.
