### ISSUE TITLE
This plugin generated a warning from the characteristic 'On' ..

### ISSUE THREAD

**Issue by MsCopernic** [kiwi-cam/homebridge-broadlink-rm#263]
Hi, I have a raspberry Pi with the following plugins:

- Homebridge UI v4.40.0
- Homebridge Broadlink RM v3.6.22
- Homebridge Apple TV Remote v0.12.1

After a recent update, now I'm receiving the following warning: [homebridge-broadlink-rm] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.

**Comment by masterfordev** [comment]
You are using the old plugin. You have to install this fork with `npm install -g homebridge-broadlink-rm-pro`. Before install this fork, uninstall the old plugin.

**Comment by MsCopernic** [comment]
> You are using the old plugin. You have to install this fork with `npm install -g homebridge-broadlink-rm-pro`. Before install this fork, uninstall the old plugin.

Thank you very much !!! Now it's working perfectly. Best regards

**Comment by MsCopernic** [comment]
> You are using the old plugin. You have to install this fork with `npm install -g homebridge-broadlink-rm-pro`. Before install this fork, uninstall the old plugin.

Hi, I made the change, but now all my buttons are gone,  please take a look at the attached config file that I was using with the older version. What change should I do in my config.json in order get my buttons again?
[jsoncopy.txt](https://github.com/kiwi-cam/homebridge-broadlink-rm/files/6118921/jsoncopy.txt)

**Comment by MsCopernic** [comment]
> You are using the old plugin. You have to install this fork with `npm install -g homebridge-broadlink-rm-pro`. Before install this fork, uninstall the old plugin.

I uninstalled the old one and installed the new one, and I'm getting the following; any idea?

Starting to advertise 'Homebridge B79A B375' using bonjour-hap backend!
[3/10/2021, 18:15:07] Homebridge v1.3.3 (Homebridge B79A) is running on port 51135.
[INFO] Adding RF Support to device 34ea3442fa5c with type 279d
[INFO] Adding RF Support to device 34ea346ff37f with type 279d
[3/10/2021, 18:15:07] [Broadlink RM] [INFO] Discovered Broadlink RM3 Pro Plus (279d) at 192.168.1.53 (34:ea:34:42:fa:5c)
[3/10/2021, 18:15:07] [Broadlink RM] [INFO] Discovered Broadlink RM3 Pro Plus (279d) at 192.168.1.58 (34:ea:34:6f:f3:7f)
[3/10/2021, 18:15:08] [Broadlink RM] Learn getSwitchState: false
[3/10/2021, 18:15:08] [Broadlink RM] Scan Frequency getSwitchState: false
[3/10/2021, 18:15:08] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.

**Comment by soulcook** [comment]
I think this is the same bug as #260

**Comment by MsCopernic** [comment]
I tried the plugin without devices, and the warning disappeared, after that, I added one device, and also worked fine, but after adding another one, the warning message appeared again:

Starting to advertise 'Homebridge EA96 B7C2' using bonjour-hap backend!
[14/03/2021, 16:29:54] Homebridge v1.3.3 (Homebridge EA96) is running on port 51113.
[INFO] Adding RF Support to device 34ea346ff37f with type 279d
[14/03/2021, 16:29:55] [Broadlink RM] [INFO] Discovered Broadlink RM3 Pro Plus (279d) at 192.168.1.58 (34:ea:34:6f:f3:7f)
[14/03/2021, 16:29:56] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.

**Comment by MsCopernic** [comment]
> I think this is the same bug as #260

Yes, exactly the same one, but why?

**Comment by masterfordev** [comment]
It is due to the 1.3 version of homebridge where some changes were made. But @kiwi-cam hasn't had time to fix them.

**Comment by MsCopernic** [comment]
> It is due to the 1.3 version of homebridge where some changes were made. But @kiwi-cam hasn't had time to fix them.

Thank you for your comment

**Comment by tehzimd** [comment]
I believe this has been fixed in 1.3.4.. I was experiencing this issue on 1.3.3, but when I updated it seemed to resolve the issue.

**Comment by masterfordev** [comment]
Nope. In my case, i have a stb (i cant ping it) and i get this warn:

![image](https://user-images.githubusercontent.com/29960705/111891985-5bab3e80-89b4-11eb-9cfe-f42a7d69b7db.jpeg)

Im still waiting Cam fix it 😅

**Comment by MsCopernic** [comment]
> I believe this has been fixed in 1.3.4.. I was experiencing this issue on 1.3.3, but when I updated it seemed to resolve the issue.

Nope, I had finally to stop using this plugin, at the end it was running into a loop that was turning on and off my devices, I understand that the developer works for free, so there is no way to get a fix until he has time.

**Comment by kiwi-cam** [comment]
> Nope, I had finally to stop using this plugin, at the end it was running into a loop that was turning on and off my devices, I understand that the developer works for free, so there is no way to get a fix until he has time.

That's very interesting - I have seen or heard of anything like that before. Any chance you could share the logs from when this happens so we can investigate?

**Comment by kiwi-cam** [comment]
I've made some refinements to this fix and released v4.4.2-beta.6.

I'm planning for this to be the last BETA version. I will avoid making changes for about a week and, if there are no issues, I'll release 4.4.2 next week. Please test and let me know if there are any issues.
