### ISSUE TITLE
config.json hosts section not working with MAC address

### ISSUE THREAD

**Issue by freedivebird** [kiwi-cam/homebridge-broadlink-rm#266]
1. hosts mac address not working per documentation,
2. Inconsistent handling of mac addresses,

**To Reproduce**
In config.json hosts section, if you try to put mac addresses as per the documentation, like 

```
                   "hosts": [
                {
                    "address": "192.168.0.200",
                    "mac": "aa:bb:cc:dd:ee:ff",
                    "isRFSupported": true,
                    "isRM4": true
                },
                {
                    "address": "192.168.0.199",
                    "mac": "ff:ee:dd:cc:bb:aa",
                    "isRFSupported": true,
                    "isRM4": true
                }
            ],
```

Open the log file and you will see that the plugin will try to insert further colons into the mac address - 
```
[INFO] Discovered Manual RM Pro Device (2223) at 192.168.0.200 
(aa::b:b::cc::d:d::ee::f:f)
```

<img width="1282" alt="Screenshot 2021-03-13 at 1 44 14 AM" src="https://user-images.githubusercontent.com/80574914/111027803-81bd6580-842d-11eb-9f66-5a6c3f9a6bcc.png">

So obviously the plugin is expecting the mac addresses in the config.json file to be without colons, but if you try to put a host value in the accessories without the colons, homebridge will issue an error warning say the host cannot be found when trying to send a hex

 - OS: Synology
 - Node.js V14.16.0
 - npm 6.14.11
 - homebridge-broadlink-rm-pro v4.4.1

**Comment by masterfordev** [comment]
You can use the IP or the MAC, so, if you are using a static IP, set up with the static ip, and dont set the MAC, and when you send the IR command, use `host: ip`. That's how I use it.

**Comment by freedivebird** [comment]
Thank you! Actually that's what I am using now - but just found out the bug with regards to the mac address while playing with the configurations earlier :)

**Comment by masterfordev** [comment]
Ok. Thanks for the report. Hope @kiwi-cam can fix it.

**Comment by freedivebird** [comment]
And @kiwi-cam while you are at it, I spotted another error in the documentation. A missing comma behind

` "isRFSupported": true`

<img width="852" alt="Screenshot 2021-03-14 at 12 46 41 AM" src="https://user-images.githubusercontent.com/80574914/111037429-e04f0780-845e-11eb-859c-2f63a837f9bd.png">


Many thanks for keeping it up to date for the RM4 Pro too! Really appreciate your work!
