### ISSUE TITLE
No Volume control for TV in home app

### ISSUE THREAD

**Issue by akkiankur** [kiwi-cam/homebridge-broadlink-rm#267]
I have added the TV accessory in my home app. I have added two functionality in the config file - On/off and volume control. However, I only see on/off button in my home app. I don't see any volume control options.

Here is my config file details - 

"name": "Living Room TV",
                    "type": "tv",
                    "pingIPAddress": "XXX",
                    "pingIPAddressStateOnly": true,
                    "pingFrequency": 120,
                    "pingGrace": 25,
                    "host": "XXX",
                    "data": {
                        "on": "XXX",
                        "off": "XXX",
                        "volume": {
                            "up": "XXX",
                            "down": "XXX"
                        }
}
![Screenshot 2021-03-14 at 3 44 34 PM](https://user-images.githubusercontent.com/69201177/111061303-96593680-84dd-11eb-8a6f-0a7b4d567a01.png)

**Comment by masterfordev** [comment]
👉 [#102](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/102#issuecomment-720813760)

**Comment by akkiankur** [comment]
> 👉 [#102](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/102#issuecomment-720813760)

thanks for pointing out.
