### ISSUE TITLE
Simple button (with no state) accessory request

### ISSUE THREAD

**Issue by kanyoo** [kiwi-cam/homebridge-broadlink-rm#268]
Hello,

Most of the devices controlled by IR or RF (TV, garage door, amp) are not able to return a status (ON, OFF...) and are sometimes controlled outside Homekit/Homebridge.
I know it is possible to configure switches with "enableAutoOff" but it is not a perfect solution.

Would it be possible to add a "button" type accessory, like a switch but without any state (nor "getSwitchState" routine)?

Thanks for your great work!

**Comment by Raphinade** [comment]
Agree.
A stateless switch would be a nice feature.
Especially for Siri & co. to switch devices that doesn't have states.

**Comment by eliteladen** [comment]
Another situation that it could be useful is to emulate the button to turn off AC light at night, since this is not possible through the air-conditioner or heater-cooler implementation

**Comment by kiwi-cam** [comment]
This looks like it'll be pretty straight forward. Other stateless accessories simply always return an Off state, e.g.: https://github.com/TommasoPino/homebridge-stateless-switch/blob/master/index.js#L36:L38.
