### ISSUE TITLE
TV accessory doesn't work like expected

### ISSUE THREAD

**Issue by bergeru** [kiwi-cam/homebridge-broadlink-rm#276]
**Describe the bug**
TV accessory doesn't show up in the Apple Home App

Within the Homebridge web app two accessories appear: A "TV" (HomeTheatre) which I can switch on and off an a "Speaker" which I can mute and unmute.  But no accessory within the the Apple Home App on iPhone

**To Reproduce**
I used the example TV "HomeTheatre" config from the config-example.json

**Expected behavior**
A TV remotrol icon will appear in the Apple Home App with sub-buttons für input and volume control

**Screenshots**
<img width="352" alt="Bildschirmfoto 2021-03-23 um 14 13 09" src="https://user-images.githubusercontent.com/81242248/112154646-c642c100-8be4-11eb-9092-0938ade507d9.png">

**Desktop (please complete the following information):**
iMac, macOS Big Sur

**Server**
raspi
Homebridge v1.3.4
homebridge-broadlink-rm-pro v4.4.1

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: latest
 - Browser: Safari
 - Version: latest

**Additional context**

**Comment by masterfordev** [comment]
[102](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/102)

**Comment by bergeru** [comment]
Tank you very much for your hint!

I also found this log message in my syslog file very helpful:
Mar 24 13:46:06 raspberrypi homebridge[27471]: [24.3.2021, 13:46:06] [BroadlinkRM] You added TVs in your configuration!
Mar 24 13:46:06 raspberrypi homebridge[27471]: [24.3.2021, 13:46:06] [BroadlinkRM] Due to a HomeKit limitation you need to add any TVs to the Home app by using the Add Accessory function.
Mar 24 13:46:06 raspberrypi homebridge[27471]: [24.3.2021, 13:46:06] [BroadlinkRM] There you'll find your TVs and you can use the same PIN as you using for this HomeBridge instance.

When I did so, the device showed up as a TV in the Home App and as a remote within the control panel :-)
