### ISSUE TITLE
Fan Speed Cycle

### ISSUE THREAD

**Issue by SmolSoftBoi** [kiwi-cam/homebridge-broadlink-rm#277]
**Describe the bug**
My fan remote has 4 buttons:
* On / Off
* Osc…
* Timer
* Speed

My fan has 3 speed steps:
* Low (default)
* Medium
* High

The speed button cycles between the speed settings (Low > Medium > High > Low…).

There's no way to set this setup in the configuration.

**Expected behavior**
Update the configuration and plugin to allow this setup.

Example config.json:
```json
{
    "name": "Fan",
    "type": "fan",
    "data": {
        "on": "…",
        "off": "…",
        "swingToggle": "…",
        "fanSpeed": "…"
    },
    "hideRotationDirection": true,
    "alwaysResetToDefaults": true,
    "defaultFanSpeed": 33,
    "stepSize": 33,
    "defaultSpeedStep": 1,
    "speedSteps": 3,
    "speedCycle": true
}
```

If `speedSteps` is set, this could calculate the `stepSize` value.

If `speedCycle` is `true`, the plugin can determine how many times the `fanSpeed` data should be sent based on the `defaultSpeedStep` value and what the stored current speed step is.

These should reset if `alwaysResetToDefaults` is `true`.

**Comment by masterfordev** [comment]
I have a fan with same buttons. There no way to config it because the plugin cant get the current speed. So, what i did? i use the config `clockwise` and `counterClockwise ` i set same hex code on both, so when i press the button for rotation direction, this just change the speed to next level, its more usefull that use fan speed, and im not set any hex code in the config for speed. I hope this can help you.

See: 
![IMG_4302](https://user-images.githubusercontent.com/29960705/112413773-0174eb00-8cde-11eb-98cb-2da8630698f5.PNG)

**Comment by SmolSoftBoi** [comment]
> I have a fan with same buttons. There no way to config it because the plugin cant get the current speed.

I know there's no way to configure it currently. That's why I proposed a way to configure it.

**Comment by masterfordev** [comment]
ok.

**Comment by masterfordev** [comment]
@kiwi-cam yesterday i was playing with the fan i got this warn:

`[homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': Characteristic not in required or optional characteristic section for service Fanv2. Adding anyway.. See https://git.io/JtMGR for more info.`

I guess it is related to the "state" of the devices that you fixed in the switches too.

**Comment by ghost** [comment]
When I turn on the fan the fan speed returns to the value that it was previously rather than the default value (20%) that I have set in the plugin config. 

For example:

The fan has 5 speed values (5 different buttons on remote)
Set default value of 20% in plug-in config
Turn on fan
Increase fan speed to highest value (100%)
Fan Speed is 100%
Turn off fan
Turn on fan
Fan Speed increases to 100% rather than the default value 20%

Sample Config
{
            "name": "Ceiling Fan",
            "type": "fanv1",
            "alwaysResetToDefaults": true,
            "defaultFanSpeed": 20,
            "stepSize": 20,
            "defaultSpeedStep": 1,
            "speedSteps": 5,
            "data": {

**Comment by kiwi-cam** [comment]
@furmese Try adding `"persistState": false`. "defaultFanSpeed" is used when the value isn't set, with persistState it pulls the previous value through.

**Comment by ghost** [comment]
@kiwi-cam I am obviously doing something wrong. What I am trying to achieve is that every time the fan is turned on the speed is set to 20% (setting 1 of 5):

 {
            "name": "Ceiling Fan",
            "type": "fanv1",
            "persistState": false,
            "alwaysResetToDefaults": true,
            "stepSize": 20,
            "defaultSpeedStep": 1,
            "speedSteps": 5,
            "data": {

**Comment by kiwi-cam** [comment]
I've just taken a closer look. Looks like the logic centres around `"alwaysResetToDefaults"`. If you set this to true it should do what you're expecting and reset everything when the fan turns off. (ignore my previous suggestion).

**Comment by ghost** [comment]
The reset back to default fan speed does not seem to work for me. Does someone have this working and be willing to share their configuration?

{
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": true,
    "debug": false,
    "accessories": [
        {
            "name": "Temperature",
            "type": "temperatureSensor",
            "temperatureUpdateFrequency": 300
        },
        {
            "name": "Humidity",
            "type": "humiditySensor",
            "humidityUpdateFrequency": 300
        },
        {
            "name": "Ceiling Fan",
            "type": "fanv1",
            "alwaysResetToDefaults": true,
            "defaultFanSpeed": 20,
            "data": {
                "on": "b1c00201429e060009b90a1d1e091d0b1d0a091e091e1c0b091e1c0b1c0b1c0b1c0c081f1b0c1b0c081f081f081f081f081f081f081f1c0b1c0b09ba091e1d0a1d0a1c0c081e091f1c0a091f1c0b1c0b1c0b1c0b081f1c0b1c0b081f091e091e091e091e091e091e1d0a1c0c08bb091e1c0b1c0b1c0b091e081f1c0b091e1c0b1c0b1c0b1c0b091e1c0c1b0c081f081f081f081f081f081f081f1c0b1c0b09ba091e1d0a1c0b1c0b091e091e1d0a091f1c0b1c0b1c0b1c0b081f1c0b1c0b081f081f081f091e091e091e091e1c0b1d0a09ba091f1c0b1c0b1c0b081f081f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0c081f081e091e091f081e091f081f1c0b1c0b080005dc00000000",
                "off": "b1c00201429e060009b90a1d1e091d0b1d0a091e091e1c0b091e1c0b1c0b1c0b1c0c081f1b0c1b0c081f081f081f081f081f081f081f1c0b1c0b09ba091e1d0a1d0a1c0c081e091f1c0a091f1c0b1c0b1c0b1c0b081f1c0b1c0b081f091e091e091e091e091e091e1d0a1c0c08bb091e1c0b1c0b1c0b091e081f1c0b091e1c0b1c0b1c0b1c0b091e1c0c1b0c081f081f081f081f081f081f081f1c0b1c0b09ba091e1d0a1c0b1c0b091e091e1d0a091f1c0b1c0b1c0b1c0b081f1c0b1c0b081f081f081f091e091e091e091e1c0b1d0a09ba091f1c0b1c0b1c0b081f081f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0c081f081e091e091f081e091f081f1c0b1c0b080005dc00000000",
                "clockwise": "b1c00201389e060009b90a1d1e091e091d0b091e091e1c0b091e1c0b1c0b1c0b1c0b091e1c0b1c0b081f081f091e091e091e1c0b1c0b091f081e09ba091e1d0a1d0b1c0b081f081f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0b081f091e091e091e091e1c0b1c0b091e091e09bb081e1d0b1c0a1d0b081f081f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0b081f081f091e091e091e1c0b1d0a091e091e09ba091e1d0a1d0a1d0a091e091e1d0a091e1d0b1c0b1c0b1c0b081f1c0b1c0b081f081f081f081f081f1c0b1c0b081f091e09ba091e1c0b1c0b1c0b091e091e1d0a091f1b0b1d0b1b0c1c0b081f1c0b1c0b081f081f081f081f081f1c0b1c0b081f081f090005dc00000000",
                "counterClockwise": "b1c00201389e060009b90a1d1e091e091d0b091e091e1c0b091e1c0b1c0b1c0b1c0b091e1c0b1c0b081f081f091e091e091e1c0b1c0b091f081e09ba091e1d0a1d0b1c0b081f081f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0b081f091e091e091e091e1c0b1c0b091e091e09bb081e1d0b1c0a1d0b081f081f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0b081f081f091e091e091e1c0b1d0a091e091e09ba091e1d0a1d0a1d0a091e091e1d0a091e1d0b1c0b1c0b1c0b081f1c0b1c0b081f081f081f081f081f1c0b1c0b081f091e09ba091e1c0b1c0b1c0b091e091e1d0a091f1b0b1d0b1b0c1c0b081f1c0b1c0b081f081f081f081f081f1c0b1c0b081f081f090005dc00000000",
                "fanSpeed20": "b1c00001389e06000a1d1d0a1d0a1d0b081f091d1d0b091e1c0b1c0b1c0b1c0c081e1c0c1b0c081f081f081f081f081f081f1c0b081f1c0b09ba091e1d0a1d0a1d0a091f081f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0b081f091e091e091e091e091e1d0b081f1c0b08bb091e1c0b1c0b1c0b091e091f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0b081f081f091e091e091f081e1c0c081f1c0b08bb081f1c0b1c0b1c0b091e091e1d0b081f1c0a1c0c1b0c1c0b081f1c0b1c0b081f081f081f091e091e091e1c0b091f1b0c08bb081f1c0b1c0b1c0b091e091e1c0b091e1c0b1c0b1c0c1b0c081f1b0c1c0b081f081f081f081f081f091e1c0b091e1c0b090005dc000000000000",
                "fanSpeed40": "b1c0fe01389e06000a1d1d0a1d0a1d0a091f091d1d0b091e1c0b1c0b1c0b1c0c081f1b0c1b0c081f081f081f081f081f1c0b091e1c0b091e09bb081e1d0b1c0b1c0b091e091e1c0b091e1c0b1d0b1c0b1c0b081f1c0b1c0b081f081f091e091e091e1c0b091e1c0c081f08bb091e1c0b1c0b1d0a091e091f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0b091f081f081f081f081f1c0b081f1c0b081f09ba091e1d0a1d0b1c0b081f081f1c0b081f1c0b1c0b1c0b1c0b091e1c0c1b0c081f081f081f081f081f1c0b081f1c0b091e09bb081f1c0b1c0b1c0b081f081f1c0b091e1c0b1c0b1c0c1b0c081f1b0c1c0b081f081f081f081f091e1c0b091e1c0b091e090001fd09bb091e1c0b1c0b1c0b091e091e1d0a091e1d0a1c0c1c0b1b0c081f1c0b1c0b081f081f091e091e091e1c0b091e1c0c081f08bb091e1c0b1c0b1c0b091e091e1d0b081f1c0b1c0b1c0b1c0b081f1c0b1c0b081f091f081e091e091e1d0b081f1c0b081f09ba091f1c0a1d0b1c0b081f081f1c0b081f1c0b1c0b1c0b1c0b091e1c0c1b0c081f081f081f081f081f1c0b081f1c0b081f09bb081f1c0b1c0b1c0b081f091e1c0b091e1c0b1c0c1b0c1c0b081f1c0b1b0c081f081f081f091e091e1c0b091e1c0c081e09bb081f1c0b1c0b1c0b091e091e1c0c081e1d0b1c0b1c0b1c0b081f1c0b1c0b081f081f091e091f081e1d0b081e1d0b081f080005dc0000000000000000",
                "fanSpeed60": "b1c008034c9e06000b06041e040a040005ac0ab90a1d1e0a1d0a1c0b091e091e1d0a091e1d0a1d0b1c0b1c0b081f1c0b1c0b081f0820081e091e091e091e1c0c1c0b081f08bb091e1d0a1c0b1d0a091f081e1d0b081f1c0b1c0b1c0b1c0b091e1c0b1c0c081e091f081f081f081f081f1c0b1c0b091e09ba091f1c0a1d0b1c0b081f091e1c0b091e1c0b1c0b1c0b1c0b091f1b0c1b0c081f081f081f081f091e091e1c0b1c0b091f08bb091e1c0b1c0b1c0b091e091e1d0a091e1d0b1c0b1c0b1c0b081f1c0b1c0b081f081f091e091e091e091e1d0b1c0b081f09ba091e1c0b1d0a1d0b081f081f1c0b081f1c0b1c0b1c0c1b0b091f1b0c1b0c081f081f081f081f091e081f1c0b1c0c081e090005cf09b90a1e1d0a1d0a1d0a091e091e1d0a091e1d0b1c0b1c0b1c0b081f1c0b1c0c071f091f0a1d081e091f081f1c0b1c0b081f08bb091e1d0a1d0a1d0a091f081f1c0b081f1c0b1c0b1c0b1c0b091e1c0c1b0c081f081f081f081f081f081f1c0b1c0b091e09ba091f1c0b1c0b1c0b091e091e1c0b091e1c0b1c0b1d0b1b0c081f1c0b1c0b081f081f091e091e091e091e1c0c1c0b081f08bb091e1c0b1c0b1d0a091f081e1d0b081f1c0b1c0b1c0b1c0b081f1c0b1c0c081f081f081f081f081f081f1c0b1c0b091e09ba091f1c0b1c0b1c0b081f081f1c0b091e1c0b1c0b1c0c1b0c081f1b0c1c0b081f081f081f081f091e091e1c0b1c0b091f080005ce0aba0a1d1d0a1d0a1d0a091e091f1c0b081f1c0b1c0b1c0b1c0b091e1c0c1b0c081f081f081f081f081f081f1c0b1c0b091e09bb081f1c0b1c0b1c0b091e091e1c0b091e1c0b1d0b1b0c1c0b081f1c0b1c0b081f081f081f091e091e091e1c0b1d0b081f08bb091e1c0b1c0b1d0a091e091e1d0b081f1c0b1c0b1c0b1c0b091e1c0b1c0c081f081f081f081f081f091e1c0b1c0b081f09bb081f1c0b1c0b1c0b081f091e1c0b091e1c0b1c0b1c0c1b0c081f1c0b1c0b081f081f081f091e091e091e1c0b1c0c081f08bb091e1c0b1c0b1c0b091e091f1b0c081f1c0b1c0b1c0b1c0b081f1c0b1c0b091e091f081f081f081f081f1c0b1c0b081f090005dc0000000000000000000000000000",
                "fanSpeed80": "b1c00001929e06000a1d1d0b1c0b1c0b091e091e1c0b091e1c0b1d0b1c0b1b0c081f1b0c1c0b081f081f081f081f081f1c0b091e091e1c0b09bb081f1c0b1c0b1c0b091e091e1c0b091e1c0b1c0b1c0c1c0b081f1c0b1c0b081f081f081f081f091e1c0b091e091e1c0b09bb081f1c0b1c0b1c0b091e091e1c0b091e1c0b1c0c1b0c1b0c081f1c0b1c0b081f081f081f081f091e1c0b091e091e1c0c08bb081f1c0b1c0b1c0b081f091e1c0b091e1c0b1c0b1c0c1b0c081f1b0c1c0b081f081f081f081f081f1c0b091e091e1c0c08bb081f1c0b1c0b1c0b081f091e1c0b091e1c0b1c0c1b0c1b0c081f1c0b1b0c081f081f081f081f081f1c0b081f091e1c0c080005dc000000000000",
                "fanSpeed100": "b1c0e601429e0600091e1c0b1c0c1b0c1b0c081f1c0b1c0b081f081f081f081f081f091e091e1c0b091e09bb091e1c0b1c0b1c0b091e091e1c0b091e1c0b1c0b1c0c1b0c081f1b0c1c0b081f081f081f081f091e091e091e1c0b091e09bb081f1c0b1c0b1c0b091e091e1c0b091e1c0b1c0b1c0c1b0c081f1c0b1c0b081f081f081f081f081f091e091e1c0b091e09bb081f1c0b1c0b1c0b091e091e1c0b091e1c0b1c0b1c0c1b0c081f1b0c1b0c081f081f081f081f091e091e091e1c0b091e09ba091e1d0b1c0b1c0b081f091e1c0b091e1c0b1c0b1c0b1c0c081f1b0c1b0c081f081f081f081f091e090b08bb081f1c0b1c0b1c0b091e091e1c0b091e1c0c1c0b1b0c1c0b081f1c0b1c0b081f081f081f091e091e091e091e1c0b091e09bb081f1c0b1c0b1c0b091e091e1c0b091e1d0b1c0b1c0b1b0c081f1c0b1c0b081f081f091e091e091f081e091f1c0b081f08bb091e1c0b1c0b1c0b091e091e1d0a091f1c0b1c0b1c0b1c0b081f1c0b1c0b081f091e081f091e091e091e091e1d0b081f08bb091e1c0b1c0b1c0b091e091e1c0c081e1d0b1c0b1c0b1c0b081f1c0b1c0b081f091e0820081e091e091f081e1d0b081f08bb091e1c0b1c0b1c0b091e091e1d0b081f1c0b1c0b1c0b1c0b081f1c0b1c0b081f081f091e091e091e091e091e1d0b081f080005dc"
            }
        }
    ]
}

**Comment by ghost** [comment]
Thanks to @kiwi-cam for his help. Using the Advanced HEX Structure enabled me to achieve what I wanted:

        {
            "name": "Ceiling Fan",
            "type": "fanv1",
            "alwaysResetToDefaults": true,
            "defaultFanSpeed": 20,
            "data": {
                "on": [
                    {
                        "data": "ON_HEX_CODE",
                        "pause": 0.3
                    },
                    {
                        "data": "FANSPEED_HEX_CODE"
                    }
                ],
                "off":
