### ISSUE TITLE
Setup for Wall AC

### ISSUE THREAD

**Issue by spinwtf** [kiwi-cam/homebridge-broadlink-rm#279]
Looking for some help on setting up a wall ac unit with this plugin.
I'm currently struggling with "mapping" the functions of the remote to config
The remote has Temp Up and Down buttons, Fan Faster and Slower, Auto Fan, Energy Saver etc.
The AC does not report back its status in regards to temp.
I'm essentially  just looking for easy toggles to advance the temp up and down and adjust fan speeds
Any help is appreciated 

This is my current config and it currently only shows the on/off toggle in the home app
```    "accessories": [
        {
            "name": "Air Conditioner",
            "type": "heater-cooler",
            "temperatureUnits": "F",
            "minTemperature": 65,
            "maxTemperature": 80,
            "fanStepSize": 1,
            "tempStepSize": 1,
            "data": {
                "cool": {
                    "on": "260050000001279314111411131213371312131213121311143713111437131114371337133713371436141114111312133714111312131213121337133713371411133714361437130005510001284814000d05000000000000",
                    "off": "260050000001279314111411131213371312131213121311143713111437131114371337133713371436141114111312133714111312131213121337133713371411133714361437130005510001284814000d05000000000000"
                },
                "temperatureCodes": {
                    "65": "260050000001259313121312131213371312131213111411133714111337141114361437133713371337131213371436141114111312131213121337131213111437133713371337130005530001274814000d05000000000000",
                    "80": "260050000001259313121312131213371312131213111411133714111337141114361437133713371337131213371436141114111312131213121337131213111437133713371337130005530001274814000d05000000000000"
                }
            }
        }
    ]

**Comment by spinwtf** [comment]
My current solution is to use stateless switches for some of the AC's functions

**Comment by malwcal** [comment]
Hi @spinwtf , can I ask how you do that?  Do you use another plugin to implement the stateless switch?

**Comment by spinwtf** [comment]
> Hi @spinwtf , can I ask how you do that?  Do you use another plugin to implement the stateless switch?

This is my current config

```

{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": true,
    "accessories": [
        {
            "name": "Air Conditioner",
            "type": "switch",
            "data": {
                "on": "260050000001279314111411131213371312131213121311143713111437131114371337133713371436141114111312133714111312131213121337133713371411133714361437130005510001284814000d05000000000000",
                "off": "260050000001279314111411131213371312131213121311143713111437131114371337133713371436141114111312133714111312131213121337133713371411133714361437130005510001284814000d05000000000000"
            }
        },
        {
            "name": "Air Conditioner Temp Up",
            "type": "switch",
            "stateless": true,
            "data": {
                "on": "2600500000012695170c1311141113371411131213121312133713121337131213371337133714371311143713371337131213121312131114371311141114111337143614371337130005520001284813000d05000000000000",
                "off": "2600500000012695170c1311141113371411131213121312133713121337131213371337133714371311143713371337131213121312131114371311141114111337143614371337130005520001284813000d05000000000000"
            }
        },
        {
            "name": "Air Conditioner Temp Down",
            "type": "switch",
            "stateless": true,
            "data": {
                "on": "260050000001259313121312131213371312131213111411133714111337141114361437133713371337131213371436141114111312131213121337131213111437133713371337130005530001274814000d05000000000000",
                "off": "260050000001259313121312131213371312131213111411133714111337141114361437133713371337131213371436141114111312131213121337131213111437133713371337130005530001274814000d05000000000000"
            }
        }
    ]
}

```

**Comment by lamatuzzi** [comment]
> Looking for some help on setting up a wall ac unit with this plugin.
> I'm currently struggling with "mapping" the functions of the remote to config
> The remote has Temp Up and Down buttons, Fan Faster and Slower, Auto Fan, Energy Saver etc.
> The AC does not report back its status in regards to temp.
> I'm essentially just looking for easy toggles to advance the temp up and down and adjust fan speeds
> Any help is appreciated
> 
> This is my current config and it currently only shows the on/off toggle in the home app
> 
> ```
>         {
>             "name": "Air Conditioner",
>             "type": "heater-cooler",
>             "temperatureUnits": "F",
>             "minTemperature": 65,
>             "maxTemperature": 80,
>             "fanStepSize": 1,
>             "tempStepSize": 1,
>             "data": {
>                 "cool": {
>                     "on": "260050000001279314111411131213371312131213121311143713111437131114371337133713371436141114111312133714111312131213121337133713371411133714361437130005510001284814000d05000000000000",
>                     "off": "260050000001279314111411131213371312131213121311143713111437131114371337133713371436141114111312133714111312131213121337133713371411133714361437130005510001284814000d05000000000000"
>                 },
>                 "temperatureCodes": {
>                     "65": "260050000001259313121312131213371312131213111411133714111337141114361437133713371337131213371436141114111312131213121337131213111437133713371337130005530001274814000d05000000000000",
>                     "80": "260050000001259313121312131213371312131213111411133714111337141114361437133713371337131213371436141114111312131213121337131213111437133713371337130005530001274814000d05000000000000"
>                 }
>             }
>         }
>     ]
> ```

@spinwtf I have the same situation. My device is a Wall AC, too. And I didn't find a way to configure it with "heater-cooler" type. Have you got a solution? I used the same as you: stateless switches.

thanks !
