### ISSUE TITLE
Input stuck on first input

### ISSUE THREAD

**Issue by ChristianPorsche** [kiwi-cam/homebridge-broadlink-rm#28]
My configuration has two inputs. 

However, if I select the second input (Ziggo in my configuration), my home app will still say my tv is on input one (Apple TV). Luckily, the IR blast is working for both inputs, so it is not really a problem, more like a bug. 

`{
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": true,
            "accessories": [
                {
                    "name": "TV",
                    "type": "tv",
                    "pingIPAddress": "192.168.178.128",
                    "disableLogs": false,
                    "pingGrace": 45,
                    "pingIPAddressStateOnly": true,
                    "data": {
                        "on": "26008c008e9313371337123812141114111412121213133713371238121312131213121312131212123813131213111412131213111411391114113812381238123812391138120005ef93911537133712381213121413121311131212381139123813121213121312141112121411381313111411131213121411141138121312381238123813371436123813000d0500000000000000000000",
                        "off": "26008c008e9313371337123812141114111412121213133713371238121312131213121312131212123813131213111412131213111411391114113812381238123812391138120005ef93911537133712381213121413121311131212381139123813121213121312141112121411381313111411131213121411141138121312381238123813371436123813000d0500000000000000000000",
                        "volume": {
                            "up": "26008c008d9312381238123813131114111312131313123713371238131212131214111311131238123812381312121410141214111312141114101511381337123812381239120005ee929413371239123712141212131212131213103a1237133812131212131215111114123712381238121411131214121311141114111411131337123813371238133713000d0500000000000000000000",
                            "down": "26008c008c9512381138133712141213111312141114123712381337121412121313121311141237123812141138121411131312121313131113143611151236133712381239120005ee92941338113812381313111312141213111411381239123712141114111411131213113912381114143513121214121311141114121311381214113812391237133712000d0500000000000000000000"
                        },
                        "inputs": [
                            {
                                "name": "Apple TV",
                                "type": "hdmi",
                                "data": [
                                    {
                                        "data": "260050000001239311141313121213121213131213131238123812381238123813381337123812141113133812381238123615121214121312381312131312121312123812381238130005100001274a11000d05000000000000"
                                    }
                                ]
                            },
                            {
                                "name": "Ziggo",
                                "type": "hdmi",
                                "data": [
                                    {
                                        "data": "2600580000012592141114111411141115101510151015351536143615351535153614361535151015101535151114111436141114111510153515101536143614111436153515351500050d00012a4715000c4f0001284814000d050000000000000000000000000000"
                                    }
                                ]
                            }
                        ],
                        "remote": {
                            "select": "26008c009095113911391139121311141114111411141138123911381115121311141213111312141114111411381213113a113911131139123812391015103911141214103a1100060e91941337123811391214101411161014121310391139123910151114101510151114101511141015113910141238113911151039123812381213113911141114113912000d0500000000000000000000",
                            "playPause": "26008c008e9312381337123812131213131212131213123713371337141113121213121312131238133712381337121312131213121313121213131213121238123813371237140005ee93931238133713371213121312131213131212381237133713131312131212131212123813371337123813121213121312131213121313121312123813371337123813000d0500000000000000000000"
                        }
                    }
                }
            ]
        }`

**Comment by silverhack77** [comment]
Not sure, but it might be how you have formatted your inputs.  The data key should have a single value instead of an array.  In other words, instead of doing:

```
"inputs": [
  	{
		"name": "Apple TV",
		"type": "hdmi",
		"data": [{
			"data": "260050000001239311141313121213121213131213131238123812381238123813381337123812141113133812381238123615121214121312381312131312121312123812381238130005100001274a11000d05000000000000"
		}
	},
	{
		"name": "Ziggo",
		"type": "hdmi",
		"data": [{
			"data": "2600580000012592141114111411141115101510151015351536143615351535153614361535151015101535151114111436141114111510153515101536143614111436153515351500050d00012a4715000c4f0001284814000d050000000000000000000000000000"
		}]
	}
]
```



Try doing...

```
"inputs": [
  	{
		"name": "Apple TV",
		"type": "hdmi",
		"data": "260050000001239311141313121213121213131213131238123812381238123813381337123812141113133812381238123615121214121312381312131312121312123812381238130005100001274a11000d05000000000000"
	},
	{
		"name": "Ziggo",
		"type": "hdmi",
		"data": "2600580000012592141114111411141115101510151015351536143615351535153614361535151015101535151114111436141114111510153515101536143614111436153515351500050d00012a4715000c4f0001284814000d050000000000000000000000000000"
	}
]

```


That works for me.

**Comment by chelala** [comment]
> Not sure, but it might be how you have formatted your inputs. The data key should have a single value instead of an array. In other words, instead of doing:
> 
> ```
> "inputs": [
>   	{
> 		"name": "Apple TV",
> 		"type": "hdmi",
> 		"data": [{
> 			"data": "260050000001239311141313121213121213131213131238123812381238123813381337123812141113133812381238123615121214121312381312131312121312123812381238130005100001274a11000d05000000000000"
> 		}
> 	},
> 	{
> 		"name": "Ziggo",
> 		"type": "hdmi",
> 		"data": [{
> 			"data": "2600580000012592141114111411141115101510151015351536143615351535153614361535151015101535151114111436141114111510153515101536143614111436153515351500050d00012a4715000c4f0001284814000d050000000000000000000000000000"
> 		}]
> 	}
> ]
> ```
> 
> Try doing...
> 
> ```
> "inputs": [
>   	{
> 		"name": "Apple TV",
> 		"type": "hdmi",
> 		"data": "260050000001239311141313121213121213131213131238123812381238123813381337123812141113133812381238123615121214121312381312131312121312123812381238130005100001274a11000d05000000000000"
> 	},
> 	{
> 		"name": "Ziggo",
> 		"type": "hdmi",
> 		"data": "2600580000012592141114111411141115101510151015351536143615351535153614361535151015101535151114111436141114111510153515101536143614111436153515351500050d00012a4715000c4f0001284814000d050000000000000000000000000000"
> 	}
> ]
> ```
> 
> That works for me.

Hi:

I ave the same problem even tested you suggested configuration and still show only the first one, as a note the TV is shown as a complex device and inside is the TV with only one input and another service with the name of the second input saying active.

Any idea, thanks in advance

**Comment by silverhack77** [comment]
>I ave the same problem even tested you suggested configuration and still show only the first one, as a note the TV is shown as a complex device and inside is the TV with only one input and another service with the name of the second input saying active.

I had the same problem with mine, it wouldn't show the last input.  I think after restarting Homebridge a few times it fixed itself.

**Comment by kiwi-cam** [comment]
@ChristianPorsche is this still an issue? The TV accessory has had a significant overhaul to accommodate iOS 14 changes recently so you might find this issue is now resolved.
