### ISSUE TITLE
Too many Logs

### ISSUE THREAD

**Issue by boehser-enkel** [kiwi-cam/homebridge-broadlink-rm#289]
Hey there,

i have so many switches within this plugin (TV controls).
Every few secons every switch state is shown in the log. Can you add an option to just show changes in the log? I can't see everything else ^^

example: https://pastebin.com/PZdZq4rb

greetz 
boehser enkel

**Comment by kiwi-cam** [comment]
The getSwitchState lines are only recorded when something queries the state of the Switch (or inheriting accessory). Are you sure you don't have the Home app or anything else open at the time you captured these logs?

**Comment by kiwi-cam** [comment]
I've added `logLevel` as an option now so this can be fine tuned. At the moment the default is info and it includes that same logs. I'll be tuning this in future.

**Comment by Mendelyeev** [comment]
I have the same issue here too. And noticied that log is triggered every time when I pull down Control Center on my iPhone (I've set show most recents homekit devices on Control Centre). When i set to NOT SHOW homekit devices on Control Center, the log isn't triggered.

**Comment by boehser-enkel** [comment]
Thanks
logLevel ist nice. But with it set to warning i don't see every update (which is nice) but i also don't see when something gets triggered.
Could you add another option to see changes?

**Comment by kiwi-cam** [comment]
Hi @boehser-enkel. Definitions of the logLevels vary a little by vendor but this is a good summary: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=dotnet-plat-ext-5.0#fields. The information you're describing doesn't really fit the warning definition. 

Generally if a value/characteristic is being modified it will log at `info` and lower, values being queried is logged at `debug` and lower. If you've got an accessory that is doing something different, let me know.
