### ISSUE TITLE
Unknown Broadlink Device RM Mini 3 

### ISSUE THREAD

**Issue by smacq08** [kiwi-cam/homebridge-broadlink-rm#291]
We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "6507". The device is connected to your network with the IP address "192.168.x.x".

This is a RM Mini 3 Orange Bean All-in-One device, sold in Germany... https://www.amazon.de/RM-Universal-Control-Compatible-Broadlink-Orange/dp/B08QJKRNY4/. Hope that helps, thank you.

**Comment by kiwi-cam** [comment]
The latest BETA should work for you now.

**Comment by smacq08** [comment]
Device is recognized in beta version. Thanks for the quick reaction.
