### ISSUE TITLE
Scwith off twice

### ISSUE THREAD

**Issue by bubblefreddo** [kiwi-cam/homebridge-broadlink-rm#292]
Hello!
To be switch off, my projector need a double press on the button "on"
I need something like that:
"name": "VideoProj",
                    "type": "switch",
                    "data": {
                        "on": "2600600...",
                        "off": "26006001000... _need 1 seconde and again 26006001000..."_
                    }

I hope someone can understand my problem!! ;-)
ThanX

**Comment by kiwi-cam** [comment]
Sounds like you need a repeat: https://broadlink.kiwicam.nz/#advanced-hex-structure (or a pause if there are two different codes)

**Comment by bubblefreddo** [comment]
Well thank you for your answer... i'm beginner...
So can you write to me what the code is?

**Comment by bubblefreddo** [comment]
I've got it...
{
                    "name": "VideoProj",
                    "type": "switch",
                    "data": {
                        "on": "260060...",
                        "off": [
                            {
                                "data": "26006001...",
                                "sendCount": 2,
                                "interval": 1
                            }
                        ]
                    }
                }
