### ISSUE TITLE
Assign codes to specific Broadlink devices

### ISSUE THREAD

**Issue by bondskin** [kiwi-cam/homebridge-broadlink-rm#293]
Right now I am having one Broadlink device.
Discovery works fine and the codes are send as expected.

I want to add a second Broadlink device (for a different room), so I manually configured the existing host in the JSON file. Although HEX code is being send according to homebridge log, the receiver does not react.

If I now add a second Broadlink, how to I make sure which code is send by which Broadlink?
I could not find an example code where I can link the RM device to a recipient.

**Comment by kiwi-cam** [comment]
There's no need to manually add the hosts. You just need to add a `"host" :"MAC or IP"` line to each accessory to define which device you'd like to use for that accessory.

e.g.
```
{
        ...
        "name": "Example Switch",
        "type": "switch",
        "host": "192.168.1.100",
        "data": {
          "on": "ON_HEX_CODE",
          "off":"OFF_HEX_CODE"
        }
        ...
      }
```

**Comment by bondskin** [comment]
thanks @kiwi-cam , that works!
But there is still just one "Learn" button and not one per room, correct?
It seems that the second/ new device does not capture the IR codes although the learning has been started according to logs
[15/04/2021, 16:26:40] [BroadlinkRM] Learn Code (ready)
[15/04/2021, 16:26:50] [BroadlinkRM] [INFO] Learn Code (stopped - 10s timeout)
[15/04/2021, 16:26:50] [BroadlinkRM] [INFO] Learn Code (stopped)

**Comment by bondskin** [comment]
got it by myself, I needed to add the host section and identify both hosts to make the "Learn" button work on both
