### ISSUE TITLE
IR Code is not working

### ISSUE THREAD

**Issue by adrianopery** [kiwi-cam/homebridge-broadlink-rm#295]
I'm trying to add a new TV on my home app and when I try to read the IR code to ON & OFF I receive the message below...

14/04/2021 22:02:57 [HOOBS 208C@On] The write handler for the characteristic 'On' on the accessory 'Learn IR' was slow to respond!
14/04/2021 22:03:03 [HOOBS 208C@On] The write handler for the characteristic 'On' on the accessory 'Learn IR' didn't respond at all!. Please check that you properly call the callback!

I'm using the latest version of Plugin 4.4.2.

**Comment by kiwi-cam** [comment]
Sorry, I haven't been able to recreate this issue - Learn IR works fine for me. Could you share your config - hopefully there's a clue in there?
