### ISSUE TITLE
missing device type code: "60c8", broadlink light bulb

### ISSUE THREAD

**Issue by nevoomer** [kiwi-cam/homebridge-broadlink-rm#296]
Following log entry:
"
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.
Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "60c8". The device is connected to your network with the IP address "192.168.199.122".
"

Broadlink Light bulb identified with python-broadlink as lb1

broadlink.light.lb1(('192.168.199.122', 80), mac=b'\xa0C\xb0\xcf\xeb\x12', devtype=24776, timeout=10, name='Smart Bulb', model='LB1', manufacturer='Broadlink', is_locked=False)

thanks

**Comment by kiwi-cam** [comment]
Sorry, this plugin is focused solely on the Broadlink RM IR/RF devices. We don't support any other Broadlink devices directly.  I believe there are other Homebridge plugins better positioned to support your device - but sorry I don't have any personal experience with them.
