### ISSUE TITLE
MQTT DHT22 Temp & Humidity sensor

### ISSUE THREAD

**Issue by ghost** [kiwi-cam/homebridge-broadlink-rm#298]
Im trying to use my DHT22 sensor for my airco but is is not working at the moment.
In the onMQTTMessage tempereature and humidity are shown.

My config:

                    "name": "Airco Slaapkamer",
                    "type": "air-conditioner",
                    "mqttURL": "mqtt://localhost",
                    "mqttUsername": "username",
                    "mqttPassword": "pass",
                    "mqttTopic": "tele/SlaapkamerTemp/SENSOR",
                    "temperatureUpdateFrequency": 150,
                    "minTemperature": 16,
                    "maxTemperature": 30,
                    "defaultCoolTemperature": 19,
                    "defaultHeatTemperature": 21,
                    "debug": true,
                    "data": {

My homebridge logs are showing this:

[19/04/2021, 19:55:16] [Broadlink RM] [DEBUG] Airco Slaapkamer onTemperature (0)
[19/04/2021, 19:55:16] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[19/04/2021, 19:55:42] [Broadlink RM] [DEBUG] Airco Slaapkamer onMQTTMessage (raw value: {"Time":"2021-04-19T18:55:42","AM2301":{"Temperature":22.2,"Humidity":46.6,"DewPoint":10.2},"TempUnit":"C"})
[19/04/2021, 19:55:42] [Broadlink RM] [DEBUG] Airco Slaapkamer onMQTTMessage (parsed value: {"Time":"2021-04-19T18:55:42","AM2301":{"Temperature":22.2,"Humidity":46.6,"DewPoint":10.2},"TempUnit":"C"})
[19/04/2021, 19:55:42] [Broadlink RM] [DEBUG] Airco Slaapkamer onTemperature (0)
[19/04/2021, 19:55:42] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.

**Comment by kiwi-cam** [comment]
What's your config look like? It looks like the Temperature and Humdity is another branch down the data structure so you might need to add "/AM2301" to the URL. The code only looks in the supplied branch for values.

**Comment by ghost** [comment]
{
                    "name": "Airco Slaapkamer",
                    "type": "air-conditioner",
                    "mqttURL": "mqtt://localhost",
                    "mqttUsername": "user",
                    "mqttPassword": "pass",
                    "mqttTopic": "tele/SlaapkamerTemp/SENSOR",
                    "temperatureUpdateFrequency": 150,
                    "minTemperature": 16,
                    "maxTemperature": 30,
                    "defaultCoolTemperature": 19,
                    "defaultHeatTemperature": 21,
                    "debug": true,
                    "data": {


Just tried "mqttTopic": "tele/SlaapkamerTemp/SENSOR/AM2301",  this did not fix the issue unfortunately

**Comment by kiwi-cam** [comment]
Try updating it to `"mqttTopic": "tele/SlaapkamerTemp/SENSOR/AM2301"`

**Comment by kiwi-cam** [comment]
Could you share the logs with "tele/SlaapkamerTemp/SENSOR/AM2301" as the topic?

**Comment by ghost** [comment]
Than it is only showing this in the logs:

[19/04/2021, 22:13:28] [Broadlink RM] Airco Slaapkamer monitorTemperature
[19/04/2021, 22:13:28] [Broadlink RM] [ERROR] Airco Slaapkamer No MQTT value could be found for topic with identifier "temperature".
[19/04/2021, 22:13:28] [Broadlink RM] [ERROR] Airco Slaapkamer No MQTT value could be found for topic with identifier "humidity".
[19/04/2021, 22:13:28] [Broadlink RM] [DEBUG] Airco Slaapkamer onTemperature (0)

**Comment by kiwi-cam** [comment]
Sorry, I don't have time to sit down and review the code right now but try this:
```
"mqttTopic": [{
          "identifier":"AM2301/Temperature",
          "topic":"tele/SlaapkamerTemp/SENSOR"
        },{
          "identifier":"AM2301/Humidity",
          "topic":"tele/SlaapkamerTemp/SENSOR"
        }]
```

**Comment by ghost** [comment]
Alright, i tried and now it gives the following error:

[Broadlink RM] [ERROR] Airco Slaapkamer onMQTTMessage (mqtt message received with unexpected identifier: AM2301/Humidity, {"Time":"2021-04-19T21:35:42","AM2301":{"Temperature":21.3,"Humidity":47.6,"DewPoint":9.7},"TempUnit":"C"})


On the tasmota website it says the AM2301 is part of the JSON:
https://tasmota.github.io/docs/AM2301/

Sensor sends a tele/%topic%/SENSOR JSON reponse:

{
  "Time": "2019-01-01T00:00:00",
  "AM2301": {
    "Temperature": 24.6,
    "Humidity": 58.2
  },
  "TempUnit": "C"
}

**Comment by kiwi-cam** [comment]
I've done some poking around and found a bug in the JSON parsing that meant nothing was being returned.  If you update to the latest BETA, **v4.4.3-beta.0**, you should be able to get it to work with this config:
```
                "name": "Airco Slaapkamer",
                "type": "air-conditioner",
                "mqttURL": "mqtt://localhost",
                "mqttUsername": "username",
                "mqttPassword": "pass",
                "mqttTopic": "tele/SlaapkamerTemp/SENSOR",
                "noHumidity": true,
                "temperatureUpdateFrequency": 150,
                "minTemperature": 16,
                "maxTemperature": 30,
                "defaultCoolTemperature": 19,
                "defaultHeatTemperature": 21,
                "debug": true,
                "data": {
```

Note that I've added `"noHumidity": true`. The JSON logic was built when only Temperature values were supported so it only returns one value when both are in a single message.  I'll need more time to solve that issue.

**Comment by uzumaki20398** [comment]
Your messenge maybe difficult.
Trying to publish number only with temperature or humidity. 

You can test MQTT with MQTT tool to public or subscrip messenge.

**Comment by ghost** [comment]
Thanks for the quick fix my temperature is now displayed.

**Comment by kiwi-cam** [comment]
@CalvinGra You should be able to get Humidity data too in version v4.4.3-beta.1 - just published.

**Comment by ghost** [comment]
Yes working perfect now
