### ISSUE TITLE
Unknown Broadlink Device 648d  - RM4

### ISSUE THREAD

**Issue by ninm002** [kiwi-cam/homebridge-broadlink-rm#3]
"[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "648d". The device is connected to your network with the IP address "10.0.1.55".
"

**Comment by kiwi-cam** [comment]
No problem @ninm002. Could you confirm which model device you're using? I'll add this device code to the supported list... and hopefully it is that easy (it usually is) 🤞

**Comment by ninm002** [comment]
RM4 mini. Is there something that is more specific?


BroadLink Smart IR Remote Control Hub with Sensor Cable-WiFi IR Blaster for Smart Home Automation, TV Remote, Works with Alexa, Google Home, IFTTT (RM4 Mini S) https://www.amazon.com/dp/B0872PPSGM/ref=cm_sw_r_cp_api_i_Zob4EbZ3N1YMR

-Zachary

On Jun 9, 2020, at 5:43 PM, Cameron <notifications@github.com> wrote:

﻿
No problem @ninm002. Could you confirm which model device you're using? I'll add this device code to the supported list... and hopefully it is that easy (it usually is) 🤞

**Comment by kiwi-cam** [comment]
homebridge-broadlink-rm-pro@**4.2.5** should support this device now. Let me know if there are any issues.

**Comment by ninm002** [comment]
Thank you very much. You are impressively quick!
I now have 
[Broadlink RM] [INFO] Discovered Broadlink RM Mini 4 S (648d) at 10.0.1.55 (a7:xx:xx:xx:xx)
so the device appear to be discovered. I am now running into the same issue utester123123bb is in the other open issue thread. The device will not trigger into a code receive mode when Learn Button is pressed.

**Comment by ninm002** [comment]
[6/9/2020, 22:12:13] [homebridge-broadlink-rm-pro] TV On/Off getSwitchState: false
[6/9/2020, 22:12:13] [homebridge-broadlink-rm-pro] Learn getSwitchState: undefined
[6/9/2020, 22:12:38] [homebridge-broadlink-rm-pro] Learn getSwitchState: undefined

Every 30 seconds it tries to communicate and is unable to.

**Comment by ninm002** [comment]
I attempted to see if the communication to send a code was working. Since I am new to this I may have made a mistake. But I found my TV Samsung Hex code to turn it on and setup an accessory switch to use. Homebridge triggered the send event, but the device did not appear to send out of the code or flash any lights.

[6/9/2020, 22:16:03] [homebridge-broadlink-rm-pro] TV On/Off sendHex (10.0.1.55; a7:df:24:b5:97:01) 26004e009191123612361236121212121212121212121236123612361212121212121212121212121236121212121212121212121212123712121236123612361236123612361200060d9191121212000c750d050000000000000000

**Comment by kiwi-cam** [comment]
I'm starting to think there's more going on here. I've just ordered myself an RM4 so I can see what's happening. Unfortunately that's going to take a few weeks to get to me.

After that sendHex log, do you see an invalid command 114 line?

**Comment by kiwi-cam** [comment]
Hi @ninm002 - would you mind being my guinea pig?  I've just found a spot in the code I imported which uses different headers for one RM4 device, but not all. Could you try the following to use these headers on all RM4 devices:

1. Locate the file index.js in homebridge-broadlink-rm-pro/node_modules/kiwicam-broadlinkjs-rm/index.js
2. Empty the file, and replace the contents with this: https://github.com/kiwi-cam/broadlinkjs-rm/blob/kiwi-cam-rm4-Testing/index.js
3. Save changes and restart homebridge

If it makes things worse, just re-install and it'll pull the master version over the top. If it works let me know and I'll integrate the changes.

**Comment by ninm002** [comment]
Here is the Log Output. No invalid commands. If I had to guess it never gets interpreted and the header is not being picked up by the device. 

[6/9/2020, 22:28:48] [homebridge-broadlink-rm-pro] TV On/Off getSwitchState: false
[6/9/2020, 22:28:55] [homebridge-broadlink-rm-pro] Learn Code (ready)
[6/9/2020, 22:29:02] [homebridge-broadlink-rm-pro] TV On/Off setSwitchState: true
[6/9/2020, 22:29:03] [homebridge-broadlink-rm-pro] TV On/Off sendHex (10.0.1.55; a7:df:24:b5:97:01) 26004e009191123612361236121212121212121212121236123612361212121212121212121212121236121212121212121212121212123712121236123612361236123612361200060d9191121212000c750d050000000000000000
[6/9/2020, 22:29:05] [homebridge-broadlink-rm-pro] [INFO] Learn Code (stopped - 10s timeout)
[6/9/2020, 22:29:05] [homebridge-broadlink-rm-pro] [INFO] Learn Code (stopped)
[6/9/2020, 22:55:22] [Config] [homebridge-broadlink-rm-pro] Failed to check registry.npmjs.org for updates: socket hang up

I believe I saw a different header format with some devices within this home assistant code. Sorry if its a waste of time, I don't know enough yet. Just trying to put some pieces together.
https://github.com/home-assistant/core/pull/32523

I'd be happy to try that coding suggestion. I will let you know if I have any trouble and report when I can later this evening.

**Comment by kiwi-cam** [comment]
Thanks @ninm002. The Invalid command is actually a red-herring I believe. I think it's a confirmation message that Broadlink have introduced.

I've made things a little easier to test and pushed a BETA release. Instead of editing the index.js file you can now just install **homebridge-broadlink-rm-pro@4.2.6-beta.1**.

Keep me posted.

**Comment by ninm002** [comment]
WOW this is great! I was able to change the index.js file. It does appear to have fixed the connection issue. I was able to trigger a learn, and receive an IR code, then output that IR code to turn the TV on. At this point it seems like it is working as planned. Any idea how to pickup the temperature sensor and humidity sensor in the cable that it ships with?

I am unable to see where I have access to 4.2.6 version to download it. HomeBridge web UI only shows 4.2.5 and I can't see it on GitHub unless I'm on the Teams or something.

**Comment by ninm002** [comment]
https://github.com/mjg59/python-broadlink/pull/374

**Comment by deeloke** [comment]
Hi my RM4 Mini 51da is working with homebridge-broadlink-rm-pro@4.2.6-beta.1 but not with homebridge-broadlink-rm-pro@4.2.5
For homebridge-broadlink-rm-pro@4.2.5, the RM4 does not send any commands. No error message is produced.

**Comment by kiwi-cam** [comment]
4.2.6 is publishing to npm now with the fixed index.js included.
