### ISSUE TITLE
Aircon Issue No heat HEX code found for XX  (SOLVED)

### ISSUE THREAD

**Issue by markwien** [kiwi-cam/homebridge-broadlink-rm#30]
` {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "accessories": [
                {
                    "name": "Klimaanlage",
                    "type": "air-conditioner",
                    "autoSwitch": "A/C Auto Switch",
                    "pseudoDeviceTemperature": 23,
                    "maxTemperature": 24,
                    "minTemperature": 10,
                    "allowResend": true,
                    "defaultCoolTemperature": 20,
                    "defaultHeatTemperature": 24,
                    "data": {
                        "off": "26006800bcee126f146d136f126f122c126f132d126f122c122d122d122d126f122d116f122d132c126f126f126f142b126f136e136e136e122d132c122d1170112d122d122d122d1170132b146d152a156c132c122c136e142c126f122c126f132d126e136e13eb12000d050000000000000000000000000000",
                        "temperature24": {
                            "data": "26006800bded116f136e146e136e132c116f132d126f122c132c112d132d126f122c136e122d122d136c156e122c122d132c132c126f126f112d142c126f126e136e126f142c122c136e122c136e142c136e132b122d126f142b146d132b126f142b126f126f12ec12000d050000000000000000000000000000"
                        },
                        "temperature23": {
                            "data": "26006800bded126f126f136e136e132c126f122d136e132c122c122d122d136e122c136e122d122d136e136c142c126f142c122c136e136e122d132c126f122c136e126f132c132c136e122c136e142c126f122c122d126f132c126f122c126f132c136e136e13eb12000d050000000000000000000000000000"
                        },
                        "temperature22": {
                            "data": "26006800bded126f126f136e136e132c126f122d136e122c132c122d122d126f122c136e122d122d126f126f122c122d136e132c126c156f112d142b136e136e132c116f142c122c136e132c126e142c126f122c122d126d152c126f122c126f122d136e136e13ea12000d050000000000000000000000000000"
                        },
                        "temperature21": {
                            "data": "26006800bded116f1370126e126f122c126f132c136e132c112d122d122d126f122c126f122c132d116f136e132c126f136e132c126d146e122d142b136e132c122c126f132c132c126e132c126f132c126f122c132c126f132c136e122c126f132c136e136e13ea12000d050000000000000000000000000000"
                        },
                        "temperature20": {
                            "data": "26006800bded126f126f136e136e132b126f132d126e132c132b122d122d136e132c126b152d122d136e136e122c122d132c136e136e136e112d142b136e136e136e122c142c122c136e122d126e142c126e132c122c136e142c126e132c126f122d136e126e13eb12000d050000000000000000000000000000"
                        },
                        "temperature19": {
                            "data": "26006800beec126f136e136f132c126e126f152b146d142a152a122d146b172a142b146c142b152a156c156c152a146d152a146d156d146c152a152a156a172a146d152a142b142b146c122d156c152a146d142b122c156c152b146d142a126f152a156c156c15e912000d050000000000000000000000000000"
                        },
                        "temperature18": {
                            "data": "26006800beec126f156d146c152a146d126f152b146c152a142b132b156d142a152a146d142a152b146d146d142a152a156d146d146c156d142a152b146d146d132b152a152a142b146d112d146d152b146c142b122d136e142b146d142b1170132b156d136e13eb12000d050000000000000000000000000000"
                        },
                        "temperature17": {
                            "data": "26006800bded116f136e146e136e132c116f132d126f122c132c112d132d126f122c136e122d122d136c156e122c122d132c132c126f126f112d142c126f126e136e126f142c122c136e122c136e142c136e132b122d126f142b146d132b126f142b126f126f12ec12000d050000000000000000000000000000"
                        }
                    }
                }
            ]
        },`

I constantly get 
"2020-8-3 11:06:18] [Broadlink RM] Klimaanlage setTargetHeatingCoolingState: 3
[2020-8-3 11:06:19] [Broadlink RM] Klimaanlage sentMode (auto)
[2020-8-3 11:06:19] [Broadlink RM] Klimaanlage getCurrentHeatingCoolingState: 0
[2020-8-3 11:06:19] [Broadlink RM] Klimaanlage getTargetHeatingCoolingState: 3
[2020-8-3 11:06:19] [Broadlink RM] Klimaanlage setCurrentHeatingCoolingState: 2
[2020-8-3 11:06:19] [Broadlink RM] Klimaanlage No auto HEX code found for 19
[2020-8-3 11:06:19] [Broadlink RM] Klimaanlage Update to default temperature (20)
[2020-8-3 11:06:19] [Broadlink RM] Klimaanlage sendHex (10.0.0.50; a7:df:24:de:e4:48) 26006800bded126f126f136e136e132b126f132d126e132c132b122d122d136e132c126b152d122d136e136e122c122d132c136e136e136e112d142b136e136e136e122c142c122c136e122d126e142c126e132c122c136e142c126e132c126f122d136e126e13eb12000d050000000000000000000000000000
[2020-8-3 11:06:19] [Broadlink RM] Klimaanlage getTargetTemperature: 20
[2020-8-3 11:06:19] [Broadlink RM] Klimaanlage sentTemperature (20)"

however hexcode for 19 is definded... can someone help me what i made wrong?

thx

Mark

**Comment by akkiankur** [comment]
I have a similar issue but the error in my case is slightly different. See below
![Capture](https://user-images.githubusercontent.com/69201177/89311364-77bdd200-d6a8-11ea-8ecd-a8d674d37c4c.JPG)

**Comment by akkiankur** [comment]
Once I added the default temperature, my error from above changed to same as yours @markwien . Were you able to resolve this? I'm using Rm Mini 4c.

**Comment by markwien** [comment]
```
      {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "accessories": [
                {
                    "name": "Klimaanlage",
                    "type": "air-conditioner",
                    "autoSwitch": "A/C Auto Switch",
                    "pseudoDeviceTemperature": 23,
                    "maxTemperature": 24,
                    "minTemperature": 10,
                    "allowResend": true,
                    "defaultCoolTemperature": 20,
                    "defaultHeatTemperature": 24,
                    "data": {
                        "off": "26006800bcee126f146d136f126f122c126f132d126f122c122d122d122d126f122d116f122d132c126f126f126f142b126f136e136e136e122d132c122d1170112d122d122d122d1170132b146d152a156c132c122c136e142c126f122c126f132d126e136e13eb12000d050000000000000000000000000000",
                        "auto24": {
                            "data": "26006800bded116f136e146e136e132c116f132d126f122c132c112d132d126f122c136e122d122d136c156e122c122d132c132c126f126f112d142c126f126e136e126f142c122c136e122c136e142c136e132b122d126f142b146d132b126f142b126f126f12ec12000d050000000000000000000000000000"
                        },
                        "auto23": {
                            "data": "26006800bded126f126f136e136e132c126f122d136e132c122c122d122d136e122c136e122d122d136e136c142c126f142c122c136e136e122d132c126f122c136e126f132c132c136e122c136e142c126f122c122d126f132c126f122c126f132c136e136e13eb12000d050000000000000000000000000000"
                        },
                        "auto22": {
                            "data": "26006800bded126f126f136e136e132c126f122d136e122c132c122d122d126f122c136e122d122d126f126f122c122d136e132c126c156f112d142b136e136e132c116f142c122c136e132c126e142c126f122c122d126d152c126f122c126f122d136e136e13ea12000d050000000000000000000000000000"
                        },
                        "auto21": {
                            "data": "26006800bded116f1370126e126f122c126f132c136e132c112d122d122d126f122c126f122c132d116f136e132c126f136e132c126d146e122d142b136e132c122c126f132c132c126e132c126f132c126f122c132c126f132c136e122c126f132c136e136e13ea12000d050000000000000000000000000000"
                        },
                        "auto20": {
                            "data": "26006800bded126f126f136e136e132b126f132d126e132c132b122d122d136e132c126b152d122d136e136e122c122d132c136e136e136e112d142b136e136e136e122c142c122c136e122d126e142c126e132c122c136e142c126e132c126f122d136e126e13eb12000d050000000000000000000000000000"
                        },
                        "auto19": {
                            "data": "26006800beec126f136e136f132c126e126f152b146d142a152a122d146b172a142b146c142b152a156c156c152a146d152a146d156d146c152a152a156a172a146d152a142b142b146c122d156c152a146d142b122c156c152b146d142a126f152a156c156c15e912000d050000000000000000000000000000"
                        },
                        "auto18": {
                            "data": "26006800beec126f156d146c152a146d126f152b146c152a142b132b156d142a152a146d142a152b146d146d142a152a156d146d146c156d142a152b146d146d132b152a152a142b146d112d146d152b146c142b122d136e142b146d142b1170132b156d136e13eb12000d050000000000000000000000000000"
                        },
                        "auto17": {
                            "data": "26006800bded116f136e146e136e132c116f132d126f122c132c112d132d126f122c136e122d122d136c156e122c122d132c132c126f126f112d142c126f126e136e126f142c122c136e122c136e142c136e132b122d126f142b146d132b126f142b126f126f12ec12000d050000000000000000000000000000"
                        },
                        "cool24": {
                            "data": "26006800bded116f136e146e136e132c116f132d126f122c132c112d132d126f122c136e122d122d136c156e122c122d132c132c126f126f112d142c126f126e136e126f142c122c136e122c136e142c136e132b122d126f142b146d132b126f142b126f126f12ec12000d050000000000000000000000000000"
                        },
                        "cool23": {
                            "data": "26006800bded126f126f136e136e132c126f122d136e132c122c122d122d136e122c136e122d122d136e136c142c126f142c122c136e136e122d132c126f122c136e126f132c132c136e122c136e142c126f122c122d126f132c126f122c126f132c136e136e13eb12000d050000000000000000000000000000"
                        },
                        "cool22": {
                            "data": "26006800bded126f126f136e136e132c126f122d136e122c132c122d122d126f122c136e122d122d126f126f122c122d136e132c126c156f112d142b136e136e132c116f142c122c136e132c126e142c126f122c122d126d152c126f122c126f122d136e136e13ea12000d050000000000000000000000000000"
                        },
                        "cool21": {
                            "data": "26006800bded116f1370126e126f122c126f132c136e132c112d122d122d126f122c126f122c132d116f136e132c126f136e132c126d146e122d142b136e132c122c126f132c132c126e132c126f132c126f122c132c126f132c136e122c126f132c136e136e13ea12000d050000000000000000000000000000"
                        },
                        "cool20": {
                            "data": "26006800bded126f126f136e136e132b126f132d126e132c132b122d122d136e132c126b152d122d136e136e122c122d132c136e136e136e112d142b136e136e136e122c142c122c136e122d126e142c126e132c122c136e142c126e132c126f122d136e126e13eb12000d050000000000000000000000000000"
                        },
                        "cool19": {
                            "data": "26006800beec126f136e136f132c126e126f152b146d142a152a122d146b172a142b146c142b152a156c156c152a146d152a146d156d146c152a152a156a172a146d152a142b142b146c122d156c152a146d142b122c156c152b146d142a126f152a156c156c15e912000d050000000000000000000000000000"
                        },
                        "cool18": {
                            "data": "26006800beec126f156d146c152a146d126f152b146c152a142b132b156d142a152a146d142a152b146d146d142a152a156d146d146c156d142a152b146d146d132b152a152a142b146d112d146d152b146c142b122d136e142b146d142b1170132b156d136e13eb12000d050000000000000000000000000000"
                        },
                        "cool17": {
                            "data": "26006800bded116f136e146e136e132c116f132d126f122c132c112d132d126f122c136e122d122d136c156e122c122d132c132c126f126f112d142c126f126e136e126f142c122c136e122c136e142c136e132b122d126f142b146d132b126f142b126f126f12ec12000d050000000000000000000000000000"
                        }
                    }
                }
            ]
        },


```
i found out that i can solve it if i use "coolXX" heatXX autoXX should work too

I guess documentation needs to be updated,

**Comment by akkiankur** [comment]
did  you @markwien use same hex code for a particular temperature with different modes?

> i found out that i can solve it if i use "coolXX" heatXX autoXX should work too
> 
> I guess documentation needs to be updated,

**Comment by markwien** [comment]
> did you @markwien use same hex code for a particular temperature with different modes?

My aircon can not heat. Only cool with 3 fan speeds and dry. 

if i not add all different states (cool, auto, heat) i would get a error... 

I would apriciate if i can disable Heat and Auto Mode on the Aircon Element on homekit. It is possible - have other homekit compatible device that has only cool.

**Comment by akkiankur** [comment]
> My aircon can not heat. Only cool with 3 fan speeds and dry.
 
My aircon is the same without heat function. How do you incorporate different fan speeds (Low, Medium, High and Auto in my case) at the same cool temperature in the config file?

> I would apriciate if i can disable Heat and Auto Mode on the Aircon Element on homekit. It is possible - have other homekit compatible device that has only cool.

I would want this functionality too where user can select the modes to appear in the home app.

**Comment by markwien** [comment]
> My aircon is the same without heat function. How do you incorporate different fan speeds (Low, Medium, High and Auto in my case) at the same cool temperature in the config file?

you could add a FAN to change fan speed or you make cool with fan speed 1 heat with fan speed 2 and auto with fan speed 3 

for me fan speed is not so important ...

**Comment by akkiankur** [comment]
Thanks for the tip. I will try it out.

> you could add a FAN to change fan speed or you make cool with fan speed 1 heat with fan speed 2 and auto with fan speed 3

**Comment by akkiankur** [comment]
@markwien - i tried your way and setup two fan modes (max and auto) using cool and auto mode for different temperatures. I haven't been able to figure out how to use siri to switch mode from cool to auto or vice versa so as to change the air conditioner fan speed at a particular temperature.

**Comment by kiwi-cam** [comment]
I've just had a bit of a dig into this issue (sorry its taken so long). I think I've found where I went wrong.  The support for modeXX hex codes was where this all started for me... and I've learnt a thing or two since then.  It looks like vfI had the scope on a variable wrong.

@markwien or @akkiankur any chance you could download the latest BETA (4.3.4-beta.4) and see if this now works correctly for you?

**Comment by akkiankur** [comment]
> @markwien or @akkiankur any chance you could download the latest BETA (4.3.4-beta.4) and see if this now works correctly for you?

@kiwi-cam - Thanks for your continued support on the plugin. I don't have access to my setup for next week days. I will only be able to test this next month.

**Comment by markwien** [comment]
@akkiankur 
i am currently on: homebridge-broadlink-rm-pro v4.3.3

For my feeling it exactly works as i thought to be. Now It looks like a termostat in homekit ON/OFF and Temperature. Only Fanspeed is not possible but this is not a big problem for me. I dont know how to pull the beta to my production setup. I use Homebridge to update plugin.
