### ISSUE TITLE
Heater-cooler accessory with MQTT Temperature and Humidity sensor

### ISSUE THREAD

**Issue by edugrt** [kiwi-cam/homebridge-broadlink-rm#301]
**Describe the bug**
I added a heater-cooler accessory with an MQTT input for the temperature and humidity sensor. In the Home app the aircon accessory won’t show the correct temperature nor the humidity. I am sure the sensor is working because I added an accessory for that using another Homebridge plugin. 

**Expected behavior**
At the heater-cooler accessory inside Home app the shown temperature and humidity should be the ones from the MQTT source. 

**Screenshots**
From the aircon accessory
![17641548-94C9-451B-9581-D22F1E0F8D01](https://user-images.githubusercontent.com/73726734/115469597-53d8f700-a20b-11eb-8883-d49043229377.jpeg)

From the MQTT source
![F5AC64FE-3348-451B-98A7-294A6A91E5D3](https://user-images.githubusercontent.com/73726734/115469599-55a2ba80-a20b-11eb-81e6-87ec2b811bdf.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone Xr
 - OS: iOS 14
 - Browser: Safari
 - Version: from iOS 14

**Additional context**
An extract from the config:

 ……..       {
                    "name": "Ar Casal",
                    "host": "BROADLINK_IP",
                    "type": "heater-cooler",
                    "minTemperature": 18,
                    "maxTemperature": 30,
                    "coolingThresholdTemperature": 25,
                    "defaultRotationSpeed": 0,
                    "tempStepSize": 1,
                    "fanStepSize": 20,
                    "temperatureUpdateFrequency": 60,
                    "mqttURL": "mqtt://BROKER_IP",
                    "mqttTopic": [
                        {
                            "identifier": "temperature",
                            "topic": "home/sensor/dht22_temperature"
                        },
                        {
                            "identifier": "humidity",
                            "topic": "home/sensor/dht22_humidity"
                        }
                    ],
                    "data": {
                        "cool": {
                            "on": "a",
                            "off": [……..

**Comment by masterfordev** [comment]
The heater-cooler dont have support for sensor or mqtt.

**Comment by edugrt** [comment]
Oh, I see… and is there any other way to accomplish that?

**Comment by edugrt** [comment]
And if there is no other way to do that, at least there should be a way to not consider the fake heater-cooler “current” temperate for a specific room (I might be missing some feature that already does that), see the image below:

![CC29B9FE-7575-4D73-8145-5FBA7FFB6369](https://user-images.githubusercontent.com/73726734/115531289-fc6a7380-a26a-11eb-975e-a6ada0c947f7.jpeg)

As you can see, that room has a temperature sensor which shows 21°C and the heater-cooler accessory that shows the fake 24°C, therefore the room temperature will be an average from that: 

![B7187BF1-9830-4DB3-AB67-CEC816DB2B96](https://user-images.githubusercontent.com/73726734/115531690-74d13480-a26b-11eb-8015-5ace139f15e0.jpeg)

**Comment by mancudben37** [comment]
This is the best plug-in for homebridge! Congrats @lprhoades and @kiwi-cam !! MQTT Temperature support would be great for heater cooler! Thanks!!

**Comment by kiwi-cam** [comment]
The latest BETA (v4.4.3-beta.2) adds this support. Let me know how it goes.

**Comment by edugrt** [comment]
@kiwi-cam, thanks! Than worked.

**Comment by mancudben37** [comment]
@edugrt @kiwi-cam Edu, could you please verify mqtt for heater cooler is working?

I have an AC working with MQTT temp and humidity, tried copying the same working mqtt config/topics to heater cooler but to no success. 

Tried deleting persist folders, deleting cached accessories, "temperatureUpdateFrequency = 10", redefining homebridge, deleting the old AC so only the heater cooler would get the mqtt payload but it's still not working.

Any ideas?

Thanks in advance!

{
                    "name": "Heater Cooler",
                    "type": "heater-cooler",
                    "host": "7.7.7.8",
                    "minTemperature": 17,
                    "maxTemperature": 30,
                    "coolingThresholdTemperature": 27,
                    "heatingThresholdTemperature": 18,
                    "defaultRotationSpeed": 75,
                    "fanStepSize": 25,
                    "tempStepSize": 1,
                    "temperatureUnits": "C",
                    "mqttURL": "mqtt://7.7.7.6",
                    "mqttTopic": [
                        {
                            "identifier": "temperature",
                            "topic": "Livingroom/Temperature"
                        },
                        {
                            "identifier": "humidity",
                            "topic": "Livingroom/Humidity"
                        }
                    ],
                    "temperatureUpdateFrequency": 10,
                    "data": {.......

**Comment by edugrt** [comment]
Hi, try to use it with Mqttthing plugin first to make sure your sensor is actually sending data to your MQTT broker.

Cameron’s beta MQTT temperature readings for a heater-cooler works for me. With regards to humidity readings, still nothing but I did not look into it to see if I’m doing something wrong.

**Comment by mancudben37** [comment]
Got it working by changing the previous topic to a random one , reseting homebridge, changing back to the original topic and resetting again.

Thanks very much!! @kiwi-cam
