### ISSUE TITLE
Fan Reset Swing Mode

### ISSUE THREAD

**Issue by SmolSoftBoi** [kiwi-cam/homebridge-broadlink-rm#303]
**Describe the bug**
My fan resets the swing mode to off after powering off, but HomeKit shows it as whatever it last was set to.

**Expected behavior**
Swing mode to reset to off or a default when turned off.

Example config.json:
```json
{
    "name": "Fan",
    "type": "fan",
    "data": {
        "on": "…",
        "off": "…",
        "swingToggle": "…",
        "fanSpeed": "…"
    },
    "hideRotationDirection": true,
    "alwaysResetToDefaults": true,
    "defaultSwing": true,
    "stepSize": 33
}
```

If `defaultSwing` is set, this could be reset after powering off.

**Comment by akkiankur** [comment]
I have the same issue and would like the swing mode to be set to off when the fan is switched off.

**Comment by SmolSoftBoi** [comment]
Bad bot.
