### ISSUE TITLE
heatercooler temperature from homekit sensor

### ISSUE THREAD

**Issue by aibkaresz** [kiwi-cam/homebridge-broadlink-rm#308]
First of all I would like to say thank you for this plugin, it is absolutely amazing!

I have set up my AC as a heatercooler, and as for many of us it shows 24 degress as temperature, since I don't have the sensor on the cable.

I also have a homekit compatible Qingping temperature and humidity sensor which is bluetooth only, and I would like to ask you guys if there is any way to expose the temperature from the sensor to the plugin to show the value as the AC temperature?

Thank you in advance!

**Comment by FranciRoosters** [comment]
Following. I'd like to set this up as well. If I'm not mistaken, this should be possible with the newest plugin version, but I'm not sure how to set it up.

**Comment by aibkaresz** [comment]
Yes I have removed it from the Home Status, this way it doesn't mess up the temperature sensor which gives you an average, but it would be nice to see the actual temperature on the AC UI when cooling

**Comment by kiwi-cam** [comment]
Sorry, mis-read that. v4.4.3 supports all the same temperature sources as the air-conditioner, and sensors do. If you can get the values into a text file or MQTT it'll be able to grab them, but I'm not sure there's a way to read from another accessory.

**Comment by kiwi-cam** [comment]
I use some Mi BLE sensors which I listen for on my RPi using this script: https://gist.github.com/kiwi-cam/f7914825fca122adf64b193385a5a6d9. It might be helpful but I expect the data encoding will difer.

**Comment by aibkaresz** [comment]
Thanks for the reply! Well my sensor is bluetooth only, so I doubt it can connect to anything like an mqtt server. It looks like the easiest way is to get a cable with the temperature sensor? :)

**Comment by FranciRoosters** [comment]
@kiwi-cam I’m a bit confused as to which string of text I should write in my config to have a different temperature than 24 show up on Home.

**Comment by aibkaresz** [comment]
Oh I just figured it out, that my RM4C does not support the temperature sensor in the cable, so it's also a dead end for me. What I was thinking of is that I could start an MQTT server and my Qingping sensor should be able to communicate with the RPi and expose the values to the MQTT server (it's a strange method, that a native homekit sensor is exposed to homebridge :)). Also I have 0 experience with MQTT, thus the hesitation.

**Comment by Vannixxo** [comment]
have you find a way? I would like to pass temperature from homepod sensors someway.. or at least to completely remove temp indicator as it messes up the mean homekit calculates through all the rooms
