### ISSUE TITLE
RM4 Pro RF Learn

### ISSUE THREAD

**Issue by darrenkhu** [kiwi-cam/homebridge-broadlink-rm#31]
Can i confirm that RF learn is still not possible with RM4 Pro?

I tried the RF button in HOME but Scan RF fails after approx 20 seconds

**Comment by Stichoza** [comment]
Check https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/10#issuecomment-655197879

**Comment by kiwi-cam** [comment]
I received my RM4 Pro last week. I'm hoping to get started on this soon.  I'll close this issue, follow #10 for updates.
