### ISSUE TITLE
Cannot update to latest version from previous

### ISSUE THREAD

**Issue by planetmarsalarm** [kiwi-cam/homebridge-broadlink-rm#312]
**Describe the bug**
Latest channel release of Homebridge and Homebridge UI, will go through process of updating but will still show previous version as active and update alert still present.  

**Expected behavior**
Expected version update after what appeared to be a successful update

**Comment by kiwi-cam** [comment]
Sorry @planetmarsalarm, I don't think I can do much to help here. I publish the releases to NPM and it should take care of the rest. Maybe raise an issue in Homebridge? Are other plug-ins updating?
