### ISSUE TITLE
Cannot trigger fan using Home app - what am I doing wrong?

### ISSUE THREAD

**Issue by ghost** [kiwi-cam/homebridge-broadlink-rm#315]
I have been able to "learn" the HEX code (0a0024000000144d4362050000000000) but I am not able to trigger the fan on/off using Home app. What am I doing wrong?

Broadlink RM Pro
Firmware:               v52079
Frequency:             433.73MHz

{
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "debug": true,
    "accessories": [
        {
            "name": "Temperature",
            "type": "temperatureSensor",
            "temperatureUpdateFrequency": 300
        },
        {
            "name": "Humidity",
            "type": "humiditySensor",
            "humidityUpdateFrequency": 300
        },
        {
            "name": "Ceiling Fan",
            "type": "fan",
            "data": {
                "on": "0a0024000000144d4362050000000000",
                "off": "0a0024000000144d4362050000000000"
            }
        }
    ]
}

09/05/2021, 11:29:27 am [Broadlink RM] **************************************************************************************************************
09/05/2021, 11:29:27 am [Broadlink RM] ** Welcome to version 4.4.3 of the Homebridge Broadlink RM Plugin!
09/05/2021, 11:29:27 am [Broadlink RM] **
09/05/2021, 11:29:27 am [Broadlink RM] ** Find out what's in the latest release here: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/CHANGELOG.md
09/05/2021, 11:29:27 am [Broadlink RM] **
09/05/2021, 11:29:27 am [Broadlink RM] ** If you like this plugin then please star it on GitHub or better yet
09/05/2021, 11:29:27 am [Broadlink RM] ** buy me a drink using Paypal https://paypal.me/kiwicamRM.
09/05/2021, 11:29:27 am [Broadlink RM] **
09/05/2021, 11:29:27 am [Broadlink RM] ** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
09/05/2021, 11:29:27 am [Broadlink RM] **
09/05/2021, 11:29:27 am [Broadlink RM] **************************************************************************************************************
09/05/2021, 11:29:27 am [Broadlink RM]
09/05/2021, 11:29:27 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:42644 (UDP)
09/05/2021, 11:29:29 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:39891 (UDP)
09/05/2021, 11:29:30 am [Ring] Found the following locations:
09/05/2021, 11:29:30 am [Ring] locationId: rbsmyy-1uncu-0 - My Location
09/05/2021, 11:29:31 am [Ring] Configuring 2 cameras and 2 devices for location "My Location" - locationId: rbsmyy-1uncu-0
09/05/2021, 11:29:31 am [myQ] myQ API: Successfully connected to the myQ API.
09/05/2021, 11:29:31 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:47178 (UDP)
09/05/2021, 11:29:34 am [Nest Protect] initing protect "Office": deviceId: 18B4300000A63262 structureId: 1108b144-1d46-11ea-ae74-12d8cf60863a
09/05/2021, 11:29:34 am [Office@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:34 am [Office@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:34 am [Nest Protect] initing protect "Hallway": deviceId: 6416660000D23F7A structureId: 1108b144-1d46-11ea-ae74-12d8cf60863a
09/05/2021, 11:29:34 am [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:34 am [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:34 am Initializing platform accessory 'Office'...
09/05/2021, 11:29:34 am Initializing platform accessory 'Hallway'...
09/05/2021, 11:29:34 am Preparing Advertiser for 'HOOBS C22D' using bonjour-hap backend!
09/05/2021, 11:29:34 am Starting to advertise 'HOOBS C22D' using bonjour-hap backend!
09/05/2021, 11:29:34 am Bridge is running on port 51826.
09/05/2021, 11:29:34 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:40893 (UDP)
09/05/2021, 11:29:35 am [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: CG08114002BB, gateway: GWA1000006C7).
09/05/2021, 11:29:35 am [myQ] myQ API: Discovered device family gateway: Home (serial number: GWA1000006C7).
09/05/2021, 11:29:35 am [HOOBS C22D@Garage Door@@Manufacturer] characteristic value expected string and received undefined
09/05/2021, 11:29:35 am [HOOBS C22D@Garage Door@@Model] characteristic value expected string and received undefined
09/05/2021, 11:29:35 am [HOOBS C22D@Garage Door@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
09/05/2021, 11:29:35 am [HOOBS C22D@Garage Door@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
09/05/2021, 11:29:35 am [Broadlink RM] Learn getSwitchState: false
09/05/2021, 11:29:35 am [Broadlink RM] Scan Frequency getSwitchState: false
09/05/2021, 11:29:35 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
09/05/2021, 11:29:35 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
09/05/2021, 11:29:35 am [Broadlink RM] Ceiling Fan getSwitchState: 0
09/05/2021, 11:29:35 am [Broadlink RM] Ceiling Fan getSwingMode: 0
09/05/2021, 11:29:35 am [Broadlink RM] Ceiling Fan getFanSpeed: 100
09/05/2021, 11:29:35 am [Broadlink RM] Ceiling Fan getRotationDirection: 1
09/05/2021, 11:29:35 am [Office@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:35 am [HOOBS C22D@Office@Office@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:35 am [Office@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:35 am [HOOBS C22D@Office@Office@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:35 am [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:35 am [HOOBS C22D@Hallway@Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:35 am [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:35 am [HOOBS C22D@Hallway@Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:29:36 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a002400000014514363050000000000
09/05/2021, 11:29:36 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a002400000014514363050000000000
09/05/2021, 11:29:36 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:46526 (UDP)
09/05/2021, 11:29:38 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:60968 (UDP)
09/05/2021, 11:29:40 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:41255 (UDP)
09/05/2021, 11:29:42 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:41152 (UDP)
09/05/2021, 11:29:44 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:41289 (UDP)
09/05/2021, 11:29:46 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:42315 (UDP)
09/05/2021, 11:29:48 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:60754 (UDP)
09/05/2021, 11:29:50 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:60330 (UDP)
09/05/2021, 11:29:52 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:54630 (UDP)
09/05/2021, 11:29:54 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:53380 (UDP)
09/05/2021, 11:29:56 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:57177 (UDP)
09/05/2021, 11:29:58 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:35119 (UDP)
09/05/2021, 11:30:00 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:40559 (UDP)
09/05/2021, 11:30:02 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:33779 (UDP)
09/05/2021, 11:30:04 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:57654 (UDP)
09/05/2021, 11:30:06 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:43082 (UDP)
09/05/2021, 11:30:08 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:54773 (UDP)
09/05/2021, 11:30:10 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:45470 (UDP)
09/05/2021, 11:30:12 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:36871 (UDP)
09/05/2021, 11:30:14 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:54540 (UDP)
09/05/2021, 11:30:16 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:49574 (UDP)
09/05/2021, 11:30:17 am [Broadlink RM] Ceiling Fan getSwitchState: 0
09/05/2021, 11:30:17 am [Broadlink RM] Ceiling Fan getFanSpeed: 100
09/05/2021, 11:30:17 am [Broadlink RM] Ceiling Fan getRotationDirection: 1
09/05/2021, 11:30:17 am [Broadlink RM] Ceiling Fan getSwingMode: 0
09/05/2021, 11:30:17 am [Broadlink RM] Scan Frequency getSwitchState: false
09/05/2021, 11:30:17 am [Broadlink RM] Learn getSwitchState: false
09/05/2021, 11:30:17 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
09/05/2021, 11:30:17 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
09/05/2021, 11:30:17 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a00240000001451440e050000000000
09/05/2021, 11:30:17 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a00240000001451440e050000000000
09/05/2021, 11:30:17 am [Broadlink RM] Ceiling Fan getSwitchState: 0
09/05/2021, 11:30:17 am [Broadlink RM] Ceiling Fan getFanSpeed: 100
09/05/2021, 11:30:17 am [Broadlink RM] Ceiling Fan getRotationDirection: 1
09/05/2021, 11:30:17 am [Broadlink RM] Ceiling Fan getSwingMode: 0
09/05/2021, 11:30:18 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:59669 (UDP)
09/05/2021, 11:30:20 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:50240 (UDP)
09/05/2021, 11:30:22 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:58064 (UDP)
09/05/2021, 11:30:23 am [Broadlink RM] Ceiling Fan setSwitchState: 1
09/05/2021, 11:30:23 am [HOOBS C22D@Ceiling Fan@Ceiling Fan@On] Characteristic not in required or optional characteristic section for service Fanv2. Adding anyway.
09/05/2021, 11:30:23 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: da00020000000a0024000000144d4362050000000000
09/05/2021, 11:30:23 am [Broadlink RM] Ceiling Fan sendHex (192.168.178.69; a0:43:b0:32:bc:5d) 0a0024000000144d4362050000000000
09/05/2021, 11:30:23 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0200000000000000000000000000
09/05/2021, 11:30:24 am [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:47790 (UDP)
09/05/2021, 11:30:25 am [HOOBS C22D@Garage Door@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
09/05/2021, 11:30:25 am [Broadlink RM] Learn getSwitchState: false
09/05/2021, 11:30:25 am [Broadlink RM] Scan Frequency getSwitchState: false
09/05/2021, 11:30:25 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
09/05/2021, 11:30:25 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
09/05/2021, 11:30:25 am [Broadlink RM] Ceiling Fan getSwitchState: 1
09/05/2021, 11:30:25 am [Broadlink RM] Ceiling Fan getSwingMode: 0
09/05/2021, 11:30:25 am [Broadlink RM] Ceiling Fan getFanSpeed: 100
09/05/2021, 11:30:25 am [Broadlink RM] Ceiling Fan getRotationDirection: 1
09/05/2021, 11:30:25 am [Office@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:30:25 am [HOOBS C22D@Office@Office@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:30:25 am [Office@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:30:25 am [HOOBS C22D@Office@Office@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:30:25 am [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:30:25 am [HOOBS C22D@Hallway@Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:30:25 am [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:30:25 am [HOOBS C22D@Hallway@Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
09/05/2021, 11:30:25 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a00240000001451440e050000000000
09/05/2021, 11:30:25 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a00240000001451440e050000000000
09/05/2021, 11:30:26 am [Broadlink RM] Ceiling Fan setSwitchState: 0
09/05/2021, 11:30:26 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: da00020000000a0024000000144d4362050000000000
09/05/2021, 11:30:26 am [Broadlink RM] Ceiling Fan sendHex (192.168.178.69; a0:43:b0:32:bc:5d) 0a0024000000144d4362050000000000
09/05/2021, 11:30:26 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0200000000000000000000000000
09/05/2021, 11:30:26 am [Broadlink RM] Ceiling Fan getFanSpeed: 100
09/05/2021, 11:30:26 am [Broadlink RM] Ceiling Fan getRotationDirection: 1
09/05/2021, 11:30:26 am [Broadlink RM] Ceiling Fan getSwingMode: 0
09/05/2021, 11:30:28 am [Ring] Side Detected Motion. Loading snapshot before sending event to HomeKit

**Comment by kiwi-cam** [comment]
Hmmm... that hex code looks amazingly short. I suspect that's not the correct code or format. I'd try learning the code again.

**Comment by ghost** [comment]
The only codes I receive when I put the Home app into Learn mode are as follows:

10/05/2021, 10:13:35 am [Broadlink RM] Learn Code (ready)
10/05/2021, 10:13:35 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0300000000000000000000000000
10/05/2021, 10:13:36 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
10/05/2021, 10:13:37 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
10/05/2021, 10:13:37 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
10/05/2021, 10:13:37 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a00240000001531461a050000000000
10/05/2021, 10:13:37 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
10/05/2021, 10:13:37 am [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a00240000001531461a050000000000
10/05/2021, 10:13:38 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
10/05/2021, 10:13:39 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
10/05/2021, 10:13:40 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
10/05/2021, 10:13:41 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
10/05/2021, 10:13:42 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
10/05/2021, 10:13:43 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
10/05/2021, 10:13:44 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
10/05/2021, 10:13:45 am [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
10/05/2021, 10:13:45 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001e
10/05/2021, 10:13:45 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001e
10/05/2021, 10:13:45 am [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001e
10/05/2021, 10:13:45 am [Broadlink RM] [INFO] Learn Code (stopped)

Does this mean that the codes are not being learnt?
