### ISSUE TITLE
Finer Log tuning, particularily when using ping for status

### ISSUE THREAD

**Issue by houmark** [kiwi-cam/homebridge-broadlink-rm#316]
**Describe the solution you'd like**
First of all, thanks for all your work on this. I've been able to get some basic controls for my TV working.

I'd like to ping track the TV fairly frequent, like more than once a minute or so, but that results in logs being fairly full of the same log output:
[5/9/2021, 2:08:45 AM] [Broadlink RM] TV getSwitchState: true

Would it maybe be possible to have a flag to disable those logs or only output the ping check logs when in debug mode? I know this is the generic state check, but it should be able to wrap that to not log if the call is happening from the check.

**Describe alternatives you've considered**
I've lowered raised the interval to something where it's not 90% showing this one state check in the logs.

**Comment by masterfordev** [comment]
Disable logs. In the [documentation](https://broadlink.kiwicam.nz/#common-accessory-options) have the info for do it.

**Comment by houmark** [comment]
Not sure how I missed that ;) I'll try it!

**Comment by kiwi-cam** [comment]
disableLogs should do the trick for you.  I'm actually going to hijack this issue and look at introducing log levels (e.g. verbose, debug, warning, error, info) instead of using "debug" and "disableLogs".

**Comment by houmark** [comment]
I like that idea, but I also like being able to debug while still not being too chatty on normal operations.

Right now I have `debug: true` so I can monitor commands sent, but I don't get the ping status update. That's pretty much the sweet spot and once everything is stable, I can disable debug and it should be running smooth and silent.
