### ISSUE TITLE
White in RGB light

### ISSUE THREAD

**Issue by imtitanic** [kiwi-cam/homebridge-broadlink-rm#325]
Hi! :D 

It's a question more than a bug, i think, but is there a way that led strip shows up white color? When I ask Siri for it, strip puts on red because homebridge logs says that put the closer hue, so there's no way to back white.

Thanx!

**Comment by thiaramus** [comment]
Same thing here, I observe when I ask Siri to set the color to **white**, I am getting **hue** set to **0** and **saturation** set to **0**, and when I ask to set the color to **red**, I am getting **hue** set to **0** as well, but saturation set to **100**, however, I don't see an option to control saturation from the plugin settings to assign separate HEX codes for those combinations.

PS: This looks more like a feature request than a bug :)
