### ISSUE TITLE
Keep state synced between remote control and HomeKit

### ISSUE THREAD

**Issue by seidnerj** [kiwi-cam/homebridge-broadlink-rm#327]
Currently this plugin works great, say if you turn the AC on / off etc. as long as you always control the target device through HomeKit. 

When you add an external remote control to the mix that’s when you get inconsistent states, e.g. the remote control turned the AC on but in HomeKit its state is off.

A solution to this could be to use the Broadlink RM to also listen for incoming infrared signals (i.e. from the remote), decode them and then use those to update the status of the target device. This same method is what is implemented in Sensibo for example.

**Comment by shanemcw** [comment]
A side benefit from this enhancement: of this plugin is able to use the Broadlink RM to report on IR/RF remote activity continuously/asynchronously and act on it (e.g. to perform the enhancement identified here to sync device state/status) that would enable any IR/RF remote to be used as a HomeKit button for any purposes.

**Comment by kiwi-cam** [comment]
This is something that has been raised before, and I'm intrigued but don't have the time to take it on right now.

I think it could work, but with a few caveats:
1. The RM can only send **OR** receive, not both simultaneously so you'd need a dedicated device for listening.
2. IR is very directional so the listening device would have to be close to the device being controlled with the remote
3. The RM can only listen on a single frequency so multiple devices may be needed; one for IR, one for 433MHz RF, and another for 355 MHz RF??

**Comment by Avi0n** [comment]
I think this would still be a nice feature to have.

**Comment by seidnerj** [comment]
It would be an awesome feature to have :)
