### ISSUE TITLE
preventResendHex vs allowResend in v4.4.4

### ISSUE THREAD

**Issue by benjaminbogdanovic** [kiwi-cam/homebridge-broadlink-rm#334]
The preventResendHex that I have set to false in the air-conditioner type is overridden by allowResend as it has been set to be explicitly to true by default in v4.4.4.

preventResendHex and allowResend effectively do the same thing. As I recall preventResendHex was in the original plugin, with allowResend added more recently. It makes sense to maintain both so not to break older configurations, but perhaps preventResendHex should have priority?

**Comment by kiwi-cam** [comment]
This issue should be fixed in the latest beta: v4.4.5-beta.0. Let me know how you get on.
