### ISSUE TITLE
Error after upgrading to version 4.4.4 - "This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 10."

### ISSUE THREAD

**Issue by akkiankur** [kiwi-cam/homebridge-broadlink-rm#338]
After upgrading to the latest version (4.4.4) today, I see the following error in the homebridge log file while using the Heater-Cooler accessory - "This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 10. See https://git.io/JtMGR for more info."

Here is a copy of my config file - 

"name": "Living Room AC",
"type": "heater-cooler",
"host": "xxx",
"minTemperature": 18,
"maxTemperature": 25,
"coolingThresholdTemperature": 23,
"defaultRotationSpeed": 50,
"tempStepSize": 1,
"fanStepSize": 50,
"data": {
                        "cool": {
                            "off": "xxx",
                            "on": "xx",
                            "temperatureCodes": {
                                "18": {
                                    "rotationSpeed50": "xx",
                                    "rotationSpeed100": "xx"
                                },
                                ....

![Capture](https://user-images.githubusercontent.com/69201177/121799676-02277880-cc60-11eb-85b8-bb712e7c222f.JPG)

**Comment by victorhenrion** [comment]
A temporary fix is to set `noHumidity` to `true`

**Comment by akkiankur** [comment]
I added the noHumidity in the config but still see the error

**Comment by 9vska** [comment]
Try assigning a `defaultNowTemperature` for your device — that should fix it.

**Comment by uzumaki20398** [comment]
If I had to take a guess ,No temperature value from MQTT ,W1 Device or temperatureFilePath.
In heater-cooler.js , if it has not any temperature value.
temperature value= 0,
But 1233 lines

`this.serviceManager   `
`    .getCharacteristic(Characteristic.CurrentTemperature)`
`    .setProps({`
`        minValue: 10,`
`         maxValue: 40,`
`         minStep: 0.1`
`    })`

You can try change "minValue: 10 "to "minValue: 0 "

**Comment by kiwi-cam** [comment]
This issue should be fixed in the latest beta: v4.4.5-beta.0. Let me know how you get on.
