### ISSUE TITLE
Volume up and down stay on for too long

### ISSUE THREAD

**Issue by TMaskell** [kiwi-cam/homebridge-broadlink-rm#34]
The Broadlink seems to send a signal for a couple of seconds when used through home bridge. In most cases this is fine say for power or source buttons. However for volume this means it is turning my volume up or down by 8 which in the case of my AV box is quite a volume change. 

For comparison I have added the AVR to the IHC app and when it sends volume controls it only sends very briefly changing volume by 1 not 8 so looks from a hardware point of view possible.

Is there any way to shorten the IR signal from the Broadlink via homebirdge?

**Comment by TMaskell** [comment]
@kiwi-cam

**Comment by TMaskell** [comment]
@kiwi-cam Any ideas? this makes using the remote app in iOS pointless and I'm having to use the IHC app?

**Comment by kiwi-cam** [comment]
Sorry @TMaskell, I've done some hunting and can't find a way to shorten the command's duration. According to the [specifications here](https://github.com/mjg59/python-broadlink/blob/master/protocol.md#sending-data), your commands should start with 2600 (this is 0x04 and 0x05 of the sent command). The 26 means IR, and the 00 means don't repeat the command. Unless you've got 2601 (or more), we're only sending the command once.

**Comment by maxvelascoknott** [comment]
@TMaskell One thing you could try is trying to read the signal from your remote control again. Try pushing the button briefly when capturing it; some remotes send different logic for a press-and-hold, and it could be that your original capture was long.
