### ISSUE TITLE
Using multiple devices - code not sending to correct device

### ISSUE THREAD

**Issue by sicnarf023** [kiwi-cam/homebridge-broadlink-rm#340]
I have two devices configured this way

"accessories": [
                {
                    "name": "Living Room TV",
                    "type": "tv",
                    "hosts": [
                        {
                            "address": "192.168.51.55"
                        }
                    ],
                    "data": {
                        ...
                },
                {
                    "name": "Bedroom Fan",
                    "type": "fan",
                    "stepSize": 25,
                    "speedSteps": 25,
                    "hosts": [
                        {
                            "address": "192.168.51.62"
                        }
                    ],
                    "data": {
                        ...

I have tried the hosts file using address only or address+mac or mac only. Either of the three have same behavior below.
Both devices are correctly detected at startup

[6/16/2021, 9:55:56 AM] [Broadlink RM] [INFO] Discovered Broadlink RM4 Mini C (62be) at 192.168.51.62 (24:df:a7:4f:f2:d0)
[6/16/2021, 9:55:56 AM] [Broadlink RM] [INFO] Discovered Broadlink RM2 Pro Plus (272a) at 192.168.51.55 (34:ea:34:c7:88:8a)

The command to turn on/off the tv sends to 192.168.51.62

[6/16/2021, 9:56:03 AM] [Broadlink RM] Living Room TV setSwitchState: 1
[6/16/2021, 9:56:03 AM] [Broadlink RM] Living Room TV sendHex (192.168.51.62; 24:df:a7:4f:f2:d0) 2600580000012a93141113121337131213111411141114111436133713121336143613371336143614111312131213361411141114111411143613371336141114361337133614361400052e00012a4913000c6300012b4814000d05

If I remove the device 192.168.51.62 (unplug it) and only 1 device is discovered, it correctly powers on/off the broadlink at 192.168.51.55

My plugin is v4.4.4 running on Mac OS homebridge.

**Comment by kiwi-cam** [comment]
I think you've got two sections of the config confused: hosts is to add devices if they're not able to be detected on your network, host is used to associate an accessory with a particular device: https://broadlink.kiwicam.nz/#common-accessory-options

Try this: 
```
"accessories": [
{
"name": "Living Room TV",
"type": "tv",
"host": "192.168.51.55"
"data": {
...
},
{
"name": "Bedroom Fan",
"type": "fan",
"stepSize": 25,
"speedSteps": 25,
"host":"192.168.51.62"
"data": {
...
},
}

...
```

**Comment by sicnarf023** [comment]
thank you so much, it works now. i tried for both ip or mac.

would be very helpful to others if you can include this example on the documentation page. i did try the "host" vs "hosts" initially but using the format in the example but as you have shown, it is just one line and not nested.
