### ISSUE TITLE
Older AC has no controls in Homekit

### ISSUE THREAD

**Issue by electricidiot** [kiwi-cam/homebridge-broadlink-rm#345]
Running Homebridge on a 2018 Mac Mini running MacOSX 11.4. Broadlink RM Mini4 doing the IR.

I have an older Haier air conditioner (circa 2009) and have Hex codes and everything, but the config only lets me turn it on or off in the Homebridge Accessories tab. I have to click Heat then click off to get it to turn on or off. 

In the Home app, I can only turn it on or off from the Home tab or Rooms. If I go deeper into the settings, I can't do anything at all to adjust anything.

Since it's older, the a/c doesn't have a "set to temperature" kind of remote, just up and down for fan speed and temperature. One button to cycle through modes, one for on/off, one for fan speed, one for up temp and one for down.

the config I've got looks like so:

 "name": "Reading Room AC",
                    "type": "air-conditioner",
                    "noHumidity": true,
                    "minimumAutoOnOffDuration": 5,
                    "data": {
                        "on": "26005000000...etc",
                        "off": "26005000000...etc",
                        "modeX": "26005000000...etc",
                        "fanStepSize": "26005000000...etc",
                        "tempStepSize": {
                            "up": "26005000000...etc",
                            "down": "26005000000...etc"
                        }

The a/c turns up in Home looking like this:

![IMG_2498](https://user-images.githubusercontent.com/86128506/122609466-07b00480-d04c-11eb-837e-267b89b23039.PNG)

I can scroll that mini control wheel in the middle but it has zero effect on anything:

![IMG_2499](https://user-images.githubusercontent.com/86128506/122609520-1dbdc500-d04c-11eb-80db-b8db4311e624.PNG)

But the only thing that makes the a/c do anything at all is turning it from Heat, Cool, or Auto to off, at which point the a/c cycles rapidly on then back off or off and then back on. I put the minimumAutoOnOffDuration in there to try and make that stop to no avail. 

I tried using heater-cooler config instead but then Homebridge just throws up a "this plug in is taking too long" error and Homebridge itself won't load. 

Is it just that I have an older a/c or am I coding something wrongly? Since it's one button for on/off, should I remove one of those lines of code? I didn't figure it could hurt. That's why I only have one code for modeX and fanStepSize since it's one button that you just press multiple times to make something happen.

**Comment by kiwi-cam** [comment]
Can you share your logs from trying to send other codes? Might be a clue in there as to why temperature changes aren’t doing anything. 

The “plug-in is taking too long” message will probably be because you’ve got no temperature source. Try setting pseudoDeviceTemperature on the AC or defaultNowTemperature for the heater-cooler.

**Comment by electricidiot** [comment]
Here's what seems like the relevant bits of error code being thrown up in the logs. I might have to go the pseudo route since like I said, it's an oldie and doesn't actually have a way to set to a certain temperature except to press the up and down button until the digital display on the front of it says 68 or whatever. 

[6/18/2021, 3:45:35 PM] [Reading Room BL] Reading Room AC No heat HEX code found for 30
(node:63260) UnhandledPromiseRejectionWarning: AssertionError: [CONFIG ERROR]  You need to provide a hex code for the following temperature:
        { "temperature30": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
        or provide the default temperature:
         { "temperature30": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
    at AirConAccessory.getTemperatureHexData (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:328:7)
    at AirConAccessory.sendTemperature (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:288:48)
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:265:14
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:60:5)
    at processTimers (internal/timers.js:495:9)
(node:63260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 52)
[6/18/2021, 3:45:37 PM] [Reading Room BL] Reading Room AC setTargetHeatingCoolingState: 2
[6/18/2021, 3:45:37 PM] [Reading Room BL] Reading Room AC setTargetHeatingCoolingState: 2
[6/18/2021, 3:45:37 PM] [Reading Room BL] Reading Room AC setCurrentHeatingCoolingState: 2
[6/18/2021, 3:45:37 PM] [Reading Room BL] Reading Room AC No cool HEX code found for 16
(node:63260) UnhandledPromiseRejectionWarning: AssertionError: [CONFIG ERROR]  You need to provide a hex code for the following temperature:
        { "temperature16": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
        or provide the default temperature:
         { "temperature16": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
    at AirConAccessory.getTemperatureHexData (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:328:7)
    at AirConAccessory.sendTemperature (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:288:48)
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:265:14
(node:63260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 53)
[6/18/2021, 3:45:38 PM] [Reading Room BL] Reading Room AC setCurrentHeatingCoolingState: 2
[6/18/2021, 3:45:38 PM] [Reading Room BL] Reading Room AC setCurrentHeatingCoolingState: already 2 (no data sent - B)
[6/18/2021, 3:45:38 PM] [Reading Room BL] Reading Room AC No cool HEX code found for 16
(node:63260) UnhandledPromiseRejectionWarning: AssertionError: [CONFIG ERROR]  You need to provide a hex code for the following temperature:
        { "temperature16": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
        or provide the default temperature:
         { "temperature16": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }

**Comment by Nelnamara** [comment]
Any progress figuring out your issue?  I also have a dumb AC with only up and down controls on the remote.  I got 
Off, cool and auto figured out and had decent success using the coolOnly option which just set it to on/off auto.  My AC also has an "Eco" option I planned to make a simple toggle for.  My only hangup here is the temp settings wheel and how to use the pseudo-mode.  Any luck?  

I've been using this plugin for quite some time for my window coverings and such but these AC/Heat pump options are a bit confusing!  Awesome.... but confusing.
