### ISSUE TITLE
Heater cooler object throws error with blank ON hex code

### ISSUE THREAD

**Issue by th3dogcow** [kiwi-cam/homebridge-broadlink-rm#346]
**Describe the bug**
My AC doesn't have a unique on button, so up until now, I have had the on hex code set to a blank string. Upon updating to the current version, it now throws an error when turned on, saying a hex code is required. Deleting the on portion stops the plug-in from loading.

**Comment by th3dogcow** [comment]
Well I fixed it by setting "turnOnWhenOff" to false. I hadn't had this set at all, and the docs say the default is false. Perhaps the docs are wrong? Anyway was good to find a quick fix.

**Comment by josemmc95** [comment]
I had a similar problem and I just send the hex "00" that means null.
