### ISSUE TITLE
TV type: Make mute button available in TV remote 

### ISSUE THREAD

**Issue by justhebus42** [kiwi-cam/homebridge-broadlink-rm#349]
Regarding the TV type: 
In iOS 15 there are three new controls in the remote view: Mute, That list icon and Power.
Is it possible to also add at least the „mute“ action to the remote property? 

![F3262724-7937-40F2-9E80-596F9C29ED68](https://user-images.githubusercontent.com/74489641/123511805-cccd5280-d683-11eb-8613-5c8cee5fe681.jpeg)

**Comment by masterfordev** [comment]
The mute option is available (untested) since v4.4.3.
Just try add it in the config and test if work. Let us know if work. 

https://github.com/kiwi-cam/homebridge-broadlink-rm/commit/d21d2490b7b7943bf24ade300704e44888ce3318

**Comment by justhebus42** [comment]
Unfortunately, it does not work.

**Comment by charleszhai1991** [comment]
Configured but there is still no mute icon.


"volume": {
                            "up": hex_",
                            "down": "hex_",
                            "mute": "hex_"
                        }
