### ISSUE TITLE
can't set the fan to a off state when setting up automation

### ISSUE THREAD

**Issue by 172505197** [kiwi-cam/homebridge-broadlink-rm#350]
![12793067-2F07-4728-BDFA-AEEB9C7BCF40](https://user-images.githubusercontent.com/68852524/123658841-a9153280-d864-11eb-9022-bba9f70bb4c7.gif)

It's a strange bug. I can't set the fan to a off state when setting up automation.
Details can be seen in gif. I hope there is someone can tell me why. Can someone who adds a fan to the configuration help me see it? I want to know how you set it up. Thank you all

**Comment by masterfordev** [comment]
Just do a "click" dont keep hold the tile.

**Comment by 172505197** [comment]
when I click the button, it will disappear too

**Comment by 172505197** [comment]
It is quite similar to the thing happened in the gif above.

**Comment by 172505197** [comment]
It is really strange

**Comment by m0kum** [comment]
Got the same issue... To create the automation, you can choose the desired state before creating the automation itself. Sort of a temporary workaround for this bug.

**Comment by 172505197** [comment]
I will test it immediately. Thank you very much for your reply.
---原始邮件---
***@***.***&gt;
发送时间:2021年7月19日 星期一 下午9:25
***@***.***&gt;
***@***.***&gt;;&quot;State ***@***.***&gt;
主题:Re: [kiwi-cam/homebridge-broadlink-rm] can&#39;t set the fan to a off state when setting up automation (#350)



Got&nbsp;the&nbsp;same&nbsp;issue...&nbsp;To&nbsp;create&nbsp;the&nbsp;automation,&nbsp;you&nbsp;can&nbsp;choose&nbsp;the&nbsp;desired&nbsp;state&nbsp;before&nbsp;creating&nbsp;the&nbsp;automation&nbsp;itself.&nbsp;Sort&nbsp;of&nbsp;a&nbsp;temporary&nbsp;workaround&nbsp;for&nbsp;this&nbsp;bug.

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;modified&nbsp;the&nbsp;open/close&nbsp;state.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.
