### ISSUE TITLE
Rm4c Pro not working

### ISSUE THREAD

**Issue by agamboagg** [kiwi-cam/homebridge-broadlink-rm#351]
Hello, I recently installed the Broadlink RM4C Pro (the one that is black and white), but I have not managed to get it to work ... if I use the automatic recognition settings, it gives me the following error:

6/29/2021 7:54:24 PM [Broadlink RM]
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "6184". The device is connected to your network with the IP address "XXX.XXX.XXX.XXX".

And the Learn and Scan buttons don't work.

If I use the setting without automatic recognition and say it is "isRM4", it does not give an error, but the Learn and Scan buttons do not work either.

My automatic recognition settings are:
(The third and sixth correspond to the RM4C Pro):

{
    "name": "Broadlink RM",
    "accessories": [
        {
            "name": "Learn IR Comedor",
            "type": "learn-code",
            "host": "34:ea:34:43:3f:18"
        },
        {
            "name": "Learn IR Sala",
            "type": "learn-code",
            "host": "78:0f:77:18:1d:4d"
        },
        **{
            "name": "Learn IR Cuarto",
            "type": "learn-code",
            "host": "A0:43:B0:70:1D:6A"
        },**
        {
            "name": "Scan RF Comedor",
            "host": "34:ea:34:43:3f:18",
            "type": "learn-code"
        },
        {
            "name": "Scan RF Sala",
            "host": "78:0f:77:18:1d:4d",
            "type": "learn-code",
            "scanFrequency": true
        },
        **{
            "name": "Scan RF Cuarto",
            "host": "A0:43:B0:70:1D:6A",
            "type": "learn-code",
            "scanFrequency": true,
        },**  etc……….

The other configuration I have tried is:

{
    "name": "Broadlink RM",
"hosts": [
        {
            "address": "XXX.XXX.XXX.XXX",
            "mac": "34:EA:34:43:3F:18",
            "isRFSupported": true
        },
        {
            "address": "XXX.XXX.XXX.XXX",
            "mac": "78:0F:77:18:1D:4D",
            "isRFSupported": true
        },
        **{
            "address": "XXX.XXX.XXX.XXX",
            "mac": "A0:43:B0:70:1D:6A",
            "isRFSupported": true,
            "isRM4": true
        }**
    ],
"accessories": [
        {
            "name": "Learn IR Comedor",
            "type": "learn-code",
            "host": "34:ea:34:43:3f:18"
        },
        {
            "name": "Learn IR Sala",
            "type": "learn-code",
            "host": "78:0f:77:18:1d:4d"
        },
        **{
            "name": "Learn IR Cuarto",
            "type": "learn-code",
            "host": "A0:43:B0:70:1D:6A"
        },**
        {
            "name": "Scan RF Comedor",
            "host": "34:ea:34:43:3f:18",
            "type": "learn-code"
        },
        {
            "name": "Scan RF Sala",
            "host": "78:0f:77:18:1d:4d",
            "type": "learn-code",
            "scanFrequency": true
        },
        **{
            "name": "Scan RF Cuarto",
            "host": "A0:43:B0:70:1D:6A",
            "type": "learn-code",
            "scanFrequency": true,
        },**  etc……….

The accessories in bold are those of the RM4C Pro, with my other Broadlink devices I have not had any problems.

Thank you very much for the help!

**Comment by kiwi-cam** [comment]
Sorry for the delay here. Did you get the new device working manually; If not, try `"isRM4": false`? There's a small set of RM4 devices that use the RM3 headers.

**Comment by agamboagg** [comment]
Hi, yes it is working, with "isRM4": true and fixed IP… I think my Logitech plugin was making my homebridge unstable, I deleted it, and now everything works great!

**Comment by kiwi-cam** [comment]
The latest beta (v4.4.7-beta..1) should support this device now. Could you test auto discovery and confirm?

**Comment by agamboagg** [comment]
> The latest beta (v4.4.7-beta..1) should support this device now. Could you test auto discovery and confirm?

Yes, it works with auto discovery. The beta finds it. Thanks!!!
