### ISSUE TITLE
Show as single tile?

### ISSUE THREAD

**Issue by ijv182** [kiwi-cam/homebridge-broadlink-rm#353]
Some accessories (both official and homebridge pluggin: meross dual smart plug and Neato vacuum pluggin respectively for example) allow associated switches to be shown as a single tile. 

Long pressing on the single tile opens up all tiles grouped under it. 

This would be useful for creating remotes for devices that don't any of the pre-defined accessory groups.

**Comment by NeoRame** [comment]
YES PLEASE! This feature would be awesome!

**Comment by kmcondit** [comment]
Also looking for this. For example, I have a fireplace with flame level (currently set up as a light) and fan control, which I would love to combine into a single tile with a "master" on/off switch

**Comment by ManuISEN** [comment]
+1

**Comment by ijv182** [comment]
Commenting to hopefully keep active. Others have commented supporting the idea.
