### ISSUE TITLE
Multiple Broadlink Detected: Only sending HEX from one.

### ISSUE THREAD

**Issue by wongeujin** [kiwi-cam/homebridge-broadlink-rm#355]
Hi, I have edited my config and everything seems to work.
All devices has been added, both Broadlink in room and hall has been detected. (RM4C Mini and RM3 Pro Plus)

However it is only sending HEX codes from one device even though I have specified the "host" and even "Mac" on each accessories.

Here is my config: https://pastebin.com/KHc8BKFg
Please let me know if this is a bug or I am not doing something correctly.

**Comment by kiwi-cam** [comment]
It looks like you've put "hosts" under each accessory.  It's subtle but the "hosts" section is for the base of the platform and defines devices if auto detection doesn't work, "host" is used under an accessory to define with device to use for that accessory.

Just change all your "hosts" to "host" and you should be away.

**Comment by wongeujin** [comment]
You sir, are awesome.
Thank you so much.
