### ISSUE TITLE
Setting AC as air-conditioner and not heater-cooler

### ISSUE THREAD

**Issue by wongeujin** [kiwi-cam/homebridge-broadlink-rm#356]
Hi I finally setup everything to work on my config before reading there is no swingToggle or fanSpeed on "air-conditioner" type: https://pastebin.com/1RckxV3j 

However I would like to have that function but changing the type to "heater-cooler" throws up errors and the plugin won't boot on Homebridge. I do not have or plan to get temp sensors (which I suspect is the issue) and I just want the full functionality on remote to be on Homekit.
Here is my attempt to config the AC as "heater-cooler" which did not boot: https://pastebin.com/Kh4uhUR6

Is it possible you let me know 1. what did I do wrong in the config? 2. is there a way to get those functionality correctly?

**Comment by kiwi-cam** [comment]
Note that the heater-cooler uses a very different data structure to the air-conditioner so you'll need to update how your hex codes are structured: https://broadlink.kiwicam.nz/#heatercooler 

e.g. 
```
"data": {
      "heat": {
      "on":"ON_HEX_CODE",
      "off":"OFF_HEX_CODE",
      "temperatureCodes":{
        "67": {
            "rotationSpeedX": {
              "swingDnd":"HEX_CODE",
              "swingToggle":"HEX_CODE"
            }, 
            "rotationSpeedY": {
              "swingDnd":"HEX_CODE",
              "swingToggle":"HEX_CODE"
            } 
          }, 
          "68": {
            "rotationSpeedX": {
              "swingDnd":"HEX_CODE",
              "swingToggle":"HEX_CODE"
            }, 
            "rotationSpeedY": {
              "swingDnd":"HEX_CODE",
              "swingToggle":"HEX_CODE"
            } 
          } 
        }
```
