### ISSUE TITLE
error during plugin installation

### ISSUE THREAD

**Issue by adrianopery** [kiwi-cam/homebridge-broadlink-rm#359]
**Describe the bug**
I'm trying to install the plugin on my Hoobs 4 and I received the error during the installation.

**To Reproduce**
21:46:12Broadlink Rm Pro Bridge starting
21:46:26yarn add v1.22.10
21:46:27info No lockfile found.
21:46:27[1/4] Resolving packages...
21:46:31[2/4] Fetching packages...
21:46:33error An unexpected error occurred: "/usr/local/share/.cache/yarn/v6/npm-googleapis-82.0.0-26ab303b065c37fc4c9723b703550e62057ea810-integrity/node_modules/googleapis/.yarn-metadata.json: Unexpected token \u0000 in JSON at position 0".
21:46:33info If you think this is a bug, please open a bug report with the information provided in "/var/lib/hoobs/broadlinkrmprobridge/yarn-error.log".
21:46:33info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 Chrome 
Versão 91.0.4472.114 (Versão oficial) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kiwi-cam** [comment]
Sorry, I don't have much to add here but it looks like an issue installing one of the dependencies. I wonder it the solution on their Github page helps: https://github.com/googleapis/google-api-nodejs-client/issues/2456.
