### ISSUE TITLE
[HOOBS] Tv is not displayed by Homebridge or HomeKit (Workarround in the comments)

### ISSUE THREAD

**Issue by emilmilow** [kiwi-cam/homebridge-broadlink-rm#360]
**Describe the bug**
I have now googled a lot and tried to find a solution to my problem, unfortunately without success. I try to add TV, but unfortunately it is not displayed anywhere. In the log there are also no errors, only a warning (Possibly that is the problem). Another device works without problems. **Except for the 2 log lines it looks like the TV does not exist.**

**What I have already tried**
- I have used a minimal config to prevent errors in it.
- I restarted Homebridge, HomePod, etc.
- I have reinstalled the plugin
- I have set up the bridge again

**To Reproduce**
Clean Homebridge install + my config

**The interesting row (Probably):**
`18.7.2021, 04:03:50Broadlink Bridge WARNING platform configured a external accessory under the plugin name "[object Object]". However no loaded plugin could be found for the name.`

```
18.7.2021, 04:03:34Broadlink Bridge starting
18.7.2021, 04:03:50Broadlink BridgeLoaded plugin 'homebridge-broadlink-rm-pro'
18.7.2021, 04:03:50Broadlink BridgeLoading 1 platforms...
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRM[INFO] Automatically discovering Broadlink RM devices.
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRMLeinwand Accessory Ready
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRM[DEBUG] Adding Accessory window-covering (undefined)
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRMtv Accessory Ready
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRM[DEBUG] Adding Accessory tv (tv)
18.7.2021, 04:03:50Broadlink Bridge WARNING platform configured a external accessory under the plugin name "[object Object]". However no loaded plugin could be found for the name.
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRM**************************************************************************************************************
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRMYou added TVs in your configuration!
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRMDue to a HomeKit limitation you need to add any TVs to the Home app by using the Add Accessory function.
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRMThere you'll find your TVs and you can use the same PIN as you using for this HomeBridge instance.
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRM**************************************************************************************************************
18.7.2021, 04:03:51Broadlink BridgeBroadlinkRM[INFO] Listening for Broadlink devices on xxx.xxx.xxx.xx:37100 (UDP)
18.7.2021, 04:03:51Broadlink BridgeBridge is running on port 57826.
18.7.2021, 04:03:51Broadlink BridgeBroadlinkRM[DEBUG] (xxxxxxxxxx) Sending command:65 with payload: xxxxxxxxxxxxxxxxxxxxxxx
18.7.2021, 04:03:51Broadlink BridgeBroadlinkRM[INFO] Discovered Broadlink RM4 Pro (649b) at xxx.xxx.xxx.xx (xx:xx:xx:xx:xx:xx)
```

**Config:**
```
{
    "accessories": [],
    "platforms": [
        {
            "platform": "BroadlinkRM",
            "logLevel": "debug",
            "accessories": [
                {
                    "name": "Leinwand",
                    "type": "window-covering",
                    "totalDurationOpen": 30,
                    "totalDurationClose": 25,
                    "data": {
                        "open": [
                            {
                                "data": "HEX_CODE",
                                "sendCount": 2,
                                "interval": 0.5
                            }
                        ],
                        "close": [
                            {
                                "data": "HEX_CODE",
                                "sendCount": 2,
                                "interval": 0.5
                            }
                        ],
                        "stop": [
                            {
                                "data": "HEX_CODE",
                                "sendCount": 2,
                                "interval": 0.5
                            }
                        ]
                    }
                },
                {
                    "name": "Cinema",
                    "type": "tv",
                    "debug": true,
                    "data": {
                        "on": [
                            {
                                "data": "HEX_CODE",
                                "pause": 0.3
                            },
                            {
                                "data": "HEX_CODE"
                            }
                        ],
                        "off": [
                            {
                                "data": "HEX_CODE",
                                "pause": 0.3
                            },
                            {
                                "data": "HEX_CODE",
                                "pause": 0.3
                            },
                            {
                                "data": "HEX_CODE"
                            }
                        ],
                        "remote": {
                            "select": "HEX_CODE",
                            "arrowUp": "HEX_CODE",
                            "arrowDown": "HEX_CODE",
                            "arrowLeft": "HEX_CODE",
                            "arrowRight": "HEX_CODE",
                            "playPause": "HEX_CODE",
                            "rewind": "HEX_CODE",
                            "fastForward": "HEX_CODE",
                            "nextTrack": "HEX_CODE",
                            "previousTrack": "HEX_CODE",
                            "back": "HEX_CODE",
                            "exit": "HEX_CODE",
                            "info": "HEX_CODE"
                        },
                        "volume": {
                            "up": "HEX_CODE",
                            "down": "HEX_CODE"
                        },
                        "inputs": [
                            {
                                "name": "(1) Nintendo Switch",
                                "type": "other",
                                "data": [
                                    {
                                        "data": "HEX_CODE",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "HEX_CODE",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "HEX_CODE",
                                        "sendCount": 1,
                                        "interval": 0.3
                                    }
                                ]
                            },
                            {
                                "name": "(2) Steam Link",
                                "type": "other",
                                "data": [
                                    {
                                        "data": "HEX_CODE",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "HEX_CODE",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "HEX_CODE",
                                        "sendCount": 1,
                                        "interval": 0.3
                                    }
                                ]
                            },
                            {
                                "name": "(3) Nintendo Wii",
                                "type": "other",
                                "data": [
                                    {
                                        "data": "HEX_CODE",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "HEX_CODE",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "HEX_CODE",
                                        "sendCount": 1,
                                        "interval": 0.3
                                    }
                                ]
                            },
                            {
                                "name": "(4) Home (Blu-Ray)",
                                "type": "other",
                                "data": [
                                    {
                                        "data": "HEX_CODE",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "HEX_CODE",
                                        "pause": 0.3
                                    }
                                ]
                            },
                            {
                                "name": "(5) AppleTV",
                                "type": "other",
                                "data": [
                                    {
                                        "data": "HEX_CODE",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "HEX_CODE",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "HEX_CODE",
                                        "sendCount": 1,
                                        "interval": 0.3
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        }
    ]
}
```

I would be very happy if someone has a solution for me :)

**Comment by masterfordev** [comment]
```

18.7.2021, 04:03:50Broadlink BridgeBroadlinkRMDue to a HomeKit limitation you need to add any TVs to the Home app by using the Add Accessory function.
18.7.2021, 04:03:50Broadlink BridgeBroadlinkRMThere you'll find your TVs and you can use the same PIN as you using for this HomeBridge instance.

```

You did that?

**Comment by emilmilow** [comment]
Yes, I have tried. Unfortunately, I can not find a device. But I can't find it in the UI of Homebridge either. I think therefore that the error happens somewhere before

**Comment by emilmilow** [comment]
I have found a more detailed log:

```
18.7.2021, 04:33:49Broadlink BridgeOne of your plugins incorrectly registered an external accessory using the platform name ([object Object]) and not the plugin identifier. Please report this to the developer!
18.7.2021, 04:33:49Broadlink BridgePreparing Advertiser for 'Broadlink Bridge DF5A' using bonjour-hap backend!
18.7.2021, 04:33:49Broadlink BridgeStarting to advertise 'Broadlink Bridge DF5A' using bonjour-hap backend!
18.7.2021, 04:33:49Broadlink Bridge[35m[INFO][0m Adding RF Support to device a043b0b94168 with type 649b
```

**Comment by masterfordev** [comment]
> I have found a more detailed log:
> 
> ```
> 18.7.2021, 04:33:49Broadlink BridgeOne of your plugins incorrectly registered an external accessory using the platform name ([object Object]) and not the plugin identifier. Please report this to the developer!
> 18.7.2021, 04:33:49Broadlink BridgePreparing Advertiser for 'Broadlink Bridge DF5A' using bonjour-hap backend!
> 18.7.2021, 04:33:49Broadlink BridgeStarting to advertise 'Broadlink Bridge DF5A' using bonjour-hap backend!
> 18.7.2021, 04:33:49Broadlink Bridge�[35m[INFO]�[0m Adding RF Support to device a043b0b94168 with type 649b
> ```

You can ignore thats logs.
In your config only have one tv added.

**Comment by emilmilow** [comment]
Yes I have only one TV in my config. Or do I need to add a second one as a dummy?

**Comment by emilmilow** [comment]
Just to have all the info:

HOOBS: v4.0.87
Node: v14.17.2
Homebridge: v1.3.4

**Comment by masterfordev** [comment]
Oooh. you are on hoobs?

**Comment by emilmilow** [comment]
> Oooh. you are on hoobs?

Yes I am

**Comment by masterfordev** [comment]
I see.. im sorry, im not use hoobs :S 
i use homebridge on a raspberry pi.

**Comment by emilmilow** [comment]
> I see.. im sorry, im not use hoobs :S
> i use homebridge on a raspberry pi.

I think it is nothing more than a wrapper + UI. Homebridge is also running in the background at hoobs

**Comment by emilmilow** [comment]
Update: With another plugin I have no problems adding the TV with exactly the same configuration. Unfortunately, the other plugin does not have all the functions I need therefore I am dependent on the plugin here. @kiwi-cam any idea on the issue?

**Comment by emilmilow** [comment]
Another Update: Version 4.3.0 ist the last working version for me with the TV accessory. As of all subsequent versions, the TV cannot be found in Homebridge or HomeKit.

**Comment by ash123-germany** [comment]
Have the same issue under hoobs:

18.7.2021, 22:08:58HOOBSBroadlinkRM[INFO] Automatic Broadlink RM device discovery has been disabled as the "hosts" option has been set.
18.7.2021, 22:08:58HOOBSBroadlinkRM[INFO] Running Bridge Broadlink RM Plugin version 4.4.5
18.7.2021, 22:08:58HOOBSBroadlinkRMBeamer Accessory Ready
18.7.2021, 22:08:58HOOBSBroadlinkRMSamsung Accessory Ready
18.7.2021, 22:08:58HOOBSWARNUNGA platform configured a external accessory under the plugin name "[object Object]". However no loaded plugin could be found for the name.
18.7.2021, 22:08:58HOOBSWARNUNGA platform configured a external accessory under the plugin name "[object Object]". However no loaded plugin could be found for the name.

**Comment by emilmilow** [comment]
> Have the same issue under hoobs:
> 
> 18.7.2021, 22:08:58HOOBSBroadlinkRM[INFO] Automatic Broadlink RM device discovery has been disabled as the "hosts" option has been set.
> 18.7.2021, 22:08:58HOOBSBroadlinkRM[INFO] Running Bridge Broadlink RM Plugin version 4.4.5
> 18.7.2021, 22:08:58HOOBSBroadlinkRMBeamer Accessory Ready
> 18.7.2021, 22:08:58HOOBSBroadlinkRMSamsung Accessory Ready
> 18.7.2021, 22:08:58HOOBSWARNUNGA platform configured a external accessory under the plugin name "[object Object]". However no loaded plugin could be found for the name.
> 18.7.2021, 22:08:58HOOBSWARNUNGA platform configured a external accessory under the plugin name "[object Object]". However no loaded plugin could be found for the name.

@ash123-germany I found a workaround for now: Hoobs version 4+ is required. Create a new Bridge with Version 4.3.0 for this Plugin and just use it for the tvs. So currently I have 2 versions of the plugin running on 2 different bridges, once the latest version and once version 4.3.0. Hope it helps

**Comment by ash123-germany** [comment]
@zitrone475 
i tried it allready with 4.3.0 but then i get this:
18.7.2021, 22:53:47HOOBSBroadlinkRMBeamer getSwitchState: undefined
18.7.2021, 22:53:47HOOBSFEHLER[HOOBS F59F@Beamer@Beamer@On] characteristic value expected boolean and received undefined

**Comment by emilmilow** [comment]
> @zitrone475
> i tried it allready with 4.3.0 but then i get this:
> 18.7.2021, 22:53:47HOOBSBroadlinkRMBeamer getSwitchState: undefined
> 18.7.2021, 22:53:47HOOBSFEHLER[HOOBS F59F@Beamer@Beamer@On] characteristic value expected boolean and received undefined

@ash123-germany Yes, I get the error as well. But it works anyway

**Comment by ash123-germany** [comment]
Beamer is not visible in Hoobs and not in Home kit

**Comment by emilmilow** [comment]
Can you send me your config? And I had to re-add the bridge to Homekit

**Comment by ash123-germany** [comment]
Now  i get this:
18.7.2021, 23:40:49TestBroadlinkRMSamsung sendHex (192.168.178.51; A0::4:3::B0::4:6::7D::7:6) 26...............0
18.7.2021, 23:40:49TestFEHLER[Test E05B@Samsung@Samsung@Active] SET handler returned write response value, though the characteristic doesn't support write response

config:
Ill give up , it is with Hoobs 4 not possible to save the config json and neither possible to use copy and paste .

So ******* **** i will downgrade to former version, where all was running and never make an upgrade from Hoobs or others .

Never change a running system .

**Comment by PilchardFriendly** [comment]
I think I have a lead on this: 

#https://github.com/hoobs-org/HOOBS/issues/1352#issuecomment-885024305

I'll have a play and see if I can pass the right plugin identifier, rather than the platform as a whole. 

Note that I only saw this in my logs because I clicked the right button:

```23/07/2021, 1:07:24 amBroadlink Rm Pro BridgeBroadlinkRM[DEBUG] Adding Accessory tv (tv)
23/07/2021, 1:07:24 amBroadlink Rm Pro BridgeOne of your plugins incorrectly registered an external accessory using the platform name ([object Object]) and not the plugin identifier. Please report this to the developer!
23/07/2021, 1:07:24 amBroadlink Rm Pro BridgeWARNINGA platform configured a external accessory under the plugin name "[object Object]". However no loaded plugin could be found for the name.```

**Comment by PilchardFriendly** [comment]
So I got it working on my hoobs.  

```
diff --git a/platform.js b/platform.js
index 9714f00..2ed4eb5 100644
--- a/platform.js
+++ b/platform.js
@@ -91,7 +91,7 @@ const BroadlinkRMPlatform = class extends HomebridgePlatform {
     if (tvs.length > 0) {
       if (tvs.length > 0) {
         const TV = homebridgeRef.hap.Accessory.Categories.TELEVISION;
-        homebridgeRef.publishExternalAccessories(this, tvs.map(tv => createAccessory(tv, tv.name, TV, homebridgeRef, tv.subType)));
+        homebridgeRef.publishExternalAccessories('homebridge-broadlink-rm', tvs.map(tv => createAccessory(tv, tv.name, TV, homebridgeRef, tv.subType)));
 
         log('');
         log(`**************************************************************************************************************`);
```

And now I have a TV working in Apple Home.

**Comment by PilchardFriendly** [comment]
@kiwi-cam PR here #363

**Comment by emilmilow** [comment]
Amazing, thank you so much @PilchardFriendly 

I am looking forward to the PR being approved

**Comment by galbartal** [comment]
You literally saved my whole house @PilchardFriendly
Thanks!

**Comment by Cr0oky** [comment]
> So I got it working on my hoobs.

> And now I have a TV working in Apple Home.

@PilchardFriendly
Sorry PilchardFriendly,
i didn't understand how u managed to get tv in Hoobs.
I've upgraded from Hoobs 3.1 something to Hoobs 4 and now my Broadlink config is broken. 
I had 5 Tvs in my previous setting, could you explain me how can i re-add them to my config?
Thank You

**Comment by PilchardFriendly** [comment]
Yep - try plug-in version 4.4.6-beta.1.  That’s got the fix.

If you want to hack, have a look

**Comment by Cr0oky** [comment]
@PilchardFriendly where can i get the beta? Cannot find it under Hoobs broadlink plugins, i can find only beta 4.4.5 released on June 23rd

**Comment by PilchardFriendly** [comment]
Hmm.  I’m still working out hoobs caches these versions.  I can see the new
version in npm:
https://www.npmjs.com/package/homebridge-broadlink-rm-pro

**Comment by Cr0oky** [comment]
@PilchardFriendly 
Nevermind! For now I’ll stick on Hoobs previous versions! Just reflashed and downgraded; It’s been a pain to rebuild all automations/scenes and don’t want/have time/energy to mess around! I’ll wait for better days and releases (also because I have 5 fake TVs  configs settled up and don’t wanna lose them😉)

**Comment by PilchardFriendly** [comment]
I think I found out to upgrade the plugin - it's a bit behind the scenes, but I think it works, at least.

if you can ssh on the hoobs, you can run the following command line:

```sudo hbs bridge ls```

which gave me:

```id                   | type   | display                 | port  | pin        | username          | advertiser
-------------------------------------------------------------------------------------------------------------
hub                  | hub    | Hub                     | 80    | 031-45-154 | 08:3A:F0:99:32:23 |           
broadlinkrmprobridge | bridge | Broadlink Rm Pro Bridge | 52826 | 031-45-154 | 2A:3E:67:8D:3F:29 | bonjour   
```

so I then ran

``` sudo hbs plugin -b broadlinkrmprobridge ls```

this gave me the following: 

```name                        | version | path                                                                        
--------------------------------------------------------------------------------------------------------------------
homebridge-broadlink-rm-pro | 4.4.5   | /var/lib/hoobs/broadlinkrmprobridge/node_modules/homebridge-broadlink-rm-pro
```

then I ```cd /var/lib/hoobs/broadlinkrmprobridge```

and run 

```sudo yarn add homebridge-broadlink-rm-pro@4.4.6-beta.2```

which shows:

```yarn add v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning homebridge-broadlink-rm-pro@4.4.6-beta.2: The engine "homebridge" appears to be invalid.
warning fakegato-history@0.6.1: The engine "homebridge" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ homebridge-broadlink-rm-pro@4.4.6-beta.2
info All dependencies
└─ homebridge-broadlink-rm-pro@4.4.6-beta.2
Done in 6.18s.
```

A restart of the bridge should be enough to bring in the fix.  

Even if you don't do this, I'll leave this here for anyone else who comes across it.   It'll be much easier when we're on the proper 4.4.6 release.
