### ISSUE TITLE
Heater-cooler defaultNowTemperature enhancement

### ISSUE THREAD

**Issue by th3dogcow** [kiwi-cam/homebridge-broadlink-rm#361]
For those who don't have a broadlink device with a temperature sensor, I thought it would be nice visually if the  defaultNowTemperature value could be dynamically updated to reflect the current cooling to or heating to temperature. When the device were powered off, this could be set to 0 perhaps, too. It's just a small thing but it would be cool if it were made a possibility. Thanks for all the work btw.

**Comment by akkiankur** [comment]
I think that's a good idea. When off, I would rather see a default / user defined temperature than 0 which could be reflecting the local temp.
