### ISSUE TITLE
Not seeing tv in control panel all the time

### ISSUE THREAD

**Issue by fratinize** [kiwi-cam/homebridge-broadlink-rm#362]
This plug in works fine all of my codes/buttons function as expected. Love it, ty. 
I have three remotes with volume control. HDMI Switch, Stereo and Tiki Tunes. The tiles always show fine in homebridge and function.
My problem is, and I'm not really sure where to look; but many times when I go to change the volume, I open my iphone se 14.6 (still same issue since 13) control panel and I only see my air play devices (5 Apple TV's and 2 Roku TV's)
There are times I see 2 of my TV/remote. But many times I do not see them at all. Funny thing sometimes when I do not see them on my iPhone I check my wife's iPhone (10) or iPad (4) and sometimes they are there and work just fine, but at the same exact moment they do not show on my iPhone. This has also
Happened the other way shows and works on my phone but it's not even in my wife's. Am I
Missing something that keeps it alive? Times I reboot homebridge I will see it, other times no. I have also shut off my WiFi turned back on and wow there it is and it works and other times doesn't help. Thanx for any direction!

**Comment by kiwi-cam** [comment]
I see this too on occasion, but haven't really narrowed it down. I do find that if I open the Home app first so the devices can refresh, then I see the TVs 99% of the time.

Sorry I can't offer more.

**Comment by subokita** [comment]
I tried to add a dummy TV accessory (I wanted to control my Topping MX3 headphone amplifier), and it never shows up on HomeKit
But it shows up when I added it as a switch.

**Comment by timesl** [comment]
observed that when the device name is "tv", it won't show up in the homekit discovery, i have to change it to such as "LG" as a workaround. Probably the "tv" is a reserved word.

Also, the volume "up" or "down" is not functioning, i can only switch on/off the tv.
