### ISSUE TITLE
AC won’t turn on

### ISSUE THREAD

**Issue by FranciRoosters** [kiwi-cam/homebridge-broadlink-rm#365]
One of my two AC units won’t turn on even though the BroadLink mini’s led flashes. The other unit works fine. What should I do to fix this? Thank you for your kind support.

**Comment by kiwi-cam** [comment]
There are a few things I'd try:
1. Re-learn the codes in case something has changed there
2. Add `"debug": true` or `"logLevel": "debug"` to the accessory and confirm the expected codes are being sent
3. Update the plug-in in case there's a bug affecting it
