### ISSUE TITLE
Help with configuring multiple RM Pro 

### ISSUE THREAD

**Issue by 3DStyle** [kiwi-cam/homebridge-broadlink-rm#368]
Hi,

I have 3 Broadlink RM Pro devices in my house. I want to control each one of them by its IP in the config.
Can someone please share a config that is good for this application? Tried to play with the config but it didn't work for me.

Thanks!

**Comment by kiwi-cam** [comment]
This is a great example of what you're describing: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/config-multiple-rm-devices-sample.json. Basically, you just setup accessories like normal but add `"host": "IP Address"` to each one, specifying which device is to control that accessory.

**Comment by 3DStyle** [comment]
Thanks @kiwi-cam, it works flawlessly!

**Comment by 3DStyle** [comment]
Edit: I figured that out from the documentation. Thanks anyhow! 

Hi @kiwi-cam, can you please let me know how can I have a Learn button for each and every BroadlinkRM? 
I tried adding to each one of the accessories a ""hideLearnButton": false", but it doesn't seem to add them.
Currently there is only one Learn button for one specific BroadlinkRM. Am I doing something wrong here?
