### ISSUE TITLE
Config Humidifier

### ISSUE THREAD

**Issue by ChristianPorsche** [kiwi-cam/homebridge-broadlink-rm#37]
I copied the config example of the original plugin, but this plugin doesn't recognize it. Can you import the humidifier?

**Comment by ChristianPorsche** [comment]
Looks like you didn't fork the humidifier from the original fork, see config sample: https://github.com/lprhodes/homebridge-broadlink-rm/blob/master/config-sample.json

**Comment by ChristianPorsche** [comment]
Looks like you need to add this file:

https://github.com/lprhodes/homebridge-broadlink-rm/blob/master/accessories/humidifier-dehumidifier.js

**Comment by kiwi-cam** [comment]
Thanks @ChristianPorsche. This looks like an easy thing to add functionality. I'll try to get this introduced soon.

**Comment by kiwi-cam** [comment]
Sorry... this one slipped by while I was distracted with the RM4 devices. I've added all the new devices in the latest BETA. It'll be in v4.3.3.
