### ISSUE TITLE
multiple RM controllers Mini 4 and Pro problem

### ISSUE THREAD

**Issue by cyb3rDor** [kiwi-cam/homebridge-broadlink-rm#370]
Hello.
I built this json cnfg as explained in the descriptions. But the two devices don’t work together. The Pro is sending hexcode with the ip configure in host of the mini - so the pro doesn’t response on the HomeKit, the mini is responding because it transmitting on the right ip and MAC address . Can someone fix my code?
"accessories": [],
"platforms": [
    {
        "platform": "BroadlinkRM",
        "name": "Wi-Fi Universal Remote",
        "hideScanFrequencyButton": "false",
        "hideLearnButton": "false",
        "host": [
            {
                "address": "192.168.1.177",
                "mac": "a0:5u:b0:cu:fe:d4",
                "isRFSupported": true,
                "isRM4": true
            }
        ],
        "accessories": [
            {
                "name": "Salon air conditioner",
                "type": "switch",
                "data": {
                    "on": "260010010001058c360f1235123512351235123512341434350f123512351235360f350f133412351235360f123512353510350f1235123512351235123512351235123512341236123412351235123512351235123512351235123413341235360f360f123512351234123512351235123512351235123535101234360f35101235123512341235360003fd0001078c350f1235123512351235123512351235350f1235123512353510350f123512351235360f12351235350f360f12351235123512351234123612341235123512351235123512351235123512341235123512351235123512353510350f1235123512351235123512351235123512351235350f123535103510123412351235123535000d05000000000000",
                    "off": "260010010001058d3510113611351236113512351235113635101136123511363510341011361235113635101136113634103510113611361136123512351136123512351234123612341235123511361235113611361235123512351235123512351234360f3510123512351235123512351235123412351334360f351011363411123412351235360003fd0001068d35101235123412351334123512351235360f123511361235350f360f1235123512353510123512353410360f11361235123512351235123512351234123512351235123512351235123511361235123512351235123413351234123535103510113612351234133512341235123511361235360f35101136341012351136123535000d05000000000000"
                }
            }
        ]
    },
    {
        "platform": "BroadlinkRM",
        "name": "Broadlink mini",
        "hideLearnButton": "false",
        "hosts": [
            {
                "address": "192.168.1.187",
                "mac": "a0:43:b0:72:76:88",
                "isRM4": true
            }
        ],
        "accessories": [
            {
                "name": "Bedroom air conditioner",
                "type": "switch",
                "data": {
                    "on": "2600ca008d9112351211123512351211121112351211121211351212121112351234121211351235121111131135123512351135123512111136123412121211121112121112123512341212111212111212111212111212121111361234123512351234123512aa8f9112351211123512341212111211361211121112351212111212341235121112351235121112111235113612341235123511121235123412121211121112121112123512341212121111121113111212111113111212341235123511351235113612000d05000000000000000000000000",
                    "off": "2600ca008d9111361211113612351211111211361211111311351212111212351135121211351113123412351235113511131135113611351212111211131112123511121112123511351235121112121112121111131211111211131135113611361135123511ab8f9112351211113612351112121111361112111311351113111211351235121112351113113512351135123511131135123512341212111212111212123412121112123511351136111211131112111211131211121111131135123511361135113611000d05000000000000000000000000"
                }
            }
        ]
    },

**Comment by masterfordev** [comment]
Hello. You can see a config sample [here](https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/config-multiple-rm-devices-sample.json).

As you can see, when you add an accesory, this should have the "host" with the ip/mac of you RM.

**Comment by cyb3rDor** [comment]
This is what I did… look at my confg

**Comment by masterfordev** [comment]
No, you dont did that. You added 2 platform (and you have add only one). And didnt added the "host" on your accesory. See the sample, please.

**Comment by cyb3rDor** [comment]
I fixed it to this: but I get this on my status:  [15/08/2021, 13:37:43] [homebridge-broadlink-rm-pro] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info. And the HomeBridge is collapsing. 


On restart for 30 minutes and eventually collapsing and all the HomeBridge accessories are disable.

{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:0B:83:2A:Y1:7C",
        "port": 51671,
        "pin": "970-50-121"
    },
    "description": "Homebridge",
    "accessories": [],
    "platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "accessories": [
                {
                    "name": "Salon air conditioner",
                    "type": "switch",
                    "host": "192.168.1.187",
                    "data": {
                        "on": "260010010001058c360f1235123512351235123512341434350f123512351235360f350f133412351235360f123512353510350f1235123512351235123512351235123512341236123412351235123512351235123512351235123413341235360f360f123512351234123512351235123512351235123535101234360f35101235123512341235360003fd0001078c350f1235123512351235123512351235350f1235123512353510350f123512351235360f12351235350f360f12351235123512351234123612341235123512351235123512351235123512341235123512351235123512353510350f1235123512351235123512351235123512351235350f123535103510123412351235123535000d05000000000000",
                        "off": "260010010001058d3510113611351236113512351235113635101136123511363510341011361235113635101136113634103510113611361136123512351136123512351234123612341235123511361235113611361235123512351235123512351234360f3510123512351235123512351235123412351334360f351011363411123412351235360003fd0001068d35101235123412351334123512351235360f123511361235350f360f1235123512353510123512353410360f11361235123512351235123512351234123512351235123512351235123511361235123512351235123413351234123535103510113612351234133512341235123511361235360f35101136341012351136123535000d05000000000000"
                    }
                },
                {
                    "name": "Bedroom air conditioner",
                    "type": "switch",
                    "host": "192.168.1.187",
                    "data": {
                        "on": "2600ca008d9112351211123512351211121112351211121211351212121112351234121211351235121111131135123512351135123512111136123412121211121112121112123512341212111212111212111212111212121111361234123512351234123512aa8f9112351211123512341212111211361211121112351212111212341235121112351235121112111235113612341235123511121235123412121211121112121112123512341212121111121113111212111113111212341235123511351235113612000d05000000000000000000000000",
                        "off": "2600ca008d9111361211113612351211111211361211111311351212111212351135121211351113123412351235113511131135113611351212111211131112123511121112123511351235121112121112121111131211111211131135113611361135123511ab8f9112351211113612351112121111361112111311351113111211351235121112351113113512351135123511131135123512341212111212111212123412121112123511351136111211131112111211131211121111131135123511361135113611000d05000000000000000000000000"
                    }
                },
                {
                    "name": "TuyaWebPlatform",
                    "options": {
                        "username": "xxxxx",
                        "password": "xxxx",
                        "countryCode": "972",
                        "platform": "tuya"
                    },
                    "defaults": [
                        {
                            "id": "bfa910a3dbaf07a0b5hnhp",
                            "device_type": "light",
                            "light_characteristics": [
                                "Brightness",
                                "Color"
                            ]
                        }
                    ],
                    "scenes": false,
                    "platform": "TuyaWebPlatform"
                },
                {
                    "name": "Switcher Boiler",
                    "accessoryType": "switch",
                    "debug": false,
                    "secondsToRemove": 600,
                    "devices": [
                        {
                            "identifier": "192.168.1.212",
                            "accessoryType": "valve"
                        }
                    ],
                    "platform": "SwitcherBoiler"
                },
                {
                    "devices": [
                        {
                            "name": "Salon LG TV",
                            "ip": "192.168.1.109",
                            "mac": "78:5D:C8:3F:8F:7A",
                            "pollingInterval": 5,
                            "volumeLimit": 100,
                            "volumeControl": "slider",
                            "channelControl": true,
                            "mediaControl": false
                        }
                    ],
                    "platform": "webostv"
                },
                {
                    "auto_detect": false,
                    "hideWelcomeMessage": false,
                    "debug": true,
                    "hosts": [
                        {
                            "address": "192.168.1.187",
                            "mac": "a0:21:b0:72:76:44",
                            "isRM4": true
                        }
                    ]
                }
            ],
            "disabledPlugins": [
                "homebridge-broadlink-easy"
            ]
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}

**Comment by kiwi-cam** [comment]
Can you share the logs of it starting up? Usually when it's taking a long time to load it's trying to retrieve something it can't.

**Comment by Metatropics** [comment]
In case anyone's curious, this config for multiple RM4's works
```
{
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": true,
            "hideSwingMode": true,
            "hideWelcomeMessage": true,
  "hosts": [
                {
                    "address": "192.168.86.46",
                    "mac": "ec:0b:ae:99:2d:8d",
                    "isRFSupported": true,
                    "isRM4": true
                },
                {
                    "address": "192.168.86.50",
                    "mac": "ec:0b:ae:9f:df:27",
                    "isRFSupported": true,
                    "isRM4": true
                }
            ],
            "accessories": [
                {
                    "name": "Master Bedroom Fan",
                    "type": "fan",
                    "host": "192.168.86.46",
                    "hideRotationDirection": true,
                    "stepSize": 100,
                    "speedSteps": 2,
                    "data": {
                        "on": "26009200270f27100b2a280e27100b2b0b2a0d290d2a0b2b0b2b27ea260f280e0d292710270f0c290d2a0c2a0b2b0c2b0d2827e9280e27100b2b260f280f0c2a0b2b0c2a0c2a0c2a0e2827e92710270f0c2a270f26100c2a0c2a0c2a0c2a0c2a0c2b26ea260f280e0d2a2610270f0c2a0c2a0b2b0c2a0c2a0c2a28e8280e27100b2b270e280f0c2a0b2b0c2a0c2a0c2a0d2927000d0500000000",
                        "off": "26009200270f27100b2a280e27100b2b0b2a0d290d2a0b2b0b2b27ea260f280e0d292710270f0c290d2a0c2a0b2b0c2b0d2827e9280e27100b2b260f280f0c2a0b2b0c2a0c2a0c2a0e2827e92710270f0c2a270f26100c2a0c2a0c2a0c2a0c2a0c2b26ea260f280e0d2a2610270f0c2a0c2a0b2b0c2a0c2a0c2a28e8280e27100b2b270e280f0c2a0b2b0c2a0c2a0c2a0d2927000d0500000000",
                        "swingToggle": "2600d000260e290e0d29270f280e0d290c2a0c2a0d2a0b2a270f0d0001032710270f0c29280e280f0c2a0b2a0d290d2a0b2b260f0e000102280f280e0d29270f280e0d290d290c2a0c2a0c2a270f0d0001032710270e0e28270f280f0c290c2a0d290c2b0b2b270e0e000102280f270f0e28270e290e0d290b2b0c2a0c2a0c2a270f0d000103270f290d0e28270f280f0c290c2a0c2b0b2b0b2a280e0e0001022710280e0d28280f280e0d290c2a0d290c2a0f2727100c000104260f290d0e282710280d0e280d290c2b0b2b0b2a280f0c000d05000000000000"
                    }
                },
                {
                    "name": "TV IR",
                    "type": "switch",
                    "host": "192.168.86.46",
                    "stateless": true,
                    "data": {
                        "on": "2600d2008d9112361236113613111213111311131211133611361236121212131014111213111311123711131112131113111312101411361311133610371335123610381236120005c18e9111361435123514101212121213121014123512371235131113111113121212121113123613121211121212121410131112361311113713351335133412371136140005bf8e901137143415331212141011131410121212361336113512131014121213111211121314341311121113111411111311131136141111371334113713351235133611000d0500000000"
                    }
                },
              {
                    "name": "Adrian's Room Fan",
                    "type": "fan",
                    "host": "192.168.86.50",
                    "hideRotationDirection": true,
                    "data": {
                        "on": "26009200270f27100b2a280e27100b2b0b2a0d290d2a0b2b0b2b27ea260f280e0d292710270f0c290d2a0c2a0b2b0c2b0d2827e9280e27100b2b260f280f0c2a0b2b0c2a0c2a0c2a0e2827e92710270f0c2a270f26100c2a0c2a0c2a0c2a0c2a0c2b26ea260f280e0d2a2610270f0c2a0c2a0b2b0c2a0c2a0c2a28e8280e27100b2b270e280f0c2a0b2b0c2a0c2a0c2a0d2927000d0500000000",
                        "off": "26009200270f27100b2a280e27100b2b0b2a0d290d2a0b2b0b2b27ea260f280e0d292710270f0c290d2a0c2a0b2b0c2b0d2827e9280e27100b2b260f280f0c2a0b2b0c2a0c2a0c2a0e2827e92710270f0c2a270f26100c2a0c2a0c2a0c2a0c2a0c2b26ea260f280e0d2a2610270f0c2a0c2a0b2b0c2a0c2a0c2a28e8280e27100b2b270e280f0c2a0b2b0c2a0c2a0c2a0d2927000d0500000000"
                    }
                },
                {
                    "name": "Adrian's Room Learn",
                    "type": "learn-code",
                    "host": "192.168.86.50"
                },
                {
                    "name": "Master Bedroom Learn",
                    "type": "learn-code",
                    "host": "192.168.86.46"
                }
            ],
            "_bridge": {
                "username": "0E:48:F2:C9:B3:31",
                "port": 41654
            }
        }
```

**Comment by hepcat72** [comment]
This issue seems the closest one related to my issue, so hopefully this can be re-opened?  I previously commented [here](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/335#issuecomment-1519113241), but I will quote that comment here:

> I'm having this issue right now. It started after I did 2 things at once: I set up a second RM mini 3 and added an outlet to my Vesync V2 plugin. I was on an older version of the plugin and updated to version 4.4.11 which did not solve the issue.
> 
> At first, I guessed at how to setup a second RM mini 3 device (by duplicating the BroadlinkRM config with a different "name" - thinking it was finding the device by name).
> 
> Another possible aspect is... I could not add the new RM mini 3 to my e-control app, so I installed the "Broadlink" app and added the new RM mini 3 to it. So each RM mini 3 is setup in 2 different apps. I had to create a new broadlink account because the one I use for e-control did not allow me to login to the Broadlink app (using "forgot password" said I didn't have an account).
> 
> I'm still in the beginning stages of figuring this out. If I find out anything more, I will let you know.

I have debugged this issue to the point where I gave up (at least for this weekend, and will tackle it again at some later point).

Some added details:

I was previously on version 4.4.6.  After upgrading to 4.4.11, I noted the following error in the log:
```
[4/23/2023, 1:18:34 PM] The plugin "homebridge-broadlink-rm-pro" requires a Homebridge version of >=1.4.1 which does not satisfy the current Homebridge version of 1.3.6. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
```
I also get this error:
```
(node:9838) UnhandledPromiseRejectionWarning: Error: Each accessory must be configured with a "type". e.g. "switch"
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/platform.js:71:35
    at Array.forEach (<anonymous>)
    at BroadlinkRMPlatform.addAccessories (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/platform.js:70:24)
    at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/base/platform.js:60:16)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:534:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:528:12)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:445:42
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9838) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[4/23/2023, 1:18:43 PM] [Broadlink RM] [INFO] Discovered Manual RM Device (2221) at 192.168.1.61 (c8:f7:42:16:f7:7f)
[4/23/2023, 1:18:43 PM] [Broadlink RM] [INFO] Discovered Manual RM Device (2221) at 192.168.1.168 (24:df:a7:36:54:9a)
```
I wasn't prepared to tackle upgrading Homebridge, currently on `v1.3.6`, so I downgraded back to `4.4.6` and no longer see that error in the log.

I don't see either error in 4.4.6, but the failure to startup occurred in both versions.

Here is my config:
```
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "hosts": [
                {
                    "address": "192.168.1.61",
                    "mac": "c8:f7:42:16:f7:7f",
                    "isRFSupported": false,
                    "isRM4": false
                },
                {
                    "address": "192.168.1.168",
                    "mac": "24:df:a7:36:54:9a",
                    "isRFSupported": false,
                    "isRM4": false
                }
            ],
            "accessories": [
                {
                    "name": "Bedroom Window Fan",
                    "host": "192.168.1.168",
                    "type": "outlet",
                    "allowResend": true,
                    "data": {
                        "on": "2600f200240e290...",
                        "off": "2600f200240e290e0d2..."
                    }
                },
                {
                    "name": "Bedroom Fan Speed Toggler",
                    "host": "192.168.1.168",
                    "allowResend": true,
                    "data": {
                        "type": "outlet",
                        "on": "26000401240d2a...",
                        "off": "26000401240d2a..."
                    }
                },
                {
                    "name": "Bedroom Fan Direction Toggler",
                    "host": "192.168.1.168",
                    "type": "outlet",
                    "allowResend": true,
                    "data": {
                        "on": "2600ea00230e290e0e2...",
                        "off": "2600ea00230e290e..."
                    }
                },
                {
                    "name": "Air Conditioner",
                    "host": "192.168.1.61",
                    "type": "outlet",
                    "allowResend": true,
                    "data": {
                        "on": "2600580000012...",
                        "off": "2600580000012694..."
                    }
                },
                {
                    "name": "TV",
                    "host": "192.168.1.61",
                    "type": "outlet",
                    "allowResend": true,
                    "data": {
                        "on": "26004e00211921...",
                        "off": "26004e00211921..."
                    }
                },

...
```
I was able to get homebridge to successfully start up by completely removing the new RM mini 3 (and all references to "host"), such that it now looks like this:
```
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "accessories": [
                {
                    "name": "Air Conditioner",
                    "host": "192.168.1.61",
                    "type": "outlet",
                    "allowResend": true,
                    "data": {
                        "on": "2600580000012...",
                        "off": "2600580000012694..."
                    }
                },
                {
                    "name": "TV",
                    "host": "192.168.1.61",
                    "type": "outlet",
                    "allowResend": true,
                    "data": {
                        "on": "26004e00211921...",
                        "off": "26004e00211921..."
                    }
                },

...
```

**Comment by hepcat72** [comment]
Ah geez. OK.  I was missing the "type" in one of the accessory settings.  I guess it would be nice for dolts like me if loading of the plugin would just fail at that exception so it doesn't prevent everything else from working.
