### ISSUE TITLE
Multiple Broadlink RM, secondary RM Pro+ crashes on RF blasts

### ISSUE THREAD

**Issue by slurpera** [kiwi-cam/homebridge-broadlink-rm#371]
I have a main RM4 Pro (653c) and a secondary RM3 Pro+ (279d).

I have two identical RF blind motors that I wish to control through the two devices respectively. Using the main RM4 Pro I am able to send out the RF commands with no issues. However, if I send the RF commands through the RM Pro+, the device crashes after sending the commands (that do work) and then becomes unresponsive with the amber light on.

Just for context, the RM Pro+ is able to send RF commands through the Broadlink app with no issues. Only the homebridge RF commands crashes the device on the very first RF command. IR commands work normally for both app and homebridge.

Also, logs do not show anything out of the ordinary and will continue acknowledging further commands even when the RM Pro+ is stuck.

Anyone else seeing this issue? Many thanks in advance.

Here are my relevant configs.

{
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "persistState": false,
            "hideWelcomeMessage": true,
            "hosts": [
                {
                    "address": "192.168.68.25",
                    "mac": "a0:43:b0:32:cf:60",
                    "isRFSupported": true,
                    "isRM4": true
                },
                {
                    "address": "192.168.68.33",
                    "mac": "78:0f:77:63:8a:c1",
                    "isRFSupported": true,
                    "isRM4": false
                }
            ],
            "accessories": [           
                {
                    "name": "Window Shades Open",
                    "type": "switch",
                    "host": "a0:43:b0:32:cf:60",
                    "resendHexAfterReload": false,
                    "enableAutoOff": true,
                    "onDuration": 0.5,
                    "data": {
                        "on": "RF CODE",
                        "sendcount": 2,
                        "interval": 0.3
                    }
                },
                {
                    "name": "Window Shades Close",
                    "type": "switch",
                    "host": "a0:43:b0:32:cf:60",
                    "resendHexAfterReload": false,
                    "enableAutoOff": true,
                    "onDuration": 0.5,
                    "data": {
                        "on": "RF CODE",
                        "sendcount": 2,
                        "interval": 0.3
                    }
                },
                {
                    "name": "Window Shades Stop",
                    "type": "switch",
                    "host": "a0:43:b0:32:cf:60",
                    "resendHexAfterReload": false,
                    "enableAutoOff": true,
                    "onDuration": 0.5,
                    "data": {
                        "on": "RF CODE",
                        "sendcount": 2,
                        "interval": 0.3
                    }
                },
                {
                    "name": "Back Shades Open",
                    "type": "switch",
                    "host": "78:0f:77:63:8a:c1",
                    "resendHexAfterReload": false,
                    "enableAutoOff": true,
                    "onDuration": 0.5,
                    "data": {
                        "on": "RF CODE",
                        "sendcount": 2,
                        "interval": 0.3
                    }
                },
                {
                    "name": "Back Shades Close",
                    "type": "switch",
                    "host": "78:0f:77:63:8a:c1",
                    "resendHexAfterReload": false,
                    "enableAutoOff": true,
                    "onDuration": 0.5,
                    "data": {
                        "on": "RF CODE",
                        "sendcount": 2,
                        "interval": 0.3
                    }
                },
                {
                    "name": "Back Shades Stop",
                    "type": "switch",
                    "host": "78:0f:77:63:8a:c1",
                    "resendHexAfterReload": false,
                    "enableAutoOff": true,
                    "onDuration": 0.5,
                    "data": {
                        "on": "RF CODE",
                        "sendcount": 2,
                        "interval": 0.3
                    }
                },

**Comment by kiwi-cam** [comment]
It's a long shot but, is it any better if you let the plug-in auto discover the devices? I.e. delete the hosts section.

**Comment by slurpera** [comment]
Yeah, I tried that. Same thing. I did try disconnecting the RM4 and just running with the RM3, but it still hangs on rf commands. Weird.
