### ISSUE TITLE
help broadlink plug bug "humidity"

### ISSUE THREAD

**Issue by cyb3rDor** [kiwi-cam/homebridge-broadlink-rm#372]
hello,

1.im getting this message every 10 seconds: "[18/08/2021, 17:59:19] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info." ן double check my json (don't see a problem) - please tell me why it's happening:

(I deleted the hexcodes because post must be under 4000 )

"platforms": [
{
"platform": "BroadlinkRM",
"name": "Wi-Fi Universal Remote",
"hideScanFrequencyButton": "true",
"hideLearnButton": "true",
"hosts": [
{
"address": "192.168.1.176",
"mac": "a0:43:b0:b8:fe:c1",
"isRFSupported": true,
"isRM4": true
},
{
"address": "192.168.1.186",
"mac": "a0:43:b0:72:76:77",
"isRM4": true
}
],
"accessories": [
{
"name": "Salon air conditioner",
"type": "switch",
"host": "a0:43:b0:b8:fe:c1",
"data": {
"on": "",
"off": ""
}
},
{
"name": "Bedroom air conditioner",
"type": "switch",
"host": "a0:43:b0:72:76:77",
"data": {
"on": "",
"off": ""
}
},
{
"name": "Bedroom air conditioner light and speed",
"type": "switch",
"host": "a0:43:b0:72:76:88",
"data": {
"on": "",
"off": ""
}
},
{
"name": "Salon Air Conditioner",
"type": "air-conditioner",
"host": "a0:43:b0:b8:fe:c1",
"minTemperature": 16,
"maxTemperature": 30,
"defaultCoolTemperature": 25,
"defaultHeatTemperature": 27,
"data": {
"off": "",
"cool16": {
"pseudo-mode": "cool",
"data": ""
},
"cool17": {
"pseudo-mode": "cool",
"data": ""
},
"cool18": {
"pseudo-mode": "cool",
"data": ""
},
"cool19": {
"pseudo-mode": "cool",
"data": ""
},
"cool20": {
"pseudo-mode": "cool",
"data": ""
},
"auto16": {
"pseudo-mode": "auto",
"data": ""
},
"auto17": {
"pseudo-mode": "auto",
"data": ""
},
"auto18": {
"pseudo-mode": "auto",
"data": ""
},
"auto19": {
"pseudo-mode": "auto",
"data": ""
},
"auto20": {
"pseudo-mode": "auto",
"data": ""
},
"auto21": {
"pseudo-mode": "auto",
"data": ""
},
"auto22": {
"pseudo-mode": "auto",
"data": ""
},
"auto23": {
"pseudo-mode": "auto",
"data": ""
},
"auto24": {
"pseudo-mode": "auto",
"data": ""
},
"auto25": {
"pseudo-mode": "auto",
"data": ""
},
"auto26": {
"pseudo-mode": "auto",
"data": ""
},
"auto27": {
"pseudo-mode": "auto",
"data": ""
},
"auto28": {
"pseudo-mode": "auto",
"data": ""
},
"auto29": {
"pseudo-mode": "auto",
"data": ""
},
"auto30": {
"pseudo-mode": "auto",
"data": ""
},
"cool21": {
"pseudo-mode": "cool",
"data": ""
},
"cool22": {
"pseudo-mode": "cool",
"data": ""
},
"cool23": {
"pseudo-mode": "cool",
"data": ""
},
"cool24": {
"pseudo-mode": "cool",
"data": ""
},
"cool25": {
"pseudo-mode": "cool",
"data": ""
},
"cool26": {
"pseudo-mode": "cool",
"data": ""
},
"heat16": {
"pseudo-mode": "heat",
"data": ""
},
"heat17": {
"pseudo-mode": "heat",
"data": ""
},
"heat18": {
"pseudo-mode": "heat",
"data": ""
},
"heat19": {
"pseudo-mode": "heat",
"data": ""
},
"heat20": {
"pseudo-mode": "heat",
"data": ""
},
"heat21": {
"pseudo-mode": "heat",
"data": ""
},
"heat22": {
"pseudo-mode": "heat",
"data": ""
},
"heat23": {
"pseudo-mode": "heat",
"data": ""
},
"heat24": {
"pseudo-mode": "heat",
"data": ""
},
"heat25": {
"pseudo-mode": "heat",
"data": ""
},
"heat26": {
"pseudo-mode": "heat",
"data": ""
},
"heat27": {
"pseudo-mode": "heat",
"data": ""
},
"heat28": {
"pseudo-mode": "heat",
"data": ""
},
"heat29": {
"pseudo-mode": "heat",
"data": ""
},
"heat30": {
"pseudo-mode": "heat",
"data": ""
}
}
},
{
"name": "Bedroom Air Conditioner",
"type": "air-conditioner",
"host": "a0:43:b0:72:76:77",
"minTemperature": 17,
"maxTemperature": 30,
"defaultCoolTemperature": 25,
"defaultHeatTemperature": 27,
"data": {
"off": "",
"cool17": {
"pseudo-mode": "cool",
"data": ""
},
"cool18": {
"pseudo-mode": "cool",
"data": ""
},
"cool19": {
"pseudo-mode": "cool",
"data": ""
},
"cool20": {
"pseudo-mode": "cool",
"data": ""
},
"auto17": {
"pseudo-mode": "auto",
"data": ""
},
"auto18": {
"pseudo-mode": "auto",
"data": ""
},
"auto19": {
"pseudo-mode": "auto",
"data": ""
},
"auto20": {
"pseudo-mode": "auto",
"data": ""
},
"auto21": {
"pseudo-mode": "auto",
"data": ""
},
"auto22": {
"pseudo-mode": "auto",
"data": ""
},
"auto23": {
"pseudo-mode": "auto",
"data": ""
},
"auto24": {
"pseudo-mode": "auto",
"data": ""
},
"auto25": {
"pseudo-mode": "auto",
"data": ""
},
"auto26": {
"pseudo-mode": "auto",
"data": ""
},
"auto27": {
"pseudo-mode": "auto",
"data": ""
},
"auto28": {
"pseudo-mode": "auto",
"data": ""
},
"auto29": {
"pseudo-mode": "auto",
"data": ""
},
"auto30": {
"pseudo-mode": "auto",
"data": ""
},
"cool21": {
"pseudo-mode": "cool",
"data": ""
},
"cool22": {
"pseudo-mode": "cool",
"data": ""
},
"cool23": {
"pseudo-mode": "cool",
"data": ""
},
"cool24": {
"pseudo-mode": "cool",
"data": ""
},
"cool25": {
"pseudo-mode": "cool",
"data": ""
},
"cool26": {
"pseudo-mode": "cool",
"data": ""
},
"heat17": {
"pseudo-mode": "heat",
"data": ""
},
"heat18": {
"pseudo-mode": "heat",
"data": ""
},
"heat19": {
"pseudo-mode": "heat",
"data": ""
},
"heat20": {
"pseudo-mode": "heat",
"data": ""
},
"heat21": {
"pseudo-mode": "heat",
"data": ""
},
"heat22": {
"pseudo-mode": "heat",
"data": ""
},
"heat23": {
"pseudo-mode": "heat",
"data": ""
},
"heat24": {
"pseudo-mode": "heat",
"data": ""
},
"heat25": {
"pseudo-mode": "heat",
"data": ""
},
"heat26": {
"pseudo-mode": "heat",
"data": ""
},
"heat27": {
"pseudo-mode": "heat",
"data": ""
},
"heat28": {
"pseudo-mode": "heat",
"data": ""
},
"heat29": {
"pseudo-mode": "heat",
"data": ""
},
"heat30": {
"pseudo-mode": "heat",
"data": ""
}
}
}
]
},

2. All of the hexcode in the air conditioner are combined with type-power-degreses example: cold-low-20c. Is there a way to control the fan power?

**Comment by cyb3rDor** [comment]
I don't have any humidity sensor, anyone? @kiwi-cam

**Comment by kiwi-cam** [comment]
If you don't have a broadlink sensor you need to provide another temperature source. Assuming MQTT and File sources aren't options try adding `"pseudoDeviceTemperature": 20` to your aircon accessories.

**Comment by cyb3rDor** [comment]
it worked! thank you...
