### ISSUE TITLE
There are couple of typos in the documentation

### ISSUE THREAD

**Issue by Botary** [kiwi-cam/homebridge-broadlink-rm#374]
**Describe the bug**
The documentation has 

`deHumifierOnly` instead of `deHumidifierOnly`
and
`humifierOnly` instead of `humidifierOnly`

<img width="327" alt="homebridge-broadlink-rm" src="https://user-images.githubusercontent.com/17464685/130250162-b7a71f73-7eca-4b4c-ab43-49a6ad0149ea.png">

**Comment by kiwi-cam** [comment]
Thanks. These are corrected now.
