### ISSUE TITLE
can issue number #372 be re-opened please ?

### ISSUE THREAD

**Issue by turbidWaters** [kiwi-cam/homebridge-broadlink-rm#377]
Getting the following error message every 10 seconds:

`[31/8/2021, 10:09:12 pm] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.`

What am I doing wrong? Please help. Thanks in advance.

config.json file pasted below here (note that i have masked the mac addresses with xx:xx and I have included only the portions relevant to this plug-in)

"platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "isRFSupported": true,
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "accessories": [
                {
                    "name": "Living Room AC Learn",
                    "type": "learn-code",
                    "host": "34:ea:xx:xx:37:d0"
                },
                {
                    "name": "Bedroom Learn",
                    "type": "learn-code",
                    "host": "34:ea:xx:xx:f1:28"
                },
                {
                    "name": "Mini Learn",
                    "type": "learn-code",
                    "host": "34:ea:34:xx:xx:e7"
                },
                {
                    "name": "Study Learn",
                    "type": "learn-code",
                    "host": "34:ea:34:xx:xx:18"
                },
                {
                    "name": "Living Climate Control",
                    "type": "switch",
                    "host": "34:ea:34:xx:xx:d0",
                    "persistState": true,
                    "data": {
                        "off": "",
                        "on": ""
                    }
                },
                {
                    "name": "Living Room AC",
                    "type": "air-conditioner",
                    "preventResendHex": false,
                    "host": "34:ea:34:xx:xx:d0",
                    "temperatureUpdateFrequency": 30,
                    "temperatureAdjustment": -2,
                    "heatTemperature": 27,
                    "minTemperature": 0,
                    "maxTemperature": 50,
                    "autoCoolTemperature": 27,
                    "autoHeatTemperature": 19,
                    "defaultCoolTemperature": 23,
                    "defaultHeatTemperature": 30,
                    "minimumAutoOnOffDuration": 420,
                    "turnOnWhenOff": true,
                    "sendTemperatureOnlyWhenOff": false,
                    "ignoreTemperatureWhenOff": false,
                    "autoSwitch": "Living Climate Control",
                    "data": {
                        "off": "26004000000117881333130f13101310123313101111131013321332131013101012140f1211130f131013101310101213101332130f1333121110131210133213000d050000000000000000",
                        "on": "260040000001178710351012140f11111432130f1112140e1112140e1310140f1012140f1012140f14311012140f103510121530150e140f123314311013133211000d050000000000000000",
                        "temperature30": {
                            "pseudo-mode": "heat",
                            "data": "26004000000117881333130f13101310123313101111131013321332131013101012140f1211130f131013101310101213101332130f1333121110131210133213000d050000000000000000"
                        },
                        "temperature29": {
                            "pseudo-mode": "heat",
                            "data": "26004400050003450001148a103511111211111211331310111212101112111112111012123313101211111210351035103510131111101212111112111110351134111211000d0500000000"
                        },
                        "temperature28": {
                            "pseudo-mode": "heat",
                            "data": "26003c00103510121211121111331310111112111112121012111012123312111112111111351035101212331211111112111211101211341112103511000d05000000000000000000000000"
                        },
                        "temperature27": {
                            "pseudo-mode": "heat",
                            "data": "2600400000011589103511121210111211341112101212111111121112101112113411121210121110351035101212111012121111121012121111341013111111000d050000000000000000"
                        },
                        "temperature26": {
                            "pseudo-mode": "cool",
                            "data": "2600400000011589113510121112111111341211101212111111111212111012123312111112111110351112123311341210131010121310111211121035103510000d050000000000000000"
                        },
                        "temperature25": {
                            "pseudo-mode": "cool",
                            "data": "260040000001148a113410121211111211341210111212111111121112101112113411111211111210351012123312111111121112111012121111111234111111000d050000000000000000"
                        },
                        "temperature24": {
                            "pseudo-mode": "cool",
                            "data": "2600400000011589113411111211111211341210111212111111111212101112123312101211111210351012121110351012121111121111111211121111113412000d050000000000000000"
                        },
                        "temperature23": {
                            "pseudo-mode": "cool",
                            "data": "260040000001148a113411121210121111341211101212111111121112111012113412111210121110351012121110121211111211111112121011121112111111000d050000000000000000"
                        },
                        "temperature22": {
                            "pseudo-mode": "cool",
                            "data": "260040000001148a103511111211111211341210111212101112111113101111133212111211111210121134123312341111101211121013113411341035103511000d050000000000000000"
                        },
                        "temperature21": {
                            "pseudo-mode": "cool",
                            "data": "260040000001168a103511121210121110351211101211121111121111111112123312111111121110121233113412111211101212111013113410351134101311000d050000000000000000"
                        },
                        "temperature20": {
                            "pseudo-mode": "cool",
                            "data": "260040000001148a113411121210121111341211101212111111121112111012123311121210121110121233111211341111121111121013103411351111123312000d050000000000000000"
                        },
                        "temperature19": {
                            "pseudo-mode": "cool",
                            "data": "26004400080007370001148a113412111211111112331211101211121111121112111012123311121112101210121233121111111211121110121211113411341112111211000d0500000000"
                        },
                        "temperature18": {
                            "pseudo-mode": "cool",
                            "data": "2600400000011589123410121211121011341112121011121111121112111012123312111112101310111310113411341211121013101013103511121134103510000d050000000000000000"
                        }
                    }
                },
                {
                    "name": "Study Climate Control",
                    "type": "switch",
                    "host": "34:ea:34:xx:xx:18",
                    "persistState": true,
                    "data": {
                        "off": "2600580000012a91141214111511151115111511141214351435143514351435143515341534151114121435141214111534151115111511153415111534153415111435153415341500050500012a4715000c3b0001294715000d05",
                        "on": "2600580000012a91141214111511151115111511141214351435143514351435143515341534151114121435141214111534151115111511153415111534153415111435153415341500050500012a4715000c3b0001294715000d05"
                    }
                },
                {
                    "name": "Study Room AC",
                    "type": "air-conditioner",
                    "preventResendHex": false,
                    "host": "34:ea:34:xx:xx:18",
                    "temperatureUpdateFrequency": 90,
                    "temperatureAdjustment": -1,
                    "heatTemperature": 27,
                    "minTemperature": 0,
                    "maxTemperature": 50,
                    "autoCoolTemperature": 26,
                    "autoHeatTemperature": 21,
                    "defaultCoolTemperature": 22,
                    "defaultHeatTemperature": 30,
                    "minimumAutoOnOffDuration": 420,
                    "turnOnWhenOff": true,
                    "sendTemperatureOnlyWhenOff": false,
                    "ignoreTemperatureWhenOff": false,
                    "autoSwitchName": "Study Climate Control",
                    "data": {
                        "off": "2600920000012992173516111711161117351711163517111611173517351635171117101711171116111711161117111611173517111611171116111711161117351711163517111611173517111600028e1735171116111711163517111611171117101711171116111711163517111711161117111611171116111711161117111711161117111611171116111735173516000d05000000000000",
                        "on": "260040000001178710351012140f11111432130f1112140e1112140e1310140f1012140f1012140f14311012140f103510121530150e140f123314311013133211000d050000000000000000",
                        "temperature30": {
                            "pseudo-mode": "heat",
                            "data": "260092000001279414371513141315371537141316361414141316361437173515131413151314131513141414131414141315371437151314141413151314131636141414371513141315371414140002901537141315131414143715131413151316121413141414131513143715131413151314141611151314131513141315131413151314141413151314131537141315000d05000000000000"
                        },
                        "temperature29": {
                            "pseudo-mode": "heat",
                            "data": "2600920000012790193516121611163616361611163616111735161216351735161216111612161116121611171116121611163616351711161216111612171116351711163616121611163616111600028f1636161116121611173516121611161216111612161117111611173516121611161216111711161117111612161116121611161216111711163616351612161117000d05000000000000"
                        },
                        "temperature28": {
                            "pseudo-mode": "heat",
                            "data": "2600920000012991173517101711163517351711173417111611171116361635171116111711171116111711171016121710173517351710171116111711161118341612163517111611173516121600028e1735161118101612163517111611171116111711171117101612163517111710171116121611161217101711171017111611181017111611161216351711161118000d05000000000000"
                        },
                        "temperature27": {
                            "pseudo-mode": "cool",
                            "data": "260092000001269415371513141315371438141315371413153714381413153714141413141414131513141315131413151314381437151314131612141415131438141315371413151314381413150002901437151314141413163614131513141315131414141315131611153714131513161214131513141315131413151314131513161214131513143715131413161214000d05000000000000"
                        },
                        "temperature26": {
                            "pseudo-mode": "cool",
                            "data": "2600920000012992163614131612163517351612163515131612163516121635171114131711161216111612161116121611153716361611161216111612141316361612163516121413163616121600028e1636161216111612143715131413161216121611161216111612163516121612161116121611151316111612161117111612161114141611161216111612161116000d05000000000000"
                        },
                        "temperature25": {
                            "pseudo-mode": "cool",
                            "data": "260092000001269415371513141315371438141315371413153714141413153714131513141315131414141315131413151314371537141414131513141315131438141314381413151314381413150002901437151314141413153714131513141315131414141315131413153714131513141414131513141315131413151314131513141414131414143715371438143715000d05000000000000"
                        },
                        "temperature24": {
                            "pseudo-mode": "cool",
                            "data": "260092000001279414371513141414371537141414371513141315131413153714141413151314131513141315131414141314381437151314141413141414131537141315371414141315371413150002901537141315131413153715131413151314131513141414131414143715131413151314141413151314131513141315131413151314141413141414371537143814000d05000000000000"
                        },
                        "temperature23": {
                            "pseudo-mode": "cool",
                            "data": "260092000001269414381413151314371537151314371513143715371537141315131414141315131413151314131513141315371537141315131413151314141437151314371513141414371513140002911437151314131513143814131513141315131413151314141413143814131513141315131414141314141413151314131513141315131414143715131437153714000d05000000000000"
                        },
                        "temperature22": {
                            "pseudo-mode": "cool",
                            "data": "2600920000012892173417111711163517351711163517111611173517351611171116111711171017111711161117111611173517341711171116111711161117351711163517111611173517111600028e1735171017111711163517111611171116111711171116111711163517111611171117111611171116111711161117111611171117111611171116111735163517000d05000000000000"
                        },
                        "temperature21": {
                            "pseudo-mode": "cool",
                            "data": "2600920000012991183417111710183417351710173517101834171117341810171018101711171016121611171117101810173418341711171018101710181017351710173517101810173517101700028e1735171017111710173517111710171117101711171017111710183417111710171117101711171018101711171017111710171117101810173517341711173417000d05000000000000"
                        },
                        "temperature20": {
                            "pseudo-mode": "cool",
                            "data": "2600920000012892173516121611163616361611163616111612161117351612161116121611161216111711161216111612163516361611171116121611161216351711163616111612163517111600028f1635171117101711163616111711161117111611171116121611163616111711161117111612161116121611161216111711161117111710181017351611173516000d05000000000000"
                        },
                        "temperature19": {
                            "pseudo-mode": "cool",
                            "data": "2600920000012893163517111612163516361612163516121635173516121611161216111612161117111611171116121611163616351711161216111612161116361611173516121611163616111700028e1636161117111612163516121611161216111612161117111612163516121611171116111711161216111612161116121611171116111711163616111612163517000d05000000000000"
                        },
                        "temperature18": {
                            "pseudo-mode": "cool",
                            "data": "2600920000012991183417101711173517341810173517101711173418101710181017111710171117101711171018101710183417351710181017101810171117341711173418101711173417111700028e1734171117101810173517101711171017111710181017101810173517101711171018101710181017111710171117101711171018101710181017111710173517000d05000000000000"
                        },
                        "temperature17": {
                            "pseudo-mode": "cool",
                            "data": "2600920000012892163616111711163616351711163616111636161117111611171116121611161216111711161117111611173516361611171116111711161216351612163517111611173517111600028f1635161216111711163616111612161117111611171116111711163616111711161117111611171116121611171116111711171017111710183416361635181016000d05000000000000"
                        },
                        "temperature16": {
                            "pseudo-mode": "cool",
                            "data": "260092000001269415371413151314381437151314371513141414131513141315131413151314141413141414131513141315371438141315131413151314131537141414371513141315371414140002901537141414131513143715131413151314141413141414131513143715131414141314141413151314131513141315131414141314141413151314371537141414000d05000000000000"
                        }
                    }
                },
                {
                    "name": "Bedroom Climate Control",
                    "type": "switch",
                    "host": "34:ea:34:xx:xx:28",
                    "persistState": true,
                    "data": {
                        "off": "",
                        "on": ""
                    }
                },
                {
                    "name": "BedRoom AC",
                    "type": "air-conditioner",
                    "host": "34:ea:34:xx:xx:28",
                    "preventResendHex": false,
                    "temperatureUpdateFrequency": 90,
                    "temperatureAdjustment": 0,
                    "heatTemperature": 27,
                    "minTemperature": 0,
                    "maxTemperature": 50,
                    "autoCoolTemperature": 24,
                    "autoHeatTemperature": 17,
                    "defaultCoolTemperature": 22,
                    "defaultHeatTemperature": 27,
                    "minimumAutoOnOffDuration": 420,
                    "turnOnWhenOff": false,
                    "pseudoDeviceTemperature": 27,
                    "sendTemperatureOnlyWhenOff": false,
                    "ignoreTemperatureWhenOff": false,
                    "replaceAutoMode": "cool",
                    "autoSwitchName": "Bedroom Climate Control",
                    "data": {
                        "off": "260066006f32110b100b1126100b1126100c100b100b11261027100b100c100b10271026110b100b100c100b100b110b100b100c100b100b110b100b100b1126100c100b100b110b100b100c100b1027100b100b110b100b1027100b110b100b100c100b100b11000d050000",
                        "temperature30": {
                            "pseudo-mode": "heat",
                            "data": "2600f6007032100b100c1026110b1026110b100b100c10261126100c100b100b11261027100b110b100b100b110b100b100c100b100b110b100b100d0f0b1027100b100b110b100b100c100b100b1126100b110b100b100c100b102710261126102710271026110b100b110b1026100c100b100c100b100b110b100b100b11261027100b110b1026110b100b110b100b10271026112610271027100b100b110b100b100c100b1027100b100c100b100b110b100b100b110b100b100c100b100b110b100b100b110b100b100c100b100b110b100b100b110b100b100c100b100b110b100b100c10261027100b1126100c10261027102710000d050000"
                        },
                        "temperature29": {
                            "pseudo-mode": "heat",
                            "data": "2600f6006d340e0e0e0d0e290e0d0e290e0d0e0e0e0d0e290e290d0e0e0e0d0e0e290d290e0e0e0d0e0e0d0e0e0d0e0e0d0e0e0d0e0e0e0d0e0e0d0e0e0d0e290e0e0d0e0e0d0e0e0d0e0e0d0e0e0d290e0e0e0d0e0e0d0e0e0d0e290e290e290d290e290e290e0d0e0e0d0e0e290e0d0e0e0d0e0f0c0e0e0d0e0f0d0e0d0e290d290e0e0d0e0f280e0d0f0d0e0d0e0d0e290e0d0e290e290e0f0c0e0d100c0d0e0e0f0c0e0e0d290e290e0d0e0e0f0c0e0e0d0e0f0c0e0e0e0d0e0d0e0e0e0d0e0e0e0d0e0d0e0e0f0c0e0e0e0d0e0d0e0e0f0c0f0c0e0e0d100d0d0d0e0f0c0e0e0d0e0e0d0f280e290e0d0e290e0d0f280f0d0e0d0e000d050000"
                        },
                        "temperature28": {
                            "pseudo-mode": "heat",
                            "data": "2600f6006d340e0e0e0d0e290e0d0e290e0d0e0e0e0d0e290e290d0e0e0e0d0e0e290d290e0e0e0d0e0e0d0e0e0d0e0e0d0e0e0d0e0e0e0d0e0e0d0e0e0d0e290e0e0d0e0e0d0e0e0d0e0e0d0e0e0d290e0e0e0d0e0e0d0e0e0d0e290e290e290d290e290e290e0d0e0e0d0e0e290e0d0e0e0d0e0f0c0e0e0d0e0f0d0e0d0e290d290e0e0d0e0f280e0d0f0d0e0d0e0d0e290e0d0e290e290e0f0c0e0d100c0d0e0e0f0c0e0e0d290e290e0d0e0e0f0c0e0e0d0e0f0c0e0e0e0d0e0d0e0e0e0d0e0e0e0d0e0d0e0e0f0c0e0e0e0d0e0d0e0e0f0c0f0c0e0e0d100d0d0d0e0f0c0e0e0d0e0e0d0f280e290e0d0e290e0d0f280f0d0e0d0e000d050000"
                        },
                        "temperature27": {
                            "pseudo-mode": "heat",
                            "data": "2600f6006d340e0e0e0d0e290e0d0e290e0d0e0e0e0d0e290e290d0e0e0e0d0e0e290d290e0e0e0d0e0e0d0e0e0d0e0e0d0e0e0d0e0e0e0d0e0e0d0e0e0d0e290e0e0d0e0e0d0e0e0d0e0e0d0e0e0d290e0e0e0d0e0e0d0e0e0d0e290e290e290d290e290e290e0d0e0e0d0e0e290e0d0e0e0d0e0f0c0e0e0d0e0f0d0e0d0e290d290e0e0d0e0f280e0d0f0d0e0d0e0d0e290e0d0e290e290e0f0c0e0d100c0d0e0e0f0c0e0e0d290e290e0d0e0e0f0c0e0e0d0e0f0c0e0e0e0d0e0d0e0e0e0d0e0e0e0d0e0d0e0e0f0c0e0e0e0d0e0d0e0e0f0c0f0c0e0e0d100d0d0d0e0f0c0e0e0d0e0e0d0f280e290e0d0e290e0d0f280f0d0e0d0e000d050000"
                        },
                        "temperature26": {
                            "pseudo-mode": "heat",
                            "data": "2600f6006d340e0e0e0d0e290e0d0e290e0d0e0e0e0d0e290e290d0e0e0e0d0e0e290d290e0e0e0d0e0e0d0e0e0d0e0e0d0e0e0d0e0e0e0d0e0e0d0e0e0d0e290e0e0d0e0e0d0e0e0d0e0e0d0e0e0d290e0e0e0d0e0e0d0e0e0d0e290e290e290d290e290e290e0d0e0e0d0e0e290e0d0e0e0d0e0f0c0e0e0d0e0f0d0e0d0e290d290e0e0d0e0f280e0d0f0d0e0d0e0d0e290e0d0e290e290e0f0c0e0d100c0d0e0e0f0c0e0e0d290e290e0d0e0e0f0c0e0e0d0e0f0c0e0e0e0d0e0d0e0e0e0d0e0e0e0d0e0d0e0e0f0c0e0e0e0d0e0d0e0e0f0c0f0c0e0e0d100d0d0d0e0f0c0e0e0d0e0e0d0f280e290e0d0e290e0d0f280f0d0e0d0e000d050000"
                        },
                        "temperature25": {
                            "pseudo-mode": "cool",
                            "data": "2600f6006f33100b100c1026100c1026100c100b100b11261027100b110b100b10271027100b100b110b100b100c100b100b110b100b100c100b100b110b1026100c100b100c100b100b110b100b1027100b100c100c0f0b110b10261126102710270f271126100d0f0b100b1126100b110b100b100c100b100b110c0f0d0e271027100b100b1126100c100b100d0e27100b110b10261126100d0f0b100b110b100b100c100b10271026110b100b100c100b100d0e0c100b100b110b100d0e0c100b100d0e0c100b100c100b100b100c100b100d0f0b100b100c100c0f0b110b100c0f0b110b10261126100c102610271027100b100c10000d050000"
                        },
                        "temperature24": {
                            "pseudo-mode": "cool",
                            "data": "2600f6006f33100b100d0f26100c1026100d0f0b100c10260f280f0d0f0c0f0d0e280f280f0c100c0e0e0f0b100c100b100b100d0f0b0f0d0f0c0f0c100c0f270f0d100b100c100b100b100c100b1027100b100c100b100d0d0d0f270f2810270f2810270f270f0e0e0c100b10270f0d100b100b100c0e0f0e0d0d0d100b10270f280f0c100b10270f0d0d0f0e0c100c100b100c0e280f280f0c0f0e0e0c0f0d0e0e0e0c0f0e0e270f280f0d0e0e0d0d0f0d0e0d0e0d100d0e0c0f0c0e0e0f0c0f0e0d0d0f0c0e0e0f0c0f0e0c0e0e0d0f0d0e0d0e0d0f0d0d0e0f0c0e0e0f0c0f0d0d0e0f0c0f280e290d0e0f280e0d0e0e0d290e0f0c000d050000"
                        },
                        "temperature23": {
                            "pseudo-mode": "cool",
                            "data": "2600f6006f32110b100b1027100b1027100b110b100b10271027100b100c100b10271026100c100b100c100b100b110b100b100b110b100b100c100b100b1126100b110b100b100c100b100b110b1026110b100b110b100b100b112610271027102611261027100b110b100b1027100b100b110b100b100c100b100b110b10261126100c100b1027100b100c100b102710261126100b1126100c100b100b110b100b100c100b100b1027100b110b100b100c100b100b100d0f0b100b100c100b100c0f0c100d0e0d0e0c100d0d0e0e0c100d0d0d0f0c0f0d0e0d0f0c0f0d100b0f0c0f0d0f0c0f0d0f0d0e280f270f280f0d0e280e0e0f000d050000"
                        },
                        "temperature22": {
                            "pseudo-mode": "cool",
                            "data": "2600f6006f330f0c100c1027100b10270f0c100b100d0e280e280f0d0e0d100b10270f280f0c100d0e0c100b100c100b100c100b100d0e0c100d0d0c0f0e0e280f0c100b0f0d100b100b100c100d0d280f0c100c100b100b100d0f260f280f2810270f280e280f0d0e0d100b0f280f0c0f0e0e0c100c0f0c100b0f0d0f0c0f2810270e0d100d0e270f0c0f0d0f0c0f0c102710270f0e0d280f0e0d0d100b100c0f0c0f0c0f0d0e0d0f280f0c100d0d0d0f0c0f0d0e0d0e0f0d0d0f0e0d0d0e0d0e0f0d0d0d0e0f0c0f0d0f0c0f0d0f0d0e0c0e0e0f0d0e0c0f0d0f0c0f0d0d0e0f0c0f0d0e0d0f0c0f0d0f280d290f0e0e270f280f0d0e000d050000"
                        },
                        "temperature21": {
                            "pseudo-mode": "cool",
                            "data": "2600f6007132100c100b1027100b1027100b100c100c0f271026110b100b100c10261027100c100b100b110b100b100c100b100b110b100d0e0b110b100b1027100b110b100d0e0c100b100b100c1026100c100b100c100b100b112610271027102610271027100b110b100b1027100d0e0c100b100d0f0b100b100c100b10271026100c100b1126100b110c0f0b1027100b1126100b1126100d0f0b100b110b100b100c100b100b1126100d0e0c100b100c100b100b110c0f0b100b100c100b100d0f0c0f0b110b100b100b110b100b100c100b100b110c0f0b100c100b100b100c100b100b110b100b10271027102610271027100d0e000d050000"
                        },
                        "temperature20": {
                            "pseudo-mode": "cool",
                            "data": "2600b60069330e0b0f260f0a100a10250f0b0f260e0b0f0b0f260f250f250f0b0f260e0b0f260e260f250f0b0f0b0f0b0f0b0f260e260e0b10250f250f0b0f0b0f260e0b0f0b10250f0a100b0f250f260e0b0f260e260f0a10250f260e260e260e0b100a10250f250f0b0f0b0f0b0f0b0f260f250f0b0f250f260e260e0b100a10250f0b0f250f0b0f0b0f0b0f260f250f0a10250f0b0f0b0f260e260f0a100a100a10250f260e260e0b0f0b10250f250f250f0b0f0b0f000d050000"
                        },
                        "temperature19": {
                            "pseudo-mode": "cool",
                            "data": "2600f6007032100b100c1026110b1027100b100b110b10261126100c100b100b11261027100b110b100c0f0b110b100b100c100b100b110b100b100b110b1027100b100b110b100b100b110b100b1027100d0f0b100b100c100b102710261126102710271026110b100b100c1026100c100b100b110b100b100d0f0c0f0b11261027100b100c1026100c100b100c10261027100d0e0c1027100b100b100c100c0f0d0e0c100b1027100b100c100b100d0d0e0f0b100c0f0c100d0e0d0f0b100b0f0d100b100c0e0e0e0c100c100b100b100d0f0b100c100b100d0e0d0e0c0f0c100c0f0e0e0c0f27100c10260f281027100d0e0c10260f000d050000"
                        },
                        "temperature18": {
                            "pseudo-mode": "cool",
                            "data": "2600f6006f32100c0f0c1027100b1027100b100c0f0c10271026100c100b100c0f271027100c0f0c100b100c0f0c100b100c100b100c0f0c100b100c0f0c10270f0c100c0f0c100b100c0f0c100b1027100c0f0c100b100c0f0c10270f271027102710270f27100c100b100c0f27100c0f0c100c0f0c100b100c0f0c100b10271027100b100c0f27100c100b100c0f0c1027100b100c0f27100c0f0c100c0f0c100b100c0f0c1027100b100c0f0c100b100c0f0c100b100c100b100c0f0c100b100c0f0c100c0f0c100b100c0f0c100b100c0f0c100c0f0c100b100c0f0c100b100c100b100c0f27100c0f271027100c0f27100c0f2710000d050000"
                        }
                    }
                }

**Comment by kiwi-cam** [comment]
Issue #372 was resolved as far as I can tell.

You've got three AC Units setup, and only one with a pseudoDeviceTemperature
1. "BedRoom AC" - has  a pseudoDeviceTemperature
2. "Study Room AC"
3. "Living Room AC"

Are the others working with Broadlink devices with Temperature and Humidity sensors?

**Comment by turbidWaters** [comment]
Thank you for your response @kiwi-cam. Yes, the other two have temperature sensors. They are both broadlink rm3. I'm not sure if they have a humidity sensor though. I was using the plugin from lprhodes and migrated without much change to the config.json.
Is there a way to specify the humidity in the absense of a humidity sensor, similar to pseudodevicetemprature?
Sorry if I have missed something from your wiki. Taking a look again now.

**Comment by kiwi-cam** [comment]
Instead what you could so it set `"noHumidity": true`. Are you getting temperature readings OK?

I'm assuming the RM3 has a temperature sensor... sorry I never owned an RM3 Pro.

**Comment by turbidWaters** [comment]
I guess I dont have a humidity sensor in broadlinks I am using. I have a mix of RM2, RM3, RM3 Pro and a RM Mini. I had to add pseudotemperature for one of the them while using it with a thermostat because it always shows zero otherwise. On the other two thermostats (both on two different braodlinks) I am getting the temperature readings without any issues. I have never seen a humidity reading ever, so I assume that I dont have humidity sensors in any of the broadlinks I am using. Will try `"noHumidity": true` and revert. Thank you.

**Comment by turbidWaters** [comment]
Thank you @kiwi-cam it worked. I had to add it to every thermostat. The error warning is not being logged anymore.
