### ISSUE TITLE
RM4 PRO discovered as RM3 Pro Plus

### ISSUE THREAD

**Issue by kikect** [kiwi-cam/homebridge-broadlink-rm#39]
Hi,

I install the last version v4.2.9 and the discovered device it´s different from mine:

[Broadlink RM PRO 4] [INFO] Discovered Broadlink RM3 Pro Plus (279d) at 192.168.1.4 (24::d:f::a7:

I tried Learn button but the device shows no led blinking and the code doesn´t appear on homebridge log.

 [Broadlink RM PRO 4] Learn Code (ready)
 [Broadlink RM PRO 4] [INFO] Learn Code (stopped - 10s timeout)
 [Broadlink RM PRO 4] [INFO] Learn Code (stopped)

any help on this?
thanks!

**Comment by ShifuHeiko** [comment]
I also got model RM4C mini + the latest version installed, yet the learning function is not working yet. 

Log:
[8/14/2020, 17:30:18] [Broadlink RM] Scan Frequency getSwitchState: undefined
[8/14/2020, 17:30:18] [Broadlink RM] Learn getSwitchState: undefined
[8/14/2020, 17:30:52] [Broadlink RM] [ERROR] Learn Code (Couldn't learn code, device not found)
[8/14/2020, 17:31:05] [Broadlink RM] [INFO] Learn Code (Couldn't learn code, device not found)

This is the config file:
  {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideWelcomeMessage": true,
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hosts": [
                {
                    "address": "10.0.X.X",
                    "mac": "24:df:a7:XX:XX:XX",
                    "isRFSupported": false
                }
            ]
        },

**Comment by kiwi-cam** [comment]
Hi @kikect. This code is based off the work done on [python-broadlink](https://github.com/mjg59/python-broadlink). Looking at their code, they identify 279d as an "R Pro+".

It certainly looks like its an RM3 model. Are you sure you've got an RM4 Pro, or is there another device on the network that the plugin could be discovering instead?

Sorry - I've got to rule out the obvious before make changes that may break the 279d for others.

**Comment by kikect** [comment]
Hi,

I bought it in Amazon (BroadLink RM4 Pro IR y RF Mando a Distancia Universal, Code Learning - Mando a Distancia WiFi para el hogar Inteligente y Dispositivos - para TV, AC, Motor de Cortina - Compatible con Alexa https://www.amazon.es/dp/B083LLLVPN/ref=cm_sw_r_cp_tai_oLdoFbZW76CGZ) I think is the RM4 Pro compared with pictures from others google searches.

At this point, what do you recommend ? Explore to install python-broadlink?

Thanks so much for your answer and your support!

**Comment by faderud** [comment]
@kikect try updating to 4.3.0, that fixed it for me.

**Comment by kiwi-cam** [comment]
@kikect It sounds like an update of the related broadlinkrmjs module has probably resolved this issue. Please let me know if this is still an issue.
