### ISSUE TITLE
migrating from homebridge-broadlink-rm by lprhodes

### ISSUE THREAD

**Issue by jat80** [kiwi-cam/homebridge-broadlink-rm#394]
Hi there,

I currently run @lprhodes plugin ([homebridge-broadlink-rm](https://www.npmjs.com/package/homebridge-broadlink-rm)) and wanting to migrate to this one.  Can I install your plugin while my current one is still running and start adding the accessories I want across first then delete the old one?

Thanks for your time.

**Comment by masterfordev** [comment]
Nope, you have to uninstall the old plugin and install this, but you can use the same config for both plugins. And add the extra options of this plugins.

**Comment by pratkai** [comment]
Hello, I am in the same migration process, but the new plugin does not recognise the BroadlinkRM device. Is there anything I should be checking? Thanks a lot
