### ISSUE TITLE
Broad link rm4 temp and humidity sensor

### ISSUE THREAD

**Issue by adrianopery** [kiwi-cam/homebridge-broadlink-rm#396]
Hi guys, I'm trying to add the Broad link rm4 temp and humidity sensor on my homekit screen.
I didn't understand how can I do it.
Is it possible someone share the configuration?

**Comment by masterfordev** [comment]
Hello, as the [documentation](https://broadlink.kiwicam.nz/#humiditysensor)

**Comment by masterfordev** [comment]
> Hello, as the [documentation](https://broadlink.kiwicam.nz/#humiditysensor)

**Comment by adrianopery** [comment]
even for the local sensors on my Broadlink RM4 I will need to use the MQTT?

**Comment by galangel** [comment]
he is referring to the sensors connected to the power cable

**Comment by Muxxx** [comment]
> Hello, as the [documentation](https://broadlink.kiwicam.nz/#humiditysensor)

I followed the doco and if I add mqtt settings I get ‘mqtt client is connected’ and if I omit mqtt settings in my config the sensor shows - value of 0. The sensors through the broadlink iOS app def show values.
These are the built in sensors to the rm4 pro.
some help please?

**Comment by fratinize** [comment]
Adding it seems easy, it shows in homebridge and I did not use mqtt 
However I am unable to add to HomeKit. Not sure what I am missing.

**Comment by fratinize** [comment]
> Adding it seems easy, it shows in homebridge and I did not use mqtt 
> However I am unable to add to HomeKit. Not sure what I am missing.

Never mind there they are...
No mqtt just name, type and in my case of multiples i added host
Next day they weee in home kit just wrong room
All good

**Comment by adrianopery** [comment]
> > Adding it seems easy, it shows in homebridge and I did not use mqtt
> > However I am unable to add to HomeKit. Not sure what I am missing.
> 
> Never mind there they are... No mqtt just name, type and in my case of multiples i added host Next day they weee in home kit just wrong room All good

Thanks for your reply.
Is it possible you post your code as example?

**Comment by fratinize** [comment]
{
                    "name": "Kitchen Temp",
                    "": "temperatureSensor",
                    "host": "192.168.1.119"
                },
                {
                    "name": "Kitchen Humidity",
                    "type": "humiditySensor",
                    "host": "192.168.1.119"
