### ISSUE TITLE
How i can add more on one tv with the same device?

### ISSUE THREAD

**Issue by masterfordev** [kiwi-cam/homebridge-broadlink-rm#40]
Hello, i tried add 2 tv with the same RM but i cant, isnt possible?

Thanks.

**Comment by Faisalthe01** [comment]
Yes, you have to add the 2nd TV manually by touching Add Accessory in Home app and you will see the 2dn TV there then you will need to original Homebridge HomeKit code to complete.

**Comment by masterfordev** [comment]
> Yes, you have to add the 2nd TV manually by touching Add Accessory in Home app and you will see the 2dn TV there then you will need to original Homebridge HomeKit code to complete.

Thanks! worked! :+1:
