### ISSUE TITLE
What's the correct way to use speedStep and stepSize?

### ISSUE THREAD

**Issue by turbidWaters** [kiwi-cam/homebridge-broadlink-rm#400]
I have a 10 speed fan regulator. Trying to get the Home app to only show 0,10,20,30... and so on till 100.  It doesn't seem to be working, and still getting steps of 1 instead of 10. Appreciate any help.

Here is my config:

                   "name": "Ceiling Fanspeed",
                    "type": "fan",
                    "host": "xx:xx:xx:xx:xx:xx",
                    "hideSwingMode": true,
                    "hideRotationDirection": true,
                    "stepSize": 10,
                    "speedSteps": 10,
                    "enableAutoOff": false,
                    "data": {
                        "on": "",
                        "off": "",
                        "fanSpeed10": [
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 9,
                                "interval": 0.05,
                                "pause": 0
                            }
                        ],
                        "fanSpeed20": [
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 9,
                                "interval": 0.05,
                                "pause": 0
                            },
                            {
                                "data": "Hex_Code ... "
                            }
                        ],
                        "fanSpeed30": [
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 9,
                                "interval": 0.05,
                                "pause": 0
                            },
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 2,
                                "interval": 0.05,
                                "pause": 0
                            }
                        ],
                        "fanSpeed40": [
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 9,
                                "interval": 0.05,
                                "pause": 0
                            },
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 3,
                                "interval": 0.05,
                                "pause": 0
                            }
                        ],
                        "fanSpeed50": [
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 9,
                                "interval": 0.05,
                                "pause": 0
                            },
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 4,
                                "interval": 0.05,
                                "pause": 0
                            }
                        ],
                        "fanSpeed60": [
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 9,
                                "interval": 0.05,
                                "pause": 0
                            },
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 4,
                                "interval": 0.05,
                                "pause": 0
                            }
                        ],
                        "fanSpeed70": [
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 9,
                                "interval": 0.05
                            },
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 3,
                                "interval": 0.05,
                                "pause": 0
                            }
                        ],
                        "fanSpeed80": [
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 9,
                                "interval": 0.05
                            },
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 2,
                                "interval": 0.05
                            }
                        ],
                        "fanSpeed90": [
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 9,
                                "interval": 0.01
                            },
                            {
                                "data": "Hex_Code ... "
                            }
                        ],
                        "fanSpeed100": [
                            {
                                "data": "Hex_Code ... ",
                                "sendCount": 9,
                                "interval": 0.05,
                                "pause": 0
                            }
                        ]
                    }
```

**Comment by bennettp123** [comment]
I'd be interested to see a working example too.

@turbidWaters here's my current config, but one caveat: it causes the child bridge to hang (no errors in the logs, it just stops responding to everything including SIGTERM, need to restart the container.)

```json
{
  "name": "Bennett’s Office Fan",
  "type": "fan",
  "host": "192.168.33.18",
  "hideSwingMode": false,
  "hideRotationDirection": true,
  "speedCycle": true,
  "speedSteps": 3,
  "defaultFanSpeed": 33,
  "data": {
    "off": "2600aa00260f280f0d2a280e280f0d2b0d290c2b0d290d290e2a28f3280f270f092f280e280f0d290d2a0d2b0c290e2b0c2a32e8280f290f0c2a280f290e0c2a0d2b0d280d2a0e290e2927f428102612082c290f280f0d290d2b0d290d2a0d2a0c2929f4280f280e0d2a2610280f0d2a0e290d290f280e2a0c2a28f3290e28100b2b280f27110b2a0c2b0d290d2a0d2a0e2829f22910270e0d2a280f290d0d2a0d2a0e280d2a0e290e2928000d05000000000000000000000000",
    "on": "2600aa00260f280f0d2a280e280f0d2b0d290c2b0d290d290e2a28f3280f270f092f280e280f0d290d2a0d2b0c290e2b0c2a32e8280f290f0c2a280f290e0c2a0d2b0d280d2a0e290e2927f428102612082c290f280f0d290d2b0d290d2a0d2a0c2929f4280f280e0d2a2610280f0d2a0e290d290f280e2a0c2a28f3290e28100b2b280f27110b2a0c2b0d290d2a0d2a0e2829f22910270e0d2a280f290d0d2a0d2a0e280d2a0e290e2928000d05000000000000000000000000",
    "fanSpeed33": "2600b600270e290e0d2a290e280e0d2a0e290d290e290e29280f0d00010d2a0e280e0d2a290e280f0d290e290d2a0d290e29290e0e00010d290e290e0d29290f280e0d2a0e290d290d2a0e29280f0e00010d290e280f0d29290f280e0d290e2a0d290d2a0e29280e0d00010f290d290f0d29290e280f0d290e2a0d290d290e2a280e0d00010f290d290f0d29290e280f0d290e290e290d2a0d2a280e0e00010d290e280f0d29290f280e0d2a0e290d290e290e29280e0e000d05",
    "fanSpeed66": "2600b600270e290e0d2a290e280e0d2a0e290d290e290e29280f0d00010d2a0e280e0d2a290e280f0d290e290d2a0d290e29290e0e00010d290e290e0d29290f280e0d2a0e290d290d2a0e29280f0e00010d290e280f0d29290f280e0d290e2a0d290d2a0e29280e0d00010f290d290f0d29290e280f0d290e2a0d290d290e2a280e0d00010f290d290f0d29290e280f0d290e290e290d2a0d2a280e0e00010d290e280f0d29290f280e0d2a0e290d290e290e29280e0e000d05",
    "fanSpeed100": "2600b600270e290e0d2a290e280e0d2a0e290d290e290e29280f0d00010d2a0e280e0d2a290e280f0d290e290d2a0d290e29290e0e00010d290e290e0d29290f280e0d2a0e290d290d2a0e29280f0e00010d290e280f0d29290f280e0d290e2a0d290d2a0e29280e0d00010f290d290f0d29290e280f0d290e2a0d290d290e2a280e0d00010f290d290f0d29290e280f0d290e290e290d2a0d2a280e0e00010d290e280f0d29290f280e0d2a0e290d290e290e29280e0e000d05",
    "swingToggle": "2600b600270f280e0e29290e290e0d2a0d29290e0e290d290e2a0d00010d290e280e0e2a280e280f0e290d29280f0e290d2a0d290e00010d290e290e0d29290f280e0d2a0e29280e0d2a0e290d2a0d00010e280e290f0d29290e290e0d290d2a290e0d290e2a0d290d00010f280e290f0d29280e2a0e0d290d2a290e0d290e290e290d00010f280e290e0e29280e290f0d290d2a290e0d290d2a0e290d00010f280e290e0d2a280e290f0d290d292a0e0d290d2a0e290d000d05"
  }
}
```

**Comment by bennettp123** [comment]
I think I've figured it out. It looks like the `fanSpeedX` items are [ignored](https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/deb5f01469006d00a15c820e8a27e7c625b3eba7/accessories/fan.js#L154) when `speedCycle` is enabled.

Instead, it uses `fanSpeed`, and repeats it until the desired step is reached.

@turbidWaters here's a working example:

```json
{
  "name": "Bennett’s Office Fan",
  "type": "fan",
  "host": "192.168.33.18",
  "hideSwingMode": false,
  "hideRotationDirection": true,
  "defaultSpeedStep": 1,
  "speedCycle": true,
  "stepSize": 34,
  "speedSteps": 3,
  "data": {
    "off": "2600aa00260f280f0d2a280e280f0d2b0d290c2b0d290d290e2a28f3280f270f092f280e280f0d290d2a0d2b0c290e2b0c2a32e8280f290f0c2a280f290e0c2a0d2b0d280d2a0e290e2927f428102612082c290f280f0d290d2b0d290d2a0d2a0c2929f4280f280e0d2a2610280f0d2a0e290d290f280e2a0c2a28f3290e28100b2b280f27110b2a0c2b0d290d2a0d2a0e2829f22910270e0d2a280f290d0d2a0d2a0e280d2a0e290e2928000d05000000000000000000000000",
    "on": "2600aa00260f280f0d2a280e280f0d2b0d290c2b0d290d290e2a28f3280f270f092f280e280f0d290d2a0d2b0c290e2b0c2a32e8280f290f0c2a280f290e0c2a0d2b0d280d2a0e290e2927f428102612082c290f280f0d290d2b0d290d2a0d2a0c2929f4280f280e0d2a2610280f0d2a0e290d290f280e2a0c2a28f3290e28100b2b280f27110b2a0c2b0d290d2a0d2a0e2829f22910270e0d2a280f290d0d2a0d2a0e280d2a0e290e2928000d05000000000000000000000000",
    "fanSpeed": "2600b600270e290e0d2a290e280e0d2a0e290d290e290e29280f0d00010d2a0e280e0d2a290e280f0d290e290d2a0d290e29290e0e00010d290e290e0d29290f280e0d2a0e290d290d2a0e29280f0e00010d290e280f0d29290f280e0d290e2a0d290d2a0e29280e0d00010f290d290f0d29290e280f0d290e2a0d290d290e2a280e0d00010f290d290f0d29290e280f0d290e290e290d2a0d2a280e0e00010d290e280f0d29290f280e0d2a0e290d290e290e29280e0e000d05",
    "swingToggle": "2600b600270f280e0e29290e290e0d2a0d29290e0e290d290e2a0d00010d290e280e0e2a280e280f0e290d29280f0e290d2a0d290e00010d290e290e0d29290f280e0d2a0e29280e0d2a0e290d2a0d00010e280e290f0d29290e290e0d290d2a290e0d290e2a0d290d00010f280e290f0d29280e2a0e0d290d2a290e0d290e290e290d00010f280e290e0e29280e290f0d290d2a290e0d290d2a0e290d00010f280e290e0d2a280e290f0d290d292a0e0d290d2a0e290d000d05"
  }
}
```

Some notes:
* My fan has three different fan speeds (low/med/high), plus the "off" state.
* `fanSpeed` is the hex code that toggles between the three states.
* `"speedCycle": true` enables cycling between speeds
* `"speedSteps": 3` represents the low/medium/high steps
* `"stepSize": 34` ensures that the last step is greater than 100.
 
For the step size, `33` probably works fine too, but the hang suggests there might be an unhandled edge case, and `100` is [hardcoded in fan.ts](https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/deb5f01469006d00a15c820e8a27e7c625b3eba7/accessories/fan.js#L14). `33*3 < 100`, but `34*3 > 100`, so 34 it is. YMMV. :D

**Comment by turbidWaters** [comment]
My fanspeed controller does not cycle thru 100 to 0 or 1, and so I cannot use this config. I've tried various combinations, but I still always get speedsteps of 1 (1 to 100), no matter what the speedstep size is, but I need a speed step of 10, as I have a 10 speed controller. I've shared my config above here.

Anyone having the same issue?

**Comment by ghost** [comment]
I had the same issue and fought with it for ages. I eventually gave up and switched to Home Assistant which has much better Broadlink integration. If you're up for it I'd recommend switching and trying it out. After fighting with coding everything manually I've found much simpler ways to accomplish the same thing through Home Assistant.

I hope this helps as I struggled for the better part of a week to get just the fan working properly and only really managed to make a janky work around as my fan has 10 speeds as well. Please let me know how it goes, I thankfully was running Hoobs from a Raspberry Pi and was able to switch without issue.

**Comment by turbidWaters** [comment]
I have all my 50 odd devices on homebridge for nearly 4 years now and its been quite a good experience. I have been thinking of Home Assistant for a bit now, considering that it can integrate well with other interfaces like google home, alexa, though I havent dived deep to make a full SWOT analysis! Meanwhile, I am speaking to the manufacturer of the fan controllers to give me discrete codes, and I am hoping that would ease the experience. Thanks for the heads up on HA though. Perhaps I will setup HA just for the fan controllers and integrate it with homekit
