### ISSUE TITLE
Unable to specify RM4C for hex code sending 

### ISSUE THREAD

**Issue by Fung1995** [kiwi-cam/homebridge-broadlink-rm#403]
Hello

Im currently having two RM4c in my setup. One in bathroom and one in living room. I had them setup with static IP address. But with the hosts function inputed in the config, the hex code cannot be be specified to send from the RM4c according to the config file. The hex code would randomly sent from any one Rm4c. 

Below is the relevant config.

"platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": true,
            "hideLearnButton": true,
            "hideWelcomeMessage": true,
            "accessories": [
                {
                    "name": "Ventilation Fan On/Off",
                    "type": "switch",
                    "hosts": "192.168.1.bb",
                    "allowResend": true,
                    "data": {
                        "on": "26008c017637100d0e2c100d0e0e0f0e0f0e0e0f0e0f0e0f0e0e110c0f0e0e0f102a100c110c0f0e100d100d100d1029100d0f2b102a100c110c102a100d100d1029100d100d100d102a1029102a102a1029100d102a100d100d1029100d102a100d100c110c102a100d102a100c110c102a100d100d1029102a102a1029110c100d102a100d1029102a102a10291129100d102a100c1129102a102a1029100d102a1029110c100d102a10291129100d100d100d1029110c102a100d1029110c100d100d102a100003e37637100d102a100d100c110c100d100d100d100d100d100c110c100d102a100d100c110c100d100d100d1029110c102a102a100d100c1129100d100d1029110c110c100d102a1029102a11291029110c102a100d100d1029110c102a100d100d100c1129100d102a100c110c102a100d100d10291129102a1029110c100d102a100d1029102a102a10291129100d102a100c1129102a102a1029100d102a1029110c100d102a102a1029100d100d100d1029110d0f2a100d0e2b0f0e0f0e0e0f0e2c0e000d05000000000000000000000000",
                        "off": "26008c0175390e0f0e2c0e0e0f0e0e0f0e0f0e0f0e0e0f0e0f0e0e0f0e0f0e0f0e2b0f0e0e0f0e0f0e0f0e0e0f0e0e2c0e0f0e2b0f2b0e0f0e0f0e2b0f0e0e0f0e2c0e0f0e0e0f0e0e2c0e2c0e2b0e2c0e2c0e0e0f2b0e0f0e0f0e0f0e0e0f2b0e0f0e0f0e0f0e0e0f0e0e0f0e0f0e0f0e2b0f0e0e0f0e0f0e0f0e0f0e0e0f0e0e0f0e2c0e0f0e0e0f0e0e0f0e0f0e2b0f0e0f2b0e0f0e0f0e0e0f0e0f0e0e0f0e2c0e2b0f0e0e0f0e0f0e0f0e0e0f0e0e0f0e0f0e2c0e0e0f2b0e0f0e2c0e0e0f0e0e0f0e2c0e0003e675380f0e0e2c0e0f0e0f0e0e0f0e0e0f0e0f0e0f0e0f0e0e0f0e0e0f0e2c0e0f0e0e0f0e0e0f0e0f0e0f0e2b0f0e0e2c0e2b0f0e0f0e0e2c0e0f0e0f0e2b0e0f0e0f0e0f0e2b0f2b0e2c0e2b0f2b0e0f0e2c0e0e0f0e0e0f0e0f0e2c0e0e0f0f0d0f0e0f0e0f0e0f0e0f0e0e0e2c0e0f0e0f0e0e0f0e0e100d0f0e0f0e0f0e2b0e0f0e0f0e0f0e0f0e0e0f2b0e0f0e2b0f0e0f0e0e0f0e0f0e0f0e100d2b0e2c0e0f0e0f0e0e0f0e0e0f0e0f0e0f0e0f0e2b0e0f0e2c0e0f0e2b0e0f0e0f0e0f0e2b0e000d05000000000000000000000000"
                    }
                },
                {
                    "name": "Ventilation Fan heat cold on/off",
                    "type": "switch",
                    "hosts": "192.168.1.bb",
                    "allowresend": true,
                    "data": {
                        "on": "26008c017637100d0e2c100d0e0e0f0e0f0e0e0f0e0f0e0f0e0e110c0f0e0e0f102a100c110c0f0e100d100d100d1029100d0f2b102a100c110c102a100d100d1029100d100d100d102a1029102a102a1029100d102a100d100d1029100d102a100d100c110c102a100d102a100c110c102a100d100d1029102a102a1029110c100d102a100d1029102a102a10291129100d102a100c1129102a102a1029100d102a1029110c100d102a10291129100d100d100d1029110c102a100d1029110c100d100d102a100003e37637100d102a100d100c110c100d100d100d100d100d100c110c100d102a100d100c110c100d100d100d1029110c102a102a100d100c1129100d100d1029110c110c100d102a1029102a11291029110c102a100d100d1029110c102a100d100d100c1129100d102a100c110c102a100d100d10291129102a1029110c100d102a100d1029102a102a10291129100d102a100c1129102a102a1029100d102a1029110c100d102a102a1029100d100d100d1029110d0f2a100d0e2b0f0e0f0e0e0f0e2c0e000d05000000000000000000000000",
                        "off": "26008c017439110c0e2b0f0e110c0e0f0e0e0f0e0e0f0f0e0e0e0e0f0e0f0e0e1129110c0e0e0f0e0e0f0e0f0e0e0f2b0e0f0e2b0e2c0e0e0f0e0e2c0e0e0f0e0e2c0e0e0e0f0e0f0e2b0e2c0e2b0e2c0e2b0e0f0e2b0f2b0e2b0f0e0e0f0e2b0f0e0e0f0e0f0e2b0e0f0e2b0f0e0e0f0e2b0f0e0e0f0e0f0e2b0e2c0e0e0e0f0e0f0e2b0e0f0e0f0e0e0f0e0e0f0e2b0f0e0e2c0e0e0f0e0e0f0e0f0e0e0f0e0e2c0e2b0e0f0e0f0e2b0e2c0e2b0e0f0e0f0e0e0e2c0e0e0f0e0e2c0e0e0f0e0e0f0e0f0e2b0e0003e576370e0f0e2b0e0f0e0f0e0e0f0e0e0f0e0e0f0e0e0f0e0f0e0e0f0e0e2c0e0e0f0e0e0f0e0f0e0e0f0e0e2c0e0e0f2b0e2b0f0e0e0f0e2b0e0f0e0f0e2b0e0f0e0f0e0f0e2b0e2b0f2b0e2b0f2b0e0f0e2b0e2c0e2b0e0f0e0f0e2b0e0f0e0f0e0e0f2b0e0f0e2b0e0f0e0f0e2b0e0f0e0f0e0e0e2c0e2b0e0f0e0f0e0e0f2b0e0f0e0e0f0e0e0f0e0f0e2b0e0f0e2b0f0e0e0f0e0f0e0e0f0e0e0f0e2b0f2b0e0f0e0e0e2c0e2b0e2c0e0e0f0e0e0f0e2b0f0e0e0f0e2b0f0e0e0f0e0f0e0e0f2b0e000d05000000000000000000000000"
                    }
                },
                {
                    "name": "Small Room Fan On/Off",
                    "type": "switch",
                    "hosts": "192.168.1.aa",
                    "allowresend": true,
                    "data": {
                        "on": "2600500000012793141114111411141214111411141114361436143514361436143514361436141114351412141114111411141214111411141114361436143514361435143614361400051900012a4814000d05000000000000",
                        "off": "2600500000012793141114111411141214111411141114361436143514361436143514361436141114351412141114111411141214111411141114361436143514361435143614361400051900012a4814000d05000000000000"
                    }

**Comment by kiwi-cam** [comment]
In your accessory block change hosts to host. The hosts section is to define hosts if auto discover doesn’t find them. Host, in an accessory, sets which host sends for that accessory.

**Comment by Fung1995** [comment]
It works! Many thanks
