### ISSUE TITLE
Possibility to add delay after on button.

### ISSUE THREAD

**Issue by Jordenjj** [kiwi-cam/homebridge-broadlink-rm#404]
Hello Kiwi-Cam,
I use HomeKit scenes to switch channels on my set top box using my voice. For instance, when I say watch Comedy Central, the TV enters the digits on the remote needed for Comedy Central. This works perfectly, except for when the set top box is off. The reason behind this, is that the set top box starts accepting further controls a second or two after starting up. This means when it switches the channel right after starting up, it misses the digits, or only receives the last meaning it goes to the wrong channel.

My idea would be the possibility to add a delay after every start up.
Say Comedy Central is on channel 12, what it does now is:
1. Send ON hex
2. Send 1 hex
3. Send 2 hex

What I would like it to do is:
1. Send ON hex
2. Wait 2000ms
3. Send 1 hex
4. Send 2 hex.

Thank you for working on this wonderful plugin!

**Comment by masterfordev** [comment]
You can use a "wait", you can see how on the [advanced hex structure](https://broadlink.kiwicam.nz/#advanced-hex-structure) documentation. I did that with my tv too. 😅

**Comment by Jordenjj** [comment]
> You can use a "wait", you can see how on the [advanced hex structure](https://broadlink.kiwicam.nz/#advanced-hex-structure) documentation. I did that with my tv too. 😅 

Thanks for your reply. I use wait for some things too, but I cant enable it to always run _after_ the on command.

In this case, pressing the On button in HomeKit always runs the delay after.

**Comment by masterfordev** [comment]
This is how i did:

```

"on": [
                            {
                                "data": "260050000001219313361238111311131238113812121237121311131138113812131113123713121113121311381237123712131138123711381138121212131212123712131212120005130001234b12000d05000000000000",
                                "pause": 7
                            },
                            {
                                "data": "260050000001219312381237121211141138123711131237121311131238113712131212123812121114113812121213113811131114123711381212123712371213113811381213110005140001234a12000d05000000000000",
                                "pause": 0.3
                            },
                            {
                                "data": "260050000001229311371238121211141237113812121237111411131237123712131113123712131138123712131212123712131212123712131212123712371213113811381212120005140001234a12000d05000000000000",
                                "pause": 0.3
                            },
                            {
                                "data": "260050000001219312381237121211141138123711131237121311131238113712131212123812121114113812121213113811131114123711381212123712371213113811381213110005140001234a12000d05000000000000",
                                "pause": 0.3
                            },
                            {
                                "data": "260050000001229311371238121211141237113812121237111411131237123712131113123712131138123712131212123712131212123712131212123712371213113811381212120005140001234a12000d05000000000000"
                            }
                        ],

```

**Comment by Jordenjj** [comment]
Can you try ending with a wait command, and seeing if that works? Whenever I pause after hex string when there's no command after the pause, the pause is not actually running meaning when I switch channels, it does it and overwriting the pause. Thats the issue.

**Comment by Jordenjj** [comment]
Tried everything and can confirm delay in final command does not delay a successive command
