### ISSUE TITLE
accessory type tv does not display buttons

### ISSUE THREAD

**Issue by atuuling** [kiwi-cam/homebridge-broadlink-rm#405]
{
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": true,
    "hideWelcomeMessage": true,
    "hosts": [
        {
            "address": "10xxx",
            "mac": "a0:xxx",
            "isRFSupported": true,
            "isRM4": true
        }
    ],
    "accessories": [
        {
            "name": "TV",
            "type": "tv",
            "data": {
                "on": "xxx",
                "off": "xxx",
                "volume": {
                    "up": "xxx",
                    "down": "xxx"
                }
            }
        }
    ]
}

**Comment by masterfordev** [comment]
Which buttons?

**Comment by atuuling** [comment]
no remote control is generated

**Comment by masterfordev** [comment]
Like [this](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/102#issuecomment-720813760)? Or how?

**Comment by atuuling** [comment]
Super, thank you very much!

How about continuing the correct code so I can also use the arrows to move, play and pause, and so on.

And please specify how I can make the right product group and icon in homekit if I want to add a projector screen and a home theater/speaker.
I currently use a garage on the projector screen and a TV in my home theater.
The projector screen has a down, pause and up button.
