### ISSUE TITLE
devices not available after latest Homebridge updates

### ISSUE THREAD

**Issue by adrianopery** [kiwi-cam/homebridge-broadlink-rm#412]
After the latest Homebridge update all my 3 devices using Broadlink plugin is appearing as No Response.
I tried to remove the devices, but no success.
I just uninstall and restart the entire system and I couldn't remove the devices on app Home.
So, I reinstall and nothing.

Is only working thru browser Safari or Chrome.

**Smartphone (please complete the following information):**
  - OS: IOS 
 - Version 15

**Additional context**
The plugin is working on Safari or on Chrome, but on app home, I can't them working.

I'm using...
Homebridge : 1.3.5
Versão Node.js: v14.17.4
Versão Npm: v7.20.3
homebridge-broadlink-rm-pro v4.4.6

**Comment by Willygoat1** [comment]
Same here any fix?

**Comment by mwhittem** [comment]
I'm seeing this as well as of a few days ago. It was working fine for the longest time. I'm using HOOBS and had my configuration for homebridge-broadlink-rm-pro (v4.4.6) set to autodiscover. I also tried explicitly setting the hosts config and adding a corresponding host entry for my one accessory but logs show that the Broadlink Pro can not be found.  I can verify though through my router's interface that the device is still on the network and also verified that I can still see it through the Broadlink app. Also verified in the Broadlink app that the "lock" setting is still off.

Here are more details for my HOOBS configuration:
Version	4.0.110
Node Version	14.18.1
Homebridge Version	1.3.4

Broadlink Pro config:
Firmware: V52079 (up-to-date)
SDK: 2.17
Plug-in version: 1.6.7

Lock device: off

**Comment by mwhittem** [comment]
FWIW, I encountered an issue with the same symptoms in the past few days. Communication from Homebridge(HOOBS in my case) was working fine and then stopped working.

I was able to resolve this by:
1. Removing the RM4 Pro from the Broadlink app
2. Depressing the reset button on the RM4 Pro until the blue led continuously flashed in rapid succession (ie not the 3 blinks then pause … if you get that then keep depressing reset)
3. Re-adding the RM4 Pro in the Broadlink app (I use the "RM4 Pro - 2019 version" set-up workflow. AP setup mode does not work for me)
4. Disabling "Lock" again in the Property settings
5. Re-starting the Broadlink plug-in in HOOBS (not sure why this was needed but appeared to be essential)

Note that I explicitly configure a "hosts" entry in my Broadlink-rm plug-in config and set a corresponding entry for my accessories. Although I'm sure auto-discovery configurations would work fine too.

I think the key to getting communication working again was resetting the Broadlink RM4 Pro. I suspect a bug on their side that isn't addressed by simply rebooting the device.

**Comment by andr-ec** [comment]
I'm having the same issue. I tried @mwhittem steps but it didn't help unfortunately.

**Comment by P4Halbig** [comment]
Can confirm this happened to my Homebridge installation as well; only downgrading fixed the issue (after the rebooting RM4 and Homebridge steps).

**Comment by andr-ec** [comment]
I'm just going to note here that what fixed it was updating to the latest release and then renaming the device in the config file. Then it just showed up in accessories under `More options..`
