### ISSUE TITLE
[BUG] Debug logs 'Sending to keepalive to IP Address'

### ISSUE THREAD

**Issue by mitch7391** [kiwi-cam/homebridge-broadlink-rm#418]
**Describe the bug**
Since the latest update (v4.4.7) there is a constant entry in my logs for debug, but I do not have debug enabled.

**To Reproduce**
Steps to reproduce the behaviour:
Install v4.4.7.

**Expected behaviour**
I do not have debug mode active, so I am unsure why I am getting debug logs, I even went into my config and made sure to set `"debug": false` and it still appears in my logs.

**Screenshots**
```
[26/11/2021, 1:01:38 pm] [Broadlink RM] [DEBUG] Sending keepalive to 192.168.0.155 : 80
[26/11/2021, 1:03:08 pm] [Broadlink RM] [DEBUG] Sending keepalive to 192.168.0.155 : 80
[26/11/2021, 1:04:38 pm] [Broadlink RM] [DEBUG] Sending keepalive to 192.168.0.155 : 80
[26/11/2021, 1:06:08 pm] [Broadlink RM] [DEBUG] Sending keepalive to 192.168.0.155 : 80
[26/11/2021, 1:07:38 pm] [Broadlink RM] [DEBUG] Sending keepalive to 192.168.0.155 : 80
[26/11/2021, 1:09:08 pm] [Broadlink RM] [DEBUG] Sending keepalive to 192.168.0.155 : 80
[26/11/2021, 1:10:38 pm] [Broadlink RM] [DEBUG] Sending keepalive to 192.168.0.155 : 80
```

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox]

**Smartphone (please complete the following information):**
- Not relevant 

**Additional context**
The issue with the debug message seems to only be on v4.4.7 and if I revert to the previous version it goes away.

**Comment by masterfordev** [comment]
Same here, roll back to 4.4.6.

**Comment by bondskin** [comment]
same here, also 4.4.8 beta contains this bug

**Comment by Mendelyeev** [comment]
same here too

**Comment by JackMorens** [comment]
same to me, I've tried to set in the configuration this value: "logLevel": 6, but don't change anything...

**Comment by mrmaximas** [comment]
"debug": false, in the plugin config solve this issue for me.

**Comment by mitch7391** [comment]
Forgot to provide feedback @kiwi-cam, your fix in the current beta sorts out the issue (as I am sure you are aware); thanks for this!

**Comment by kiwi-cam** [comment]
Thanks for the update. I'll push a new version next week... assuming work starts to quieten down soon.

**Comment by masterfordev** [comment]
Tested, no issues from here.

**Comment by JackMorens** [comment]
I also confirm the resolution of the problem after installing the 4.4.8-beta.1
