### ISSUE TITLE
No plugin was found

### ISSUE THREAD

**Issue by lorenzoCuevas** [kiwi-cam/homebridge-broadlink-rm#420]
Hi, 
When I first install the plugin into homebridge and modified my config.json it gave me this error:
No plugin was found for the platform "BroadlinkRM" in your config.json. Please make sure the corresponding plugin is installed correctly.

This is the platform name that you gave us to put in the config.json to work with and it still gave me this error and here is the config.json:
{
            "platform": "BroadlinkRM",
            "name": "Broadlink RM"
        }

I wonder what could fix this issue, if so share me the solution.

**Comment by mitch7391** [comment]
Mine is as follows and can confirm it works:

```
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "debug": false,
            "accessories": []
         }

```

I would suggest completely uninstalling the plug-in, removing the config and any cached accessories in Homebridge related, and then re-installing.

**Comment by lorenzoCuevas** [comment]
Okay I'll comment back when something comes up

**Comment by kiwi-cam** [comment]
The error message makes me think this is an installation issue, not a config issue. My interpretation of the error wording makes me think it found "BroadlinkRM" in your config.json, but cannot find the plugin installed. When you installed did you use the global flag - assuming you installed from the command line?

**Comment by lorenzoCuevas** [comment]
No, I did not use the global flag. I installed it from the homebridge web UI.
