### ISSUE TITLE
Can't re-add TV-device

### ISSUE THREAD

**Issue by Marius-19-89** [kiwi-cam/homebridge-broadlink-rm#424]
Hey,

I can't re-add device of type TV, after unassign/delete this device from Home-App.

Stops:
1. configure TV remote in Homebridge config.
2. restart
3. add device in Home-App
4. delete TV from Home
5. ... can't find TV-device to readd.

I delete the whole bridge from Home-App and readded this. But the missing TV-devices are still not shown.

Any idea or bug fix?

I could recognized this bug also on there TV-devices-homebridge-providers. Same issue at @homebridge-samsungtv-control.

**Comment by junkbond916** [comment]
Similar issue here.  Can't get any tv accessory to show up in Home app or remote, regardless of configuration.

**Steps:**
1. Add following (or similar) BroadlinkRM configuration to Homebridge config:

```
{
  "platform": "BroadlinkRM",
  "name": "Broadlink RM",
  "hideScanFrequencyButton": true,
  "hideLearnButton": true,
  "accessories": [
    {
      "name": "Test",
      "type": "tv",
      "data": {
        "on": "<IR CODE>",
        "off": "<IR CODE>",
        "volume": {
          "up": "<IR CODE>",
          "down": "<IR CODE>"
        }
      }
    }
  ]
}
```
2. Save Configuration
3. Restart Homebridge

**Result:**
TV "Test" does not show up in Home app or in remote app.


Homebridge v1.3.8
homebridge-broadlink-rm-pro v4.4.8
IOS 15.1.1
RM mini 3 firmware: V44057

**Comment by Ricky-Garcia1110** [comment]
I have the same problem, I have set up a TV and it is not shown as an accessory

**Comment by junkbond916** [comment]
Not sure if this will help or not, but I struggled a bit with similar issues and eventually found a solution.  

Re: question from @Ricky-Garcia1110 - When you add a TV in the config file, the homebridge log will print instructions on how to add the TV to Homekit.  The process is different than for other accessories (switch, etc) - you have to manually add it by clicking the '+' button on the Homekit App home screen and selecting 'add accessory'.  Then you enter the same code that you entered to add the homebridge itself.  If you already tried this and it still isn't working, it may be a naming issue (see below) or maybe a bug I'm not aware of.  

Re: the question above from @Marius-19-89 - I had a similar issue (couldn't re-add TV after deleting it from HomeKit).  The only way to resolve I found was to rename the accessory in the homebridge config file.  Ie - change the name in the config json from _"name" : "TV"_ to _"name": "TV2"_ or something like that.  Then it reappeared in Homekit.  From there, I just renamed it in Homekit to reflect the name I wanted.  I still think this is a bug, but for the sake of expediency this workaround worked for me.

Hope that helps.

**Comment by Stichoza** [comment]
You need to clear the cached accessories of homebridge (Under "Manage Cached Accessories" in homebridge settings, assuming you have homebridge-config-ui-x), or try "Unpair Bridges / Cameras / TVs / External Accessories" under Reset

**Comment by junkbond916** [comment]
Woot!  That fixed it for me.  Thanks.
