### ISSUE TITLE
Unable to get Homebridge to automatically discover RM4 Pro

### ISSUE THREAD

**Issue by ethandavis4** [kiwi-cam/homebridge-broadlink-rm#431]
I just got a new RM4 pro to go with my homebridge. I am thus far unable to get homebridge to see it. 
I've never edited my config.json file before. I don't know what I am supposed to put in it, or even where in the file to put it. 

I've tried the Broadlink app and the IHC app, but nothing seems to get homebride to discover it. 

I've read all the documentation available but I can't seem to find instructions for someone like me who has no experience with this before. 

I currently have many other plugins in homebridge working without issue, though none of them have be configured manually using the Homebridge UI Config Editor.

Can anyone out there offer me some simple instructions or point me in the right dircetion to getting my RM4 Pro up and running with homebridge? 

Thank you in advance!

**Comment by siangloon** [comment]
Have you try unlocking your broad link device via the broad link app?
