### ISSUE TITLE
Please add broadlink RM 4S

### ISSUE THREAD

**Issue by Archaeus** [kiwi-cam/homebridge-broadlink-rm#44]
![4s](https://user-images.githubusercontent.com/36544054/90613786-6d6d0d80-e23c-11ea-926f-5eb68e5fd09e.png)
thank you

**Comment by kiwi-cam** [comment]
Sorry, this one slipped past me somehow.  I don't see this device code in other projects eithers, could you confirm exactly which device it is?

Broadlink RM4 Mini S - new device, without RF support?
