### ISSUE TITLE
No accessories have been added to the "undefined" platform config.

### ISSUE THREAD

**Issue by danceralison** [kiwi-cam/homebridge-broadlink-rm#441]
I apologize if this isn't the correct forum for this query but I am a total noob and I'm trying my best to set up my Broadlink NM 4 Pro in Hoobs.  I successfully learned the remotes in Broadlink for my track lighting and ceiling fan.  Now I'm trying to add the Broadlink to Hoobs.

I have tried a couple of suggested config.JSONs and each time I get the same result:
"No accessories have been added to the "undefined" platform config."

At one point I had Learn buttons on my Hoobs interface and my Homekit.  I was able to learn the "on" and "off" hex codes and input them to my Hoobs config.JSON but the log still said "No accessories have been added to the "undefined" platform config."

I started from scratch, uninstalled and reinstalled the plugin.  This is the config I have now:

{
	"platform": "BroadlinkRM",
	"name": "Broadlink RM",
	"hideScanFrequencyButton": false,
	"hideLearnButton": false,
	"hideWelcomeMessage": true,
	"hosts": [{
		"address": "192.168.1.90@80",
		"mac": "a0:43:b0:54:43:50",
		"isRFSupported": true,
		"isRM4": true
	}]
}

![Hoobs log](https://user-images.githubusercontent.com/97811446/149642272-b8bc3d15-8449-4cb6-b8da-f0f7d2bae36f.png)

One thing I noticed is that when I hit "save" in the Hoobs config:
"platform": "BroadlinkRM",
automatically changes to
"platform": "homebridge-broadlink-rm-pro"

I don't know if that could be the problem?  Or maybe its because I set up the Broadlink first?  TYIA to anyone who is able to help out this noob.

**Comment by shivanathd** [comment]
I have the same exact issue, I setup the RM4 Pro first on the app, made it learn the RF buttons .. works great.. installed the plugin on HOOBS

`{
    "platform": "homebridge-broadlink-rm-pro",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "hideWelcomeMessage": true,
    "hosts": [
        {
            "address": "192.168.XX.XXX",
            "mac": "34:ea:34:XX:XX:XX",
            "isRFSupported": true,
            "isRM4": true
        }
    ],
    "accessories": [
        {
            "name": "Galaxy Lights",
            "type": "switch",
            "data": {
                "on": "HEX CODE",
                "off": "HEX CODE "
            }
        }
    ]
}`

**Comment by ananthrajah** [comment]
+1

I have the same issue. I just configured the plugin, when I save the config, this is the log from hobos
I tried editing the config.json file directly and did a restart, got this message. Same errors with edit from the gui and restart

Should we move to an olderversion temporarily ?
2022-03-22, 11:13:48 PMBroadlink Rm Pro Bridge starting
2022-03-22, 11:13:54 PMBroadlink Rm Pro BridgeLoaded plugin 'homebridge-broadlink-rm-pro'
2022-03-22, 11:13:54 PMBroadlink Rm Pro BridgeLoading 2 platforms...
2022-03-22, 11:13:54 PMBroadlink Rm Pro BridgeBroadlinkRM[INFO] Automatically discovering Broadlink RM devices.
2022-03-22, 11:13:54 PMBroadlink Rm Pro BridgeBroadlinkRMNo accessories have been added to the "undefined" platform config.
2022-03-22, 11:13:54 PMBroadlink Rm Pro BridgeBridge is running on port 51886.
2022-03-22, 11:13:54 PMBroadlink Rm Pro B

**Comment by Chrisdsawyer** [comment]
I have the exact same issue

has anyone found a solution?

**Comment by apowers313** [comment]
Same issue. Anyone have any luck finding a fix?

@kiwi-cam any ideas on where to start debugging? Happy to submit a pull request if I can find the problem.

**Comment by Willygoat1** [comment]
Same problem, can't find a solution.

**Comment by kiwi-cam** [comment]
Looks like there are a combination of things happening here:

- @shivanathd  and @ananthrajah your platform name needs to be exactly: `"platform":"BroadlinkRM",` refer to: https://broadlink.kiwicam.nz/#installation. It sounds like HOOBS is being "helpful" and reverting that. I haven't used HOOBS but I believe there's an advanced editor that should help.
- @danceralison You need to define an "accessories" section - that's the part that is "undefined". Get started here: https://broadlink.kiwicam.nz/#common-accessory-options and feel free to post what you have if you hit issues.

**Comment by mski363** [comment]
Thanks @kiwi-cam - I've the same challenge - interestingly when I generate the code in Hoobs it adds and additional  line of code at the bottom "platform": "homebridge-broadlink-rm-pro" - see screenshot.  each time I delete it and save code it re-appears?

![Screenshot 2022-06-08 181157](https://user-images.githubusercontent.com/106911942/172566517-01d609e7-15d1-4ce6-8d2e-d25d4b33cadb.jpg)

**Comment by Willygoat1** [comment]
I've added an accessory and I have BroadlinkRM, still getting:
6/8/2022, 6:56:52 PMBroadlink Rm Pro BridgeBroadlinkRM[INFO] Automatically discovering Broadlink RM devices.
6/8/2022, 6:56:52 PMBroadlink Rm Pro BridgeBroadlinkRMNo accessories have been added to the "undefined" platform config.
6/8/2022, 6:56:52 PMBroadlink Rm Pro BridgeBridge is running on port 51856.
6/8/2022, 6:56:52 PMBroadlink Rm Pro BridgeBroadlinkRM[INFO] Discovered Broadlink RM4 Pro (653c) at 192.168.50.253 (a0:43:b0:55:02:fa)
6/8/2022, 6:56:54 PMBroadlink Rm Pro 

{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "hideWelcomeMessage": false,
    "hosts": [
        {
            "address": "192.168.4.174",
            "mac": "a0:43:b0:55:02:fa",
            "isRFSupported": true,
            "isRM4": true
        }
    ],
    "accessories": [
        {
            "name": "Fan",
            "type": "fan",
            "data": {
                "on": "b1c0a200a69e06000407040404040509042104180400016100016700024d270e0c29260e0d28270e270e270e0c29260e270e0d280c290d280c280d280d280d280d280d280d270e270e270d28280d0d280d280d27280d0e270e27280d0d280d00018d280c0e27280d0e27280d280d280d0d27280d280d0e270d280d280d280d270e270e270e270e270e270d280d270e27280d0e270e270d28280d0d270e27280d0e270e0005dc00000000",
                "off": "b1c0a200a69e06000407040404040509042104180400016100016700024d270e0c29260e0d28270e270e270e0c29260e270e0d280c290d280c280d280d280d280d280d280d270e270e270d28280d0d280d280d27280d0e270e27280d0d280d00018d280c0e27280d0e27280d280d280d0d27280d280d0e270d280d280d280d270e270e270e270e270e270d280d270e27280d0e270e270d28280d0d270e27280d0e270e0005dc00000000"
            }
        }
    ]
}

**Comment by Willygoat1** [comment]
I finally got this to work.

**Comment by mski363** [comment]
@Willygoat1 - what did you do?

**Comment by Willygoat1** [comment]
This is all that is in my configuration inside the plugin:

{
    "platform": "homebridge-broadlink-rm-pro"
}

This is in the advanced tab:

{
    "accessories": [],
    "platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "BroadlinkRM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "hosts": [
                {
                    "address": "192.168.50.253",
                    "mac": "a0:43:b0:55:02:fa",
                    "isRFSupported": true,
                    "isRM4": true
                }
            ],
            "accessories": [
                {
                    "name": "Fan",
                    "type": "fan",
                    "data": {
                        "on": "b1c0a200a69e06000407040404040509042104180400016100016700024d270e0c29260e0d28270e270e270e0c29260e270e0d280c290d280c280d280d280d280d280d280d270e270e270d28280d0d280d280d27280d0e270e27280d0d280d00018d280c0e27280d0e27280d280d280d0d27280d280d0e270d280d280d280d270e270e270e270e270e270d280d270e27280d0e270e270d28280d0d270e27280d0e270e0005dc00000000",
                        "off": "b1c0a200a69e06000407040404040509042104180400016100016700024d270e0c29260e0d28270e270e270e0c29260e270e0d280c290d280c280d280d280d280d280d280d270e270e270d28280d0d280d280d27280d0e270e27280d0d280d00018d280c0e27280d0e27280d280d280d0d27280d280d0e270d280d280d280d270e270e270e270e270e270d280d270e27280d0e270e270d28280d0d270e27280d0e270e0005dc00000000"
                    }
                }
            ]
        }
    ]
}

**Comment by Willygoat1** [comment]
The plugin likes to change what you've put in the config. Delete the plugin and bridge. Re-install. Don't put anything in the config in the plugin. Go to the advanced tab, over to the broad link tab, insert the below info, of course change your mac, ip, and hex codes, it will then add another platform and accessory line at the top.

{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "hideWelcomeMessage": false,
    "hosts": [
        {
            "address": "192.168.50.253”,
            "mac": "a0:43:b0:55:02:fa",
            "isRFSupported": true,
            "isRM4": true
        }
    ],
    "accessories": [
        {
            "name": "Fan",
            "type": "fan",
            "data": {
                "on": "b1c0a200a69e06000407040404040509042104180400016100016700024d270e0c29260e0d28270e270e270e0c29260e270e0d280c290d280c280d280d280d280d280d280d270e270e270d28280d0d280d280d27280d0e270e27280d0d280d00018d280c0e27280d0e27280d280d280d0d27280d280d0e270d280d280d280d270e270e270e270e270e270d280d270e27280d0e270e270d28280d0d270e27280d0e270e0005dc00000000",
                "off": "b1c0a200a69e06000407040404040509042104180400016100016700024d270e0c29260e0d28270e270e270e0c29260e270e0d280c290d280c280d280d280d280d280d280d270e270e270d28280d0d280d280d27280d0e270e27280d0d280d00018d280c0e27280d0e27280d280d280d0d27280d280d0e270d280d280d280d270e270e270e270e270e270d280d270e27280d0e270e270d28280d0d270e27280d0e270e0005dc00000000"
            }
        }
    ]
}

**Comment by mski363** [comment]
@Willygoat1 - sweet! worked for me also - didn't realise there was an 'advanced' tab in HOOBS - thanks!

**Comment by mski363** [comment]
@Willygoat1 - How did you get you accessory added to homekit?  I was expecting to see a homekit device code in the log on bridge reboot, but instead get 'Fan Accessory Ready' - seems like I'm almost there :D

**Comment by Willygoat1** [comment]
> @Willygoat1 - How did you get you accessory added to homekit? I was expecting to see a homekit device code in the log on bridge reboot, but instead get 'Fan Accessory Ready' - seems like I'm almost there :D

Have you added the bridge as an accessory?

**Comment by bgiuriceo** [comment]
> The plugin likes to change what you've put in the config. Delete the plugin and bridge. Re-install. Don't put anything in the config in the plugin. Go to the advanced tab, over to the broad link tab, insert the below info, of course change your mac, ip, and hex codes, it will then add another platform and accessory line at the top.
> 
> { "platform": "BroadlinkRM", "name": "BroadlinkRM", "hideScanFrequencyButton": false, "hideLearnButton": false, "hideWelcomeMessage": false, "hosts": [ { "address": "192.168.50.253”, "mac": "a0:43:b0:55:02:fa", "isRFSupported": true, "isRM4": true } ], "accessories": [ { "name": "Fan", "type": "fan", "data": { "on": "b1c0a200a69e06000407040404040509042104180400016100016700024d270e0c29260e0d28270e270e270e0c29260e270e0d280c290d280c280d280d280d280d280d280d270e270e270d28280d0d280d280d27280d0e270e27280d0d280d00018d280c0e27280d0e27280d280d280d0d27280d280d0e270d280d280d280d270e270e270e270e270e270d280d270e27280d0e270e270d28280d0d270e27280d0e270e0005dc00000000", "off": "b1c0a200a69e06000407040404040509042104180400016100016700024d270e0c29260e0d28270e270e270e0c29260e270e0d280c290d280c280d280d280d280d280d280d270e270e270d28280d0d280d280d27280d0e270e27280d0d280d00018d280c0e27280d0e27280d280d280d0d27280d280d0e270d280d280d280d270e270e270e270e270e270d280d270e27280d0e270e270d28280d0d270e27280d0e270e0005dc00000000" } } ] }

Thanks so much for providing this...it works!. Without this I'd still be troubleshooting. It's too bad that the developer did not add this to his documentation. He wrote an awesome plugin.
