### ISSUE TITLE
Is is not clear in the documentation how to make a light not dimmable but a simple switch

### ISSUE THREAD

**Issue by anjrew** [kiwi-cam/homebridge-broadlink-rm#453]
I have a light that is only able to be turned on or off with no intermediate state.

To me, it is not clear in the documentation or any of the parameters in the configuration how to configure the light just to be a simple on/off switch.

**Comment by kiwi-cam** [comment]
You're probably best to set it up as a switch in this plug-in. Within Home you can then change the icon on the switch to then be a light.
