### ISSUE TITLE
tv volume and remote controls don't appear in the Home app.

### ISSUE THREAD

**Issue by Rem9876543** [kiwi-cam/homebridge-broadlink-rm#470]
For the 'tv' accessory, I do not see the "volume" and "remote" controls in the Home app (see screenshot attached). Am I missing something or is it a bug?

Here is the config JSON I am using.
Note: I had the "inputs" section initially, and saw the associated control in the Home app, and when I removed the "inputs" section, the associated control disappeared from the Home app. So that worked fine.
![IMG_1013](https://user-images.githubusercontent.com/101171429/157190099-d8cd794c-1e38-489b-ae07-f0dec4eb4b07.PNG)

                {
                    "name": "VIVO TV",
                    "type": "tv",
                    "data": {
                        "on": [
                            {
                                "data": "260058000001239514111114121410141213121311141114153511381435113815351236153511141412133514351237113812141014121411381213121413121113153514351435110005400001254b11000c490001254a12000d050000000000000000000000000000",
                                "pause": 3
                            },
                            {
                                "data": "260058000001239514111114121410141213121311141114153511381435113815351236153511141412133514351237113812141014121411381213121413121113153514351435110005400001254b11000c490001254a12000d050000000000000000000000000000"
                            }
                        ],
                        "off": "260058000001239514111114121410141213121311141114153511381435113815351236153511141412133514351237113812141014121411381213121413121113153514351435110005400001254b11000c490001254a12000d050000000000000000000000000000",
                        "remote": {
                            "select": "2600580000012593141210141511131114121113141211131535113811381435153514351138141211371535113715351336141211371412101415111410151112131138141113351500053c0001264a15000c450001264915000d050000000000000000000000000000",
                            "arrowUp": "2600580000012493131212131114131212121412111314111436103913371536103913371238131212371238121413101511111411131312121410131535133614371337123811381400053e0001294712000c470001264a12000d050000000000000000000000000000",
                            "arrowDown": "2600580000012592141210141511121215111114131211141435113814351336153514351138141114121435133614351138141213351412133514121311111415101336141210381400053d0001284811000c490001264914000d050000000000000000000000000000",
                            "arrowLeft": "2600580000012691141113111214141213111311121410141436133613371536123714361436141114111436141115111311131214111311153511141138143613371437103914361400053e0001284810000c480001284911000d050000000000000000000000000000",
                            "arrowRight": "26005800000127911510141111141213141111141213111311391435123912381138123815361113121315120f1415101511101414361113123814351536123811391138121411391200053f0001274911000c490001254b14000d050000000000000000000000000000",
                            "info": "2600580000012394131212131214111312141114111413121336123712371238113813361138141211141114123711381237121315111113143611371511141012141237143613361100053f0001254b12000c490001244b12000d050000000000000000000000000000"
                        },
                        "volume": {
                            "up": "2600580000012593131212131113141113111511111414111238103913371337113813371437131113121238141115361114131212121214133714121138151111391337133711381400053e0001294712000c470001264a14000d050000000000000000000000000000",
                            "down": "26005800000125931213111312131312121213121313111312381138123912381138123812391113121314371238111312131213131112131239121315120f3912381238113812391200053f0001254b14000c460001254b10000d050000000000000000000000000000"
                        }
                    }
                }

Thanks for your great work by the way!!!

**Comment by pirates-killer** [comment]
In iOS setting > Control Centre > (add) Apple TV Remote

Then open your control centre, click on Apple TV Remote Icon, it should appear there. You can control your volume using your devices volume keys

Your code looks good I think. This is what I use currently. 

```json
 {
            "name": "Haier TV",
            "type": "tv",
            "subType" : "tv",            
            "data": {
                "on": "26004800000125941312131311391213121313131114131212381338121312381238123813381138131213131213123812141213121312131337133712391114123812381238133713000d050000000000000000000000000000",
                "off": "26004800000125941312131311391213121313131114131212381338121312381238123813381138131213131213123812141213121312131337133712391114123812381238133713000d050000000000000000000000000000",
                "remote": {
                    "select": "26005000000125941313121312381213131311141213131311391139121312381337133712381337121412160f3812131313111412381312123812381313123811391238121313371300051d0001264b13000d05000000000000",
                    "arrowUp": "2600500000012693121313131238121313131213111412141139123811141337123813371337133712141114131213131114121312381313123812381238113911391238131212381200051f0001284913000d05000000000000",
                    "arrowDown": "26004800000124951313121311391312121313131213121312391238121312381238123813371238133712141114121313131213123812131214123812381238123811391114123812000d050000000000000000000000000000",
                    "arrowLeft": "2600500000012693131311141238131212141114121313131139123811141337123812381238123812391238123812131312131312131312131311141312123813371338113912381100051f0001274a11000d05000000000000",
                    "arrowRight": "26004800000125941312131311391114121313131213131212381337121411381338113912381238131212381337131311141312121411141238131213131139123812381238123812000d050000000000000000000000000000",
                    "playPause": "2600500000012495131212141238121313121214121313121238133812131139123812381238133713381138133713131114121312381313111412131214123812381337121313371300051e0001274a11000d05000000000000",
                    "info" : "2600500000012594131212141238121312131214111412131337123812141139113911391238123812381238121313381238121312381213121411141238121312141238111412381300051e0001254b13000d05000000000000",
                    "nextTrack" : "2600500000012594121313121238131311141214111411141238123812141139123811391139123812131213123813131139121312381238133712381313123812131238131213131200051e0001274a12000d05000000000000",
                    "previousTrack" : "26004800000125941313111412381213131312131114121412381139131213371238133713371337123813371313111412381213123911391213121313371337131312381213131312000d050000000000000000000000000000",
                    "back" : "26004800000124951213121412381114121312141213121313371238131312381238113911391238123912381113133712141213121312141213131213371214113912381139123812000d050000000000000000000000000000"
                },
                "volume": {
                    "up": "26004800000125941213141211391114121312141213121312381238131311391238123811391238121313371214121313121313121313121238121412381139123812381239123713000d050000000000000000000000000000",
                    "down": "26004800000125941213121411391214121213131114121313371338111411391238123813371337123813371313121312141213131213121313111413371337133712381238133812000d050000000000000000000000000000"
                }
            }
        }

```
