### ISSUE TITLE
Support of BroadLink RM4C Pro?

### ISSUE THREAD

**Issue by sunnycmf** [kiwi-cam/homebridge-broadlink-rm#472]
Hi, I'm considering to buy RM4C Pro and use it with home bridge, wondering anyone is using this setup now?

**Comment by kiwi-cam** [comment]
The platform has support for one RM4C Pro model: https://github.com/kiwi-cam/broadlinkjs-rm/blob/7d7122370592c426e0b5d33f429d60012638d0fe/index.js#L58. It's likely others will work too - just note there are some issues learning 315MHz RF codes: https://broadlink.kiwicam.nz/#RFScanIssue
