### ISSUE TITLE
How to use codes from http://www.remotecentral.com/

### ISSUE THREAD

**Issue by thejurassic** [kiwi-cam/homebridge-broadlink-rm#473]
This website http://www.remotecentral.com/ seems to have a lot of codes which I'd like to use. Specifically they show a Sony TV ON code and OFF code. If I capture the hex using the Learn in the Home app then it gives a vastly longer code than is provided on this website. The code I learn from the app does work, but it is simply a power toggle command. The codes ive tried from this website dont work but I'm guessing its becuase they are only a quater of the length of the code that homebridge-broadlink-rm identifies and prints to console when you learn an IR code. I'd like to use the specific POWER ON and POWER OFF commands to ensure i dont accidently power the tv on when i send a power off command. Is it possible to convert the codes listed on this website to the same format that homebridge-broadlink-rm uses?

**Comment by movy** [comment]
@thejurassic , could you solve this? Facing similar issue with Daiking AC, as its remote offers only power toggle code, but I need sure way to turn it off or on...
