### ISSUE TITLE
Heater Cooler not working correctly on iOS 15.4

### ISSUE THREAD

**Issue by elkinjosetm** [kiwi-cam/homebridge-broadlink-rm#475]
After updating to iOS 15.4, my heater-cooler accessories are not working with Siri, I can still use them from the Home app, but asking Siri to turn the  on/off or changing the temperature doesn't work. Siri's answer: "your heater doesn't support this functionality"

Module version: 4.4.9
Hoobs version: 4.0.110

**Comment by tibtiby** [comment]
noticed the same behaviour on 15.4. siri says: "hmmm...there are no accessories in the living room that support temperature control." there was no such problem before 15.4. 
module version: 4.4.9
homebridge version: 1.4.0
node: 16.14.2
npm: 8.5.5

**Comment by powjk** [comment]
Same here after upgrading to 15.4. 
Switching on or off works with Siri, but not setting up the temperature.

module version: 4.4.9
homebridge version: 1.4.0
node: 14.18.0
nem: 6.14.15

**Comment by elkinjosetm** [comment]
Any update on this?

**Comment by LiranCaduri** [comment]
Having the same issue too.
Is there a patch for this?
Thanks in advance.

**Comment by esosan** [comment]
Same here with iOS 15.4.1 / v4.4.10

**Comment by tibtiby** [comment]
noticed another bug that wasn’t there before. my heater-cooler accessory has 4 speed levels (25%-50%-75%-100%) and when I tell siri to set an accessory to 25%, it drops it from 100% to 75% and must repeat the command until il reaches 25% speed, whereas before the update it would have set the desired speed right away.

**Comment by solvpnvpn** [comment]
Upgraded iphone and homepod mini to ios 15.5 and the voice command for temperature setting is working again.

**Comment by LiranCaduri** [comment]
> Upgraded iphone and homepod mini to ios 15.5 and the voice command for temperature setting is working again.

Worked for me too :)

**Comment by elkinjosetm** [comment]
Yes, it's working again after the iOS update. Closing this issue.
