### ISSUE TITLE
"This plugin generated a warning from the characteristic 'Relative Humidity Dehumidifier Threshold'"

### ISSUE THREAD

**Issue by SymphonX** [kiwi-cam/homebridge-broadlink-rm#477]
Great project!

Issue: Using the plugin with an RM 4 Pro to control a humidifer via IR, my homebridge log is littered with warnings stating the following: 

[homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Relative Humidity Dehumidifier Threshold': characteristic value 0 is not contained in valid values array. See https://git.io/JtMGR for more info.

This warning is being spilled out every 15 mins, leading to relatively large log files that need to be deleted upon maintenance. Not exactly ideal if you want to prolong the life of an SD card running on a Raspberry Pi (arch-linux, latest Homebridge and plugin [v4.4.9], with everything else working as expected). 

My config is attached below. I don't think there are any mistakes but just in case.

Would appreciate any help!

Thanks! 

------------------------------

{
    "bridge": {
        "name": "Homebridge 81DE",
        "username": "secret",
        "port": 51117,
        "pin": "secret"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "accessories": [
                {
                    "name": "Klarstein",
                    "type": "humidifier-dehumidifier",
                    "humidifierOnly": true,
                    "showSwingMode": true,
                    "defaultFanSpeed": 33,
                    "threshold": 1,
                    "alwaysResetToDefaults": true,
                    "persistSate": false,
                    "noHumidity": true,
                    "data": {
                        "on": [
                            {
                                "comment": "TURNS ON DEVICE AND ENABLES COOLING MODE",
                                "data": "26002201280e2a0e0e292a0e2a0e0e290f290e290f290f290e292ae72a0e2a0e0e292a0e2a0e0e290f290f290e2a0e290f2929e72a0e2a0e0e292a0e2a0e0e290f290f290e290f290e2a29e72a0e2a0e0e292a0e2a0e0e290f290f290e290f290e2a29e72a0e2a0e0e2a290e2a0e0e290f290f290e290f290e2a29e72a0e2a0e0e292a0e2a0e0e2a0e2a0d2a0e290f290e292ae72a0e290e0f292a0e290e0f290e290f290e2a0e290f292ae7290e2a0e0e292a0e2a0e0e290f290e290f290f290e292ae72a0e290e0f29290e2a0e0e290f290e2a0e290f290e292ae7290e2a0e0e2a290e2a0e0e290f290e290f290e290f292ae62a0e2a0e0e292a0e290e0f290e290f290e290f290e292ae72a0d2a0e0e292a0e2a0e0e290e290f290e290f290e292a000d0500000000",
                                "pause": 2
                            },
                            {
                                "data": "26006a01270e2a0e0e2a290f2a0d2a0e0d2a0e2a0d2b0d2a2a0e29e8290f290e0e2a2a0e290e2a0e0d2b0d2a0e2a0f282a0e2ae8290e290e0e2a290f290e2a0e0d2b0d2a0f290d2a2a0e29e8290e2a0e0d2b290e2a0e290f0d2a0d2b0d2a0e2a290e2ae72a0e2a0d0e2a2810290e2a0e0d2a0e2a0d2b0d2a2a0e29e72a0e290f0d2a2a0e27102a0e0d2a0e2a0d2b0d2a2a0e2ae62a0e290e0e2a290f290e290f0c2b0d2b0d2a0d2b290e29e72a0e27100e2a290e290f290e0d2a0e2a0d2a0f28290f27e8290f27100d2a28102710290e0d2a0d2a0d2a0d2a290e29e52a0e290e0d2a2710280e290e0d2a0d2a0d290e29290e28e4290e27100d2a270f271026100c2a0d2a0d290d2a280e26e52610280e0d2a2610261026100d290d290d290d29280e28e1270f280e0d292610280e260f0d290d280d290d29260f28e02610270e0c2a260f280e25100d280d280d290c29260f26e0270e260f0d29260f270e270e0c290c280d280d28280d26000d05000000000000000000000000",
                                "pause": 2
                            },
                            {
                                "comment": "WIND DIRECTION AUTO ON",
                                "data": "2600640125102a0e0e2a290e28100e2a0d2a28100d2b0d2a0e2a0d000104281027100e2a271028100e2a0d2a28100d2b0d2a0e2a0d000104271028100e2a271028100d2b0d2a28100d2a0e2a0d2b0d000103281028100d2a281028100d2a0e2a27100e2a0d2b0d2a0e000103280f290f0d2b271028100d2a0e2a27100e2a0d2a0e2a0d000104271028100d2b271027100e2a0d2a28100d2a0e2a0d2a0e000103271028100d2a281027100e2a0d2a28100d2a0d2b0d2a0d000103281027100d2a281027100d2a0e2a27100d2a0d2a0d2a0e000102271027100e29281027100d290e2927100d2a0d2a0d2a0d000101271027100d2a270f27100d2a0d2927100d290e290d290eff2710270f0d2a270f27100d290d29270f0e290d290d290dfe270f27100d29270f270f0d290d2926100d290d290d290dfc270f270f0d29261026100d280d29260f0f270d280d290dfb2610260f0d29260f26100d280d2826100e270d280d290c000d050000"
                            }
                        ],
                        "off": [
                            {
                                "data": "2600b201261028100d2a281028100d2a0e2a0d2b0d2a0e2a0d2b27ea271028100e2a280f290f0d2b0d2a0e2a0d2b0d2a0e2b27e9281027100e2a290e28100e2a0d2a0e2a0d2b0d2a0e2a27e8291028100e2a271028100f290d2a0f290d2a0e2a0e2a27ea271028100f29271028100d2a0e2a0e2a0d2a0e2a0d2b27e9281028100d2a281028100d2a0e2a0d2b0d2a0d2b0d2a28e92810290e0e2a281027100d2b0d2a0e2a0d2a0e2a0e2a29e728102a0e0d2a2810271010280d2b0d2a0e2a0d2a0e2a29e72810290f0f282a0e290e0f290d2a0f290d2a0e2a0f282ae72a0e290e0f29290e2a0e0f2810280f2810280d2a10282ae62810290f0f282810290e0f290f280d2a0e2a0f28102829e72a0e290e0f29290e290e10280d2a0d2a0e2a0f280e2a29e62a0e290e0e2a2710290e0d2a0d2a0f2810280d2a0f2829e62a0e290e0e29290e290e0d2a0f280f280d2a0d290e2929e6290e290e0f27290e290e0f270f280f280f280f270f2827e6270f290e0f28280e290e0e280f270f280f270f270f2829e4270e280e0f28280e280e0d290f270f270f270f270f2729e2280e280e0f27280e280e0e270f270f270f270d290f2726000d0500000000",
                                "sendCount": 3,
                                "interval": 0.3
                            }
                        ],
                        "swingToggle": "2600640125102a0e0e2a290e28100e2a0d2a28100d2b0d2a0e2a0d000104281027100e2a271028100e2a0d2a28100d2b0d2a0e2a0d000104271028100e2a271028100d2b0d2a28100d2a0e2a0d2b0d000103281028100d2a281028100d2a0e2a27100e2a0d2b0d2a0e000103280f290f0d2b271028100d2a0e2a27100e2a0d2a0e2a0d000104271028100d2b271027100e2a0d2a28100d2a0e2a0d2a0e000103271028100d2a281027100e2a0d2a28100d2a0d2b0d2a0d000103281027100d2a281027100d2a0e2a27100d2a0d2a0d2a0e000102271027100e29281027100d290e2927100d2a0d2a0d2a0d000101271027100d2a270f27100d2a0d2927100d290e290d290eff2710270f0d2a270f27100d290d29270f0e290d290d290dfe270f27100d29270f270f0d290d2926100d290d290d290dfc270f270f0d29261026100d280d29260f0f270d280d290dfb2610260f0d29260f26100d280d2826100e270d280d290c000d050000",
                        "fanSpeed33": "2600d000280e290e0e2a290e28100f280e2a0d2a0e2a0d2a290f0d000103290e2a0e0d2a2810290e0e2a0f280e2a0d2a0d2b290e0d0001032a0e290e1028271028100d2a0e2a0d2a0e2a0d2a2a0e0d000103280f2a0e0d2a2a0e280f0e2a0d2a0e2a0d2a0e2a290e0e000103290e2a0e0d2b290e27100e2a0d2a0e2a0d2a0e2a27100e000102281027100e2a290e2a0e0d2a0e2a0d2a0e2a0d2a28100d000103280f28100d2a2810280f0e2a0d2a0e2a0d2a0e2a27100e000103271028100d2a281027100e2a0d2a0e2a0d2a0e2a27100e000d05000000000000",
                        "fanSpeed66": "2600ea00261028100d2a281027100e2a0d2a0e2a0d2a0e2a27100e000102281028100d2a281027100d2b0d2a0d2a0e2a0d2b27100d000103281027100e2a271028100d2a0e2a0d2a0e2a0d2a28100d000103271028100d2a281027100e2a0d2a0e2a0d2a0e2a27100e000102281027100e2a27102a0e0d2a0e2a0d2a0e2a0d2a28100d000103280f28100d2a281027100e2a0d2a0e2a0d2a0e2a27100e0001022810280f0e2a280f28100d2a0e2a0d2a0e2a0d2a290f0d0001032a0e27100d2b290e28100d2a0d2a0e2a0d2a0e2a27100e0001022a0e290e0e2a2a0e280f0d2a0e2a0d2a0e2a0d2a2a0e0f000d05000000000000000000000000",
                        "fanspeed100": "26000401280e27100e2a290e290f0d2a0d2b0d2a0d2b0d2a280f0e000103290e28100d2a2a0e27100e2a0d2a0d2b0d2a0d2b290e0d000103281027100e2a271028100d2a0d2b0d2a0d2a0e2a27100e0001022810290e0e2a290e28100d2a0e2a0d2a0e2a0d2a28100d00010327102a0e0d2a280f2a0e0d2b0d2a0d2a0e2a0d2a2a0e0d0001032a0e290e0d2a2810290f0d2a0d2a0e2a0d2a0e2a27100e00010327102a0e0d2a2810290e0d2b0d2a0e2a0d2a0e2a290e0d0001032810290e0e2a290e2a0e0d2a0e2a0d2a0e2a0d2a2a0e0d000103290e2a0e0d2b2a0d290e0e2a0d2a0e2a0d2a0e2a290e0e000103290e2a0e0d2a2a0e27100e2a0d2a0e2a0d2a0e2a290e0e000d050000"
                    }
                },
                {
                    "name": "Klarstein COOLING",
                    "type": "switch",
                    "persistState": true,
                    "data": {
                        "on": "26005201261027100e2a2710281027100d2a0e2a0d2a0e2a271028e82810290e0e2a2710281027100e2a0d2a0d2a0e2a271028e8281027100e2a2710281027100e2a0d2a0e2a0d2a281027e9271028100d2a2810271028100f280f290f280f29271029e72a0e290e0f29290e2a0e290e10280f280f290f282a0e29e7290e2a0e0f282a0e290e2a0e0f280f290f280f29290e2ae62a0e290e0f29290e2a0e290e0f290f280f281028290e2ae7290e2a0e0f282a0e290e2a0e0f280f290f280f282a0e29e72a0e290e0f29290e2a0e290e0f2810280f281028290e2ae62b0d2a0d10282a0d2a0e2a0d10280f2810280f282a0e2ae7280e2a0e0f282a0e290e2a0e0f2810280f281028290e2ae62a0e290e1028290e2a0e290e10280f280f290f282a0e29e7290e2a0e0f282a0e290e2a0e0f280f290f290e29290e2ae62a0e290e1028290e2a0e290e10280f2810280f282a0e29000d0500000000",
                        "off": "260022012610280f0e2a2710281027100e2a0d2a0e2a0d2a281027e9271028100d2a2810271028100d2a0e2a0d2a0e2a271028e9271027100e2a2710281027100e2a0d2a0d2a0e2a271028e8281027100e2a2710281027100e2a0d2a0e2a0d2a281027e9271028100d2a2810271028100d2a0e2a0d2a0e2a271028e8281027100e2a2710281027100e2a0d2a0e2a0d2a281027e9271028100d2a2810271028100d2a0e2a0d2a0e2a271028e8281027100e2a2710281027100e2a0d2a0e2a0d2a281027e9271028100d2a28102710281013250d2a0d2a0d2a281028e8281027100e2a2710281027100e2a0d2a0e2a0d2a281027ea270f28100d2a2810271028100d2a0d2a0e2a0d2a281027e9281027100d2a2810271028100d2a0e2a0d2a0e2a271028000d0500000000"
                    }
                },
                {
                    "name": "Klarstein MODE",
                    "type": "switch",
                    "stateless": true,
                    "enableAutoOff": true,
                    "onDuration": 0.1,
                    "data": {
                        "on": "2600b8000c000a3c2a0e290e0e2a290e290f0d2a0e2a0d2a0d2a2a0e0d2a0e000103290e290f0d2a290f290e0d2a0e2a0f280e2a290e0e2a0f000101290e2a0e0d2a290f290e0f290d2a0e2a0d2a290f0d2a0d000103290e2a0e0d2a2a0e290e0f290d2a0d2b0d2a290e0e2b0c000103290e2a0e0f282a0e290e0e2a0f280d2a1028290e0e2a0dfe2e0e28100d2a2a0e290e0e2a0d2a0d2a0e2a290e0e2a0d000103290e2a0e0d2a290f290e0d2a0e2a0d2b1225290e0e2a0d000d050000000000000000000000000000"
                    }
                },
                {
                    "name": "Klarstein TIMER",
                    "type": "switch",
                    "stateless": true,
                    "enableAutoOff": true,
                    "onDuration": 0.1,
                    "data": {
                        "on": "26003801270e2a0e0d2a2a0e290e0e2a0f280f29290e0f290e290f0001012a0e290e0f29290e2a0e0f280f290f282a0e0f280f290f000101290f290e0d2b290e2a0e0f280f281029290d0e2a0d2a0e000103290e2a0e0f282a0e290e0e2a0d2a0e2a290e0e2a0f280f0001012a0e2a0e0f28290f290e0f290f280f29290e0f290f280f0001012a0e290e0e2a290e2a0e0f280e2a0f282a0e0d2a0e2a0f0001012a0e290e0f29290e2a0e0d2a0f290f282a0e0f280f290d000104280f290e0d2b290e2a0e0d2a0f290d2a2a0e0d2a0f290f000101290e2a0e0d2a2a0e290e10280e291028290e0e2a0f2810000101290e290f0f28290f290e0d2a10280d2b290e0f290f280f0001012a0e290e0f29290e2a0e0d2a0f290f282a0e0d2a0e2a0d000103290e2a0e0d2a2a0e290e0e2a0f280f29290e0e2a0f280f000d050000000000000000000000000000"
                    }
                },
                {
                    "name": "DeLonghi POWER",
                    "type": "switch",
                    "persistState": false,
                    "data": {
                        "on": "2600580000012a94133814371337133715371312141113131337133715371337133715371337143615371337131313121411131313111537131115111337153713371337153713111500047200012a4b13000c7800012a4b13000d050000000000000000000000000000",
                        "off": [
                            {
                                "data": "2600780000012995133713371537133713371511131313111437143713371437143713381337143713371437141114121312141114121238141212131337133814371337133814111300047200012b4a14000c7600012a4915000c7500012b4915000c7500012c4914000c7800012b4915000c7900012b4914000d050000000000000000000000000000",
                                "sendCount": 3,
                                "interval": 0.3
                            }
                        ]
                    }
                },
                {
                    "name": "DeLonghi SWING",
                    "type": "switch",
                    "persistState": true,
                    "data": {
                        "on": "2600580000012995143713371437143713371412131214111437143713371437143713371437143713381312133714121312141213121337141213371412133714371437133714121300047200012a4c11000c7b00012a4c11000d050000000000000000000000000000",
                        "off": "2600580000012995143713371437143713371412131214111437143713371437143713371437143713381312133714121312141213121337141213371412133714371437133714121300047200012a4c11000c7b00012a4c11000d050000000000000000000000000000"
                    }
                },
                {
                    "name": "DeLonghi UP",
                    "type": "switch",
                    "stateless": true,
                    "enableAutoOff": true,
                    "onDuration": 0.1,
                    "data": {
                        "on": "26005800000127971139123a1139113a12391114121311151139113a12391139113a12391139113a1213121411391214111412141114113912391239111412391139123912391114120004750001294b12000c7b0001294c11000d050000000000000000000000000000"
                    }
                },
                {
                    "name": "DeLonghi DOWN",
                    "type": "switch",
                    "stateless": true,
                    "enableAutoOff": true,
                    "onDuration": 0.1,
                    "data": {
                        "on": "2600580000012896123912391139113a12391214111311151139113b11391139123912391139113a1213121411151114111411151113113a13381139123a11391239113913381115110004750001284d11000c7c0001274d11000d050000000000000000000000000000",
                        "off": "2600580000012896123912391139113a12391214111311151139113b11391139123912391139113a1213121411151114111411151113113a13381139123a11391239113913381115110004750001284d11000c7c0001274d11000d050000000000000000000000000000"
                    }
                },
                {
                    "name": "DeLonghi ECO",
                    "type": "switch",
                    "stateless": true,
                    "enableAutoOff": true,
                    "onDuration": 0.1,
                    "data": {
                        "on": "26006800000127971139123a113911391438111312141115113911391239123911391239123911391214113912141114111412141114113a1139121411391239113a1139123a1014120004730001294d11000c7a0001284c11000c7a0001284c13000c790001284c13000d050000000000000000000000000000",
                        "off": "2600680000012796133812391139123a103a11141114121411391338113a113a12381139123a12381114123912131213111511141213113a123911141338113911391339113911151100047300012a4b11000c7900012a4a12000c7800012b4912000c7800012b4a11000d050000000000000000000000000000"
                    }
                },
                {
                    "name": "DeLonghi SILENT",
                    "type": "switch",
                    "stateless": true,
                    "enableAutoOff": true,
                    "onDuration": 0.1,
                    "data": {
                        "on": "260058000001279711391438133711391437141114121114133811391437113a11391437133811391412113914371114141112141312143713381114131214371337123914371312140004710001294c12000c780001294c12000d050000000000000000000000000000",
                        "off": "2600600000012797113a13381337113a123911141114111513371139123a1139113912391239113914121139143711141412111413121437113a1114111412391139123913381114140004720001284c12000c790001284c11000c790001294c11000d05000000000000"
                    }
                },
                {
                    "name": "BL Humidity",
                    "type": "humiditySensor"
                },
                {
                    "name": "BL Temperature",
                    "type": "temperatureSensor"
                }
            ]
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
]
}

**Comment by SymphonX** [comment]
Anyone? I would really appreciate any help with this! 

Thanks!

**Comment by Al-Mclean** [comment]
Same issue here

**Comment by kard8** [comment]
Hi @SymphonX ,

I had a similar error with an heater cooler accessory. I had an older version in the config file without the noHumidity data. The error disappeared after Added that single line of code. And the error disappeared.

Please try this.

```

{
    "name": "BL Temperature",
    "type": "temperatureSensor",
    "noHumidity" : true
}

```

Let me know the results. :+1:

**Comment by Al-Mclean** [comment]
Hi @kard8 ,

I had to add the line within the accessory, type "air-conditioner", but it did the job - thanks a heap!
(Note: my issue was on an RM mini 3)

Cheers!

**Comment by SymphonX** [comment]
> 

Hi @kard8,

Thanks for helping out! Much appreciated.

Unfortunately, the "nohumditiy" argument does not help in my case. As you can see above (in the pasted config file), I had nohumidity included already in my initial config. Neither that nor removing the threshold argument changes anything. The issue stems from the way the plugin handles humidifier-dehumidifier accessories. As things stand, I will likely have to make a switch to another solution in the near future. The constant logging clogs up my memory card and reduces its lifespan. A shame. 

Anyway, thanks for trying to help!
