### ISSUE TITLE
Enable setting "minimum time between commands" for window-covering

### ISSUE THREAD

**Issue by seidnerj** [kiwi-cam/homebridge-broadlink-rm#478]
My situation is as follows: I have a window covering that takes about 1 second to respond to an IR signal. Once the first signal, say "open", is sent it starts processing it and it takes about 1 second until it actually starts opening. Any other signal sent in that 1 second is ignored by the window covering. 

The scenario that I deal with many times is someone opens then immediately closes the window covering via the home app (e.g. they did not intend to open it originally and actually want to keep it closed). What happens in this case is that since the window covering ignores the "close" signal it just ends up opening all the way but the status in HomeKit shows that its actually closed. This is very frustrating.

If there was an option to set a time between consecutive commands during which another command cannot be sent, this would solve this. I tried solving this by using "initialDelay" but that doesn't really makes sense since for the initial command this is not applicable, also the window covering's behavior is not reflected in the Home app's UI reflecting that you simply cannot send a signal until X seconds has passed (e.g. reflected via the device showing a timeout or something similar).

Thanks in advance.

**Comment by seidnerj** [comment]
An additional option that would be good is instead of ignoring the command, which is what I suggested before, you could opt to have the command sent after X seconds, ensuring that it will have an effect. You could then choose what makes the most sense for your scenario.

**Comment by Avi0n** [comment]
I still think this is a good feature to add.
