### ISSUE TITLE
Finds wrong model

### ISSUE THREAD

**Issue by Cloudore** [kiwi-cam/homebridge-broadlink-rm#48]
Hey! I've been out for a while, haven't been automating too much in the last months, but this weekend i was back in business,

Decided to update this plugin because I'm expecting a couple broad link minis, however, with the one I already have (a PRO one with the temperature sensor), it seems that it now discovers it as a PRO+ (The version without the temperature sensor).

`[8/29/2020, 22:37:23] [Broadlink RM] [INFO] Discovered Broadlink RM2 Pro Plus v2 (2787) at 10.0.1.20 (xx:xx:xx:xx:c9:92)`

This made it so that the AC would be not responding, as the plugin could not find a temperature to attribute to the AC accessory, probably because its not trying to reach the sensor as it does not expect that model to have one, I have corrected the issue putting in the json the line:
`                    "pseudoDeviceTemperature": 28,`
But of course now I'm missing temperature readings and its stuck at 28, I might upgrade this one to the RM 4 Plus, with the temperature sensor cable, but wanted to expose this possible bug nonetheless, i tried searching where in the plug in the match happens, searched for "2787" and "Broadlink RM2 Pro Plus", didn't try to hard as I haven't had the time.

Best regards and thanks for the constant updates!

**Comment by Cloudore** [comment]
https://github.com/kiwi-cam/broadlinkjs-rm/blob/master/index.js

Found where it matches, tried changing "Broadlink RM2 Pro Plus v2" to "Broadlink RM2 Pro Plus" but that didn't make it try to fetch the temperature as before

I think mine might be a Broadlink RM2 and the index incorrectly assumes it does not have RF?mine definitely does, as I use it to control my shades, In the IHC app it is labeled as "RM PRO". PID according to the IHC app is ...00087270000

**Comment by kiwi-cam** [comment]
It should be getting RF support, being it's identified as a "Plus" device.

Could you enable debugging and share your logs? It should certainly be attempting to get the temperature from the device (if no other sources are configured).

**Comment by kiwi-cam** [comment]
This should've been resolved in the updated hosts functionality. Custom "manual" device types added to support configured options.

Let me know if there are any ongoing issues.
