### ISSUE TITLE
Unknown Broadlink Device - 5216

### ISSUE THREAD

**Issue by okthx1** [kiwi-cam/homebridge-broadlink-rm#483]
Receiving the message:

We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "5216". The device is connected to your network with the IP address ***

This is the latest RM mini 4 bought from amazon. Not sure if I'm missing anything in the setup on my end of if that code needs to be added to the beta. Thanks in advance for any help

**Comment by ghost** [comment]
I too am receiving the above error. Did you happen to find a resolution?

**Comment by ericmazur** [comment]
I have the same error with a device received from Amazon one day ago. The device type code is 5213, however.

**Comment by aw-0** [comment]
Encountered this same issue just now with an RM4 Pro delivered today. [Manually adding the host of the device](https://broadlink.kiwicam.nz/#device-discovery) ended up fixing this on my end.

**Comment by FBomb55** [comment]
I'm also having the same issue. I tried manually adding the host but couldn't get it to work.

**Comment by kiwi-cam** [comment]
Could you please confirm what type of devices these are - I'll add them to the configuration?

5213 - ??
5216 - RM mini 4 ?

**Comment by ghost** [comment]
RM4 Mini

**Comment by tylerdak** [comment]
I am also having this issue. Code 5216 with an RM4 Mini

**Comment by crofford** [comment]
I'm receiving 5213 for an RM 4 Pro

**Comment by kiwi-cam** [comment]
Beta 4.4.11-beta.3 should support these two devices now.
