### ISSUE TITLE
Suddenly "Device not found"

### ISSUE THREAD

**Issue by Cesco117** [kiwi-cam/homebridge-broadlink-rm#484]
Hi,

I love this plugin ! But one day, without any reason, the plugin stopped working.
When I try to make a command, I have the "no device found" on the log. Same thing on the "Learn" or "Scan Frequency".

- I checked that "lock device" is still off on the Broadlink app.
- The broadlink app still works like before, perfectly.

I tried to reboot homebridge, come back on a previous version, and even restart my Broadlink, same issue.

How can I resolve this issue ?
Can I "help" the plugin find my Broadlink with an IP setting ?

Thanks a lot !

-- -- --

[4/16/2022, 8:05:43 PM] [Broadlink RM] Ecran setSwitchState: true
[4/16/2022, 8:05:43 PM] [Broadlink RM] [ERROR] Ecran sendData (no device found)

-- -- --

Here is the config file, just in case 👍 

{
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "accessories": [
                {
                    "name": "Ecran",
                    "type": "switch",
                    "data": {
                        "on": "b1c07c00b09e060045220c0001530c20210b0b20220a210b210b200c200b210b210b0b210a210b210b210b20210b0b21200b210b210b0b21200c0a210b230b0001540b21210a0c20210b210b210a210b210b210b200c0b200b210b210b200b21210b0b20210b210b210b0b20210b0b210b220b0001540c20210b0b200c0005dc00000000000000000000",
                        "off": "b1c0e600889e060044220c0001530c1f220a0c1f220a210b210b200b210b210b200b0b210b200b210b200b21210b0a21210b200b210b200c0a210b210b220b0001530c20210b0b20210b210a210b210b210b200b210b0b200b210b200c200b21200b0b21200b210b210b200b0b210b200b230b0001530b20210b0b21210a210b210b200b210b210b200b0b210b200b210b200c20210a0c20210b200c200b210b0b200b210b220c0001530b20210b0b20220a210b210b200b210b210b200b0b210b200b210b200b21210a0c20210b200b210b210b0b200b210b220b0001550a20210b0b20220a210005dc"
                    }
                },
                {
                    "name": "ATV",
                    "type": "switch",
                    "data": {
                        "on": "260042021b1d1d1e1d1d3a1d1e1c1d1e1c961d1e1c1e1c1e1d3a3a1e1c3b3a3a3a3b1c0009ad1b1e1e1d1c1e3a1d1d1d1d1e1c961d1e1c1e1c1e1d3a3b1d1c3b3a3a3b3a1c0009ad1b1e1e1d1c1e3a1d1d1d1e1d1c961e1d1c1e1c1e1d3a3b1e1b3b3a3b393b1c0009ac1d1d1e1d1d1d391e1c1e1d1e1c961d1e1c1e1d1e1c3a3b1d1c3b3b3a393b1c0009ad1c1e1c1e1c1e3b1c1d1e1c1e1c971c1e1d1d1d1d1d3b391e1d3a3b3a393b1d0009ac1d1d1d1d1e1d3a1d1c1e1d1d1d961d1e1c1e1c1e1c3b3b1d1c3b393b3a3b1c0009ac1d1d1d1e1c1e3a1d1d1e1d1d1d961c1e1c1e1d1e1d3a391e1c3b3a3b393b1d0009ac1c1e1d1d1c1e3a1e1c1e1d1d1d961c1e1d1d1d1e1c3b3a1d1d3b3a3a3a3a1d0009ac1c1e1c1e1d1d3a1e1c1e1c1e1d961d1d1d1e1c1e1c3b3a1d1d3b393b3a3b1c0009ac1c1e1d1d1d1d3a1e1c1e1c1e1d961d1d1d1e1c1e1c3b3a1e1c3b393b3a3b1c0009ae1b1d1d1e1c1e3a1d1d1e1c1e1c971d1d1c1e1d1e1d3a391e1c3b3a3b393b1d0009ad1b1e1d1d1d1e3a1d1d1d1d1d1d961d1e1c1e1c1e1c3b3a1e1c3b3a3b393b1c0009ac1d1e1c1e1c1e3a1d1d1e1c1e1c971c1e1c1e1e1c1d3b391e1c3b3a3b393b1d0009ab1e1d1c1e1c1e3a1e1c1e1d1d1c961d1e1d1d1d1e1c3b391e1e3a393b3a3a1d0009ac1c1e1d1d1d1d3a1e1c1e1c1e1d961d1d1d1e1c1e1c3b3b1d1c3b393b3a3b1c0009ac1c1e1d1d1d1e391e1c1e1d1d1d961d1e1c1e1c1e1c3b3a1e1d3a393b3a3b1c0009ab1d1d1d1e1c1e391e1d1d1d1e1c961d1e1c1e1c1e1d3a3a1e1c3b3a3a3b3a1c000d0500000000",
                        "off": "260098011a1e3a3b391e1d1d1d1d1d1e1c1e1c3b1c1e3a1e1c000ba01b1e3a3a3a1e1c1e1c1e1d1d1d1e1c3b1c1e3a1d1d000b9f1d1d393b3a1d1d1e1c1e1c1e1c1e1e3a1c1e391e1d000b9e1c1e3a3b391e1d1d1d1e1c1e1c1e1c3b1d1e391e1d000b9e1c1e3a3a3a1e1c1e1c1e1d1e1c1e1c3b1c1e3a1e1c000b9e1d1e393b3a1d1d1e1c1e1c1e1c1e1e391d1e391e1d000b9e1c1e3a3a3a1e1c1e1c1e1d1d1d1e1c3b1c1e3b1d1c000b9e1c1e3a3b391e1c1e1d1e1c1e1c1e1c3b1d1e391e1c000b9f1c1e3a3b391e1d1d1d1d1d1e1c1e1c3b1d1e391e1d000b9e1c1e393b3a1e1c1e1c1e1c1e1d1d1d3b1c1e3a1d1d000b9e1d1e393b3a1d1d1e1c1e1c1e1d1d1d3b1c1e3a1d1d000b9f1c1e3a3a3a1e1c1e1c1e1c1e1d1e1d3a1c1e3a1e1c000b9f1c1e3a3a3a1e1c1e1c1e1d1e1c1e1c3b1c1e3a1e1d000b9e1c1e393b3a1e1c1e1c1e1d1d1d1e1c3b1c1e3a1e1c000b9f1c1e393b3a1e1c1e1c1e1d1d1d1e1c3b1c1e3a1e1c000b9f1c1e393b3a1e1c1e1c1e1d1d1d1e1c3b1c1e3a1e1c000b9f1c1e393b3a1e1c1e1c1e1d1d1d1e1c3b1c1e3a1e1c000d050000000000000000000000000000"
                    }
                },
                {
                    "name": "PS4",
                    "type": "switch",
                    "data": {
                        "on": "260044001a1e1c1e1d1d3a1e1c1e1c1e1d961d1d1e1d1c1e1c3b3a1d1d3b393b1c1e3a0009c91c1e1c1e1d1d3a1e1c1e1c1e1d961d1d1d1d1e1d1c3b391e1d3b393b1c1e3a000d050000",
                        "off": "260098011a1e3a3b391e1d1d1d1d1d1e1c1e1c3b1c1e3a1e1c000ba01b1e3a3a3a1e1c1e1c1e1d1d1d1e1c3b1c1e3a1d1d000b9f1d1d393b3a1d1d1e1c1e1c1e1c1e1e3a1c1e391e1d000b9e1c1e3a3b391e1d1d1d1e1c1e1c1e1c3b1d1e391e1d000b9e1c1e3a3a3a1e1c1e1c1e1d1e1c1e1c3b1c1e3a1e1c000b9e1d1e393b3a1d1d1e1c1e1c1e1c1e1e391d1e391e1d000b9e1c1e3a3a3a1e1c1e1c1e1d1d1d1e1c3b1c1e3b1d1c000b9e1c1e3a3b391e1c1e1d1e1c1e1c1e1c3b1d1e391e1c000b9f1c1e3a3b391e1d1d1d1d1d1e1c1e1c3b1d1e391e1d000b9e1c1e393b3a1e1c1e1c1e1c1e1d1d1d3b1c1e3a1d1d000b9e1d1e393b3a1d1d1e1c1e1c1e1d1d1d3b1c1e3a1d1d000b9f1c1e3a3a3a1e1c1e1c1e1c1e1d1e1d3a1c1e3a1e1c000b9f1c1e3a3a3a1e1c1e1c1e1d1e1c1e1c3b1c1e3a1e1d000b9e1c1e393b3a1e1c1e1c1e1d1d1d1e1c3b1c1e3a1e1c000b9f1c1e393b3a1e1c1e1c1e1d1d1d1e1c3b1c1e3a1e1c000b9f1c1e393b3a1e1c1e1c1e1d1d1d1e1c3b1c1e3a1e1c000b9f1c1e393b3a1e1c1e1c1e1d1d1d1e1c3b1c1e3a1e1c000d050000000000000000000000000000"
                    }
                }
            ]
        },

**Comment by patricegautier** [comment]
running in to the exact same issue.. I reset the device and re did the whole setup, but same result..

I do have the ip of the device hardcoded:

       {
            "platform": "BroadlinkRM",
            "name": "BroadlinkRM",
            "hideWelcomeMessage": true,
            "hosts": [
                {
                    "address": "192.168.208.12",
                    "mac": "24:df:a7:e8:80:22",
                    "isRM4": true,
                    "isRFSupported": false
                }
            ] ...

**Comment by bondskin** [comment]
Do you guys have the 4.5.0 beta installed?
(I have this issue and will open a separate issue)

**Comment by patricegautier** [comment]
I do not..

**Comment by Cesco117** [comment]
I even tried with 4.5.0 beta, even went back to old versions, still the same issue.

But I found the solution by specifying IP and MAC address with the « hosts » parameter, and it’s working back. ( https://broadlink.kiwicam.nz/#device-discovery )

Be sure to have your BroadLink a static IP address on your network.

**Comment by Cesco117** [comment]
> running in to the exact same issue.. I reset the device and re did the whole setup, but same result..
> 
> I do have the ip of the device hardcoded:
> 
> ```
>    {
>         "platform": "BroadlinkRM",
>         "name": "BroadlinkRM",
>         "hideWelcomeMessage": true,
>         "hosts": [
>             {
>                 "address": "192.168.208.12",
>                 "mac": "24:df:a7:e8:80:22",
>                 "isRM4": true,
>                 "isRFSupported": false
>             }
>         ] ...
> ```

Are you sure the IP address is static ?

**Comment by masterfordev** [comment]
Try using only the static IP (remove MAC).

**Comment by patricegautier** [comment]
Well something got fixed overnight - everything is back to normal today, without any change on my part.

For what it's worth, I confirmed from the router's side that the MAC and IP are both correct on the config.

**Comment by kinander** [comment]
I still have [Broadlink RM] [ERROR]  *** sendData (no device found)
I have v4.4.10
and host def. and static IP in the router for my Broadlink. 

It was working fine until a week or two ago, then suddenly stoped. Would work shortly if I unplugged the Broadlink and plugged it in again and then restarted Homebridge. But just shortly then [Broadlink RM] [ERROR] again. 

Works well with the Broadlink app.

**Comment by fratinize** [comment]
Same Problem All been Good TilL Today No Device found

**Comment by h2oota** [comment]
Do you all have Node18 installed?
I think Node18 is the cause of this problem.

I posted a workaround for 4.5.0 beta. I hope it is also valid for 4.4.
https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/486#issuecomment-1144402244

**Comment by bondskin** [comment]
@h2oota , Node 16.5.1 here but no issues with the devices at the moment

**Comment by fratinize** [comment]
> Same Problem All been Good TilL Today No Device found

Came back for a Few Days, Now I Only See 1 Of my 3. Weird. Works Great, Then All of a sudden it does not find the device(s).
I Down graded, Upgraded, same results. Rebooted the Pi. Currently Running the Latest  v4.4.10

**Comment by kiwi-cam** [comment]
This should now be resolved in v4.4.11-beta.1. Could you test and confirm?

**Comment by h2oota** [comment]
Great!. v4.4.11-beta.1 works fine with Node18.3.0.
