### ISSUE TITLE
"no device found" with 4.5.0 beta

### ISSUE THREAD

**Issue by bondskin** [kiwi-cam/homebridge-broadlink-rm#486]
**Describe the bug**
When running 4.5.0 beta, I am not able to switch off/on a device
Using the Broadlink app it works instantly.

**To Reproduce**
1. install 4.5.0 beta (2) 
2. restart HB. 
3. switch device on/off -> does not work
4. rollback to 4.4.10. 
5. restart HB
6. switch device on/off -> does work as expected 

*Expected behavior**
Same behavior as with 4.4.10 which let me switch off/on the devices.

**Screenshots**
[37m[21/04/2022, 19:59:37] [39m[36m[BroadlinkRM][39m [31m[ERROR] [0mAcer sendData (no device found at a0:43:b0:54:4d:89)

once rolling back to 4.4.10, it works again
[37m[21/04/2022, 22:08:55] [39m[36m[BroadlinkRM][39m Acer sendHex (192.168.2.135; a0:43:b0:54:4d:89) 26004800000124931410121313121237121212131311121312381237131213111337121312121312123712371337121314101212121413351312121311131237133712381139121113000d050000000000000000000000000000

**Desktop (please complete the following information):**
not relevant

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 15.4.1

**Comment by h2oota** [comment]
Undocumented change to "family" attribute in os.networkInterfaces() in Node 18.
https://github.com/nodejs/node/issues/42787

here is a workadound.

kiwi-cam/broadlinkjs-rm

--- /index.js
+++ b/index.js
@@ -118,7 +118,7 @@ class Broadlink extends EventEmitter {
       const currentInterface = interfaces[interfaceID];

       currentInterface.forEach((address) => {
-        if (address.family === 'IPv4' && !address.internal) {
+        if ((address.family === 'IPv4' || address.family === 4) && !address.internal) {
           ipAddresses.push(address.address);
         }
       })

**Comment by kiwi-cam** [comment]
This should now be resolved in v4.4.11-beta.1. Could you test and confirm?
