### ISSUE TITLE
MQTT temp conversion

### ISSUE THREAD

**Issue by euphguy** [kiwi-cam/homebridge-broadlink-rm#495]
I am trying to get MQTT temperature display working and I am very close!

The Ecobee api seems to only send values in Fahrenheit and this plug-in expects Celsius. I have the plug-in and Home app set to display in F so it does an extra conversion and displays the temperature incorrectly. 

Is there or can there be a way for the plug to deal smoothly with this?

Is there a workaround outside of this plug-in using MQTT I am not aware of? I have explored setting the Ecobee to C but that doesn't seem to be an option.

**Comment by euphguy** [comment]
I worked around this by setting up a simple NodeRED flow to do the conversion I needed.

**Comment by kiwi-cam** [comment]
This should be simple to implement and could be of use for others. I'll re-open and look at integrating it in another version
