### ISSUE TITLE
RM4 Pro and RM4 Mini do not work

### ISSUE THREAD

**Issue by ivantam0903** [kiwi-cam/homebridge-broadlink-rm#497]
Under Version 4.4.11. My new RM4 Pro is given out the following error.

Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "520b". The device is connected to your network with the IP address "192.168.10.20".

Error message for RM4 Mini was as below.

Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "520c". The device is connected to your network with the IP address "192.168.10.21".

Even I have tried to disable the "lock device" from the broadlink apps and define the following devices code under the jason config. It did not helped at all.

       {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "host": [
                {
                    "address": "192.168.10.20",
                    "mac": "ec:0b:ae:8c:36:ad",
                    "isRFSupported": true,
                    "isRM4": true
                },
                {
                    "address": "192.168.10.21",
                    "mac": "ec:0b:ae:98:cf:8b",
                    "isRFSupported": true,
                    "isRM4": true
                }

**Comment by lcryst** [comment]
Got the same error with a newly purchased RM4 pro (device type code: "520b") with homebridge-broadlink-rm-pro v4.4.11. Added IP and MAC in the hosts section but doesn't help. The original RM4 Mini (653a) is working fine.

[Broadlink RM] 
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.
Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "520b".

**Comment by ivantam0903** [comment]
It is good that I am not alone in having problem on the new RM4 Pro and RM4 mini.

**Comment by ivantam0903** [comment]
The firmware version of my RM4 Pro and RM4 Mini are both in V62092

**Comment by derekspelledcorrectly** [comment]
Same issue here with a new RM4 Pro. I wasn't able to get it to work manually by settings `hosts` and I haven't been able to find any workaround yet.

**Comment by badrabbit** [comment]
It seems that no device can be found. Just getting this:
...`
[7/3/2022, 1:45:40 PM] [Broadlink RM] [INFO] Listening for Broadlink devices on 10.0.1.10:50904 (UDP)
[7/3/2022, 1:45:42 PM] [Broadlink RM] [INFO] Listening for Broadlink devices on 10.0.1.10:59521 (UDP)
[7/3/2022, 1:45:44 PM] [Broadlink RM] [INFO] Listening for Broadlink devices on 10.0.1.10:54392 (UDP)
[7/3/2022, 1:45:46 PM] [Broadlink RM] [INFO] Listening for Broadlink devices on 10.0.1.10:55845 (UDP)
[7/3/2022, 1:45:48 PM] [Broadlink RM] [INFO] Listening for Broadlink devices on 10.0.1.10:60744 (UDP)
[7/3/2022, 1:45:50 PM] [Broadlink RM] [INFO] Listening for Broadlink devices on 10.0.1.10:58714 (UDP)
[7/3/2022, 1:45:52 PM] [Broadlink RM] [INFO] Listening for Broadlink devices on 10.0.1.10:55204 (UDP)
[7/3/2022, 1:45:54 PM] [Broadlink RM] [INFO] Listening for Broadlink devices on 10.0.1.10:49812 (UDP)
[7/3/2022, 1:45:56 PM] [Broadlink RM] [INFO] Listening for Broadlink devices on 10.0.1.10:55015 (UDP)
[7/3/2022, 1:45:58 PM] [Broadlink RM] [INFO] Listening for Broadlink devices on 10.0.1.10:58512 (UDP)
...`

`[7/3/2022, 1:50:34 PM] [Broadlink RM] [ERROR] Learn Code (Couldn't learn code, device not found)
`

**Comment by lcryst** [comment]
There was a similar issue with unknown device code which was later supported.
https://github.com/lprhodes/homebridge-broadlink-rm/issues/665

**Comment by badrabbit** [comment]
Cannot test right now, but maybe this helps:

_"If the plugin is unable to discover your device, it’s likely you’ve registered the device with the cloud so it no longer accepts local connections. In this case, follow these steps":_


- Hold the reset button on your broadlink device until the light flashes
- In the IHC app go through the “Add Device” steps
- When you reach the step to add the device to a room - quit the IHC app

Original [thread](https://community.homey.app/t/app-pro-broadlink-app/6389/176)

[EDIT] 
**I can confirm that these steps worked for me! 
RM 4 Pro is now discovered correctly and learning/sendig codes works as expected!**

**Comment by masterfordev** [comment]
Yup, that info can find it in the documentation of the plugin.

**Comment by jeremylwf** [comment]
> Cannot test right now, but maybe this helps:
> 
> _"If the plugin is unable to discover your device, it’s likely you’ve registered the device with the cloud so it no longer accepts local connections. In this case, follow these steps":_
> 
> * Hold the reset button on your broadlink device until the light flashes
> * In the IHC app go through the “Add Device” steps
> * When you reach the step to add the device to a room - quit the IHC app
> 
> Original [thread](https://community.homey.app/t/app-pro-broadlink-app/6389/176)
> 
> [EDIT] **I can confirm that these steps worked for me! RM 4 Pro is now discovered correctly and learning/sendig codes works as expected!**

I cannot seem to be able to add RM4 Pro to Homebridge even though I followed the above steps and my RM4 Pro is connected to my home wifi

**Comment by ursusHU** [comment]
> > Cannot test right now, but maybe this helps:
> > _"If the plugin is unable to discover your device, it’s likely you’ve registered the device with the cloud so it no longer accepts local connections. In this case, follow these steps":_
> > 
> > * Hold the reset button on your broadlink device until the light flashes
> > * In the IHC app go through the “Add Device” steps
> > * When you reach the step to add the device to a room - quit the IHC app
> > 
> > Original [thread](https://community.homey.app/t/app-pro-broadlink-app/6389/176)
> > [EDIT] **I can confirm that these steps worked for me! RM 4 Pro is now discovered correctly and learning/sendig codes works as expected!**
> 
> I cannot seem to be able to add RM4 Pro to Homebridge even though I followed the above steps and my RM4 Pro is connected to my home wifi

@jeremylwf 
Hi,
I have the same issue, did you manage to connect?
