### ISSUE TITLE
Feature Request: Add Change Logs to Config-UI-X

### ISSUE THREAD

**Issue by mitch7391** [kiwi-cam/homebridge-broadlink-rm#5]
Hey @kiwi-cam I was wondering if you can make your change logs appear in config-ui-x? Some plugins when updated on that UI have a pop-up box that lists the latest updates to the plug-in :) I believe all you need to do is move the Changelog from README.md to the CHANGELOG.md file. I am quoting the developer of the homebridge-xiaomi-roborock-vacuum for what he said he did when I raised the issue there.

**Comment by kiwi-cam** [comment]
Great tip thanks @mitch7391. I've added a CHANGELOG.md file and made some initial version notes. The next release should come through as requested.

**Comment by mitch7391** [comment]
Thanks @kiwi-cam! You’re a champion!
