### ISSUE TITLE
iOS 16 b2 - HeaterCooler, fan speed and Oscilliate toggle greyed out after a while inside HomeKit app

### ISSUE THREAD

**Issue by Write** [kiwi-cam/homebridge-broadlink-rm#504]
**Describe the bug**
After a while, I'm not able to change HeaterCooler devices fanspeed bar and the oscillate toggle.
Both are greyed out. However, changing temperature works. 

Rebooting Homebridge always resolve the issue momentarily and I can't say how much times after a reboot it become greyed out. 

**To Reproduce**
1. Wait after booting Homebridge boot, 10 min seem enough for the interface to become greyed out inside HomeKit app. Sometimes it may take longer. Can't figure out what triggers the bug.
Rebooting the iPhone does not fix the issue. 

**Expected behavior**
For oscilliate toggle and fanspeed bar to not become grey.

**Screenshots**
![image](https://user-images.githubusercontent.com/541722/176977844-276b138b-0fdf-4847-b795-a183b1b7830b.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 16 beta 2
 - Inside HomeKit app

**Additional context**
I know it's a beta, and it may just be an HomeKit issue that'll be resolved in future beta, but just in case I prefer to post the "bug".

**Comment by retoocs007** [comment]
Same here, on first public beta iOS & iPadOS 16. I have got briefly working on iPhone but after few minutes it's again grayed out, and now I can't get it to work again.
On the iPad i have got it working by turning off WiFi while in Home app, waiting few seconds and turning WiFi back on.
On the iPhone (12) first time I have got it to same as on iPad but after changing temperature (or closing Home app - i don't know exactly) I can't get it to work again on iPhone.

Similar to fan problem I have experienced problem with setting up TV, where inputs won't show up in the Home app. Same procedure with turning off WiFi shows inputs in the Home app.

So, yeah, maybe it sa beta bug, will see if future updates resolves this issues.

**Comment by Write** [comment]
Seems fixed on latest beta ? Or maybe it's because I rolled back my HomePods mini to 15.6 ?

**Comment by retoocs007** [comment]
I'm on new public beta (2) on iPhone and iPad and can confirm that is now working.

**Comment by drlkp** [comment]
Hi guys just a question, I'm trying to add th air-conditioning toggle to HomeKit, but even if I put codes into jsone no way just frequency scan appears in HomeKit. Can you please indicate to me the correct way to use plugin? Thanks in advance
