### ISSUE TITLE
tv is not shown

### ISSUE THREAD

**Issue by prhmps** [kiwi-cam/homebridge-broadlink-rm#505]
hello dears
i am using this plugin,and i want use tv features but tv controller is not goes to my apple home kit!
is there anybody to help me?
i am waiting for your answers
thanks alot

**Comment by masterfordev** [comment]
Read the documentation on tv accesories.

**Comment by Barba4life** [comment]
when adding accessory to Homekit, click "more options" and it should pop up if you did it right.

if you have connected multiple tv remotes in the past and it has stopped working now, try deleting old ones. In "Homebrigde settings", check under "Reset", and click "purple box arrow" to view existing Accessories, delete old ones. Best reset afterwards.
