### ISSUE TITLE
"inputs" show up as separate tiles; "volume" controls not seen in HomeKit

### ISSUE THREAD

**Issue by maxvelascoknott** [kiwi-cam/homebridge-broadlink-rm#51]
I love that this plugin exists! I can get the power on/off working correctly and the TV icon shows up in my HomeKit app, however, I can't get volume and inputs to work:

• Volume buttons don't appear anywhere in the app; the TV tile simply has a power on / off button + state
• Inputs show up as tiles rather than an input dropdown

I admit that I'm running iOS 14, but I am also guessing that I either have the syntax wrong or I'm missing something. Any thoughts?

            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideWelcomeMessage": true,
            "accessories": [
                {
                    "name": "Projector",
                    "type": "tv",
                    "data": {
                        "on": "HEX",
                        "off": [
                            {
                                "data": "HEX",
                                "sendCount": 2,
                                "interval": 0.5
                            }
                        ],
                        "volume": {
                            "up": "HEX",
                            "down": "HEX"
                        },
                        "inputs": [
                            {
                                "name": "Apple TV",
                                "type": "HDMI",
                                "data": "HEX"
                            },
                            {
                                "name": "Xbox One",
                                "type": "HDMI",
                                "data": "HEX"
                            },
                            {
                                "name": "Turntable",
                                "type": "other",
                                "data": "HEX"
                            }

**Comment by dresken** [comment]
If it helps, I've had to restart the Home app on both MacOS and iOS for it to pickup that the inputs aren't separate tiles.

Not sure about the volume controls - still looking at what they are for

**Comment by dresken** [comment]
Found out that "Volume Controls" are used in the Control Center Remote (https://www.macrumors.com/how-to/apple-tv-remote-ios-11-control-center/) - but it's not an on screen button - but you use the physical volume buttons while the remote is on screen

**Comment by maxvelascoknott** [comment]
Omg! I hadn't seen that before. That's incredible.

I don't really have menu controls to navigate, but since I had been previously using four remotes:

Projector
Screen
Speaker
Apple TV

And can do it all from my phone or Siri commands, it's pretty incredible!

Now, if I can only find that damned Siri remote in the couch cushions _that's been missing for three months_ …![image](https://user-images.githubusercontent.com/25709372/93161982-98764000-f6c8-11ea-8c2e-d291e0244429.png)
