### ISSUE TITLE
HomeBridge Codes learned not working

### ISSUE THREAD

**Issue by EricS1019** [kiwi-cam/homebridge-broadlink-rm#518]
Hello, I have been trying to troubleshoot this for weeks not and I need some help. I setup my RM4 up with the new Broadlink App on my iPhone to control my Select Blinds remote controlled blinds. The RM4 works great to control my blinds through the Broadlink App but when I try to learn the same codes through HomeBridge I can not get it to work through HomeKit.

I learned the code through HomeBridge and the HomeKit learn button and got this code to open the blind

b0c0ae02689b06007a4f350b160a0c150c15170a160b0b160b16160a170a170a160b160b160b160b0b16160b150b0c150c150b160b150c16160a170a170a0c150b160b150c150c150c150c15160b160a170a0c150c15170a160b160bb450350a160b0b160b16160a170b0b150c15160b160b160b160a170a170b160a0c15160b160b0b150c150c150c150c15160b160b160a0c150c150c150c150b160b150c16160a170a170a0c150b16160a170b160ab54f350a170a0c150c15160b160b0b160b15170a170a170a160b160b160b160b0b15170a170a0c150b160b150c150c15170a170a160b0b160b160b150c150c150c150c15160b160b160b0b150c15160b170a160bb450350a160b0b160b16160b160a0c150c15170a160b160b160b160b160a160b0b16160b160b0b160b150c150c150c15160b160b160a0c150c150c150c150b160b160b15170a170a160b0c150b16160b160a170ab451340b160b0b150c15160b160b0b160b16160b160b150b160b160b160b160b0b16160b150b0c150b160b160b160b15170a160b160b0b160b160b160b150c150c150c15160b160b160b0b160b16160a160b160b8e040c0409040750350a160b0c150b16160b160b0b160b16160a160b160b160b160b160a170a0c15160b160b0b160b160b150c150c15160b160b160b0b160b150c150c150c150b160b16160a170b160a0c150b16160b160a170ab550340b160b0b160b15170a160b0b160c15160b160b160a170a170a160b160b0b16160b160a0c150c160a160b160b16160a170a170a0c150c150b160b160b160b150c16160a160b160b0b160b16160a170a170ab54f350a170a0b160b16160b160b0b160b16160a170a160b160b160b160b160b0b15160b160b0b160b160b160b150c15170a160b160b0b160b160b160b160b150c150b16160b160b160a0c150c15160b160b160b160005dc0000000000000000
I entered the above code into the HomeBridge config file where the hex code goes to raise the blinds but  through the homekit app and it doesn't work. I am not even sure if those are the correct type of code but those are the codes that the homebridge is showing when I select learn code.

Again the blinds and the RM4 work fine through the Broadlink App but for some reason I cannot get them to work through the homekit app. Can someone help me out and let me know if those codes even look correct at all? and also what I need to do to get the correct codes to work through the homekit app. Thanks
I have everything setup ad programmed properly when I turn on the Learn button in homekit I see in the log of the homebridge it says learning then I press the button on the controller and after a few seconds it spits out that code above in the homebridge log viewer, so I then copy that code to the Homebridge config file in the correct location for that blind and save it. The blind shows up in HomeKit and when I press it to open the blind I see the RM4 send a signal but nothing happens with the blind. So I am assuming that the above code is incorrect. Because when I try to learn the same button a second time I get a similar code with just a few digits different. But like I said my blinds learned the commands through the Broadlink app fine with no issues and send the commands no problem my problem is figuring out how to get the correct HEX codes so I can paste them in the HomeBridge config file. Any help would be greatly appreciated. I am not even sure if the above code is a correct HEX code or not.

**Comment by kard8** [comment]
Hi @EricS1019 

Can you please post the part of the config.json file containing the broadlink hex code and log files for debugging.

**Comment by CyberGiant443** [comment]
I’m having the same issue. The accessory gets created properly and I’ve learned the RF Hex codes and entered them in and checked them multiple times to make sure they were in correct areas. In HomeKit the blinds think they are operating. The log shows what the command is (like if I choose 32% it counts down in the log). Anyone else have this working and can help? Thanks. I have all my other accessories are working fine for all other accessories in the config.
