### ISSUE TITLE
Multiple tv’s with control center remotes

### ISSUE THREAD

**Issue by guitarpro44** [kiwi-cam/homebridge-broadlink-rm#52]
Is it possible to have 2 separate tv’s with control center remotes in the same platform? I tried adding another one and it replaced the original rather than adding on. Also wondering what the available types of accessories Besides tv, switch and ac were possible. Thanks for your time!

**Comment by masterfordev** [comment]
Type of Accessories: https://lprhodes.github.io/slate/#accessories
 
Yes, its possible, i have 2 TV with one central control. Just when you add the second tv you have go to your Home app and click on Add Accessory, then select the TV and enter the code of your Homebridge and you should see the new tv on the app.

**Comment by dresken** [comment]
I've added three TVs - two of them show up in the Control Center Remote. All three of them show up in the Home App. 

I think it's only the "primary" TV that doesn't show - like the one I didn't have to add manually to the Home App.

**Comment by masterfordev** [comment]
The first TV dont need add manually, but after 2 or more tvs, you have to add manually each one.

**Comment by dresken** [comment]
Yeah - but we are saying one TV is not appearing in the Control Center Remote. We have manually added the additional TV and they do show up in the Home App.

**Comment by masterfordev** [comment]
Can you share your config file?

**Comment by guitarpro44** [comment]
That worked! Thank you so much. It’s an amazing plugin.

**Comment by masterfordev** [comment]
> That worked! Thank you so much. It’s an amazing plugin.
> […](#)

Yw :)

**Comment by dresken** [comment]
Obviously we were _not_ talking about the same thing then (glad you got it fixed)

In the Home app I can see all three TVs. In the Control Center remote - I can see TV 1 and TV 3. 

TV 2 is currently the primary. I've deleted and readded TVs - and different TVs have been primary - it's always one missing from the Control Center and always the primary

`{
    "platform": "BroadlinkRM",
    "hideWelcomeMessage": true,
    "hideLearnButton": true,
    "scanFrequencyAccessory": true,
    "accessories": [
        {
            "name": "TV 1",
            "type": "tv",
            "host": "a7:df:24:11:11:11",
            "data": {
                "on": "HEX_CODE",
                "off": "HEX_CODE",
                "volume": {
                    "up": "HEX_CODE",
                    "down": "HEX_CODE"
                },
                "inputs": [
                    {
                        "name": "Tuner",
                        "type": "tuner",
                        "data": "HEX_CODE"
                    },
                    {
                        "name": "HDMI1",
                        "type": "hdmi",
                        "data": "HEX_CODE"
                    },
                    {
                        "name": "HDMI2",
                        "type": "hdmi",
                        "data": "HEX_CODE"
                    }
                ]
            }
        },
        {
            "name": "TV 2",
            "type": "tv",
            "host": "a7:df:24:22:22:22",
            "data": {
                "on": "HEX_CODE",
                "off": "HEX_CODE",
                "volume": {
                    "up": "HEX_CODE",
                    "down": "HEX_CODE"
                },
                "remote": {
                    "rewind": "HEX_CODE",
                    "fastForward": "HEX_CODE",
                    "nextTrack": "HEX_CODE",
                    "previousTrack": "HEX_CODE",
                    "arrowUp": "HEX_CODE",
                    "arrowDown": "HEX_CODE",
                    "arrowLeft": "HEX_CODE",
                    "arrowRight": "HEX_CODE",
                    "select": "HEX_CODE",
                    "back": "HEX_CODE",
                    "exit": "HEX_CODE",
                    "playPause": "HEX_CODE",
                    "info": "HEX_CODE"
                }
            }
        },
        {
            "name": "TV 3",
            "type": "tv",
            "host": "a7:df:24:22:22:22",
            "data": {
                "on": "HEX_CODE",
                "off": "HEX_CODE",
                "volume": {
                    "up": "HEX_CODE",
                    "down": "HEX_CODE"
                },
                "inputs": [
                    {
                        "name": "Tuner",
                        "type": "tuner",
                        "data": "HEX_CODE"
                    },
                    {
                        "name": "Bluray",
                        "type": "hdmi",
                        "data": "HEX_CODE"
                    },
                    {
                        "name": "HDMI1",
                        "type": "hdmi",
                        "data": "HEX_CODE"
                    },
                    {
                        "name": "HDMI2",
                        "type": "hdmi",
                        "data": "HEX_CODE"
                    }
                ]
            },
            "pingGrace": 15,
            "pingIPAddress": "192.0.2.200",
            "pingIPAddressStateOnly": true,
            "disableLogs": true
        }
    ]
}
`

**Comment by masterfordev** [comment]
Ok, you have 2 broadlink? you are using BL1 to control TV 1, and BL2 to control TV 2 and TV 3. Right?

**Comment by dresken** [comment]
I am. I think it was the same when I had just two on the same broadlink before I added the third.

**Comment by masterfordev** [comment]
It's weird because I have the same thing as you. Two broadlink with 3 tvs.

**Comment by dresken** [comment]
I saw this issue and thought - okay that's what I'm seeing (an issue with Control Center - not the Home app) - but obviously not by the sounds. I'll play around with it a bit more and see what I can work out.

**Comment by masterfordev** [comment]
I just proved what you say. One of my TVs does not appear in my control panel (being off, although the second TV does appear even being off), but if I turn it on it appears again in the control panel.

**Comment by masterfordev** [comment]
Perhaps it has something to do with the fact that a TV being off cannot be controlled. But I don't know why the second TV appears even when it's off. It's weird.

@kiwi-cam Are you aware of this?

**Comment by dresken** [comment]
That is strange. But unfortunately it doesn't seem to matter the power state for me

**Comment by kiwi-cam** [comment]
I've changed the way TVs are connected in order to fix the icons in iOS 14. I'm curious if this will also resolve this issue, since all TVs are now separate accessories.

Could you try updating to 4.3.1+ and see if you still have this issue?

**Comment by masterfordev** [comment]
With me it works perfectly, they appear to me even if the televisions are off.

![Screenshot](https://user-images.githubusercontent.com/29960705/93729563-5181c200-fb82-11ea-9489-f9f522970e68.jpeg)

**Comment by dresken** [comment]
I had to re-add one of the TVs to home app after upgrading (totally not a problem - just noting for anyone reading in future).

But all TVs show up now show up in Remotes - as well as having the correct icons in the home app on iOS 14.

Cheers

**Comment by kiwi-cam** [comment]
Glad to hear its come right.
