### ISSUE TITLE
[ERROR] sendData (no device found, ensure the device is not locked)

### ISSUE THREAD

**Issue by arkhazim** [kiwi-cam/homebridge-broadlink-rm#525]
hi, since I updated node.js, I have this issue that I cannot resolve : [ERROR]  sendData (no device found, ensure the device is not locked)
the device is not locked in the app, and I see the RM 3 pro + in the devices connected to my network.
I tried to use the "hosts" to bypass the automatic discovery... but the issue is still here.
thank you in advance

**Comment by djsomi** [comment]
Hi All,

I have a similar strange issue: I have 3 Broadlink devices, and cannot get working all of them in the same time. If I define all devices in host section, one of the RM MINI 3 wont work. Plugin drops this:

[Broadlink RM] [ERROR] Heater sendData (no device found at xx.xx.xx.xx, ensure the device is not locked)
(Device is not locked working fine for example from Home Assistant at that time.)

If I let the plugin auto discover my devices, than randomly one of them gets the same issue. (assuming that which is answering slower)


Many Thanks
Zoltan
