### ISSUE TITLE
TV accessory, unable to send input hex code multiple times

### ISSUE THREAD

**Issue by paludarium** [kiwi-cam/homebridge-broadlink-rm#526]
I have defined an accessory as tv with subtype receiver and multiple **inputs**, added it to **Home App** and created a scene to be able to power on and put the receiver on the right **input** (CD in my case).

When I activate the scene, commands are not necessarily sent in the right order (by Home App I suppose) so I want to repeat sending the **input** commands multiple times so the receiver will have a chance to receive the command once fully powered on.

For example, my inputs are defined like so:

                        "inputs": [
                            {
                                "name": "CD",
                                "type": "hdmi",
                                "data": [
                                    {
                                        "data": "0000 006D 0000 0020 000A 001E 000A 0046 000A 001E 000A 001E 000A 001E 000A 001E 000A 001E 000A 0046 000A 001E 000A 001E 000A 001E 000A 0046 000A 0046 000A 001E 000A 001E 000A 0679 000A 001E 000A 0046 000A 001E 000A 001E 000A 001E 000A 0046 000A 0046 000A 001E 000A 0046 000A 0046 000A 0046 000A 001E 000A 001E 000A 0046 000A 0046 000A 0679",
                                        "sendCount": 3,
                                        "interval": 0.5
                                    }
                                ]
                            },
                            {
                                "name": "DVD",
                                "type": "hdmi",
                                "data": "0000 006D 0000 0020 000A 001E 000A 0046 000A 001E 000A 001E 000A 001E 000A 0046 000A 0046 000A 001E 000A 001E 000A 001E 000A 0046 000A 0046 000A 0046 000A 001E 000A 001E 000A 0679 000A 001E 000A 0046 000A 001E 000A 001E 000A 001E 000A 001E 000A 001E 000A 0046 000A 0046 000A 0046 000A 001E 000A 001E 000A 001E 000A 0046 000A 0046 000A 0679"
                            }
                        ]

When the scene is activated in Home App, the **input CD** command is issued first but sent only once even though I have defined the required settings. I see it only once in the log and the receiver doesn't switch inputs because it received the change when it was powered off.

I expect the **Input CD** command to be sent three times at the specified interval.

Using homebridge-broadlink-rm-pro v4.4.11
Running on OS | Ubuntu Focal Fossa (20.04.4 LTS)

**Comment by Barba4life** [comment]
my config, hope it helps. Everything working for me so far. Make sure your codes are correct in HEX format, because your blaster wont sent it if it's wrong. Check your codes.

(I had similar problem...)

---

{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideWelcomeMessage": true,
    "hideScanFrequencyButton": true,
    "hideLearnButton": true,
    "hosts": [
        {
            "address": "192.168.1.179",
            "port": 80,
            "mac": "a0:43:b0:5e:8b:e9",
            "isRFSupported": false,
            "isRM4": true
        }
    ],
    "accessories": [
        {
            "name": "Samsung TV",
            "type": "tv",
            "data": {
                "on": "26008c009592143614361436121314101510141114111436143612381411141114111410151015101535141114111411141114111411143614101535153514361436143614361400060597921436143614361411141015101510151015351436143614111411141114111410151015351510141114111411141114111436141114351535153514361436143614000d0500000000000000000000",
                "off": "26008c009592143614361436121314101510141114111436143612381411141114111410151015101535141114111411141114111411143614101535153514361436143614361400060597921436143614361411141015101510151015351436143614111411141114111410151015351510141114111411141114111436141114351535153514361436143614000d0500000000000000000000",
                "remote": {
                    "select": "26008c009592143614361435151015101510151014111436143614351510151015101510141114111411141114361410153515351411143614361435151015351510141114361400060495941535143614361410151013121510151014361436143614101510151015101411141114111411143614101535153514111436143614351510153514111411143614000d0500000000000000000000",
                    "arrowUp": "26008c009593143515351535141114111411141114111435153514361411141114111411141015101510151014111411143614351510153515351436143515351510151015351400060497921535143614361411141015101510151015351436143614101510151015101510141114111411141114111435153515101535143614351535153515101411143614000d0500000000000000000000",
                    "arrowDown": "26008c009394133713361337141113121312131213121238133614361411131213121312121312381213121312121312133713371312131213371237133714361312131212381300060596931337123813361411131214111312131213371337133614111411131213121312133713121213121313111337143613121312123812381336143613121312133713000d0500000000000000000000N",
                    "arrowLeft": "26008c009394133713371337121312131213121312121337133713371213121312131213121213371312133712131213123812371312131213371312123812371312131213371300060498931237133713371312141112131411141114351535133713121411141114111411143515101436141114111436143614111410143614111436143614111411143515000d0500000000000000000000",
                    "arrowRight": "26008c009394143613371337121312131213121312121337133713371213131212131213131114111436141113121312133713371213123713121436133713371213131113371300060695941436123812371411131213121411131213371337133614111312131213121312131212381312131212131237133713121337131212381336143614111312133712000d0500000000000000000000",
                    "playPause": "26008c009394133712381237131213121312131213121238123713371312131213121312121312381213121312371337133712131238121312371337131213121312123812131200060794941337133713371213121312131213121213371337133712131213121312131213123713121312133713371238121312371312133713371312121312131238121312000d0500000000000000000000",
                    "info": "26008c009592153514351535151015101510141114111436143515351510151014111411141114361410151015351535143614361411141015351535141114111411141112381400060495941337123812371312131213121312121312381237133714111312131213121213123813121212133713371337143613121213123714361510141114111411143614000d0500000000000000000000",
                    "back": "26008c009593143515351634141114111213141112131237153513371312121312131213121312131212131213371337131213371213123813361337131213121337131212381300060695941337123713371312131213121312131212381336153514111312131213121312121312131213143612371510133714111337143614361212131213371510133714000d0500000000000000000000"
                },
                "volume": {
                    "up": "2600460093941337133713361411131213121312131212381336143614111411151013121312123813361436131213121312121313121312121213121337133713371337123714000d05",
                    "down": "26008c009592143614361436141114101510151015101436143614351510151015101510141114361436141114351510141114111411141114111436141114351535143614361400060497921436143515351411141114111411141114361435153514111411141114111411143515351510143614111411141114111411141114351510143614361436143515000d0500000000000000000000"
                }
            }
        }
    ],
    "_bridge": {
        "username": "0E:FD:D6:B7:D7:59",
        "port": 52247
    }
}
