### ISSUE TITLE
Initial Configuration Not Working (RM4 Pro with HOOBS Homebridge Installation)

### ISSUE THREAD

**Issue by rjhewitt3** [kiwi-cam/homebridge-broadlink-rm#527]
I can't seem to get this Homebridge plugin up and running, not sure what's going on. My RM4 Pro device is being auto-discovered but none of the linked accessories are showing up in the config (nor did the RM4 Pro get added). 

I've attached a couple of pictures of my config (I'm using HOOBS, so you only see the plugin-specific layer of the config). I disabled the welcome message there, for example, and even that isn't affecting anything. Because the details for my RM4 Pro aren't pulling in I manually set that portion of the config up based on the IP and MAC address shown in the log (but I've obfuscated this for privacy).

I was under the impression that accessories and the Broadlink device would be automatically configured by the plugin—is this a misunderstanding? I'm not sure where or how to get all of the details that I would need to set up my accessories manually (like the RF codes, etc.). Can someone point me in the right direction?

![Screenshot 2022-08-26 at 13 55 01@2x](https://user-images.githubusercontent.com/6742828/186964662-3f5fc9fc-2732-4f9f-b012-3536cd3ada25.png)

![Screenshot 2022-08-26 at 13 54 37@2x](https://user-images.githubusercontent.com/6742828/186964668-0820948a-fe34-403a-a0bf-8b656b764a7e.png)

**Comment by rjhewitt3** [comment]
Update: I found a second location for config of the plugin in HOOBS and was able to successfully add my accessories manually—but I'd love to solve the automatic detection portion of this still. For what it's worth I had previously configured my accessories in the Broadlink app, so I was expecting that to be pulled in automatically. Perhaps I've misunderstood?

**Comment by euphguy** [comment]
> I was expecting that to be pulled in automatically. Perhaps I've misunderstood?

Yeah, this plug-in does not pull any configuration from the BroadLink app. Use the learn button to get the codes to manually enter into your config. 

Any reference to auto discovery is about finding the BroadLink device itself on your network, not any hex codes or configuration.

**Comment by rjhewitt3** [comment]
@euphguy Thanks for confirming.
