### ISSUE TITLE
Select which device will learn the codes

### ISSUE THREAD

**Issue by masterfordev** [kiwi-cam/homebridge-broadlink-rm#53]
Is it possible to select the device I want to learn the codes? Because when i activate the option it is activated on the device in my room and I need it on the device in my office room.

Thanks.

**Comment by dresken** [comment]
The plugin will add automatic learn accessories for one device. You can override this by defining your own in the accessories array:

"accessories": [
        {
            "name": "Learn Remote Not Office",
            "type": "learn-code",
            "host": "a7:df:24:12:12:12"
        },
        {
            "name": "Learn Remote Office",
            "type": "learn-code",
            "host": "a7:df:24:23:23:23"
        },
....


If you want to scan RF, then add
"scanFrequency": true

**Comment by masterfordev** [comment]
> The plugin will add automatic learn accessories for one device. You can override this by defining your own in the accessories array:
> 
> 
> 
> "accessories": [
> 
>         {
> 
>             "name": "Learn Remote Not Office",
> 
>             "type": "learn-code",
> 
>             "host": "a7:df:24:12:12:12"
> 
>         },
> 
>         {
> 
>             "name": "Learn Remote Office",
> 
>             "type": "learn-code",
> 
>             "host": "a7:df:24:23:23:23"
> 
>         },
> 
> ....
> 
> 
> 
> 
> 
> If you want to scan RF, then add
> 
> "scanFrequency": true 

Thanks! Work! Just add i used the IP's device and not the MAC Address.
