### ISSUE TITLE
Cannot add fan accessory

### ISSUE THREAD

**Issue by keithpointon** [kiwi-cam/homebridge-broadlink-rm#532]
**Describe the bug**
. I am having difficulty installing the Broadlink RM plug in.
I managed to install the plug in and bridge ok and was able to obtain on/off hex codes for my Fan.
However, I have been unable to add the Fan as an accessory.
I followed the instructions in issue 441 in the plug in notes;
I deleted the plugin and bridge and reinstalled, adding the suggested text in the Advanced config tab using my IP, mac and hex codes.
I restarted the bridge but my Fan does not show as an accessory. I was expected to see a Fan accessory with on/off switch.
Config and Advanced config and log attached.
Thank you.
[Photos-export-09-14-2022-165616.pdf](https://github.com/kiwi-cam/homebridge-broadlink-rm/files/9569730/Photos-export-09-14-2022-165616.pdf)
[Uploading log.txt…]()

**Comment by kard8** [comment]
Hi @keithpointon ,
Kindly rearrange your code in this syntax. This worked for me.

If your having a standard fan without rotating function i would recommend changing the accessory type to **"fanv1"** an old accessory type. It also gives additional glyph choices in the Home `app.` 


```
{
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": false,
    "hideWelcomeMessage": true,
    "accessories": [
          {
                "name": "Example Fan",
                "type": "fan",
                "data": {
                  "on": "ON_HEX_CODE",
                  "off":"OFF_HEX_CODE",
                "fanSpeed20":"FAN20_HEX_CODE",
                "fanSpeed60":"FAN60_HEX_CODE",
                "fanSpeed100":"FAN100_HEX_CODE"
              }
          ]
    }

```

**Comment by keithpointon** [comment]
Thank you very much for your reply. I only want on - off control for my fan. Do I just omit the lines that refer to fan speed? Is this code under Advanced? Thanks, againOn 17 Sep 2022, at 09:01, kard8 ***@***.***> wrote:﻿
Hi @keithpointon ,
Kindly rearrange your code in this syntax. This worked for me.
If your having a standard fan without rotating function i would recommend changing the accessory type to "fanv1" an old accessory type. It also gives additional glyph choices in the Home app.
{
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": false,
    "hideWelcomeMessage": true,
    "accessories": [
          {
                "name": "Example Fan",
                "type": "fan",
                "data": {
                  "on": "ON_HEX_CODE",
                  "off":"OFF_HEX_CODE",
                "fanSpeed20":"FAN20_HEX_CODE",
                "fanSpeed60":"FAN60_HEX_CODE",
                "fanSpeed100":"FAN100_HEX_CODE"
              }
          ]
    }

**Comment by keithpointon** [comment]
I added the code you said, deleting the lines referring to fan speed, under Advanced. When I Saved, it reverted to the syntax below.

{
    "accessories": [
        {
            "name": "Example Fan",
            "type": "fanv1",
            "data": {
                "on": "600900000019646cd482668276827676b25246c246b6a24260003f60001964ace45256b266a26686a26246a27686828260003f400019a46cf47246b286627696925266a266a6826270003f500019847cd49266a2668256b6727266a26686a26270003f500019749cf462768256a266869272868246a6927250003f700019847cf46266a266a246a6c24246a256a692528000d05000000000000",
                "off": "2600900000019548cd4826672769246a6c24246a25696928250003f400019847d04627692568266a6927246a28676925270003f500019649ce48256a286628686a24256b28656b25270003f500019847cc4a2569256a276969252569266a6a26270003f500019747cd472868266a25696a252866266b6925260003f400019b46cf46256b256926696c24246a2769682625000d05000000000000"
            }
        }
    ],
    "platforms": [],
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": false,
    "hideWelcomeMessage": true
}

This is my log as a result 

7/09/2022, 12:40:40Broadlink Rm Pro BridgeBroadlinkRM**
17/09/2022, 12:40:40Broadlink Rm Pro BridgeBroadlinkRM**************************************************************************************************************
17/09/2022, 13:15:00Broadlink Rm Pro BridgeConfiguration change
17/09/2022, 13:15:00broadlinkrmprobridge stopping
17/09/2022, 13:15:05Broadlink Rm Pro Bridge starting
17/09/2022, 13:15:28Broadlink Rm Pro BridgeLoaded plugin 'homebridge-broadlink-rm-pro'
17/09/2022, 13:15:28Broadlink Rm Pro BridgeLoading 1 accessories...
17/09/2022, 13:15:28Broadlink Rm Pro BridgeBridge is running on port 51836.

But no accessory is added.

What am I doing wrong?

Thank you for your help
