### ISSUE TITLE
Adding manual devices have incorrect device type

### ISSUE THREAD

**Issue by dresken** [kiwi-cam/homebridge-broadlink-rm#54]
"hosts": [
        {
            "address": "192.0.2.22",
            "mac": "a7df24222222",
            "isRFSupported": false
        }
]

Autodiscovery finds RM Mini 4 
14/09/2020, 7:22:29 pm [BroadlinkRM] [35m[INFO][0m Discovered Broadlink RM Mini 4 (62bc) at 192.0.2.22 (a7:df:24:22:22:22)

Manual finds Broadlink RM2 instead (which looks to matter in the code)
14/09/2020, 8:06:53 pm [BroadlinkRM] [35m[INFO][0m Discovered Broadlink RM2 (2712) at 192.0.2.22 (a7:df:24:22:22:22)

A side note for Mac addresses has to be specified without colons - if specified it displays as a7::d:f::24::2:2::22::2:2

I'd be fine with replacing "isRFSupported" with manually specifying the "type" instead - seems a lot more reliable.

**Comment by kiwi-cam** [comment]
4.3.5 added "Manual" device types to resolve this. The device type is dictated by the use of "isRFSupported" and "isRM4" as these define the capabilities.

https://github.com/kiwi-cam/homebridge-broadlink-rm#hosts-configuration
