### ISSUE TITLE
Accessories don't populate 

### ISSUE THREAD

**Issue by buzzshot** [kiwi-cam/homebridge-broadlink-rm#540]
Good day all, not sue if its something i am not doing properly or its a bug.

What i have for a setup 

Pi3 B+ with a fresh install of the new HOOBs
HOOBS 4
Node 16.18.1
Everything is up to date.
Broadlink Pro Min.

My problem is that i cant seem to add any accessories to my dashboard or my homekit like my TV, Switch, Receiver.. I has able to setup the Broadlink and its talking HOOBS. The Training button and frequency button did pop up and i can get the the IR codes.

I even tried just copy and paste the example code in and save and noting pops up.

My simplified sketch
{
    "platform": "homebridge-broadlink-rm-pro",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "hideWelcomeMessage": true,
    "hosts": [
        {
            "address": "192.168.1.178",
            "mac": "c.............0",
            "isRFSupported": true,
            "isRM4": true
        }
    ],
    "accessories": [
        {
            "name": "Auto-off Switch",
            "type": "switch",
            "enableAutoOff": true,
            "onDuration": 5,
            "data": {
                "on": "2600500000012a96131213121214121312131214111313131139133812381239133811391139133812381214111413121214111412131238131311391338133712391239113911141200052a0001294c12000d050000000000000000",
                "off": "2600500000012a96131213121214121312131214111313131139133812381239133811391139133812381214111413121214111412131238131311391338133712391239113911141200052a0001294c12000d050000000000000000"
            }
        },
        {
            "name": "TV",
            "type": "tv",
            "data": {
                "off": "HEX...",
                "on": "HEX...",
                "remote": {
                    "select": "HEX...",
                    "arrowUp": "HEX...",
                    "arrowDown": "HEX...",
                    "arrowLeft": "HEX...",
                    "arrowRight": "HEX...",
                    "back": "HEX...",
                    "exit": "HEX...",
                    "playPause": "HEX...",
                    "info": "HEX..."
                },
                "powerMode": {
                    "show": "HEX..."
                },
                "volume": {
                    "up": "HEX...",
                    "down": "HEX..."
                },
                "inputs": [
                    {
                        "name": "INPUT 1",
                        "type": "hdmi",
                        "data": "HEX..."
                    }
                ]
            }
        }
    ]
} 

Here's my Log

![Screenshot 2022-11-20 133903](https://user-images.githubusercontent.com/28534883/202922417-8430c8b5-3550-408d-895e-7c5be111f69e.png)

11/20/2022, 12:58:07 PMbroadlinkrmprobridge stopping
11/20/2022, 12:58:12 PMBroadlink Rm Pro Bridge starting
11/20/2022, 12:58:22 PMBroadlink Rm Pro BridgeLoaded plugin 'homebridge-broadlink-rm-pro'
11/20/2022, 12:58:22 PMBroadlink Rm Pro BridgeLoading 2 platforms...
11/20/2022, 12:58:22 PMBroadlink Rm Pro BridgeBroadlinkRM[INFO] Automatically discovering Broadlink RM devices.
11/20/2022, 12:58:22 PMBroadlink Rm Pro BridgeBroadlinkRMNo accessories have been added to the "undefined" platform config.
11/20/2022, 12:58:22 PMBroadlink Rm Pro BridgeBridge is running on port 51856.
11/20/2022, 12:58:22 PMBroadlink Rm Pro BridgeBroadlinkRM[INFO] Discovered Broadlink RM3 Mini (2737) at 192.168.1.178 (c..........0)
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM**************************************************************************************************************
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM** Welcome to version 4.4.11 of the Bridge Broadlink RM Plugin!
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM** 
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM** Find out what's in the latest release here: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/CHANGELOG.md
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM** 
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM** If you like this plugin then please star it on GitHub or better yet
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM** buy me a drink using Paypal https://paypal.me/kiwicamRM.
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM**
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM**
11/20/2022, 12:58:24 PMBroadlink Rm Pro BridgeBroadlinkRM**************************************************************************************************************

If any one has any ideas that would help me that would be great thanks,

**Comment by sptv1** [comment]
I'm having basically the same problem. Trying to add accessory TV on/off switch. It won't add.

**Comment by aadkszcn** [comment]
I have the same problem. I cannot add the accessories. I can extract the Hex codes through the learn button but I cannot add the accessories.

I get the following log:

[BroadlinkRM] Initializing BroadlinkRM platform...
[BroadlinkRM] [INFO] Automatically discovering Broadlink RM devices.
[BroadlinkRM] **No accessories have been added to the "undefined" platform config.**
Initializing platform accessory 'Learn'...
Initializing platform accessory 'Scan Frequency'...

(...)

[BroadlinkRM] [INFO] Discovered Broadlink RM4 Mini (62bc) at 192.168.3.xxx (ec:xx:ae:xx:ce:xx)

(...)

**Comment by sptv1** [comment]
I gave up on Broadlink. Using Switchbot to control TV and Bond to control fan and shades. No problem with either of them.

**Comment by aadkszcn** [comment]
> I have the same problem. I cannot add the accessories. I can extract the Hex codes through the learn button but I cannot add the accessories.
> 
> I get the following log:
> 
> [BroadlinkRM] Initializing BroadlinkRM platform... [BroadlinkRM] [INFO] Automatically discovering Broadlink RM devices. [BroadlinkRM] **No accessories have been added to the "undefined" platform config.** Initializing platform accessory 'Learn'... Initializing platform accessory 'Scan Frequency'...
> 
> (...)
> 
> [BroadlinkRM] [INFO] Discovered Broadlink RM4 Mini (62bc) at 192.168.3.xxx (ec:xx:ae:xx:ce:xx)
> 
> (...)

Never mind I did figure it out and it is now working. 1) I had the homebridge platform information double. 2) There was an unidentifiable problem with he host settings. By removing the host specifications, it prompted the auto configuration of the host settings, so it is finally working. Thanks to the developers for this plugin! I can finally include the TV in automations (Y)

**Comment by flamephi** [comment]
Hi! Could you paste in some example code so I can see what you did to fix the "host settings"? I'm having the same issue but nothing has helped so far. Thanks!

**Comment by aadkszcn** [comment]
> Hi! Could you paste in some example code so I can see what you did to fix the "host settings"? I'm having the same issue but nothing has helped so far. Thanks!

FYI: I have removed many standard functions on the TV as I basically only power on/off, HDI input and volume, and these functions are working without issues. 

{
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": false,
    "hideWelcomeMessage": true,
    "accessories": [
        {
            "name": "TV On/Off",
            "type": "switch",
            "data": {
                "on": "260020036...",
                "off": "26006801..."
            }
        },
        {
            "name": "KonkaTV",
            "type": "tv",
            "data": {
                "off": "2600235...",
                "on": "260020036...",
                "remote": {
                    "select": "2600c80...",
                    "arrowUp": "26004001...",
                    "arrowDown": "2600a0...",
                    "arrowLeft": "2600c800...",
                    "arrowRight": "2600c80..."
                },
                "volume": {
                    "up": "2600c80...",
                    "down": "2600f00..."
                },
                "inputs": [
                    {
                        "name": "INPUT 1",
                        "type": "hdmi",
                        "data": "260050..."
                    }
                ]
            }
        }
    ]
}

**Comment by flamephi** [comment]
Thanks!
