### ISSUE TITLE
New Device Type 520c for Broadlink RM4 Mini

### ISSUE THREAD

**Issue by jwkelso** [kiwi-cam/homebridge-broadlink-rm#541]
We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "520c".

**Comment by Mikunics** [comment]
Same issue here, have pictures of the box below:
![317004704_924099642284020_1574066817174985314_n](https://user-images.githubusercontent.com/17171510/213191482-b895b9a1-47ba-48bc-9667-7f7e0078e5fa.jpg)
![326005502_641190087758190_5778128595332968234_n](https://user-images.githubusercontent.com/17171510/213191494-e7c67b49-a784-4742-a680-48dafa4ad18a.jpg)

**Comment by AlNitsi** [comment]
**Same Issue here..  RM4 mini**  
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/kiwi-cam/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "520c".
