### ISSUE TITLE
Documentation is not accurate. 

### ISSUE THREAD

**Issue by CyberGiant443** [kiwi-cam/homebridge-broadlink-rm#553]
I’m not sure why the documentation is wrong and missing so much, but I finally got this plugin working by changing the platform name to the one in the attached screenshot. I appreciate the hard work you’ve done, but I have been making myself crazy because the documentation clearly states in every example json that you have to use BroadlinkRM as the platform. Just changing that allowed by json to be validated and works as expected. Also for those who can’t get the temp and humidity sensors attached to the RM4 Pro or Mini, you have to add the host IP, and update frequency. I’m looking at all the options and these parameters aren’t shown in the documentation. If there is a newer updated version that I have missed I apologize. 

**To Reproduce**
![5BD27592-40FA-4159-89D1-89E451387022](https://user-images.githubusercontent.com/121060157/211203571-6a38ed01-69af-4bd0-b80b-255057252805.jpeg)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masterfordev** [comment]
I have same name as in docu and not problems. 

![image](https://user-images.githubusercontent.com/29960705/211215361-e6c90b94-26bf-400d-b8f2-dfbcb6316e3d.jpeg)
