### ISSUE TITLE
BroadLink Temp/Humidity Sensor Cable Working Configuration - May fix other issues as well

### ISSUE THREAD

**Issue by CyberGiant443** [kiwi-cam/homebridge-broadlink-rm#554]
![7EC22C24-A7EC-4B2A-8E73-B9314DC09A0B](https://user-images.githubusercontent.com/121060157/211213156-c50a5571-01f8-44b2-b338-002fe8f6cd5b.jpeg)
![D8607417-B874-4D49-B4AC-11A8F693B539](https://user-images.githubusercontent.com/121060157/211213157-e0ba6712-560f-42ab-86a2-2a0c47e1d534.jpeg)
![9A8660EA-7DDB-4FAD-8769-9CF7ACCB71C2](https://user-images.githubusercontent.com/121060157/211213155-e1174c3b-ec1b-4b94-8782-b8594ec54c4f.jpeg)

**Comment by CyberGiant443** [comment]
Here are the screenshots of it presented in Home after I moved the sensors from the Default room to the correct room where the sensors are. 
![109A1C91-7A8B-4EAB-BF07-B5006A46E9B6](https://user-images.githubusercontent.com/121060157/211213278-126c92eb-70aa-46b5-934e-f4d26dbc146f.jpeg)
![DD6EDE0E-5854-45CB-9929-674672A463A1](https://user-images.githubusercontent.com/121060157/211213279-9c252a00-cbae-4c27-95a1-56e26c0fd8a1.jpeg)
![5A7E8258-D613-45D7-AE8C-0800538C00DC](https://user-images.githubusercontent.com/121060157/211213280-a04c00e1-939b-47ab-9c85-924d23f72b18.jpeg)

**Comment by sandrodz** [comment]
Thanks, this works.
