### ISSUE TITLE
Wrong buttons showing and expected buttons missing

### ISSUE THREAD

**Issue by rubernck21** [kiwi-cam/homebridge-broadlink-rm#555]
I have a Broadlink RM4 Pro that I just purchased. got it setup on my network and its controlling my wall mounted Twinstar Home heater.

I just installed this plugin and going through the JSON code I believe that I have it setup right, but only the Learn & Scan Frequency buttons are showing...even though they should be turned off. I am a JSON noob, so it's probably my fault, but I asked in the Facebook Hoobs group and only 1 person who replied said that the plugin is broken...so I'm here now.

https://pastebin.com/r98fFf5E

Hoobs version: 4.2.8
Node version: 16.19.0
Homebridge version: 1.5.0

**Comment by tientmit88** [comment]
it should be like this one
Your devices have to under accessories
"hosts": [{
    "address": "192.168.0.208",
    "mac": "EC:0B:AE:D8:A0:60",
    "isRFSupported": true,
    "isRM4": true
}],
"accessories": [
    "type": "switch",
    "data": {
        "power on": "xxx",
        "power off": "xxx"
    }
]

**Comment by rubernck21** [comment]
Thank you for responding to my issue.

So, im taking this to believe that the extra { and } are not needed? When I run this in jsonlint, I keep getting errors. Here is what Ive been able to get together without jsonlint giving me any errors.

`{
    "platform": "homebridge-broadlink-rm-pro",
    "name": "Wall Heater",
    "hideScanFrequencyButton": true,
    "hideLearnButton": true,
    "hideWelcomeMessage": true,
    "hosts": [
        {
            "address": "192.168.0.208",
            "mac": "EC:0B:AE:D8:A0:60",
            "isRFSupported": true,
            "isRM4": true
        }
    ],
    "accessories": [
        {
            "type": "switch",
            "data": {
                "power on": "26001e012a0d2a0c0f272a0d",
                "power off": "26000401270e280e0e29280e"
            }
        }
    ]
}`

**Comment by tientmit88** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/2247182/222609763-4527f5dd-dfee-4efa-8589-fb5bebbbbf7e.png">
here is the full config
You should change bridge & config port. I added switch name
I think it will work
