### ISSUE TITLE
Plugin identifies RM3 but accessories are not shown

### ISSUE THREAD

**Issue by edento** [kiwi-cam/homebridge-broadlink-rm#559]
**Describe the bug**
In broadlink app, I added 2 devices of type UserConfig (RF remote).
I installed the plugin and didn't change the json config so that it will automatically discover my devices.
the plugin managed to discover the broadlink hub, but I cant see the accessories in HB (or in its logs).

**To Reproduce**
1. Go to HB
2. Click on accessories
3. no broadlink remotes are there ( I can see "scan frequency" and "learn")

**Expected behavior**
The 2 accessories (**Fan left** and **Fan right**) should appear in HB accessories (see screenshot below)

**Screenshots**
broadlink app:
![image](https://user-images.githubusercontent.com/12493042/213909036-23451689-9e85-4a1c-9313-cbc7288caee0.png)

HB accessories:
where are **Fan left** and **Fan right**?
![image](https://user-images.githubusercontent.com/12493042/213909232-5a0f5f2d-6df0-41da-a02c-c2c1b12f296e.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 pro
 - OS: 16.2

**Additional context**
Plugin config:

```json
{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideWelcomeMessage": true
}
```

Homebrodge log:
```sh
[1/22/2023, 11:35:24 AM] [BroadlinkRM] Initializing BroadlinkRM platform...
[1/22/2023, 11:35:24 AM] [BroadlinkRM] [INFO] Automatically discovering Broadlink RM devices.
[1/22/2023, 11:35:24 AM] [BroadlinkRM] [INFO] Running Homebridge Broadlink RM Plugin version 4.4.11
[1/22/2023, 11:35:25 AM] [BroadlinkRM] No accessories have been added to the "BroadlinkRM" platform config.
[1/22/2023, 11:35:25 AM] Initializing platform accessory 'Learn'...
[1/22/2023, 11:35:25 AM] Initializing platform accessory 'Scan Frequency'...
[INFO] Adding RF Support to device 780f77fd4c61 with type 279d
[1/22/2023, 11:35:25 AM] [BroadlinkRM] [INFO] Discovered Broadlink RM3 Pro Plus (279d) at 192.168.86.84 (XX mac address XX)
```

I don't mind adding the remotes manually, but not sure how to extract the relevant data from the Broadlink app.
Please assist, thanks!

**Comment by mrrust310** [comment]
I'm having the same problem. No matter what code I type the log always shows the same "No accessories have been added to the "BroadlinkRM" platform config."

It is noteworthy to mention disabling the welcome message doesn't do anything.

Devices are not being added automatically or manually.

**Comment by fratinize** [comment]
Just want to add my 2 cents about this plug-in as it is happening Now, for the past couple weeks, my Red Bean, and Pro 4 which have Worked Just fine, except every so many months, All of a Sudden they are no longer found, nThey Work fine through the Native app, and They are not locked. They have Been Rebooted but still do not show up
Then All of a Sudden, They Show up…

I have no idea, just find it strange, that of all my devices running through my Homebridge, this is the only one having issues.
Is this some conflict in the network every so often?


Thanx for listening

**Comment by Stilnight** [comment]
Read the docs... You'll get the fact this need to be set up... The JSON needs to be updated with HEX code that you get from the scan mecanism that you unlocked setting the plugin. This is really powerful but not dumb as a plug and play. Read the documentation.
