### ISSUE TITLE
Aircondition status

### ISSUE THREAD

**Issue by Mikellas** [kiwi-cam/homebridge-broadlink-rm#56]
Hi ,

This is more a clarification and not an issue...
I have noticed that if i turn on the aircon via the actual remote ,status of aircondition in Homekit is not updated,
is that natural ? Do i need to only use Home for this to be accurate?

**Comment by masterfordev** [comment]
I think this is an issue with the new release of Homebridge. Are you aware o this @kiwi-cam ?

The automations also dont work with the air conditioners. 

Siri answer that some devices arent responding.

**Comment by masterfordev** [comment]
Nevermind. Now are working fine the air conditioners but i have a new issue.

**Comment by Mikellas** [comment]
I dont know about you but nothing changed my side.If i turn on aircon with remote nothing changes in Home

**Comment by kiwi-cam** [comment]
There's no feedback from the AC to the Broadlink - so we've got no way to update the device status in Home.

**Comment by Mikellas** [comment]
@kiwi-cam Ok thanks for clarifying this ill just hide the remote controls hehehe

**Comment by kiwi-cam** [comment]
That’s about right 😊

The other thing to consider is setting allowResend to true so automations will run anyway. I.e. it will turn the AC off when you leave even if it thinks it’s already off.

**Comment by Mikellas** [comment]
So just to b  sure i got this

Allow resend sends same command twice just to make sure it went through?

**Comment by masterfordev** [comment]
It will send the command again regardless of whether the status in the app home is off or on.

**Comment by benjaminbogdanovic** [comment]
> The other thing to consider is setting allowResend to true so automations will run anyway. I.e. it will turn the AC off when you leave even if it thinks it’s already off. 

To clarify, is it allowResend, 
preventResendHex, or do both work?

**Comment by kiwi-cam** [comment]
They’re identical but opposite. Only one is used in the code, the other just sets it to its opposite.

**Comment by benjaminbogdanovic** [comment]
Thanks for clarifying. I only came across preventResendHex in the documentation.
