### ISSUE TITLE
No Accessories have been added problem

### ISSUE THREAD

**Issue by mrrust310** [kiwi-cam/homebridge-broadlink-rm#561]
I just can't seem to figure out what's wrong. I keep getting this:

![image](https://user-images.githubusercontent.com/115042099/215169504-ce35566d-d76f-41d4-ad91-f3ce4644f846.png)

Here is my json config:

https://pastebin.pl/view/5128d96a

I can't figure out why Hoobs is adding this at the end:     "platform": "homebridge-broadlink-rm-pro". Maybe that's part of the problem?

I'd appreciate your help.

Thanks!

**Comment by tientmit88** [comment]
you should use "platform": "BroadlinkRM",

**Comment by mrrust310** [comment]
> you should use "platform": "BroadlinkRM",

Tried that already, same problem.

I've given up on this and switched to Bond.

**Comment by tientmit88** [comment]
can you share your config ?

**Comment by mrrust310** [comment]
Sure, https://pastebin.pl/view/5128d96a

**Comment by tientmit88** [comment]
I think you missing the 
{
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
Please change the port to your port
<img width="328" alt="image" src="https://user-images.githubusercontent.com/2247182/221473733-274f1c8b-4495-497e-813c-2ccb72079685.png">
