### ISSUE TITLE
I am able to operate Broadlink devices with Siri but girlfriend is not - voice recognition issue?

### ISSUE THREAD

**Issue by ppascuzz** [kiwi-cam/homebridge-broadlink-rm#563]
I am able to issue a Siri command to turn a Broadlink device off/on etc. but my girlfriend cannot. When she tries Siri says 'please continue in the broadlink app'. It seems as though she recognises a different user and fails the request. Have I made a mistake in the config somewhere?

**Comment by tientmit88** [comment]
she should remove all config add to siri within Broadlink app. It conflicts with Apple Home
