### ISSUE TITLE
'remote' and 'volume' buttons not showing in Home-App

### ISSUE THREAD

**Issue by juanReTMS** [kiwi-cam/homebridge-broadlink-rm#567]
With the following configuration, I only get the on/off button and the input selection button in the Home app. Neither the remote nor the volume buttons are displayed.

`{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": false,
    "hideWelcomeMessage": true,
    "accessories": [
        {
            "name": "Verstärker",
            "type": "tv",
            "subType": "Receiver",
            "data": {
                "on": "HEX...",
                "off": "HEX...",
                "remote": {
                    "select": "HEX...",
                    "arrowUp": "HEX...",
                    "arrowDown": "HEX...",
                    "arrowLeft": "HEX...",
                    "arrowRight": "HEX...",
                    "back": "HEX...",
                    "exit": "HEX...",
                    "playPause": "HEX...",
                    "info": "HEX..."
                },
                "volume": {
                    "up": "HEX...",
                    "down": "HEX..."
                },
                "inputs": [
                    {
                        "name": "DVD",
                        "type": "other",
                        "data": "HEX..."
                    },
                    {
                        "name": "TV",
                        "type": "other",
                        "data": "HEX..."
                    }
                ],
                "powerMode": {
                    "show": "HEX..."
                }
            }
        }
    ]
}`

What am I doing wrong?

**Comment by masterfordev** [comment]
https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/102#issuecomment-720813760

**Comment by fratinize** [comment]
It should show up on the remote in the control center 
Although there are times it will not be available says it's offline yet the the red bean is on my network and the native app works fine. I have no idea why it "disappears" at times

**Comment by tientmit88** [comment]
the buttons won't be showing in Home app, it will be shown in remote app
