### ISSUE TITLE
Can't get accessories added

### ISSUE THREAD

**Issue by mrrust310** [kiwi-cam/homebridge-broadlink-rm#568]
@kiwi-cam  I read some past documents where you suggested to add the Broadlink device by stepping out of the setup when the room is assigned. I've done that, the device doesn't show in the app but it does on my Hoobs.

I can't get past this: No accessories have been added to the "undefined" platform config.

Another thing I've noticed is that I get a "platform": "homebridge-broadlink-rm-pro" added to the end of my Json, wich I think could be related. 

I have previously describe the issue on https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/561 but no one has replied in weeks.

I would appreciate your help. I could be doing something wrong, or maybe the Broadlink app is updated (I noticed some differences in how the process to add the device is described and what I'm actually seeing on the app)

I appreciate your help.

**Comment by anferpp** [comment]
Having the very same issue here.

**Comment by mrrust310** [comment]
> Having the very same issue here.

There doesn't seem to be a solution. I've switched to Bond and it's easier to set up and works flawlessly.

**Comment by tientmit88** [comment]
@mrrust310  you should add
{
            "name": "Config",
            "port": 8581, <-- change to your port
            "platform": "config"
        },
<img width="483" alt="image" src="https://user-images.githubusercontent.com/2247182/222398954-8fed713e-7087-450b-8042-3451c1a1da82.png">
