### ISSUE TITLE
Two TVs

### ISSUE THREAD

**Issue by Ricky-Garcia1110** [kiwi-cam/homebridge-broadlink-rm#569]
Is there any way to add two TVs, with a single instance? With one instance and a child bridge, would it be possible?

I currently have three tvs in three different instances but I would like to reduce the instances to two and keep all three tvs, to free up some memory on the pi 3b+

**Comment by masterfordev** [comment]
Yes. Just read the log:
![image](https://user-images.githubusercontent.com/29960705/221420692-4c89b3d6-52b6-4b75-98df-9eb7c8bd1573.jpeg)

**Comment by Ricky-Garcia1110** [comment]
Yes, I have three added in three instances, but my question is that if I only leave two instances, could two TVs be added in a single instance with a child bridge? one on the main bridge and one on the child bridge?

**Comment by masterfordev** [comment]
I have 3 added in one instance.
