### ISSUE TITLE
Issues with icon TVs on iOS 14 GM

### ISSUE THREAD

**Issue by masterfordev** [kiwi-cam/homebridge-broadlink-rm#57]
When i add 2 or more tv for broadlink device i have this error on the homebridge log:

`[2020-9-16 20:27:18] One of your plugins incorrectly registered an external accessory using the platform name ([object Object]) and not the plugin identifier. Please report this to the developer!`

It should be clarified that if I add only one TV, this does not happen.

And on iOS 14, the Home App dont display the devices as TV, in this case it doesn't matter if I have one or more televisions, never put the TV icon on them (see the screenshot):
![Screenshot](https://user-images.githubusercontent.com/29960705/93413272-1880df00-f85c-11ea-9b24-aaa40973fece.jpg)

I hope you can check this issues. Im on homebridge 1.2.2, and plugin 4.3.0. Thanks.

**Comment by sergoo-lbt** [comment]
I also have a house instead of a TV

**Comment by masterfordev** [comment]
We need help @kiwi-cam :p 

I've been trying to locate the error in the plugin code but I can't detect where it originates.

**Comment by Faisalthe01** [comment]
it is due to something that changed in iOS 14 GM Version.

New icons too

https://twitter.com/HerrSupereg/status/1306278447317123072

https://github.com/homebridge/homebridge/issues/2683

**Comment by masterfordev** [comment]
but I'm also using the [homebridge-samsung-tizen](https://github.com/tavicu/homebridge-samsung-tizen) plugin with my smart tv samsung and that tv does show a tv icon.

![Screenshot](https://user-images.githubusercontent.com/29960705/93418889-9cd95f00-f868-11ea-99e0-13351268e3a2.jpg)

> it is due to something that changed in iOS 14 GM Version.
> 
> New icons too
> 
> https://twitter.com/HerrSupereg/status/1306278447317123072
> 
> [homebridge/homebridge#2683](https://github.com/homebridge/homebridge/issues/2683)

**Comment by Faisalthe01** [comment]
> but I'm also using the [homebridge-samsung-tizen](https://github.com/tavicu/homebridge-samsung-tizen) plugin with my smart tv samsung and that tv does show a tv icon.
> 
> > it is due to something that changed in iOS 14 GM Version.
> > New icons too
> > https://twitter.com/HerrSupereg/status/1306278447317123072
> > [homebridge/homebridge#2683](https://github.com/homebridge/homebridge/issues/2683)

Can you changes the icon for that TV in home app?

**Comment by masterfordev** [comment]
> > but I'm also using the [homebridge-samsung-tizen](https://github.com/tavicu/homebridge-samsung-tizen) plugin with my smart tv samsung and that tv does show a tv icon.
> > > it is due to something that changed in iOS 14 GM Version.
> > > New icons too
> > > https://twitter.com/HerrSupereg/status/1306278447317123072
> > > [homebridge/homebridge#2683](https://github.com/homebridge/homebridge/issues/2683)
> 
> Can you changes the icon for that TV in home app?

No, I have never been able to change a TV icon, ios 14 or ios 13, never allowed me to change it.

**Comment by sergoo-lbt** [comment]
I tried deleting the TV in homekit and in the.json config. Nothing helped. The problem remained. TV-Home!

**Comment by masterfordev** [comment]
> I tried deleting the TV in homekit and in the.json config. Nothing helped. The problem remained. TV-Home!

Yes, as mentioned @Faisalthe01 and (@Supereg on twitter), it seems to be a Homekit problem and not a homebridge or plugin problem.

**Comment by sergoo-lbt** [comment]
> > I tried deleting the TV in homekit and in the.json config. Nothing helped. The problem remained. TV-Home!
> 
> Yes, as mentioned @Faisalthe01 and (@Supereg on twitter), it seems to be a Homekit problem and not a homebridge or plugin problem.

And it's very sad

**Comment by masterfordev** [comment]
We must wait, maybe there is a solution because the samsung tizen plugin does work without problem. Only in this one it does not.

**Comment by Faisalthe01** [comment]
> > I tried deleting the TV in homekit and in the.json config. Nothing helped. The problem remained. TV-Home!
> 
> Yes, as mentioned @Faisalthe01 and (@Supereg on twitter), it seems to be a Homekit problem and not a homebridge or plugin problem.

no don't think HomeKit problem. more of a Homebridge and Plugin issue since Apple changed something. Read @Supereg comment on the tweet i sent

**Comment by masterfordev** [comment]
But the samsung tizen plugin is working fine with the icons. That makes me think that maybe the problem comes from the plugin.

**Comment by Faisalthe01** [comment]
> But the samsung tizen plugin is working fine with the icons. That makes me think that maybe the problem comes from the plugin.

yeah maybe Broadlink is missing a TV category code in the TV accessory file and Samsung Tizen does not. @kiwi-cam would be the best and qualified person to look at the code

https://github.com/tavicu/homebridge-samsung-tizen/blob/c3e879b78c547399a845525cd40a0b945b4ef510/lib/accessories/television.js#L20

If you don't mind can you re add the TV connected to your Samsung Tizen Plugin and see if you get option to choose a different icon like Setup box or Stick?

**Comment by masterfordev** [comment]
I did and it doesn't allow me to choose an icon for the tv. It automatically places the TV icon.

**Comment by Faisalthe01** [comment]
I did some research and found out this.

With this Plugin https://github.com/Martvvliet/homebridge-denon-heos Their TV now looks like a Audio Receiver Box after GM because the plugin have the Category code for Audio Receiver 
https://github.com/Martvvliet/homebridge-denon-heos/blob/d34ee5786ab900c4a838be4a2414c25887ecb195/index.js#L813

Same as Samsung Tizen TV accessory have the code for Category as Television
https://github.com/tavicu/homebridge-samsung-tizen/blob/c3e879b78c547399a845525cd40a0b945b4ef510/lib/accessories/television.js#L20

Unfortunately, Broadlink does not have any category listed and just the Service which is Television and since Apple added categories to Television service that's why Broadlink TV does not have any icon now.

https://github.com/homebridge/HAP-NodeJS/blob/b3bc73ceb99c4cb1df17d910ed557c3e6c8362e1/src/lib/Accessory.ts#L87

**Comment by masterfordev** [comment]
Yes! That's the reason! I told you that the problem was coming from the plugin xD

**Comment by Faisalthe01** [comment]
> Yeah! Thats the reason! I said, the issue becomes from the plugin xD

lol. so would you know how to define the category in Broadlink tv.js file?

it is defined like this in Denon-Heos plugin 

```
		this.tvAccesory = new Accessory(this.name, UUIDGen.generate(this.ip+this.name+"tvService"));
		this.tvAccesory.category = this.api.hap.Categories.AUDIO_RECEIVER;
```

and like this in Samsung-Tizen

```this.platformAccessory = new Homebridge.platformAccessory(this.device.config.name, this.UUID, Homebridge.hap.Accessory.Categories.TELEVISION);```

**Comment by masterfordev** [comment]
So the problem is here?: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/a62c43a091cc65a5f43dd0eefe0772f6186c3e5b/helpers/accessoryCreator.js#L14

**Comment by Faisalthe01** [comment]
> So the problem is here?:
> 
> https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/a62c43a091cc65a5f43dd0eefe0772f6186c3e5b/helpers/accessoryCreator.js#L14

Yes looks something like this.

Is this file linked to Tv.js?

**Comment by masterfordev** [comment]
Look this: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/a62c43a091cc65a5f43dd0eefe0772f6186c3e5b/platform.js#L81

**Comment by Faisalthe01** [comment]
> So the problem is here?:
> 
> https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/a62c43a091cc65a5f43dd0eefe0772f6186c3e5b/helpers/accessoryCreator.js#L14

So this file that you mentioned did work for me. thank you for that but i had to add an extra TV with random hex codes in my Home App then hid it in default room so i cannot see it anymore on main screen because for some reason the first TV added automatically by Broadlink is not picking up the category for it but for rest of the TV that i had to manually in Home App does pick up the category. Maybe you can figure it out why

So i did it one by one first i added my TV but before i added this on line 14

` const accessory = new platformAccessory(displayName, accessoryUUID, Accessory.Categories.TELEVISION);`

then i added the TV manually in Home app and it showed up as TV.

then i changed the line 14 to 

` const accessory = new platformAccessory(displayName, accessoryUUID, Accessory.Categories.AUDIO_RECEIVER);`

then i added my Panasonic surround system manually and it showed up as Audio Receiver 

then i changed the line 14 to 

` const accessory = new platformAccessory(displayName, accessoryUUID, Accessory.Categories.TV_SET_TOP_BOX);`

then i added my Vodafone Android TV Box manually and it showed up as Set top box.

this is how my icons look now

![new icons](https://user-images.githubusercontent.com/62862684/93436315-f778c680-f90d-11ea-8931-2d54d2eea776.jpg)

and this icon does not do anything but it has to be there as broadlink adds 1st TV automatically 

![old icon](https://user-images.githubusercontent.com/62862684/93436346-02335b80-f90e-11ea-808c-0cc8123f3ff5.jpg)

**Comment by kiwi-cam** [comment]
Nice work @Faisalthe01 and @masterfordev. I'm just publishing a BETA version which fixes the issue for additional TVs. Just need to find the code for the first one. HomeKit only allows a single TV on a bridge so the plugin uses accessoryCreator.js to create standalone accessories for all additional TVs.  Just need to work out how to fix the Category for the initial TV.

I'm also totally adding Receiver and STB support soon too!

**Comment by Faisalthe01** [comment]
> Nice work @Faisalthe01 and @masterfordev. I'm just publishing a BETA version which fixes the issue for additional TVs. Just need to find the code for the first one. HomeKit only allows a single TV on a bridge so the plugin uses accessoryCreator.js to create standalone accessories for all additional TVs. Just need to work out how to fix the Category for the initial TV.
> 
> I'm also totally adding Receiver and STB support soon too!

Hey mate. Thank you for looking into this. 

So with the extra code you put in "accessoryType". We will be able to define that in our config file whether it a TV, Set top box or Audio Receiver?

**Comment by kiwi-cam** [comment]
> So with the extra code you put in "accessoryType". We will be able to define that in our config file whether it a TV, Set top box or Audio Receiver?

No, they'll just be TVs.... for now. I've got a STB too so I'm keen to integrate the categories you've found. Just pondering how to do it (new types or expand the existing tv type).

**Comment by sergoo-lbt** [comment]
> No, they'll just be TVs.... for now. I've got a STB too so I'm keen to integrate the categories you've found. Just pondering how to do it (new types or expand the existing tv type).

Hi! Should we wait for beta now? Thank you for your work!

**Comment by masterfordev** [comment]
> Nice work @Faisalthe01 and @masterfordev. I'm just publishing a BETA version which fixes the issue for additional TVs. Just need to find the code for the first one. HomeKit only allows a single TV on a bridge so the plugin uses accessoryCreator.js to create standalone accessories for all additional TVs. Just need to work out how to fix the Category for the initial TV.
> 
> I'm also totally adding Receiver and STB support soon too!

Thanks @kiwi-cam ! im testing the beta. and work for the additional TVs.

**Comment by kiwi-cam** [comment]
So... the HomeBridge documentation (https://developers.homebridge.io/#/service/Television) sets up all TVs as separate accessories (not using Homebridge as a Bridge). This works nicely to resolve our issue... but it does mean people will need to add all TVs separately in the Home app - and their current first TV will disappear and need to be re-added this way.

It's a bit of pain, but I think it's a better approach.

A new BETA using this approach has been published. This *should* get all your TVs looking right... after you re-add them 😁

**Comment by masterfordev** [comment]
> So... the HomeBridge documentation (https://developers.homebridge.io/#/service/Television) sets up all TVs as separate accessories (not using Homebridge as a Bridge). This works nicely to resolve our issue... but it does mean people will need to add all TVs separately in the Home app - and their current first TV will disappear and need to be re-added this way.
> 
> It's a bit of pain, but I think it's a better approach.
> 
> A new BETA using this approach has been published. This _should_ get all your TVs looking right... after you re-add them 😁

Thanks!
I have upgraded to Beta 2 and it is working perfectly.

**Comment by Faisalthe01** [comment]
> So... the HomeBridge documentation (https://developers.homebridge.io/#/service/Television) sets up all TVs as separate accessories (not using Homebridge as a Bridge). This works nicely to resolve our issue... but it does mean people will need to add all TVs separately in the Home app - and their current first TV will disappear and need to be re-added this way.
> 
> It's a bit of pain, but I think it's a better approach.
> 
> A new BETA using this approach has been published. This _should_ get all your TVs looking right... after you re-add them 😁

Appreciate your quick and great work @kiwi-cam 

There is another category that icon looks like a Fire Stick, add that too. the category name is `TV_STREAMING_STICK`

**Comment by masterfordev** [comment]
@kiwi-cam I still have this in the homebridge log after each reboot, but all is working fine.

`[2020-9-17 19:29:52] One of your plugins incorrectly registered an external accessory using the platform name ([object Object]) and not the plugin identifier. Please report this to the developer!`

**Comment by kiwi-cam** [comment]
@masterfordev - Not much we can do about that. There's some discussion on that issue here: #26

**Comment by Faisalthe01** [comment]
Christmas comes early. i wanted these icons for a long time now. Really happy :D

**Comment by masterfordev** [comment]
> @masterfordev - Not much we can do about that. There's some discussion on that issue here: #26

Oh... I see. thanks anyway 😅

**Comment by masterfordev** [comment]
> Christmas comes early. i wanted these icons for a long time now. Really happy :D

lol! i just want the STB. But is like an TV, just witht other icon hehe

**Comment by Faisalthe01** [comment]
> > Christmas comes early. i wanted these icons for a long time now. Really happy :D
> 
> lol! i just want the STB. But is like an TV, just witht other icon hehe

lol. Still looks better than only TV. Audio Receiver looks very dope. If your STB is like a Fire Stick you can use Stick icon too the one i mentioned above, i think @kiwi-cam did add that in the beta too

**Comment by kiwi-cam** [comment]
I've got an update in git that should update the icons but I haven't been able to test yet - I'm not at home right now to add the new TV.

All going well I'll update the BETA this evening.  If you like, you can install direct from Git using: `npm install -g git+https://github.com/kiwi-cam/homebridge-broadlink-rm.git#kiwi-cam-tv-subtypes`.  I usually do a bit of testing before pushing a beta so this is very ALPHA status... maybe even DRAFT status.

The documentation will be updates too: https://github.com/kiwi-cam/homebridge-broadlink-rm/tree/kiwi-cam-tv-subtypes (note the new option under TV)

**Comment by masterfordev** [comment]
> I've got an update in git that should update the icons but I haven't been able to test yet - I'm not at home right now to add the new TV.
> 
> All going well I'll update the BETA this evening. If you like, you can install direct from Git using: `npm install -g git+https://github.com/kiwi-cam/homebridge-broadlink-rm.git#kiwi-cam-tv-subtypes`. I usually do a bit of testing before pushing a beta so this is very ALPHA status... maybe even DRAFT status.
> 
> The documentation will be updates too: https://github.com/kiwi-cam/homebridge-broadlink-rm/tree/kiwi-cam-tv-subtypes (note the new option under TV)

Yup, i was reading the changes in the repository https://github.com/kiwi-cam/homebridge-broadlink-rm/tree/kiwi-cam-tv-subtypes 😅 dont worry. We can wait until you have time to make the changes and tests.

**Comment by kiwi-cam** [comment]
I've just pushed the new BETA. I re-added my TVs and they worked beautifully. If you can install and let me now if there are issues, I'll push a new version in a day or two.

**Comment by masterfordev** [comment]
After update is working with no problems. But now i can use sub-category or that is a future update?

**Comment by masterfordev** [comment]
I found a issue. After add the TV, if i use the Control from Control Panel for volume up/down, the TV turn off.

**Comment by kiwi-cam** [comment]
Yep. Under your TV config add “subType” and set it to tv, stb, receiver, or stick. 

E.g.
`“subType”: “stb”`

You might have to remove and re-add the TV for it to update.

**Comment by masterfordev** [comment]
> Yep. Under your TV config add “subType” and set it to tv, stb, receiver, or stick.
> 
> E.g.
> `“subType”: “stb”`
> 
> You might have to remove and re-add the TV for it to update.

Work! 👏



> I found a issue. After add the TV, if i use the Control from Control Panel for volume up/down, the TV turn off.

nevermind this, now is working fine 😅 i dont know why but is working!!

**Comment by masterfordev** [comment]
OMG this look very nice! :D 
![Screenshot](https://user-images.githubusercontent.com/29960705/93561415-5c99df80-f941-11ea-8f29-2294a051321d.jpg)

great work @kiwi-cam !! thanks for all!

**Comment by sergoo-lbt** [comment]
Everything is fine! Great beta! Low bow to you!

**Comment by Faisalthe01** [comment]
the Audio Receiver icon does not appear in Remote app it still displayed as TV.

I have reported it to Apple, anyone else wanna to do that too.

**Comment by kiwi-cam** [comment]
> the Audio Receiver icon does not appear in Remote app it still displayed as TV.

I have a feeling I might’ve got a typo in there. I’ll check soon.

**Comment by sergoo-lbt** [comment]
![C3287CBF-05D3-45C9-9D55-ED7FBAEFDCA7](https://user-images.githubusercontent.com/64399012/93562026-afee4b00-f99e-11ea-89ba-2558e30bca1f.jpeg)
> > the Audio Receiver icon does not appear in Remote app it still displayed as TV.
> 
> I have a feeling I might’ve got a typo in there. I’ll check soon.

"subType”:" stb " doesn't work for me.

**Comment by masterfordev** [comment]
> > > the Audio Receiver icon does not appear in Remote app it still displayed as TV.
> > 
> > 
> > I have a feeling I might’ve got a typo in there. I’ll check soon.
> 
> "subType”:" stb " doesn't work for me.

`"subType": "stb"`

**Comment by masterfordev** [comment]
you deleted the tv and added again?

**Comment by sergoo-lbt** [comment]
> you deleted the tv and added again?

Yes! Deleted and added again. I'll try again.

**Comment by sergoo-lbt** [comment]
This time it worked! I'm sorry!

**Comment by masterfordev** [comment]
> This time it worked! I'm sorry!

cool! :D

**Comment by Faisalthe01** [comment]
> > the Audio Receiver icon does not appear in Remote app it still displayed as TV.
> 
> I have a feeling I might’ve got a typo in there. I’ll check soon.

Nah, it appears fine in the Home App not the Remote app. its a iOS 14 bug

**Comment by Faisalthe01** [comment]
Also, if anyone else have not noticed this. the TV accessory window looks much cleaner if you don’t have any inputs before the input area was there without any text but if there are no Inputs it only have a button

![031ADAF9-3E16-46F1-863A-43BFB6B7C65F](https://user-images.githubusercontent.com/62862684/93658318-d3d48e00-fa7d-11ea-85c7-e58f7f6f77ca.jpeg)

**Comment by masterfordev** [comment]
Yup. That's how I have my TVs. Only the power button with no inputs.

**Comment by Faisalthe01** [comment]
> Yup. That's how I have my TVs. Only the power button with no inputs.

Yeah it looks neat now with only on/off button before there was blank input selector if no inputs were added in iOS 13

**Comment by masterfordev** [comment]
> > Yup. That's how I have my TVs. Only the power button with no inputs.
> 
> 
> 
> Yeah it looks neat now with only on/off button before there was blank input selector if no inputs were added in iOS 13
> 
> 

I don't know what you're talking about. I've always been that way from a long time before.

**Comment by Faisalthe01** [comment]
> > > Yup. That's how I have my TVs. Only the power button with no inputs.
> > 
> > 
> > Yeah it looks neat now with only on/off button before there was blank input selector if no inputs were added in iOS 13
> 
> I don't know what you're talking about. I've always been that way from a long time before.

This it what it looked like in iOS 13 with empty input selector if no inputs were added.

![98774297-0F38-48A4-9B25-FE4ACA0228AF](https://user-images.githubusercontent.com/62862684/93659435-5bbf9580-fa88-11ea-91a6-68e6fa9fe695.jpeg)

**Comment by masterfordev** [comment]
As I told you, I always had the power button. Without the list of inputs. How did you have your configuration?

**Comment by Faisalthe01** [comment]
> As I told you, I always had the power button. Without the list of inputs. How did you have your configuration?

Interesting. I didn’t change my config after iOS 14 and the empty input selector disappeared as i had no input config.
```

{
                    "name": "Vodafone  TV",
                    "type": "tv",
                    "pingIPAddress": "192.168.0.96",
                    "pingIPAddressStateOnly": true,
                    "pingFrequency": 7,
                    "host": "192.168.0.161",
                    "disableLogs": true,
                    "data": {
                        "on": "260058000001229214111138133713111337111311131213111311131213111311131238111312121238111312131113111312381113121212131138123811381236131312381138120005c700012a4516000c580001254a11000d050000000000000000000000000000",
                        "off": "260058000001219213131138123812121238111312121213121212121312111312121238121212131138121212131113121213371212121311131138123812371337121213371237120005c70001264a13000c590001274912000d050000000000000000000000000000",
                        "remote": {
                            "select": "2600540000012491141114351436160e1436131114101411131114101411131114101436141014101436141014111336143613111410141113111435143614101411143514361435140002ef0a0002cc0001284913000d050000",
                            "arrowUp": "26005000000123921311143514361410143614101411131114101411131114160e111336141014111435141113361411133614101411131114101436141014361311143613361436130005c50001294615000d05000000000000",
                            "arrowDown": "260050000001288f16111435143614101436141014111311141014111311141014101436141014111311143514361410143614101411131114351411131114361311143514361435140005c50001294714000d05000000000000",
                            "arrowLeft": "260050000001249213111435143614101436141014111311141014111311141014111336141014111336143614351411133614111311141014111311141014361311143514361436130005c50001294417000d05000000000000",
                            "arrowRight": "260050000001249213111435143614101436141014111311141014111311141014111336141014111311141014111336143614101410141114351436143514111311143514361436130005c50001294813000d05000000000000",
                            "back": "260050000001239114111336143613111435141114101410141114101410141114101436131114101411131114101436141014101436141014361435143614101436143514111336140005c50001284814000d05000000000000",
                            "info": "260050000001269114111336143613111435141113111410141113111410141113111436131114101436143514361410141113111435141113111410141113361436133614111336140005c60001274814000d05000000000000",
                            "playPause": "260050000001249114111336143613111435141114101410141114101410141113111436131114101411133614111311143514111336141113361410143614351411143514111336140005c50001284814000d05000000000000"
                        },
                        "volume": {
                            "up": "260050000001239213111435143614101436141014111311141014111311141014111336141014111435143614101411131114351411131114101411133614361336141113361436130005c50001294813000d05000000000000",
                            "down": "260050000001239114111336143613111436131213101411131114101411131114101436141014101411141014351411141113361410141014361435141114351436141014361435140005c60001274814000d05000000000000"
                        }
                    }
                },
```

**Comment by masterfordev** [comment]
Looks like the mine :/ I don't know why looked like that with you

**Comment by Faisalthe01** [comment]
> Looks like the mine :/ I don't know why looked like that with you

So it was just me lol. Glad iOS 14 fixed it

**Comment by masterfordev** [comment]
Yeah haha. Its working fine the beta with you?

**Comment by Faisalthe01** [comment]
> Yeah haha. Its working fine the beta with you?

I didn’t install it yet, still using they way i changed the icons one by one after the AccesoryCreator.js file you showed me the other day and then i found a way to remove the first TV that had no icon so all of them are as a seperate bridge like Its now in the beta. And a few weeks ago i changed the Thermostat accessory to HeaterCooler accessory and modified the HumidifierDehumidifier to only Humidifier so didn’t want to mess it up 😀 

I first changed the Thermostat to Heat only like Cameron later added into his plugin but I didn’t like its On/off button so I changed it to HeaterCooler that can also have Fan function within it.
![E4FDFB82-DD1E-4146-A7FB-BB8FAE920012](https://user-images.githubusercontent.com/62862684/93660420-06888180-fa92-11ea-9960-21bfcd4b63c4.png)

And this is the humidifier one.
![2387EAA0-1A87-4F7A-AD7C-799213DF04FC](https://user-images.githubusercontent.com/62862684/93660442-49e2f000-fa92-11ea-87fc-a790c66f834f.png)

**Comment by masterfordev** [comment]
The HeaterCooler look great!

**Comment by masterfordev** [comment]
Maybe you can add an option like that @kiwi-cam , with HeaterCooler and we can use it with air-conditioners that only allow cool mode. 🤔

**Comment by masterfordev** [comment]
@Faisalthe01 but with the HeaterCooler, this display the current temperature of the room? for example: can get the sensors in the cable?

**Comment by masterfordev** [comment]
Nevermind, i saw the options is available 😂 i will use it!

**Comment by masterfordev** [comment]
Dont looks like with you 🤔
and you already saw that there is an error in the temperature image? (indicated in red, there is a slight gap)
![Screenshot](https://user-images.githubusercontent.com/29960705/93688908-e30c0980-fa86-11ea-910f-352736b7b3ff.JPG)

**Comment by Faisalthe01** [comment]
> Dont looks like with you 🤔
> and you already saw that there is an error in the temperature image? (indicated in red, there is a slight gap)
> ![Screenshot](https://user-images.githubusercontent.com/29960705/93688908-e30c0980-fa86-11ea-910f-352736b7b3ff.JPG)

I think this is how Apple made it too look like.
It changes when you turn it on

![F46C07A4-D4A5-4175-8E72-73D1048DE12B](https://user-images.githubusercontent.com/62862684/93692175-1dcb7b80-fb33-11ea-969a-b23ad83e85e1.jpeg)

**Comment by masterfordev** [comment]
I think I don't explained, I mean that. The line is not continuous.
![Screenshot](https://user-images.githubusercontent.com/29960705/93692244-cc2cdd80-faad-11ea-9b0d-2d1b71efe332.JPG)

**Comment by masterfordev** [comment]
And why with you the "heat", "cool", "auto" options are hide? with me not-

**Comment by Faisalthe01** [comment]
> Maybe you can add an option like that @kiwi-cam , with HeaterCooler and we can use it with air-conditioners that only allow cool mode. 🤔

@kiwi-cam 
Don’t have to convert Thermostat to HeaterCooler if you don’t want to but you can add one more config for Cool Only the same way i did for Heat Only.

https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/a62c43a091cc65a5f43dd0eefe0772f6186c3e5b/accessories/aircon.js#L688

Something like this

```
    if (this.coolOnly) {
	    this.service.getCharacteristic(Characteristic.TargetHeatingCoolingState)
	      .setProps({
	        minValue: 0,
	        maxValue: 2,
	        validValues: [0,2]	
				});
		}
```
0 is for Off and 2 if for Cool

https://developers.homebridge.io/#/characteristic/TargetHeatingCoolingState

The other differences between HeaterCooler and Thermostat is that you can turn the accessory on/off without opening the accessory window in home app by simply touching on the tile plus the fan option within the accessory and when you disable other options like cool or auto the button is missing I/0 text in it while it shows in HeaterCooler

**Comment by Faisalthe01** [comment]
> I think I don't explained, I mean that. The line is not continuous.
> ![Screenshot](https://user-images.githubusercontent.com/29960705/93692244-cc2cdd80-faad-11ea-9b0d-2d1b71efe332.JPG)

Yea i saw that i think this is from Apple.

**Comment by Faisalthe01** [comment]
> And why with you the "heat", "cool", "auto" options are hide? with me not-

Because there is an option to hide them and that’s what i did.

**Comment by masterfordev** [comment]
> > I think I don't explained, I mean that. The line is not continuous.
> 
> > ![Screenshot](https://user-images.githubusercontent.com/29960705/93692244-cc2cdd80-faad-11ea-9b0d-2d1b71efe332.JPG)
> 
> 
> 
> Yea i saw that i think this is from Apple. 

I also believe that

**Comment by masterfordev** [comment]
> > Maybe you can add an option like that @kiwi-cam , with HeaterCooler and we can use it with air-conditioners that only allow cool mode. 🤔
> 
> 
> 
> @kiwi-cam 
> 
> Don’t have to convert Thermostat to HeaterCooler if you don’t want to but you can add one more config for Cool Only the same way i did for Heat Only.
> 
> 
> 
> https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/a62c43a091cc65a5f43dd0eefe0772f6186c3e5b/accessories/aircon.js#L688
> 
> 
> 
> Something like this
> 
> 
> 
> ```
> 
>     if (this.coolOnly) {
> 
> 	    this.service.getCharacteristic(Characteristic.TargetHeatingCoolingState)
> 
> 	      .setProps({
> 
> 	        minValue: 0,
> 
> 	        maxValue: 2,
> 
> 	        validValues: [0,2]	
> 
> 				});
> 
> 		}
> 
> ```
> 
> 0 is for Off and 2 if for Cool
> 
> 
> 
> https://developers.homebridge.io/#/characteristic/TargetHeatingCoolingState
> 
> 
> 
> The other differences between HeaterCooler and Thermostat is that you can turn the accessory on/off without opening the accessory window in home app by simply touching on the tile plus the fan option within the accessory and when you disable other options like cool or auto the button is missing I/0 text in it while it shows in HeaterCooler
> 
> 

That would be great for many users like me 😅

**Comment by masterfordev** [comment]
@Faisalthe01 can show me your config for the HeanOnly? I set this but jt still show me all the options on the Home App.

**Comment by Faisalthe01** [comment]
> @Faisalthe01 can show me your config for the HeanOnly? I set this but jt still show me all the options on the Home App.

I have it disabled in the aircon.js file not in the config.
Add this in your aircon config

`heatOnly: true`

**Comment by masterfordev** [comment]
I have the "heatOnly" activated and dont hide cool/auto mode.

**Comment by Faisalthe01** [comment]
> I have the "heatOnly" activated and dont hide cool/auto mode.

woops my bad, i messed it up but i fixed it just now and did a test.

if you want you can download this and replace it with your aircon.js file. I have also added coolOnly in it as well. so cooOnly : true in your config will force it to work in cool only mode
https://github.com/Faisalthe01/homebridge-broadlink-rm-heater/blob/master/accessories/aircon.js

hey @kiwi-cam, I'm sorry can you do the pull request thing again i made some mistakes but i have corrected them now and also added coolOnly like the heatOnly. Thank you

**Comment by felixmueller** [comment]
Hello @kiwi-cam, hi everyone,

thank you so much for maintaining this project and keeping up the development for all iOS 14 quirks! 👏

Is there any estimate on when the TV icon fix will make its way into the release version of the plugin?

Keep up the good work!

Best
Felix

**Comment by Faisalthe01** [comment]
> Hello @kiwi-cam, hi everyone,
> 
> thank you so much for maintaining this project and keeping up the development for all iOS 14 quirks! 👏
> 
> Is there any estimate on when the TV icon fix will make its way into the release version of the plugin?
> 
> Keep up the good work!
> 
> Best
> Felix

Install the beta. Icons already fixed

**Comment by benjaminbogdanovic** [comment]
Anyone having this issue? #62

**Comment by benjaminbogdanovic** [comment]
Anyone having this issue as you guys seem to the most involved! #64
