### ISSUE TITLE
Repeat Codes Not Working as Expected

### ISSUE THREAD

**Issue by AnthonySiravo** [kiwi-cam/homebridge-broadlink-rm#579]
Repeat Codes are not working as expected.  I have followed the guide and added the required variables (sendcount,interval,pause)but it isn't working.  The log doesn't show it repeating the code.  It's for the item "Golf Projector" which needs to send the Off Hex Twice to shut off.  Here is my .json contents:

{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "hideWelcomeMessage": false,
    "hosts": [
        {
            "address": "10.100.1.110",
            "mac": "EC:0B:AE:A0:49:76",
            "isRFSupported": true,
            "isRM4": true
        }
    ],
    "accessories": [
        {
            "name": "Dart TV",
            "type": "switch",
            "stateless": true,
            "data": {
                "on": "26001801918f13351435133613121311141113121311133613361336141013121212131213111411133514121212131212121410141212361312133514351336133513361336130005c2918f14351336133613111312131113121312133514351435121214111312141013121311143513111411141113121311131213351312143512371236133614351335140005c2909013361335143514101412121213121212133613361237121213111312141014121212133613111312131114111312131113361312133612361335143514351435130005c2918f1435133613361212131212121411131213361236133514121311131212121312121214351411131212121312121213111435141113351435133613361336133612000d050000000000000000000000000000)",
                "off": "2600d200908f14351336133614101312121214121212133613351335141114111312131113121311143514101412121213121212141014351312133613351336133613361336120005c3918f13351435143512121412121214101312133513361435131213111312121214111312133613111312121213111411141113361411123514351435143513361336120005c390901336143512371212131113121311141113361335133613121311151013121410131213361212131114121311131212121336131113361336133613361236133514000d0500000000)"
            }
        },
        {
            "name": "Golf Projector",
            "type": "switch",
            "data": {
                "on": "2600900000011e9013121310121213111310121313101213121113101213131013351236141013111235143513351335131013121235111313111113111313101137133513111335110005a0000120901310121312111212131113101213101312121113131012131235133513121211113713351136123713111211143513101212131113101312133512351311143510000d05000000000000)",
                "off": "260090000001218f121114101311131113111211141013111311131013121310133513351311131112111435133512351311141013351310143414111211141013351335131014351300059e000120901310131113111311121213101311131113111212131013111334143513111211141013351335133514101311123613111335121114101311133512361311133512000d05000000000000)",
                "sendCount": 2,
                "interval": 2,
                "pause": 2
            }
        },
        {
            "name": "Golf Spot Light",
            "type": "switch",
            "data": {
                "on": "b1c0b004749e06000c28260e0c280d270d270d270d270d27270d0d270d27270d0d270d270d280c280c280c28260d260e0c000185270c270d260e0c280d28250e0c280c280c280d270c290c28250e0c280c28260e0d270d270d270d270d270d27270d260d0d000185270d260d270d0d270d27260d0d270e260e260e270d270d28260d0d270d28250e0c280c280d270d270d270d28260d260e0c000186260d260e250e0c280d28250e0c280c280d270e270d260e27270c0e260e26270d0d270d270d280c280d280c28250e260e0b000186270c270d260e0c280d27260e0c280c280c280c280c280d27260e0c280c28260e0d270d270d270d270d270d27270d260d0d000185270d270c270d0d270d27270c0e270d270d270d270d270d28260d0d280c28250e0c280c280c280d280c280c28250e260e0c000186260d260e250e0c280d28250e0c280c280d270d270e270d26270d0d270d27270d0d270d270d270d280d270d27260e250e0c000186260d270d260d0d280c28260e0c280c280c280c280c280c28260e0c280c28260e0d270d270d270d270d270d27270d260d0d000185270d270c270d0d270d27270d0d270d270d270d270d280c28260e0c280c28260d0c290c280c280c280c280c28260d260e0c000186260e250e260e0b290c28250e0c280c280e270d270d270d27260d0d270e26270d0d270d270d270d280c280d28250e260e0c000185270c270d270e0c280c28250e0c280c290c280c280c280c28260e0c280c28270c0d280c280d270d270d270d27270d260d0d000186260d270d260d0d270d27270d0d270d270d270d280c290b28260e0c280c28260e0c280c280c280c280c280d28260d270d0c000186260d260e260e0c280c28250e0d270e260e270d270d270d27270c0e270d27270c0e270d280c280c280c280c28260e250e0c000186260e260d260e0c280c28260e0c280c280c280c280c290c27270d0d270d27270d0d270d270d270d270e270d27260d270d0d000185270d260d270d0d270d27270c0d280d280c280c280c280c28260e0c280c28260e0c280c280c280c280d270e26270d270c0d000186260e250e260e0d270d27270c0d280d260e270d270d270d27270d0d270d28260e0c280c280c280c280c280c28260e250e0c000187250e260e250e0c280d27260e0c280c280c280c290d260e27270c0d270e27260d0d270d270d270e260e270d28250e260e0c000185270d270c270d0d270d28260e0c280c280c280c280c280c28260e0c280c28260e0c280c280d270d270d270d27270d270c0d000186260d270d260d0d270e27260d0d270d270d270e260e270d28250e0c280c29250e0c280c280d280c280c280c28260d260e0c000187250e260e250e0c280c29250e0c280d270e260e270d270d27270c0e260e27270c0d280d270d280c280c280c28260e250e0c000187260e250e260e0c280c28260e0c270d280c280c280c280c28260e0c280d27270d0d260e270d270d270d270d27270d260d0d000186260d270c270d0d270d27270d0d270d270d280d270d270d28250e0c280d27260e0c280c280c280d270d270e27270c270d0d000185260e260d260e0c280d27270d0d270d270d270d270d270d27270d0d270d28260e0c280c280c280c280c280d27260e260d0c000187260d260e250e0c28000000000000",
                "off": "b1c0b004929e06000c28260d0d270d27260e0c280d270d270d270d270d270d28260d0c000186270d260e260d0c280d28250e0c280c280c280d270d270d28260d0c280d27260e0d270d270e260e270d260e270d27270c0e000185260d260e250e0c280d27270d0c280d270d270e260e260e27260d0d270d27270d0d270d270d270d270e260e270d28260d0c000185270d270d260d0d270d27270d0d270d270d270d270d270e27260e0c280c28260e0c280c280c280c280c280c280d27260e0c000185270e250e260e0c280c28260d0c280d280c280c280c280c28260d0d280c28250e0c290c270d280c280d270d270d27270d0d000185260e250e260e0c280c28260d0d280c280c280d270d270d27270d0d270d27270d0d270d270d270d270d270e260e26270d0d000185270d270c270d0d270d27270d0d270d270d270d270d270e26270d0d280c28260e0c280c280c280c280d270d270d28250e0c000186270d260d270d0d270d28250e0c280c280c280d270d280c28260e0c280c28260d0c280d280c280d270d270d270d27270d0d000185260e250e260e0c280c28260d0d280c280c280d270d270d27270d0d270d27270d0d270d270d270d270d270d270e26270d0d000185270d270c270d0d270d27270d0d270d270d270d270e260e26270d0d280c28260e0c280c280c280d270d270d270d28250e0c000186270c270c270d0d280c28260e0c280c280c280d270c280d28250e0c280c28260e0c280c280c280c280d270e260e27270c0d000186260d260e250e0c280d27260e0c280c280d270d280c280d27270c0e270d27260d0d270e260e270d270d270d270d27270c0e000185270d270c270d0d270d27270d0d270d270d270d270e260e26270d0d270d28260d0d280c280c280c280d270d270d28260d0c000186270c270d270c0d280d28250e0c280c290c270d280c280c28260e0c280c28260d0c280d270d280c280c280d270d27270c0e000185260e250e260e0c280c28260d0c280c290c270d280c280d27270c0e270d27260d0d270e260e270d270d270d270d27270c0e000185270c270d270d0d270d27270d0d270d270d270d270d270e27260d0d270d27270d0d280c280c280c280d270d270d28260d0c000186270c270d270c0d270d29250e0c280c280d270d280c280c28260d0d280c28260d0d270d280c280c280c280e260d28260d0d000185260e260d260e0c280c28260e0c280c280c280c280d270e26270d0d270d27270d0d270d270d270e260e260e260e26270d0d000185270d270c270d0d270d27270d0d270d270d270d270d270e27260d0d270d27270d0d270d280c280c280d270d280c28260d0c000185270d270d260d0d270d27270d0d280c280c280c280c280d27260e0c280c28260e0c280c280c280c280d270d270d27270d0d000186250e260d260e0c280c28260e0c280c280c280c280c280d27270d0c280d27270d0d270d270d270d270d270d270d27270c0e000185260e260d260e0d270d27260d0d270e260e260e270d270d27270c0e260e27260d0d270d270e260e270d280c280c28260d0c000186270c270d270c0d270e27260d0d270d270d290c280c280c28260d0d270d28250e0c280d270d280c280c280c280c28260d0d000186260e250e260e0c280c28260d0d280c280c280c280c28000000000000"
            }
        }
    ]
}

**Comment by ggroel** [comment]
Hello, I send you an example of my code, it seems to me that your error is to send the code as “OFF"

                {
                    "name": "Luz Luli",
                    "type": "switch",
                    "host": "10.0.0.23",
                    "data": {
                        "on": [
                            {
                                "data": "2600880000012892141115121411131314121411141214121335153514351535143515351435153515111412143514121412131214351511143515351412143514351535141214351511141213131312131313121313141213121412131314111411141213131313121314121412131213121313141213131213131313121313131213131412141114000d050000000000000000000000000000",
                                "sendCount": 2,
                                "interval": 0.5
                            }
                        ],
                        "off": [
                            {
                                "data": "2600880000012892141115121411131314121411141214121335153514351535143515351435153515111412143514121412131214351511143515351412143514351535141214351511141213131312131313121313141213121412131314111411141213131313121314121412131213121313141213131213131313121313131213131412141114000d050000000000000000000000000000",
                                "sendCount": 2,
                                "interval": 0.5
                            }
                        ]
                    }
                },

**Comment by AnthonySiravo** [comment]
@ggroel Thank you that worked perfectly!
