### ISSUE TITLE
Window covering accesory not respecting the initialDelay 

### ISSUE THREAD

**Issue by neramirez** [kiwi-cam/homebridge-broadlink-rm#589]
**Describe the bug**
Whenever I send multiple commands to windowCovering trough RF, I can see in the logs that the sendHex is executed without waiting specified `initialDelay` rendering in conflicting hex on the broadlink device

This seems to be happening when there are more than ~2-3 window covering commands executed at the same time

**Comment by neramirez** [comment]
The problem is due to commands not being enqueued, so its needed to be queued, Im working on a fix if anyone is interested

**Comment by tomky** [comment]
I encountered similar issues and find that it is due to that commands are not queued. Is it possible to fix this?
