### ISSUE TITLE
ON Blasts 3 times

### ISSUE THREAD

**Issue by paulobriennz** [kiwi-cam/homebridge-broadlink-rm#590]
Have got it all working and learning with a Broadlink RM4 Pro. Learnt TV off and on all okay.

Trying to add Daikin heat pumps.  I train it with the ON command from remote.  When it sends the ON through HomeBridge, it send like three times.. (can see in log) and that turns Heatpump on then off, then confuses it.

Ive implemented the sendCount and set to 1 but still happens.. any ideas?  Works fine when I choose Daikin remote through Broadlink app.

I've read forums where someone ended up buying another RM4 and setting that up to learn and then using original one to send the codes from the broad link app (which differ from what the remote sends out...)... any help appreciated.

**Comment by kiwi-cam** [comment]
Can you share what you have in your config.json? I use this for my Heat pump and don't have this issue so I'm curious where this is coming from.
