### ISSUE TITLE
Logging level stuck on INFO (v4.4.12)

### ISSUE THREAD

**Issue by rfcarv** [kiwi-cam/homebridge-broadlink-rm#594]
**Describe the bug**
The level of logging is always INFO no matter the level set in config.

**To Reproduce**
1) Install last plugin version 4.4.12
2) Set “logLevel” to any level
3) Logs appear with INFO description

**Comment by kiwi-cam** [comment]
What accessory are you seeing this on? I'll see if I can recreate the issue.

**Comment by rfcarv** [comment]
On air conditioner accessories.
I did a little debugging and verified that the "logLevel" variable is always set to value "2" even if i set it to another value  in config (ex: "logLevel": "critical"). But I couldn't find the reason why.
The result of this, is that temperature and humidity values are logged aproximately once every second, spamming the logs.
As a temporary measure to limit the excess logging, I change the onTemperature() function (line 425 of aircon.js) to show log temperature and humidity only if "logLevel < 2", instead of the original "logLevel <=2" (lines 436 and 444 of aircon.js).

**Comment by murtazabasrai** [comment]
I have the same issue where logLevel=warning is not working for temperature and humidity sensors. 
I think this issue relates to https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/603

I have shared more details about the issue in my comment: https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/603#issuecomment-1600871044

Thank you

**Comment by murtazabasrai** [comment]
Update: See if this solution fixes your issue @rfcarv 
https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/603#issuecomment-1600942137

**Comment by rfcarv** [comment]
@murtazabasrai 

Thank you.
Your solution works!

PS: Same problem as https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/603

CC: @kiwi-cam
