### ISSUE TITLE
 TypeError: log is not a function

### ISSUE THREAD

**Issue by banboobee** [kiwi-cam/homebridge-broadlink-rm#595]
Dear kiwi-cam

I believe following exception is raising at restarting for the users running the versions prior to the latest. 

> TypeError: log is not a function

To deal with the problem, in the following line, 

https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/d89f6e7b82e60d76cbd36bd03b8fb8a6cd1a8a18/platform.js#L48

argument 'log' needs to be passed to checkForUpdates(). I think.

If this is my misunderstanding, sorry for the bothering.

**Comment by Itay1787** [comment]
I just updated to the latest version of the plugin and everything working again.

**Comment by banboobee** [comment]
#606
