### ISSUE TITLE
air-conditioner completely stopped working

### ISSUE THREAD

**Issue by lpamota** [kiwi-cam/homebridge-broadlink-rm#60]
Not sure if caused by the update of iOS 14 but my air-conditioner completely stopped working. I can only turn it on but after that it won't turn off, change temperature or change between heat and cool. I can see in homebridge logs that the hex codes are being sent. Can someone have any idea of what might be the root cause?

**Comment by Edsonytic** [comment]
I have three air conditioning accessories running through two Rm devices and have updated to iOS 14 without any responsiveness issues. I would suggest to provide your configuration and maybe run-in debug mode for a minute to provide logs.

**Comment by kiwi-cam** [comment]
Hi @lpamota.  Could I suggest you add `"debug": true` to your BroadlinkRM config and capture the logs for us to see what is happening? Then share your logs and your config and we'll see if we can get to the bottom of this for you.
