### ISSUE TITLE
plug in crashes with "Log is not a function"

### ISSUE THREAD

**Issue by jeremydvoss** [kiwi-cam/homebridge-broadlink-rm#601]
**Describe the bug**
Starting recently, plug in crashes and restarts indefinitely with the same message. Most devices lost in Homekit (all except projector)

**To Reproduce**
Use my config. Restart homebridge. See log for error.

**Expected behavior**
Plug in succeeds and adds devices to homekit

**Screenshots**

**Desktop (please complete the following information):**
 - OS: homebridge running in windows.
 - Browser firefox
 - Version plug inv4.4.11

**Smartphone (please complete the following information):**
 - Device: iphone 12
 - OS: ios
 - Browser firefox
 - Version:

**Additional context**
Config:
![image](https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/4807316/c460457c-4508-4694-88a9-4d90c8aa5065)
![image](https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/4807316/43c0c461-ef68-46fb-9ebb-ba3da540d1b4)
![image](https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/4807316/7fb86921-0460-4ea4-abc0-b321df42dc60)
Log:
![image](https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/4807316/2b454b07-c6db-49d0-9a15-690ca0866233)

**Comment by ggroel** [comment]
Hello, you have updated the node.js?. I threw a similar mistake until I updated the version. The last version of the node is 18.16.0.

**Comment by kiwi-cam** [comment]
This fix is included in v4.4.13
