### ISSUE TITLE
Red RM Mini 3 must have `isRM4` set to true to work

### ISSUE THREAD

**Issue by hepcat72** [kiwi-cam/homebridge-broadlink-rm#604]
**Describe the bug**
**UPDATE**: A user's comment lead me to a solution: change the `isRM4` setting to true, even though it's an [RM Mini 3](https://www.amazon.com/dp/B07X5XKM4L/?coliid=I1HNWYBQLTC6M8&colid=ZGS6KPUUTGG3&psc=1&ref_=list_c_wl_lv_ov_lig_dp_it). As soon as I did that, it started working.

**Original issue description:**
I recently got a second RM Mini 3.  It is my second such device, but this one is red in color.  The old black one works but the new red one fails to send codes via this plugin.  I am on plugin version 4.4.6.

I have 4 buttons setup using the new red mini.  When I toggle them on/off in the home app:

- The home app happily changes the virtual button stats
- The homebridge log shows no errors and appears as if the codes were sent by the mini
- The virtual button statuses in the homebridge web interface happily show the button statuses changing
- The red mini's light never blinks on at all and the target device does not turn on or off

Note that I can control the red mini just fine using the Broadlink iPhone app.

The old black RM mini 3 works just fine via homebridge.  No problems there.

A few possibly relevant notes:

- I **did** unlock the new red mini in the broadlink app settings.
- My old RM mini 3 is not set up in the Broadlink app.  It's still in the e-control app (not sure if that's relevant).
- I set fixed IPs for both devices and quadruple-checked the mac addresses and the (fixed) DHCP addresses.
- After a false start with the config, I think it's right. Here's the config:
```
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "hosts": [
                {
                    "address": "192.168.1.61",
                    "mac": "c8:f7:42:16:f7:7f",
                    "isRFSupported": false,
                    "isRM4": false
                },
                {
                    "address": "192.168.1.168",
                    "mac": "24:df:a7:36:54:9a",
                    "isRFSupported": false,
                    "isRM4": false
                }
            ],
            "accessories": [
                {
                    "name": "Bedroom Window Fan",
                    "host": "192.168.1.168",
                    "type": "outlet",
                    "allowResend": true,
                    "data": {
                        "on": "2600f200240e290e0d2a290e290e0e290e290e290e290e290e292aea2a0d2a0d0e2a290e290e0e290e290e290e290e290e2929eb2a0d2a0d0e292a0d2a0d0e2a0d2a0e290e290e290e2929eb2a0d2a0d0e292a0d2a0d0e2a0d2a0d2a0d2a0e290e2929eb2a0d2a0d0e292a0d2a0d0e290e2a0d2a0d2a0d2a0d2a29eb290e2a0d0e292a0d2a0d0e290e290e2a0d2a0d2a0d2a29eb290e290e0e292a0d2a0d0e290e290e2a0d2a0d2a0d2a29eb290e290e0d2a290f290e0c2b0d2a0d2a0c2b0d2a0d2a29eb290e290e0e29290e2a0e0d290e290e2a0d2a0d2a0d2a29eb290e290e0e292a0d2a0d0e290e290e2a0d2a0d2a0d2a29000d05",
                        "off": "2600f200240e290e0d2a290e290e0e290e290e290e290e290e292aea2a0d2a0d0e2a290e290e0e290e290e290e290e290e2929eb2a0d2a0d0e292a0d2a0d0e2a0d2a0e290e290e290e2929eb2a0d2a0d0e292a0d2a0d0e2a0d2a0d2a0d2a0e290e2929eb2a0d2a0d0e292a0d2a0d0e290e2a0d2a0d2a0d2a0d2a29eb290e2a0d0e292a0d2a0d0e290e290e2a0d2a0d2a0d2a29eb290e290e0e292a0d2a0d0e290e290e2a0d2a0d2a0d2a29eb290e290e0d2a290f290e0c2b0d2a0d2a0c2b0d2a0d2a29eb290e290e0e29290e2a0e0d290e290e2a0d2a0d2a0d2a29eb290e290e0e292a0d2a0d0e290e290e2a0d2a0d2a0d2a29000d05"
                    }
                },
```

**To Reproduce**
1. Get a [red RM Mini 3](https://www.amazon.com/dp/B07X5XKM4L/?coliid=I1HNWYBQLTC6M8&colid=ZGS6KPUUTGG3&psc=1&ref_=list_c_wl_lv_ov_lig_dp_it)
2. Set `isRM4` to false (because it's an RM3) and set up any accessory
3. Go to the accessories tab on the homebridge web interface
4. Click any of the buttons for the devices for the red mini (e.g. my window fan)
5. See the command being sent in the log without error, but the light on the mini never flashes

**Expected behavior**
The light on the red mini should flash on and it should send the code.  If it doesn't, there should be an error in the homebridge log, but neither happen.

Outside of renaming the "isRM4" setting to something more accurate, I suggest changing the doc's `isRM4` description from:
> Marks the device as a newer RM4 device and sends data with required new headers.
to:
> Marks the device as a newer RM4 device and sends data with required new headers. Note, some RM3's may need to have `isRM4` set to true, such as the red RM3's.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: Monterey

**Smartphone (please complete the following information):**
 - Device: iPhone SE second gen
 - OS: 16.2
 - Browser: Stock browser, Safari
 - Version: 16.2?

**Additional context**
I've been using this plugin for my original RM Mini 3 for years without issue, with approximately 20 accessories set up for it. I added "host" to their configs when I set up the second mini and they still work just fine.  There is another issue with another user here who has the same issue as me and he managed to get his to work, but he cannot explain what did it and even though I tried the same things he did, my new mini refuses to respond.

**Comment by hepcat72** [comment]
I just tried searching through the code to see if I could figure out a way to try to manually send commands to my Mini so that I can view the responses and debug my issue, but I couldn't quickly figure it out.  Anyone have any tips on trying to manually send commands and view the responses?

**Comment by euphguy** [comment]
Try setting isRM4 to true in the hosts section for your new mini. I had to set that for my red minis. Works great now.

**Comment by hepcat72** [comment]
> Try setting isRM4 to true in the hosts section for your new mini. I had to set that for my red minis. Works great now.

That worked! That should probably be documented. Don't know if it's specific to the red RM Mini 3, but clearly `isRM4` is misleading. Perhaps it's really a firmware thing?

**Comment by kiwi-cam** [comment]
This device must use newer coding, the same as RM4 devices. Automatic discovery should've detected this - and things like this is the reason it is generally recommended: https://broadlink.kiwicam.nz/#device-discovery

**Comment by hepcat72** [comment]
Automatic discovery didn't work, that's why I added the config to set the address and everything.

**Comment by hepcat72** [comment]
Until I added the config, all the commands were going to the old RM3.
