### ISSUE TITLE
Choosing decimal numbers in air-conditioner configuration for temperature

### ISSUE THREAD

**Issue by tb3o3** [kiwi-cam/homebridge-broadlink-rm#605]
Add in configuration of air-conditioner the ability to choose decimal numbers used to select temperature. 
My air-conditioner accept only numbers without decimal, so when I choose in home app a wrong temp (21,5) the plug-in set on a/c the default temp. In home app I want only integer numbers

Regards

**Comment by giuliomagnifico** [comment]
Same issue, I tried to use  `"stepSize": 1,` but doesn't seem to work.

**Comment by amitmargalit** [comment]
I don't know if there is a way of not exposing to HomeKit .5 numbers. great idea tho.

**Comment by kiwi-cam** [comment]
For an airconditioner, you should be using tempStepSize, the same as for the heater-cooler accessory: https://broadlink.kiwicam.nz/#air-conditioner

Sorry - I'd missed adding it to the documentation but it's there now.

**Comment by giuliomagnifico** [comment]
> For an airconditioner, you should be using tempStepSize, the same as for the heater-cooler accessory: https://broadlink.kiwicam.nz/#air-conditioner

I've already tried `tempStepSize` but it doesn't work for me:

```
                    "name": "Clima salotto",
                    "host": "192.168.50.201",
                    "type": "air-conditioner",
                    "replaceAutoMode": "cool",
                    "coolOnly": true,
                    "tempStepSize": 1,
                    "defaultCoolTemperature": 22,
                    "minTemperature": 17,
                    "maxTemperature": 30,
                    "data": {
...
```
![Screenshot 2023-06-19 at 08 18 59](https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/1975176/8c23300e-af31-4c2f-b760-ada5c54b470f)

**Comment by kiwi-cam** [comment]
Hmmm I've been testing tempStepSize on an AC here and it's working as expected for me.

Are you running the latest version? Is there anything in the logs?

**Comment by giuliomagnifico** [comment]
After a reboot of my Homebridge server it worked as expected with one degree steps. Thanks for the help!
