### ISSUE TITLE
RM4 Pro Learn Feature Doesn't Work -- Scan Feature Produces inconsistent results. With Workaround.

### ISSUE THREAD

**Issue by smweil** [kiwi-cam/homebridge-broadlink-rm#611]
**Describe the bug**
RM4 Pro does not pick up button presses on the learn feature.  When using the scan feature inconsistent results are reported with varying hex code lengths. 

**To Reproduce**

1. Click on 'Learn'

**Expected behavior**
Expect it to pick up RF button on single press

**Additional context and Workaround**
The new RMPro's on the Broadlink app ask for a frequency before starting the learn command. I suspect this is not captured in the plug-in so it causes a failure.  The workaround to have home bridge pickup single button presses was to have two iPhones, one connected to HomeKit and one connected to the RM4 Pro with the Broadlink app.

1) In the Broadlink app: Add a new device and start learn button procedure. Pause where it asks you to input a frequency
2)In the HomeKit app prepare to toggle the the "Learn" feature on HomeKit
3)Advance the Broadlink app to the next screen (the learn screen) and IMMEDIATELY toggle the learn feature on the HomeKit phone
4)Quickly single press the button that you want to learn on your remote

If successful the code will be displayed on the home bridge console. If the Broadlink app detects a button press, try again with more precise timing. It takes a bit to have the code forwarded to home bridge and not broad link.

This method was adapted from a HA post by AhmedBahgat and pasted below:
[HA Post](https://community.home-assistant.io/t/broadlink-manager-nicer-way-to-learn-and-send-ir-rf-commands/58770/352)

Sure and I am sorry for the lengthy steps as I wanted to make sure it is followed with no confusion:

The environment I have is Home Assistant 0.115.2 on Raspberry Pi 4 with 4GB RAM, I also use Powershell on Windows to set the SSID and Password for the RM4 Pro, but you can use any method of setting the SSID for the Broadlink devices

I will say the idea in brief then I will walk you through the steps in more details . We will use the Broadlink App (latest version) to learn the RF codes while HA is also set to learn the RF codes at the same time, it will be like a competition between the two but we always want HA to win, if Broadlink App wins the learning before HA then we reject it and redo the process of learning again for that button we currently programming, so here is the steps in details

1- We need HA to talk to RM4 Pro and recognize it through the Broadlink integration released with HA 0.115

2- To do that we need to put the RM4 Pro in AP mode and set the SSID and password, hold reset button until light flashes quick and let it restart then hold reset again until light flashes quick with pauses between 4 or 5 flashes, then you set the SSID with whatever means, I used PowerShell ran as Administrator on Windows machine then executed Python commands from the PowerShell window to set the SSID and password for the RM4 Pro while my pc is connected to the RM4 Pro access point, very easy but you need Python installed on Windows and I think you also need the Broadlink components under Python which you can get easily from GetHUB

3- You also need to set the RM4 Pro with a static IP address through your DHCP under your router and by using the MAC address of the RM4 Pro

4- After you set the SSID and password and restarted your Broadlink, HA will connect easily to it through the integration, you only need to supply the IP address of the Broadlink which should be reserved for it under your router

5- Get all your RF remotes ready as we do not need to worry about IR remotes because HA can learn their codes easily, our problem is the RF remotes
6- Now we need to run Broadlink App latest version on your mobile, and if you have Home, Devices, and Remotes configured, you MUST remove all of them

7- Create a new home in a totally different country and time zone to whatever you set before, and if you will do the process again always start with deleting the home and all devices/remotes and always select different country and time zone to whatever you selected before

8- Broadlink app should then ask you to configure the ‘found’ RM4 Pro, say yes and it will add it to the new home you created and you should give it a name BUT before the last step of adding the device, we need to get HA ready to learn

9- Go to Developers Tools and under Services select
remote.learn_command

The entity_id should be the RM4 Pro we added to HA before
In my case the service data yaml was

entity_id: remote.rm4_pro_remote
device: fan_rumpus
command: Low
timeout: 20

Note here that the device should be the same name for each remote and its buttons, i.e. under each remote, we only going to change the command after we learn the previous command

in my next case, the service data for the next button on the same remote was

entity_id: remote.rm4_pro_remote
device: fan_rumpus
command: Med
timeout: 20

And so on until we finish all buttons on the remote the we move on to the next remote and at that point, we need to change the device to be the next remote, for example

entity_id: remote.rm4_pro_remote
device: fan_living
command: Low
timeout: 20

10- Now Press the Call service once on the HA Services, then finish adding the Broadlink device to the Broadlink app that we paused on step 8

11- In the App add RF remote and we will only use one button to learn all our RF remotes and their buttons, this will allow us to do the process quickly if you have a lot of RF remotes, I programmed 8 fans’ remotes at once

13- When the app starts the learning countdown and the red light comes on the Broadlink device, at this moment you will need to Call the Service under HA and WAIT until you get the HA notification to press the button on the remote

14- When you get the HA notification to press the remote button, this may take a second or it may take few seconds, just be patient until you see the notification, and then you can point the remote to the Broadlink and press the button you want on it to be learned

15- Here we have such situation when we want HA to learn first, for us it does not matter if the App learns or not, in fact, if the app learns the code we need to reject it

16- In my case HA learned the code most of the times before the App and you will know that when you see the HA notification colour disappears

17- If HA learns first then we need to wait until the app learning countdown expires and fails and it will ask you to try again and we say yes and we move on to the next button

18- When we move on to the next button, we need to change the command in the service data under HA or the device also if we moved on to another remote

19- If the app learns first, we need to reject it but do not start the try again until the HA notification disappears which will take a few seconds, and after it disappears try learning again on the app and when the countdown starts press Call service on the HA tools and wait for the HA notification to appear then you press the button on the remote, I cannot stress more how you MUST wait for the HA notification to appear before you press the button on the remote

20- If it fails at any point to learn just start learning again with the app and repeat the process for the same button until it learns, in my case, it was reliable most of the times, and when it was not I just repeated the process and succeeded for whatever button on whatever remote

21- After you finish all your RF remotes you will end up with the Broadlink file under .storage filled with all the learned codes which can be used now to create switches under HA, please make a copy of this file and save it somewhere so you don’t lose it or overwrite it

22- The last step is to reset the Broadlink again by the two long presses because the moment you restart the Broadlink device, HA will lose connection to it because the App will take control, but at least we got all the RF codes, all you need to do after resetting is simply add the SSID and password again and add it to home-assistant via the new Broadlink integration

23- And finally if you want to add more RF remotes or discovered later that any of the learned RF remotes not working, you can redo the process for only the buttons you found not working or the new remotes, and the process will be the same from step 1, keep in mind that all the learned and working codes will stay working even if you redo the process again for any new RF remotes

Have a great day everyone

**Comment by tablatronix** [comment]
reference, add frequency selection, 

https://github.com/mjg59/python-broadlink/pull/613

Is this fork dead? stalebot should not be running on issues with tags..
