### ISSUE TITLE
是否能减少下日志输出

### ISSUE THREAD

**Issue by installH** [kiwi-cam/homebridge-broadlink-rm#613]
<img width="219" alt="image" src="https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/29174111/1dcefd29-4692-40e2-9766-81cfd762b076">

这块逻辑
<img width="1663" alt="image" src="https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/29174111/76a4e576-8b6a-4fbc-a9f1-35421af37615">

**Comment by kiwi-cam** [comment]
You've got two options, specify a temperature source so it has meaningful information, or adjust the loglevel: https://broadlink.kiwicam.nz/#logLevels
