### ISSUE TITLE
Default tempStepSize (0.5) leads to rebooting of the bridge if there is no IR command for this temperature

### ISSUE THREAD

**Issue by stephenkopylov** [kiwi-cam/homebridge-broadlink-rm#616]
First of all - thanks for this amazing plugin!

**Describe the bug**
Default tempStepSize (0.5) leads to rebooting of the bridge if there is no IR command for this temperature

**To Reproduce**
Just put something like this in your config and try to set 16.5 as temp.
```
"temperatureCodes": {
    "16": "260...",
    "17": "260....",    
}
```

I think at least it should just pass the call withount crashing

Also - is it okay to set the default value of tempStepSize to 0.5? I haven't seen any AC with this temp step here in Europe 😄
So maybe 1 is better as more common step overall?

**Comment by wizardofozzie** [comment]
It doesn't reboot for me but is `tempStepSize` a property in heater-cooler?

**Comment by kiwi-cam** [comment]
Sure is: https://broadlink.kiwicam.nz/#heatercooler

**Comment by wizardofozzie** [comment]
> Sure is: https://broadlink.kiwicam.nz/#heatercooler

Man I just got the heater-cooler working today after playing around for 2-3 weeks- I am so happy and incredibly grateful for your work with this plugin! Thank you!
