### ISSUE TITLE
Hex codes not sending since v4.3.1 update

### ISSUE THREAD

**Issue by benjaminbogdanovic** [kiwi-cam/homebridge-broadlink-rm#62]
I updated, set up my TV again, and now the codes won't send from either my RM3 or RM4.

![image](https://user-images.githubusercontent.com/16837687/93726404-bf8fae80-fbad-11ea-81af-d03b32dd288e.png)

![image](https://user-images.githubusercontent.com/16837687/93726346-73dd0500-fbad-11ea-83ce-5bfbcb2d88b2.png)

**Comment by masterfordev** [comment]
Whats version of homebridge have installed?

**Comment by benjaminbogdanovic** [comment]
v1.2.3

**Comment by masterfordev** [comment]
Im on 1.2.2 and no problems. You tried get back to 1.2.2?

**Comment by kiwi-cam** [comment]
It appears to be an issue in homebridge-upnp: https://github.com/langovoi/homebridge-upnp/issues/10.  I know that's not much help but hopefully someone there can come up with a solution.

If it helps, I'm using these versions and not having the issue:
homebridge-broadlink-rm-pro@4.3.1
homebridge@1.2.2

I don't have homebridge-upnp

I'll try updating to homebridge@1.2.3 and see if I can recreate the issue too.

**Comment by benjaminbogdanovic** [comment]
The homebridge-upnp issue has been around for a while, and it was not causing an issue with this plugin. I shall remove it and see.

I shall try homebridge@1.2.2.

Thanks for trying to recreate the issue.

**Comment by kiwi-cam** [comment]
No issues on homebridge@1.2.3 here either - sorry.

The latest version of this did include a fix for an incorrect format of the MAC address - the first and third octet were swapped. Do you specify hosts by MAC address in your config by chance?

**Comment by benjaminbogdanovic** [comment]
It was the MAC address issue. I do specify hosts. It might catch a few people out!
Thanks for the help!

**Comment by kiwi-cam** [comment]
I'll update some notes and push another release to help others. Thanks!
