### ISSUE TITLE
Broadlink RM didn't supported anymore under iOS 17 Bete 3 

### ISSUE THREAD

**Issue by NeoRame** [kiwi-cam/homebridge-broadlink-rm#627]
**Describe the bug**
Since iOS Beta 3 This plugin isn't supported anymore from the Home App. I can use it via HomeBridge but it isn't useable in the HomeApp

**To Reproduce**

**Expected behavior**

**Screenshots**
![IMG_8603](https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/3717141/1a01a8f3-f282-4b74-a371-3c158a2c0262)
![IMG_8602](https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/3717141/7501ead6-316a-4778-a7aa-4be996358b61)

**Smartphone (please complete the following information):**
 - Device: iPhone13 Pro
 - OS: iOS17 Beta3
 - Browser Chrome
 - Version ??

**Additional context**

**Comment by alexbrazier** [comment]
@NeoRame Is this still an issue even after restarting everything? I had a similar issue recently but after restarting my apple TV (home hub) it started working again.

I'm on iOS 17 beta 2 where it is still working so reluctant to update if it is going to break.

Edit: Upgraded and it still works for me
