### ISSUE TITLE
RM3 Device Does Not Work When Host Is Defined Unless Specified As "RM4" Device

### ISSUE THREAD

**Issue by iSteve-O** [kiwi-cam/homebridge-broadlink-rm#628]
**Describe the bug**
I was having trouble lately where after a while I would press a button in the home app and it wouldnt work because the broad link device was not discovered or had disconnected from homebridge. I decided to define my hosts instead of using the auto-discovery to see if they would work any better. One is RM4 pro & the other is RM3. When I had the RM3 defined as RM3 it would not work but defined as RM4 (without RF) it works perfectly. 

**To Reproduce**
1. Define a host using an RM3 device defined as RM3 device.
2. It will not work...
3. Re-define in config as RM4
4. Watch it work...

**Expected behavior**
I expect an RM3 to work when RM3 is defined in the config.

**Additional context**
My working config (top is RM3, bottom is RM4):
```
            "hosts": [
                {
                    "address": "192.168.1.xx",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "isRFSupported": false,
                    "isRM4": true
                },
                {
                    "address": "192.168.1.xx",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "isRFSupported": true,
                    "isRM4": true
                }
            ]
```

I know this isn't urgent but it could confuse some. I'm good I just couldn't live with myself if I didn't bring it up.

**Comment by kiwi-cam** [comment]
Not much I can do about this when you're manually specifying your hosts. Some RM3 devices use the newer RM4 command formats. The auto discovery is setup to handle this but it's a bit of a trick to pick up on if you're setting them up manually.

**Comment by iSteve-O** [comment]
Maybe you can just add a note to the doc about some RM3's having newer headers requiring it being set to rm4 in the config. 

Just a suggestion to save people some time, as it would have saved me about 2 hours of fiddling. 

I appreciate you taking the time to respond & I appreciate your work on the plugin. 

Have a great day!
