### ISSUE TITLE
TV not responding periodically since external accessory change

### ISSUE THREAD

**Issue by benjaminbogdanovic** [kiwi-cam/homebridge-broadlink-rm#64]
HomeBride: v1.2.3
Node.js Version: v12.18.4
homebridge-broadlink-rm-pro: v4.3.2
Config:
{
                    "name": "Bedroom TV",
                    "host": "24:df:a7:d6:00:75",
                    "type": "tv",
                    "enableAutoOff": false,
                    "data": {
...

- - -
Since external accessory change my TV is showing as not responding from time to time. The external accessory is shaky on another TV plugin I use. Could it be checking the device is still there from time to time and not getting a response? Any ideas?

**Comment by masterfordev** [comment]
Everything works perfectly with me, but i use an assigned IP on the host.

**Comment by Faisalthe01** [comment]
Yeah same here i use IP with host, it works fine. Why don’t you use IP address? Give Broadlink a static ip first.

**Comment by Faisalthe01** [comment]
> Everything works perfectly with me, but i use an assigned IP on the host.

Hey @masterfordev, off topic but the coolOnly and heatOnly should also work for AC, did you try it?

**Comment by benjaminbogdanovic** [comment]
> Yeah same here i use IP with host, it works fine. Why don’t you use IP address? Give Broadlink a static ip first.

I will try that. I used the MAC address as it was a once step process when I first set everything up.

**Comment by benjaminbogdanovic** [comment]
> Hey @masterfordev, off topic but the coolOnly and heatOnly should also work for AC, did you try it?

I have tried it actually. Works as it should. Shame I will not probably need it until next summer! I'm in the UK 🤣

**Comment by Faisalthe01** [comment]
> > Yeah same here i use IP with host, it works fine. Why don’t you use IP address? Give Broadlink a static ip first.
> 
> I will try that. I used the MAC address as it was a once step process when I first set everything up.

Always use IP instead of MAC its more reliable. Just give static IP to Broadlink from your router, otherwise you will be updating your config file every time Broadlink gets a new IP

**Comment by masterfordev** [comment]
> > Everything works perfectly with me, but i use an assigned IP on the host.
> 
> 
> 
> Hey @masterfordev, off topic but the coolOnly and heatOnly should also work for AC, did you try it? 

Yeah bro! Works like a charm! 👌👌 thanks! Is a great option. I just had to change "temperatureXX" to "coolXX" but works fine 👍👍

![Screenshot](https://user-images.githubusercontent.com/29960705/93735829-8b12f700-fb9b-11ea-9e4c-b4ac9b024638.png)

**Comment by Faisalthe01** [comment]
> > > Everything works perfectly with me, but i use an assigned IP on the host.
> > 
> > 
> > Hey @masterfordev, off topic but the coolOnly and heatOnly should also work for AC, did you try it?
> 
> Yeah bro! Works like a charm! 👌👌 thanks! Is a great option. I just had to change "temperatureXX" to "coolXX" but works fine 👍👍
> 
> ![Screenshot](https://user-images.githubusercontent.com/29960705/93735829-8b12f700-fb9b-11ea-9e4c-b4ac9b024638.png)

Awesome! See in your screenshot how the on/off button is missing the I/O graphic with thermostat accessory  but its there with HeaterCooler accessory if you hide other functions(Auto/off/cool) not sure why would Apple do that lol

![D730EA45-C5E0-4ED3-96C9-AE165DF7C364](https://user-images.githubusercontent.com/62862684/93736049-7d548480-fc22-11ea-8a15-2ea913033f8f.jpeg)

**Comment by benjaminbogdanovic** [comment]
> Always use IP instead of MAC its more reliable. Just give static IP to Broadlink from your router, otherwise you will be updating your config file every time Broadlink gets a new IP

I'll see how that goes for me. I was under the impression that the host was just used for determining which device the hex code is sent from. @kiwi-cam?

**Comment by masterfordev** [comment]
> Awesome! See in your screenshot how the on/off button is missing the I/O graphic with thermostat accessory  but its there with HeaterCooler accessory if you hide other functions(Auto/off/cool) not sure why would Apple do that lol
> 
> 
> 
> ![D730EA45-C5E0-4ED3-96C9-AE165DF7C364](https://user-images.githubusercontent.com/62862684/93736049-7d548480-fc22-11ea-8a15-2ea913033f8f.jpeg)
> 
> 

I thought it was normal lol 😂 i will re-add them.

**Comment by masterfordev** [comment]
> 
> I thought it was normal lol 😂 i will re-add them. 

Nope, its still hidden. Dont show I/O 😕

**Comment by benjaminbogdanovic** [comment]
What does your config look like?

**Comment by masterfordev** [comment]
![image](https://user-images.githubusercontent.com/29960705/93736921-01fdbf00-fb9f-11ea-9989-bc66e6d465fe.jpeg)

**Comment by Faisalthe01** [comment]
> > Awesome! See in your screenshot how the on/off button is missing the I/O graphic with thermostat accessory  but its there with HeaterCooler accessory if you hide other functions(Auto/off/cool) not sure why would Apple do that lol
> > ![D730EA45-C5E0-4ED3-96C9-AE165DF7C364](https://user-images.githubusercontent.com/62862684/93736049-7d548480-fc22-11ea-8a15-2ea913033f8f.jpeg)
> 
> I thought it was normal lol 😂 i will re-add them.

yeah it won't show that graphic only empty button that turns yellow when you turn it on. That's what i am saying if you hide functions with HeaterCooler accessory like i did, that graphic in button is there but with Thermostat Accessory (Broadlink is using) if you hide functions that graphic in button is not there. not sure why Apple would do that, a button with I/0 graphic in it seems empty

**Comment by Faisalthe01** [comment]
> > Always use IP instead of MAC its more reliable. Just give static IP to Broadlink from your router, otherwise you will be updating your config file every time Broadlink gets a new IP
> 
> I'll see how that goes for me. I was under the impression that the host was just used for determining which device the hex code is sent from. @kiwi-cam?

yea but it cannot fine the broadlink and send a HEX code the accessory will go to non responsive state

**Comment by masterfordev** [comment]
> 
> yeah it won't show that graphic only empty button that turns yellow when you turn it on. That's what i am saying if you hide functions with HeaterCooler accessory like i did, that graphic in button is there but with Thermostat Accessory (Broadlink is using) if you hide functions that graphic in button is not there. not sure why Apple would do that, a button with I/0 graphic in it seems empty

Oooh ok. Now I understand. Another off topic, your home app doesnt freeze when you try edit automatizations on ios14?

Ex: when i try edit one for turn off lights, tvs and ac, i tried add the ac again (because i re-added on homebridge) but the Home App freeze, idem if i try add a tv.

**Comment by Faisalthe01** [comment]
> it one for turn off lights, tvs and ac, i tried add the ac again (because i re-added on homebridge) b

it does with Scenes only and not with Automations and its been there since Beta 1. I have reported it to Apple, you do it too so they have more complaints.

**Comment by masterfordev** [comment]
> 
> it does with Scenes only and not with Automations and its been there since Beta 1. I have reported it to Apple, you do it too so they have more complaints.

It's true, i wanted to say scenes. I will report it too.

**Comment by benjaminbogdanovic** [comment]
It is still happening. It is noticeable when running scenes as they fail.

**Comment by masterfordev** [comment]
Working fine here. But today I noticed a bug, in the control panel, the ac appears “this accessory does not respond”. But if I open the Home app everything appears fine.

![image](https://user-images.githubusercontent.com/29960705/93843552-6d0acc80-fc57-11ea-9c8e-3a6a773720ae.jpeg)

![image](https://user-images.githubusercontent.com/29960705/93843355-d2aa8900-fc56-11ea-94d3-9924702da529.jpeg)

![image](https://user-images.githubusercontent.com/29960705/93843409-f077ee00-fc56-11ea-8c8a-8fdb3de74e4d.png)

You have this issue @kiwi-cam @Faisalthe01 ? Or this is because the AC dont have a feedback response over the broadlink?

**Comment by Faisalthe01** [comment]
@masterfordev mine is fine in the control centre too. what happens if you touch Home Favorites on Control Centre, same no response? and what happens when the AC is on and running?

**Comment by masterfordev** [comment]
> @masterfordev mine is fine in the control centre too. what happens if you touch Home Favorites on Control Centre, same no response? and what happens when the AC is on and running?
> 
> 

I haven't had the problem again. That is why I had no longer responded. If this come back, I'll notify it.

**Comment by kiwi-cam** [comment]
@benjaminbogdanovic Could you confirm the current status of your original issue - is it still occurring? is it a issue with this plug-in, or HomeKit in general?

**Comment by imtitanic** [comment]
Same here, sometimes the TVs showing as No response in Home App but in homebridge log everything look normally.

![Screen Shot 2020-10-21 at 11 30 00](https://user-images.githubusercontent.com/68301159/96756178-f1548a80-1390-11eb-986d-d8e77b9627a6.png)

**Log:**
> [2020-10-21 12:25:48] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> [2020-10-21 12:25:53] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> [2020-10-21 12:25:58] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> [2020-10-21 12:26:03] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> [2020-10-21 12:26:08] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> [2020-10-21 12:26:13] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false

**Config:**
```
"name": "Televisión Samsung",
                    "type": "tv",
                    "pingIPAddress": "192.168.101.120",
                    "pingIPAddressStateOnly": true,
                    "pingFrequency": 5
```

> @benjaminbogdanovic is it a issue with this plug-in, or HomeKit in general?

Now, I think it's a homekit (or homebridge) problem because Xbox (homebridge-xbox-tv) is showing as No response too.

**Comment by masterfordev** [comment]
I dont have thats issues. Yo have switch addeds to your Tv? Maybe thats the reason.

**Comment by sergoo-lbt** [comment]
> Same here, sometimes the TVs showing as No response in Home App but in homebridge log everything look normally.
> 
> ![Screen Shot 2020-10-21 at 11 30 00](https://user-images.githubusercontent.com/68301159/96756178-f1548a80-1390-11eb-986d-d8e77b9627a6.png)
> 
> **Log:**
> 
> > [2020-10-21 12:25:48] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> > [2020-10-21 12:25:53] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> > [2020-10-21 12:25:58] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> > [2020-10-21 12:26:03] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> > [2020-10-21 12:26:08] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> > [2020-10-21 12:26:13] [Broadlink RM3 Pro Plus] Televisión Samsung getSwitchState: false
> 
> **Config:**
> 
> ```
> "name": "Televisión Samsung",
>                     "type": "tv",
>                     "pingIPAddress": "192.168.101.120",
>                     "pingIPAddressStateOnly": true,
>                     "pingFrequency": 5
> ```
> 
> > @benjaminbogdanovic is it a issue with this plug-in, or HomeKit in general?
> 
> Now, I think it's a homekit (or homebridge) problem because Xbox (homebridge-xbox-tv) is showing as No response too.

Confirm! This problem has been present for a long time. There was no time to open the issue. The TV and receiver on one broadlink and the TV on the other broadlink always change the status to Not responding at the same time.  Several times a day. On the latest beta version too.

**Comment by sergoo-lbt** [comment]
> @benjaminbogdanovic Could you confirm the current status of your original issue - is it still occurring? is it a issue with this plug-in, or HomeKit in general?

@kiwi-cam , Hi! I wrote a comment above. The problem is present. Exactly the same.

**Comment by sergoo-lbt** [comment]
@kiwi-cam , Please look at this. And so every day!
![12DA2D8F-A151-4C90-A1E6-17B5076ED2FD](https://user-images.githubusercontent.com/64399012/97960094-8c5a5500-1dd2-11eb-9575-033cbcae0cd5.jpeg)

**Comment by kiwi-cam** [comment]
Sorry @sergoo-lbt , I'm not seeing this issue myself so troubleshooting is difficult. Could you try updating the config to `"debug": true,` and see what the logs show when you're having this issue?

**Comment by sergoo-lbt** [comment]
> Sorry @sergoo-lbt , I'm not seeing this issue myself so troubleshooting is difficult. Could you try updating the config to `"debug": true,` and see what the logs show when you're having this issue?

Yes, of course! I will definitely try to catch this bug.

**Comment by sergoo-lbt** [comment]
TVs still continue to bother. Constantly not responding. Several times a day. Everything is fine in the log. But for some reason, only the first TV added. This is very annoying...

**Comment by sergoo-lbt** [comment]
@kiwi-cam , hi! It doesn't work. I was never able to catch the log of this error. For some reason, only my second added TV is in the log. No more... Sadness...
