### ISSUE TITLE
Volume Control not working in Remote App

### ISSUE THREAD

**Issue by Crox77** [kiwi-cam/homebridge-broadlink-rm#66]
HI, I have updated to the latest version with the great new sub-cat icons, ive just tried to add volume control to my receiver, but every time I press the volume buttons on my iPhone when the remote app is open and deleted the receiver I get this error message.

[Crox-RM-Mini] Sony Amp VolumeSelector: No settings data found. Ignoring request

Anybody have any ideas please?
{
                    "name": "Sony Amp",
                    "type": "tv",
                    "subType": "Receiver",
                    "host": "192.168.1.87",
                    "data": {
                        "on": "2600fe015111291216112a1116122813151215121611161215121611291229121611160002d34f122a1116112a1116122812161215121611161215121512291228131611160002d44f1229121611291216112912161116121512161116121512281329121512160002d4511228121612281315122912151216111612151216111611291229121611160002d351112a1116112a1116122912151215121611161215121611291229121611160002d35112291116122912151229121512161116121512161116112a112a111611160002d3501229121611291216122912151215121611161215121611291229121611160002d35112281216122912151229121512161116121512151216112a1129121611160002d351112a1116112a1116122912151215121611161215121512291229121512160002d351122911161228131512281315121611161215121512161129122a111611160002d35111291216112a1116122911161215121611161215121512291229121611160002d35112281216122912151228131512161116121512151216112a112a111611160002d3511129121611291216122911161215121611161215121512291229121611160002d351112a111612291215122912151216111612151215121611291229121611160002d350122912161129121612291116121512161116111612151229122912151216000d0500000000000000000000",
                        "off": "2600fe015111291216112a1116122813151215121611161215121611291229121611160002d34f122a1116112a1116122812161215121611161215121512291228131611160002d44f1229121611291216112912161116121512161116121512281329121512160002d4511228121612281315122912151216111612151216111611291229121611160002d351112a1116112a1116122912151215121611161215121611291229121611160002d35112291116122912151229121512161116121512161116112a112a111611160002d3501229121611291216122912151215121611161215121611291229121611160002d35112281216122912151229121512161116121512151216112a1129121611160002d351112a1116112a1116122912151215121611161215121512291229121512160002d351122911161228131512281315121611161215121512161129122a111611160002d35111291216112a1116122911161215121611161215121512291229121611160002d35112281216122912151228131512161116121512151216112a112a111611160002d3511129121611291216122911161215121611161215121512291229121611160002d351112a111612291215122912151216111612151215121611291229121611160002d350122912161129121612291116121512161116111612151229122912151216000d0500000000000000000000"
                    },
                    "volume": {
                        "up": "2600b004281228131513140002e84f1314132813141315132813141314131413151314121513281328131413150002e8501215122912151216112a11161215121512161116121512291229121512160002e8511215122912151215122912151216121413151216111612291129131412160002e74f1315122913141314132813141315131412151314131513281228131513140002e8501314132813141315122813151215131413151215121513281229131413140002e8501314132812151314132813151215121513141315131412291229121513140002e8501314132813151215122912151215131413151314131413281328131413150002e7501215132813141315132812151215131413151215121513281328131413150002e84f1315132812151215132813141314131512151314131513271328131512150002e7501314132813151215132812151314131513141215131413281328131413150002e8501215122913141314132813141315131413141315121513281328131412150002e84f1315132812151314132813141315121513141314131513281228131513140002e8501216122813151215122813161214121612161115131413291228121612140002e8501314122a11151315122813151216121512151216121512291229121512150002e7511215122912161116112a12151116121611161215121512291229121512160002e6511215122912161116122911161215121611161215121512291229121512160002e7501216122911161215122912151216111612151215121612291129121612150002e6521116112a11171115122a1115121611161216111611161129122a111710160002e7521017112912151215122912161116121512151216111612291229121512150002e7511116122a1115121512291215121612151116121611161229112a111612150002e7511215122912151216112912161116121512161116111612291229121512140002e8501314132813141314132813151215121513141315121513281229131413140002e8501314132813151215122912151314131413151314121513281328131413150002e7501215132813141315122912151215131413151215121513281328121513140002e94f1315122813151215132812151314131513141215131512281328131512150002e7501314132813151215132812151215131512151215131413281328131413150002e8501215132812151314132813141315121512151315121512291229121512150002e84f1315122912151215132812151315121512151314131512291228131512150002e8501215132812151315122813151215121513141315121513281229121513140002e8501215132812151314132813151215121513141315121512291229121512150002e8501314132813141315122912151314131413151215121513281328131413150002e7501215132813141315122912151215131413151215121513281328121513140002e94f1315122813151314122912151314131512151215131512281328131512150002e7501314132813151215122912151314131512151215131413281328131413150002e850121512291215121513281314131512151215131512151229122912151215000d050000000000000000",
                        "down": "26008800501229122912151216112912161215121512161116121512291229121512160002d2501228122a111612151229121512161116121512161116112a1129121612150002d54f12281328131512151229121513141316111710171117102a112b101710170002d350132813281314131413281315131413141314131513141328132813141314000d05"
                    }
                },

**Comment by maxvelascoknott** [comment]
Did it work prior to the upgrade? Does it work if you remove the subtype?

**Comment by Crox77** [comment]
Thanks for your reply, I had never tried adding it before and I’ve not tried removing the sub type

**Comment by maxvelascoknott** [comment]
Oh I think the problem is you close the bracket after "off", so doesn't have volume in the "data" item.

**Comment by Crox77** [comment]
> Oh I think the problem is you close the bracket after "off", so doesn't have volume in the "data" item.

Ok so how should it look please?

**Comment by Crox77** [comment]
Thanks for your help I’ve sorted it
