### ISSUE TITLE
Not discovering Broadlink RM4 Pro

### ISSUE THREAD

**Issue by mebryant** [kiwi-cam/homebridge-broadlink-rm#679]
**Version**
Node: v20.11.0 
OS: Raspberry Pi 4 :: Debian GNU/Linux Bookworm (12)
Homebridge: v1.7.0

**Description**
I've downloaded this plugin to my Homebridge image and have followed [this](https://broadlink.kiwicam.nz/#installation) site. 

Essentially I have tried to run the plugin to discover my Broadlink RM4 Pro in two suggested ways:

- After fully setting up the Broadlink Rm4 Pro in the Broadlink app and unlocking the device 
- After aborting set-up before adding the rm4 to the room and after it connects it to wifi (suggested by reddit)

**Note Worthy**

- I've tried using `hosts` as well and posts a log message like it connected but didn't add any accessories like the logs below
- I've run the plugin in both a Child Bridge and not, but most of my debugging was done as a Child Bridge.
- Using the Learn switch within HomeKit prints a log message and fails to run
`[Broadlink RM] [ERROR] Learn Code (Couldn't learn code, device not found)`

**To Reproduce**
1. Download plugin w/ homebridge
2. Apply config below
3. Set-up rm4 pro within Broadlink app
4. restart Homebridge

**Debugging**

**Config json**
```
{
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": true,
    "hideLearnButton": true,
    "hideWelcomeMessage": true,
    "_bridge": {
        "username": "0E:15:18:5D:42:E3",
        "port": 35432
    }
}
```

**Logging in Hombridge**
```
[11/01/2024, 13:49:54] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
[11/01/2024, 13:49:54] [Broadlink RM] No accessories have been added to the "Broadlink RM" platform config.
[11/01/2024, 13:49:54] Initializing platform accessory 'Learn'...
[11/01/2024, 13:49:54] Initializing platform accessory 'Scan Frequency'...
[11/01/2024, 13:49:54] Homebridge v1.7.0 (HAP v0.11.1) (Broadlink RM) is running on port 35432.
[11/01/2024, 13:49:55] [Broadlink RM] 
[11/01/2024, 13:49:55] [Broadlink RM] **************************************************************************************************************
[11/01/2024, 13:49:55] [Broadlink RM] ** Welcome to version 4.4.15 of the Homebridge Broadlink RM Plugin!
[11/01/2024, 13:49:55] [Broadlink RM] ** 
[11/01/2024, 13:49:55] [Broadlink RM] ** Find out what's in the latest release here: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/CHANGELOG.md
[11/01/2024, 13:49:55] [Broadlink RM] ** 
[11/01/2024, 13:49:55] [Broadlink RM] ** If you like this plugin then please star it on GitHub or better yet
[11/01/2024, 13:49:55] [Broadlink RM] ** buy me a drink using Paypal https://paypal.me/kiwicamRM.
[11/01/2024, 13:49:55] [Broadlink RM] **
[11/01/2024, 13:49:55] [Broadlink RM] ** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
[11/01/2024, 13:49:55] [Broadlink RM] **
[11/01/2024, 13:49:55] [Broadlink RM] **************************************************************************************************************
[11/01/2024, 13:49:55] [Broadlink RM] 
```

I've cloned the repo but haven't had a chance to look into anything so any suggestions in that realm could help as well.
Thanks in advanced!

**Comment by AllanPinheiroDeLima** [comment]
Having this issue too. Have you solved ?

**Comment by arthur-moebios** [comment]
Hi guys, you probably need to update to this version of firmware

http://124.71.130.238/RMBL4-62092-8720-BL-FC-3389.upd.bin

Go to device in Broadlink app, three dots menu, firmware update, manual update

Paste the link above, and wait. V62093 broke the plug-in.

**Comment by arthur-moebios** [comment]
> Having this issue too. Have you solved ? 

If your version is not v62092 give it a try. Worked for me

**Comment by arthur-moebios** [comment]
After downgrade/upgrade to v62092, restart child bridge or homebridge instance. After that it must be found.

**Comment by AllanPinheiroDeLima** [comment]
So, I just tried this. I have updated the firmware to v62092. I get it to show up in logs now, but I do not know how to map the commands from my A/C remote to the homebridge, which leads to a message "No accessories added to Broadlink" ( or something like that ). If there is a way to add my devices, how should I do it ? I have read the docs but there it says that my devices should be detected automatically ( I already unlocked it on the Broadlink app )

Thanks for the help!

**Comment by arthur-moebios** [comment]
Oh, I think you miss understood the concept, the devices you add in homebridge are manually added. See above my config to understand better:

     {
            "platform": "BroadlinkRM",
            "name": "BroadlinkRM4Pro",
            "hideScanFrequencyButton": true,
            "hideLearnButton": true,
            "hideWelcomeMessage": true,

Here you add your accessories, your devices, not in Broadlink app this "learn-code" accessory is a switch will appear in home app on your iPhone, when you turn it on the rm4 pro will stand in learner mode and you will press a button to receive the hex code representation of IR code in logs on homebridge. What brand is your AC?

     {
            "accessories": [
                {
                    "name": "RF Scan",
                    "type": "learn-code",
                    "scanFrequency": false 


This accessory below is a temperature sensor, the data is given by my rm4 pro with a power cord with temp and humidity sensor

     {
                    "name": "Termometro Suite",
                    "type": "temperatureSensor",
                    "host": "xx:xx:xx:xx:xx"
                },

In the doc reference here:

https://broadlink.kiwicam.nz

You'll find a list of possible accessories and a guide to all options of this plugin

**Comment by arthur-moebios** [comment]
> So, I just tried this. I have updated the firmware to v62092. I get it to show up in logs now, but I do not know how to map the commands from my A/C remote to the homebridge, which leads to a message "No accessories added to Broadlink" ( or something like that ). If there is a way to add my devices, how should I do it ? I have read the docs but there it says that my devices should be detected automatically ( I already unlocked it on the Broadlink app )
> 
> 
> 
> Thanks for the help!

And just for your information:
The devices the plug-in discover automatically are just the Broadlink boxes, in my case, I use 4 of them, and the plug-in discover all 4 in my lan

**Comment by AllanPinheiroDeLima** [comment]
Oh, that explains a lot. I totally misunderstood what was for. I thought it would recognize my added devices directly from the RM4 using its metadata, but after what you said, I came to realize that who have the codes is the app, not the blaster! 

Vacilo meu! 

Thank for your help and patience! I’ll try put this together tomorrow morning and I report back! 

Thank you!

**Comment by arthur-moebios** [comment]
> Oh, that explains a lot. I totally misunderstood what was for. I thought it would recognize my added devices directly from the RM4 using its metadata, but after what you said, I came to realize that who have the codes is the app, not the blaster! 
> 
> 
> 
> Vacilo meu! 
> 
> 
> 
> Thank for your help and patience! I’ll try put this together tomorrow morning and I report back! 
> 
> 
> 
> Thank you! 

no problem! in fact the documentation could be clearer, I noticed that you are also from Brazil, but I kept the conversation in English so that in history it can help other people. If you need anything, you can call me, I have codes ready for Philco air conditioning

Tamo junto!

**Comment by mebryant** [comment]
@arthur-moebios You're my hero. As shown in my logs below my RM4 is now being discovered and `Learn Code` functionality is restored .

 I had version `v62093` installed on my RM4 which I now assume is not a supported version for this Homebridge plugin. I also had the miss understanding that the accessories from the Broadlink app would be automatically injected into HomeKit. 

Thanks for helping out! Also apologizes for the late response I just now saw the email from GitHub updating me on this thread.

```
[Broadlink RM] [INFO] Discovered Broadlink RM4 Pro (5213) at 192.168.68.69 (e8:16:56:53:d4:1b)

---

[06/02/2024, 13:08:17] [Broadlink RM] [RESULT] Learn Code (learned hex code: 2600fa00290d290d0f28280e280f0d280d290e280e280e280d2929e7280e280e0d29280e290e0d290e280e280d290d290d282900010a280e280e0d29280e290e0d290d290e280d290d280d2929e7280e290e0d28290e280e0d290e280e280d290d290d292800010a280e290e0c29290e280e0d290e270e290d290d290d2928e7280e280f0d29280e290d0d290d290d290d290e270e292800010a280f270f0d29280e280e0d290d290d290e280e270e2928e7280e290d0e29280f270f0d290d290d280d290d290d292800010a280e280e0e29270f280e0d290d290d290d290c290d2928e8280e280e0d29280e280e0e280e290d280d290d290d2928000d05000000000000000000000000)
[06/02/2024, 13:08:17] [Broadlink RM] [INFO] Learn Code (complete)
[06/02/2024, 13:08:17] [Broadlink RM] [INFO] Learn Code (stopped)
```

**Comment by mebryant** [comment]
For future viewing, The solution was to was to manually update/downgrade the firmware of the RM4 through the Broadlink app: (`v62092`)

`http://124.71.130.238/RMBL4-62092-8720-BL-FC-3389.upd.bin`

Credit: @arthur-moebios

**Comment by arthur-moebios** [comment]
> @arthur-moebios You're my hero. As shown in my logs below my RM4 is now being discovered and `Learn Code` functionality is restored .
> 
> I had version `v62093` installed on my RM4 which I now assume is not a supported version for this Homebridge plugin. I also had the miss understanding that the accessories from the Broadlink app would be automatically injected into HomeKit.
> 
> Thanks for helping out! Also apologizes for the late response I just now saw the email from GitHub updating me on this thread.
> 
> ```
> [Broadlink RM] [INFO] Discovered Broadlink RM4 Pro (5213) at 192.168.68.69 (e8:16:56:53:d4:1b)
> 
> ---
> 
> [06/02/2024, 13:08:17] [Broadlink RM] [RESULT] Learn Code (learned hex code: 2600fa00290d290d0f28280e280f0d280d290e280e280e280d2929e7280e280e0d29280e290e0d290e280e280d290d290d282900010a280e280e0d29280e290e0d290d290e280d290d280d2929e7280e290e0d28290e280e0d290e280e280d290d290d292800010a280e290e0c29290e280e0d290e270e290d290d290d2928e7280e280f0d29280e290d0d290d290d290d290e270e292800010a280f270f0d29280e280e0d290d290d290e280e270e2928e7280e290d0e29280f270f0d290d290d280d290d290d292800010a280e280e0e29270f280e0d290d290d290d290c290d2928e8280e280e0d29280e280e0e280e290d280d290d290d2928000d05000000000000000000000000)
> [06/02/2024, 13:08:17] [Broadlink RM] [INFO] Learn Code (complete)
> [06/02/2024, 13:08:17] [Broadlink RM] [INFO] Learn Code (stopped)
> ```

Glad to help my friend!

**Comment by AllanPinheiroDeLima** [comment]
@arthur-moebios just reporting back. I tried ( all night, because I'm too stubborn ) and it did really work. Unfortunately I have different devices from yours. I'm configuring the Samsung Remote and an LG A/C. The AC is already working ( and it's beautiful ). I did a bit of programming to get some of my other devices working and I jerry rigged an addressable led strip to the setup and even that worked correctly!

I still have a kind of signal breakup when I try to use the learn feature and it couldn't be interference because I have no other blaster in range. I think I'll figure this one out later

Again, thank you for clarifying how it was supposed to work :)

**Comment by arthur-moebios** [comment]
> @arthur-moebios just reporting back. I tried ( all night, because I'm too stubborn ) and it did really work. Unfortunately I have different devices from yours. I'm configuring the Samsung Remote and an LG A/C. The AC is already working ( and it's beautiful ). I did a bit of programming to get some of my other devices working and I jerry rigged an addressable led strip to the setup and even that worked correctly!
> 
> 
> 
> I still have a kind of signal breakup when I try to use the learn feature and it couldn't be interference because I have no other blaster in range. I think I'll figure this one out later
> 
> 
> 
> Again, thank you for clarifying how it was supposed to work :) 

Glad to know!!!! It's magical to get all devices working, I feel as a wizard hahaha

The learn mode of Broadlink is a little annoying, one tip I use is to use a notebook to get the codes generated in the log, and use the phone to activate the learn switch, so you can check if it really captured it. 

Good luck!

**Comment by jeremydvoss** [comment]
@arthur-moebios Where did you find this link? I think this is my issue, but I'm not installing a mysterious unnamed os on a device

**Comment by arthur-moebios** [comment]
> Where did you find this link? I think this is my issue, but I'm not installing a mysterious unnamed os on a device

Hello! I didn't get what you mean. The link of the downgrade/update file I've found on a thread in a forum about Broadlink devices. Have used that one with my devices and they are well

**Comment by jeremydvoss** [comment]
I see these links a lot, but downloading anything from unverified IP addresses is pretty dangerous, especially for a device exposes on your home network. Trying to figure out where this came from. I've emailed broadlink support to figure out if this is legit and why it's not shown on any of their webpages.

**Comment by arthur-moebios** [comment]
> I see these links a lot, but downloading anything from unverified IP addresses is pretty dangerous, especially for a device exposes on your home network. Trying to figure out where this came. I've emailed broadlink support to figure out if this is legit and why it's not shown on any of their webpages.

Oh! Got it. See if they send you the v62092. It's all you need to get this working. Is the file hosted in the sus link. 🫡

**Comment by jeremydvoss** [comment]
Confirmed with broadlink support that this unverified ip link is actually right. What a weird company...

**Comment by arthur-moebios** [comment]
> Confirmed with broadlink support that this unverified ip link is actually right. What a weird company...

🥵😁
