### ISSUE TITLE
TV type accessories not displaying in Home app

### ISSUE THREAD

**Issue by arhan8642** [kiwi-cam/homebridge-broadlink-rm#68]
Hi! For some reason, all TV type accessories do not display in my home app. They display in the home bridge accessories display, though. I've tried resetting home bridge, re-pairing home bridge, removing and re-adding the bridge, etc. If I change it to a switch style accessory it works but TV does not. This happens across both my iOS 14 and iOS 13 devices. What can I do? Thank you!

**Comment by Faisalthe01** [comment]
You need to add them manually go to your Apple Home app then touch + on top right Then Add Accessory then I dont have a code or cannot scan, there you will see your TV accessories

**Comment by kiwi-cam** [comment]
Hi @arhan8642, what you're describing sounds exactly like what @Faisalthe01 has explained above. Please let us know if you're still having issues.

**Comment by CVHvisuals** [comment]
My TV accessories disappeared also within the last couple of updates. I made them switches and they reappeared. 

Edit: I made them tv accessories again and had to re-add them in the Home app as Faisal stated above.

**Comment by arhan8642** [comment]
Hi all, thanks for the advice. This is exactly what I had done, but I was only able to “add” one accessory from the menu. The other TV accessory didn’t show up. I was able to fix this today by adding the “remote” part of the data in the config. Turns out it doesn’t show up without it.

**Comment by CerberusVelvet** [comment]
I was having the same issue. TV not showing up. Ran through 'add accessory', selected don't have code or cannot scan, selected the TV accessory that was shown. But then I am asked for an 8 digit code? Is this something I should have set up somewhere in the config?
