### ISSUE TITLE
Broadlink RM app and Homebridge Not able to Share devices?

### ISSUE THREAD

**Issue by fratinize** [kiwi-cam/homebridge-broadlink-rm#70]
After Installing This Plug In, I was Unable to Find my Device (RM mini 3). Read through the Readme and Reset the Device and Quit before adding to a Room. Homebridge then Discovered my Mini. I had issues trying to Learn the Codes. In the Meantime I decided I wanted to be able to Use the Broadlink App, and it would come in handy not to Have to Rely 100% on home kit to control this device.
After Restarting Homebridge, It no longer discovered the Device. Is this on Purpose? or Can it be accomidated?
I do have a Hosts section with proper Mac and ip.
Thank You for any assistance.

**Comment by kiwi-cam** [comment]
Unfortunately that seems to be the way with the new apps/firmware. Once you register the device in the cloud it's no longer discoverable locally. The only way I know to change between the two is to reset and reconfigure your device.

**Comment by fratinize** [comment]
Ty
