### ISSUE TITLE
HomeKit AC Hardware Display Units incorrect

### ISSUE THREAD

**Issue by JasonGoldenDDT** [kiwi-cam/homebridge-broadlink-rm#705]
**Describe the bug**

Does not reflect configured display units.  

![Screenshot 2024-06-03 at 8 52 00 AM](https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/107149125/1a4b367a-3468-4e3d-8168-b13d305cded5)

`            "name": "Air Con RM",
            "type": "air-conditioner",
            "host": "xx:xx:xx:xx:xx:xx",
            **"temperatureDisplayUnits": "F",**
            "defaultCoolTemperature": 15.5556,
            "temperatureUpdateFrequency": 900,
            "minTemperature": 15.5556,
            "maxTemperature": 30,
            "replaceAutoMode": "cool",
            "minimumAutoOnOffDuration": 100,
            "turnOnWhenOff": true,
            "preventResendHex": true,
            "coolOnly": true,
            "noHumidity": false,
            "noHistory": true,
            "monitored_conditions": [
                "temperature",
                "humidity"
            ],`

**To Reproduce**
1. Go to 'AC Device Settings in HomeKit, see Hardware display Units shown incorrectly as celsius.  Not matching config.json in Homebridge.'

**Expected behavior**
Would expect the "temperatureDisplayUnits" to reflect accurately in HomeKit

**Screenshots**
![Screenshot 2024-06-03 at 8 49 51 AM](https://github.com/kiwi-cam/homebridge-broadlink-rm/assets/107149125/c4354da0-bd7e-49fa-9822-c36fc8b4a20c)

**Desktop (please complete the following information):**
 - OS: Sonoma 14.5
 - Browser: Safari
 - Version latest

**Smartphone (please complete the following information):**
 - Device: iPhone Mini 12
 - OS: Latest Public
 - Browser Safari
 - Version latest

**Additional context**
Latest release of Homebridge, Node, and Plugin installed.

**Comment by kard8** [comment]
Have you tried deleting this line

**"temperatureDisplayUnits": "F",** 

And changing the temperature setting in the Home App?

**Comment by JasonGoldenDDT** [comment]
I suspect I tried both, but to be sure I just removed the reference and restarted the plugin.  It still shows celsius.  Interestingly it doesn't affect the actual value displayed.

<img width="581" alt="Screenshot 2024-07-25 at 10 47 22 AM" src="https://github.com/user-attachments/assets/28ec79a8-6022-4a0f-98de-f52942c59983">

<img width="187" alt="Screenshot 2024-07-25 at 10 48 17 AM" src="https://github.com/user-attachments/assets/e9c1745c-902c-4a82-b150-bceb08d29082">

And changing it in HomeKit doesn't stick.

**Comment by banboobee** [comment]
How about "**units**" instead of "temperatureDisplayUnits" ?

**Comment by kard8** [comment]
Use it bare bones without any arguments and try using  heater-cooler accessory type  like

 ```
{
"name": "Air Con RM", 
"type": "heater-cooler", 
"host": "xx:xx:xx:xx:xx:xx", 
 "minTemperature": 15, 
"maxTemperature": 30, 
"coolOnly": true, 
"data": {
              "cool": { 
                                "HEX CODE"
                           }
}

```
If it Works then add on the extra options one by one.
Further Documentation is here : https://broadlink.kiwicam.nz/#heatercooler

**Comment by JasonGoldenDDT** [comment]
Getting error with this config.  LMK if I missed something. 

`        {
            "name": "Air Con RM",
            "type": "heater-cooler",
            "host": "10.0.145.12",
            "minTemperature": 15.5556,
            "maxTemperature": 30,
            "coolOnly": true,
            "data": {
                "off": "26004800000121931336131213121212131213111312133613121336133613121312133613361312133613121212131213121311131213361312133613361337123713361336131213000d050000000000000000000000000000",
                "cool": "26004800000121931336131213121212131213111312133613121336133613121312133613361312133613121212131213121311131213361312133613361337123713361336131213000d050000000000000000000000000000"
            }
        },`
<img width="1344" alt="Screenshot 2024-08-15 at 8 47 09 AM" src="https://github.com/user-attachments/assets/edc533f0-5137-4e14-b3b3-0e1261e4bb02">

**Comment by JasonGoldenDDT** [comment]
Quick update.  Since removing the device and adding it back... the issue resolved. 

EDIT> It keeps reverting back... suspect it happens between Home apps that view the device.

**Comment by JasonGoldenDDT** [comment]
I'm experiencing issues with this plug in recently after months of stability.  Not sure why. 

For some reason once the Broadlink RM 4 drops below 73 degrees it stops updating Homekit... or at least appears that way.  

![Screenshot 2024-08-18 at 7 32 20 AM](https://github.com/user-attachments/assets/66f8f8a8-b44f-4687-a81e-3ff141152f87)

I have automation that triggers the AC to turn off once temp drops below 73, this worked well for months and now it doesn't... not sure why.

when I observe the accessory via Homebridge I see the temp drop below 73, but it doesn't reflect in HomeKit.   But when the temp starts to rise the it does reflect in HomeKit quickly. 

I'm also still seeing the Display Units reflected in C in stead of F and I'm wondering if it matters if its "f" or "F."  IN Homebridge in the accessory details it shows as "0" for both the Broadlink Temp sensor and the AC accessory for the Broadlink IR. 

<img width="719" alt="Screenshot 2024-08-18 at 7 27 57 AM" src="https://github.com/user-attachments/assets/9880d1a3-8ac3-40f7-9080-b959682bcb79">

`{
                    "name": "Broadlink Temperature",
                    "type": "temperatureSensor",
                    "disabled": false,
                    "host": "10.0.145.12",
                    "temperatureUnits": "F",
                    "humidityUpdateFrequency": 300,
                    "logLevel": "warning"
                },
                {
                    "name": "Air Con RM",
                    "type": "air-conditioner",
                    "disabled": false,
                    "host": "10.0.145.12",
                    "defaultCoolTemperature": 15.5556,
                    "minTemperature": 15.5556,
                    "maxTemperature": 30,
                    "temperatureUnits": "F",
                    "replaceAutoMode": "cool",
                    "minimumAutoOnOffDuration": 100,
                    "turnOnWhenOff": true,
                    "preventResendHex": true,
                    "coolOnly": true,
                    "noHumidity": false,
                    "noHistory": false,
                    "logLevel": "warning",
                    "monitored_conditions": [
                        "temperature",
                        "humidity"
                    ],
                    "data": {
                        "off": "26004800000121931336131213121212131213111312133613121336133613121312133613361312133613121212131213121311131213361312133613361337123713361336131213000d050000000000000000000000000000",
                        "on": [
                            {
                                "data": "26004800000121931336131213121212131213111312133613121336133613121312133613361312133613121212131213121311131213361312133613361337123713361336131213000d050000000000000000000000000000",
                                "pause": 0.5
                            },
                            {
                                "data": "2600480000011f951237121312121114111411131114113812131138123810141213123711391113113811391113113911381114101411391113111411381114111410391138121311000d050000000000000000000000000000"
                            }
                        ],
                        "cool15.5556": {
                            "pseudo-mode": "cool",
                            "data": "260058000001209411371313111411141014121311141138121211391237111411131238113812131014113911131138111411141114113811381213113811141039113812371114110005700001244d12000c4a0001264b11000d050000000000000000000000000000",
                            "sendCount": 2,
                            "interval": 0.5
                        }
                    }
                },`

**Comment by JasonGoldenDDT** [comment]
Continuing to troubleshoot this odd behavior.  It seems like the setting reverts when the Home app is restarted, either on iOS or macOS.  

The change in the home app is reflected on the Accessory detail in Homebridge... and I can see the setting revert back to "0" when the home app restarts. 

using "1" or "f" in the config file for temperatureUnits doesn't do anything.

**Comment by JasonGoldenDDT** [comment]
> How about "**units**" instead of "temperatureDisplayUnits" ?

I've tried all of the variations mentioned in the threads I've found.  No resolution.  I'm also noticing this issue on iOS public beta 5.
