### ISSUE TITLE
2 Broadlink Rm 4 when one is working is the other locks

### ISSUE THREAD

**Issue by mikellas1983** [kiwi-cam/homebridge-broadlink-rm#713]
**Describe the bug**
Bought 2 new Rm 4 minis.Both installed via app and both unlocked via app.For some reason whenever i restart homebridge only one is unlocked although i toggled both off from the app

Anyway i dont even know if anyone sees the issues section anymore but did anyone have a similar experience?

**Comment by fratinize** [comment]
Reboot your router believe it or not every year of so all of a sudden 1 or 2 of my remotes (2 mini beans and 1 rf pro) show on my network but not seen by Homebridge Restarted these, they work via the app drive me crazyRebooted my udm pro and walah there they are and the volume control is back Go figure Sent from my iPhoneOn Jun 29, 2024, at 4:45 PM, mikellas1983 ***@***.***> wrote:﻿
Describe the bug
Bought 2 new Rm 4 minis.Both installed via app and both unlocked via app.For some reason whenever i restart homebridge only one is unlocked although i toggled both off from the app
Anyway i dont even know if anyone sees the issues section anymore but did anyone have a similar experience?

**Comment by mikellas1983** [comment]
Hi and thanks for replying! i already did that , the only thing left for me to restart is my actual switch but ill give that a try as well.The weirdest part is that homebridge recognizes the device upon restart but once i try use it it says error check if device is locked!!!

**Comment by mikellas1983** [comment]
Unfortunately it didnt work!I restarted everything even the homebridge instance twice!!
I have 3 Broadlink Broadlink RM3 Mini B (5f36) and 2 RM4 Mini (5216) .Every time i restart homebridge one the two RM4  says that it is locked whereas the other works as expected.Funny thing is,  one of them is  active in a random order.I have set static ips for all 5 of them i have the isrm4 to true for the two RM4 restarted homebridge,router,switch and still have this issue...
So sad....I even tried the beta version of the plugin

**Comment by fratinize** [comment]
I should have mentioned that was my last effort to resolve the missing remotesHomebridge stopped seeing them but my network showed them there and as I mentioned I was able to control via the native appBut I had also removed all regencies from Homebridge removed from HomeKit. Booted every thing and was still not seeing them when the router reboot resolved Good luckSent from my iPhoneOn Jun 30, 2024, at 9:41 AM, mikellas1983 ***@***.***> wrote:﻿
Unfortunately it didnt work!I restarted everything even the homebridge instance twice!!
I have 3 Broadlink Broadlink RM3 Mini B (5f36) and 2 RM4 Mini (5216) .Every time i restart homebridge one the two RM4  says that it is locked whereas the other works as expected.Funny thing is,  one of them is  active in a random order.I have set static ips for all 5 of them i have the isrm4 to true for the two RM4 restarted homebridge,router,switch and still have this issue...
So sad....

**Comment by banboobee** [comment]
> did anyone have a similar experience?

Possibly, mac addresses of your two RM4 become identical internally. See kiwi-cam/broadlinkjs-rm#22 in details.

**Comment by mikellas1983** [comment]
There was beta update today, i managed to update but didnt resolve the issue.First restart it actually missed 2 my RM4 and had to to do a second HB restart to find at least one that was missing.Let me know if i can assist in any way as i have the setup here anyway and i am available at anytime

**Comment by kiwi-cam** [comment]
@mikellas1983 Sorry about that, I've found the issue with that release. The new beta today should include the suggested changes.

**Comment by mikellas1983** [comment]
@kiwi-cam Yo rock mate!!! I just updated everything seems  to be working as expected.All 4 devices are discoverable and working
I will test it out throughout the day and let you know but for now all is good!!

**Comment by kiwi-cam** [comment]
That's great to hear. Credit goes to @octavifs for finding the fix on this one.

**Comment by mikellas1983** [comment]
Updated to Version 4.4.17 error started again showing that devices are locked.Rolled back to 4.4.16 all is good! @kiwi-cam
