### ISSUE TITLE
[Temperature Display Units] Config value ignored

### ISSUE THREAD

**Issue by JasonGoldenDDT** [kiwi-cam/homebridge-broadlink-rm#728]
**Describe the bug**
When config.json value set to 'f,' accessory value remains 0 or Celsius.

**To Reproduce**
1. Create "air-conditioner" type accessory in config.json.  Include "temperatureDisplayUnits": "f" in the accessory configuration profile. 
2. Click on the Accessory Details in HomeBridge, find "0" as value for Temperature Display Value.  Click on Accessory Details in HomeKit, find "Degrees Celsius" for "Hardware Display".  Accessory displays Fahrenheit in UI. 
3. Attempt to change value in Homekit, find it will reflect as 1 in Homebridge Accessory Detail. Will revert back to C or 0 after a few seconds or after Home App / Related apps restart.

**Expected behavior**
Expect Accessory Hardware Display value to align with displayed accessory temperature value. F =  F.  Currently F = C.

**Screenshots**
Expected - "Hardware Display" value aligns with accessory displayed temperature reading.
<img width="1121" alt="Screenshot 2024-08-18 at 11 54 21 AM" src="https://github.com/user-attachments/assets/7a2a5a43-749e-44de-a19a-426f725bb9b8">

Actual - "Hardware Display" reverts to "Celsius" after app relaunch. 
<img width="1072" alt="Screenshot 2024-08-18 at 11 55 52 AM" src="https://github.com/user-attachments/assets/a497c7bf-c122-4e17-8ea1-eac92f7301dd">

**Desktop (please complete the following information):**
 - OS: Latest Public OS

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: Latest Public OS

**Additional context**
I am troubleshooting issues with Homekit Automation failures with temperature triggers.  I have Home Shortcuts configured that have recently stopped working.  Through my efforts to track down the cause I found this discrepancy.  I suspect recent iOS 17.6 changes have affected how hubs are assigned and how their data is synced resulting in instability in HomeKit.   Example: an automation on one hub may not be accurate on a second or third. and if wifi is unstable, like it can be in a crowded urban environment, this inconsistency in data can lead to issues. 

I do not know if this displayed value affects data sent to HomeKit, **I'm finding temperatures below 73 F are not showing in HomeKit anymore, breaking automation triggers.**

**Comment by banboobee** [comment]
https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/705#issuecomment-2253538654

**Comment by JasonGoldenDDT** [comment]
> [#705 (comment)](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/705#issuecomment-2253538654)

I've tired all of the config references with no resolution.  I installed iOS 18 public beta to see if that resolves it.  It doesn't.

**Comment by banboobee** [comment]
In my experience, 'HARDWARE DISPLAY Unit' shows 'Degrees Fahrenheit' by adding following line in config.json.

`"units": "F"`

**Comment by JasonGoldenDDT** [comment]
Nice! - It would be awesome if someone could push that information back to the plug-in documentation.  I searched it multiple times and missed it. 

I've added "units" to the AC accessory and it appears to be sticking in the "F" units position. 

Thank you for that.
