### ISSUE TITLE
Blinds scenario problem

### ISSUE THREAD

**Issue by burakcankose** [kiwi-cam/homebridge-broadlink-rm#73]
Hello everyone, I have four blinds. I use broadlink rm4pro device and manage with rf. For example, in a scenario where all the shutters are closed, sometimes two and sometimes three shutters close. What can I do to fix this problem?

**Comment by kiwi-cam** [comment]
This sounds a lot like #36. @mitch7391 did you make any progress?

The only thought I have is, can you setup each blind with a different delay so the commands are staggered?

**Comment by burakcankose** [comment]
I have read the topic you mentioned now, we will benefit if the friend returns, but if you have a code you say or suggest, I am ready to try it. Thank you.

**Comment by kiwi-cam** [comment]
Can you share your config.json?

**Comment by burakcankose** [comment]
[config.json.txt](https://github.com/kiwi-cam/homebridge-broadlink-rm/files/5303314/config.json.txt)

Thank you !

**Comment by mitch7391** [comment]
I have been a on a little hiatus as life has been a bit busy for anything more than just using my HomeKit devices; so I have made no progress. In my issue, I had meant that I had an issue with delays, all of the blinds do not start or stop at the same tome; they start or stop one at a time when executed as a scene.

But I have actually had this issue too without realising it. Everything now and then in my morning automation for 5 of my blinds to open, one in particular would occasionally not get the command and would still be closed. At the time I was going through the entire last beta of homebridge and knew that a new beta roll out sometimes meant automations in the next 12-24hrs would play up; I had put it down to that at the time...

**Comment by burakcankose** [comment]
@kiwi-cam ?

**Comment by burakcankose** [comment]
Does anyone have an idea?
