### ISSUE TITLE
temperature from rm mini 4 c (62be)

### ISSUE THREAD

**Issue by hassman12** [kiwi-cam/homebridge-broadlink-rm#76]
hi!
first of all - thanks for the great tool!
just updated the version and i tried to take advantage of the internal temperature of the broadlink. i have 2 broadlinks for 2 different A\C so:
i commented out the "pseudoDeviceTemperature"
and then the home app shows a question mark instead the temperature and the log shows:
Oct 01 19:01:31 raspberrypi homebridge[9505]: [10/1/2020, 7:01:31 PM] [Broadlink RM] Air Conditioner2 addTemperatureCallbackToQueue (requested temperature from device, waiting)
Oct 01 19:01:41 raspberrypi homebridge[9505]: [10/1/2020, 7:01:41 PM] [Broadlink RM] Air Conditioner addTemperatureCallbackToQueue (requested temperature from device, waiting)
Oct 01 19:01:41 raspberrypi homebridge[9505]: [10/1/2020, 7:01:41 PM] [Broadlink RM] Air Conditioner2 addTemperatureCallbackToQueue (requested temperature from device, waiting)
Oct 01 19:01:51 raspberrypi homebridge[9505]: [10/1/2020, 7:01:51 PM] [Broadlink RM] Air Conditioner addTemperatureCallbackToQueue (requested temperature from device, waiting)
Oct 01 19:01:51 raspberrypi homebridge[9505]: [10/1/2020, 7:01:51 PM] [Broadlink RM] Air Conditioner2 addTemperatureCallbackToQueue (requested temperature from device, waiting)
Oct 01 19:02:01 raspberrypi homebridge[9505]: [10/1/2020, 7:02:01 PM] [Broadlink RM] Air Conditioner addTemperatureCallbackToQueue (requested temperature from device, waiting)
Oct 01 19:02:01 raspberrypi homebridge[9505]: [10/1/2020, 7:02:01 PM] [Broadlink RM] Air Conditioner2 addTemperatureCallbackToQueue (requested temperature from device, waiting)
Oct 01 19:02:11 raspberrypi homebridge[9505]: [10/1/2020, 7:02:11 PM] [Broadlink RM] Air Conditioner addTemperatureCallbackToQueue (requested temperature from device, waiting)
Oct 01 19:02:11 raspberrypi homebridge[9505]: [10/1/2020, 7:02:11 PM] [Broadlink RM] Air Conditioner2 addTemperatureCallbackToQueue (requested temperature from device, waiting)

then i tried adding a temperaturesensor, and that crashed homebridge and the log shows:
Oct 01 19:09:33 raspberrypi homebridge[11417]: [10/1/2020, 7:09:33 PM] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
Oct 01 19:09:33 raspberrypi homebridge[11417]: [10/1/2020, 7:09:33 PM] Error: homebridge-broadlink-rm doesn't support accessories of type "temperatureSensor".
Oct 01 19:09:33 raspberrypi homebridge[11417]: at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/platform.js:66:46)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at Array.forEach (<anonymous>:null:null)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at BroadlinkRMPlatform.addAccessories (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/platform.js:63:24)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/platform.js:28:10)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:403:20)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:341:16)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at Module._compile (internal/modules/cjs/loader.js:701:30)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at Module.load (internal/modules/cjs/loader.js:600:32)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at startup (internal/bootstrap/node.js:283:19)
Oct 01 19:09:33 raspberrypi homebridge[11417]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Oct 01 19:09:33 raspberrypi homebridge[11417]: [10/1/2020, 7:09:33 PM] Got SIGTERM, shutting down Homebridge...

what am i doing wrong?
and another question - can i add a "host" section to the temperaturesensor accessory? because i have 2 broadlinks so how does the software "knows" from which one to take the temperature?

thanks!

**Comment by kiwi-cam** [comment]
This looks like two issues.  First, are you sure your Broadlink device has (and supports) a temperature sensor? What model of devices do you have?

Second issue looks like you're not running a version with the new accessories.  Try running `npm -g install homebridge-broadlink-rm-pro@latest`

Finally, your question. Yes you should be able to add a "host" to the sensor. I haven't been able to test this so let me know how that goes.

**Comment by kiwi-cam** [comment]
> What model of devices do you have?

Just looked at the title 🤦‍♂️
The RM Mini 4 C isn't compatible with the in cable sensors. I got caught out on that one too.

> Note: It only supports BroadLink RM4 mini and RM4 Pro universal remote, it doesn’t support BroadLink RM mini3, RM Pro+ or BestCon RM4C mini. 
From: https://www.amazon.com/Broadlink-Accessory-Temperature-Humidity-Monitor/dp/B081F3C4T4/

**Comment by hassman12** [comment]
thanks for the response!

you answered everything!

thanks again!
