### ISSUE TITLE
Accessory Request- Heater

### ISSUE THREAD

**Issue by Faisalthe01** [kiwi-cam/homebridge-broadlink-rm#8]
Is it possible to add a Heater accessory that have controls for rise temperature, low temperature , heat, off, on and child lock. Just only Heater without Cool or Auto like this Rio Heater? 

https://youtu.be/ZVeMkpWCEcc

**Comment by Faisalthe01** [comment]
This plugin for dyson fans have Heater only accessory too, maybe it could help.

https://github.com/joe-ng/homebridge-dyson-link

**Comment by Faisalthe01** [comment]
or an option to disable Auto/Cool Mode in AirCon accessory would work too. @kiwi-cam would you be able to help please?

**Comment by Faisalthe01** [comment]
i have created my own fork with Heat only mode. anyone interested can use it. Cheers

**Comment by kiwi-cam** [comment]
Nice one @Faisalthe01. Can we create a Pull Request and merge the changes?

**Comment by Faisalthe01** [comment]
> Nice one @Faisalthe01. Can we create a Pull Request and merge the changes?

Hey mate @kiwi-cam , I’m not 100% sure how to do merge with Pull Requests but i will try. Also, HomeKit does allow minimum temperature to be more than 10 now so i have also removed the code that was not allowing the temperature to be more than 10 in my fork. Cheers
