### ISSUE TITLE
Aircon current temperature validation should be removed in onTemperature method

### ISSUE THREAD

**Issue by CyberMrProper** [kiwi-cam/homebridge-broadlink-rm#80]
When I set my aircon configuration with min and max values:

"minTemperature": 18,
"maxTemperature": 30,

I get some weird behaviour, those restrictions apply also to the "sensor temperature" and for me that does not make sense. I was expecting 18-30 min and max values to be the operation values my heater/cooler supports.

Eg. min temperature operation value I can set for my heat pump is 18 and room temperature is 15, then I get the following warning:
[Broadlink RM] [INFO] Reported temperature (15.11) is too low, setting to minTemperature (18).

My suggestion would be to remove those checks in the "onTemperature" method:

if (temperature > config.maxTemperature) {
      log(`\x1b[36m[INFO]\x1b[0m Reported temperature (${temperature}) is too high, setting to \x1b[33mmaxTemperature\x1b[0m (${maxTemperature}).`)
      temperature = config.maxTemperature
}

if (temperature < config.minTemperature) {
      log(`\x1b[36m[INFO]\x1b[0m Reported temperature (${temperature}) is too low, setting to \x1b[33mminTemperature\x1b[0m (${minTemperature}).`)
      temperature = config.minTemperature
}

**Comment by Faisalthe01** [comment]
Have you tried to remove them and test to see what happens?

**Comment by CyberMrProper** [comment]
Yes, I have removed the following lines and seems to be working as expected:

- From line: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/accessories/aircon.js#L394
- To line: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/accessories/aircon.js#L407

And also deleted 2 lines from the CurrentTemperature property definition:
- https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/accessories/aircon.js#L769
- https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/accessories/aircon.js#L770

Hope that helps

**Comment by Faisalthe01** [comment]
it worked. thank you.

**Comment by CyberMrProper** [comment]
@kiwi-cam when you have time, would you mind applying the change?

**Comment by kiwi-cam** [comment]
Thanks. I copied this logic from somewhere.... now you point it out, it doesn't make sense.  I'll get this sorted this week.

**Comment by kiwi-cam** [comment]
The latest Beta has this fixed. Let me know if you have any issues.

**Comment by CyberMrProper** [comment]
Ifs in lines 394 and 399 need to be removed too. Right @kiwi-cam ?

**Comment by kiwi-cam** [comment]
I think you're right. Missed those ones sorry.

New beta shortly. Thanks!

**Comment by CyberMrProper** [comment]
This is working perfectly in beta version. Thanks!
