### ISSUE TITLE
Air purifier 

### ISSUE THREAD

**Issue by roberkane212** [kiwi-cam/homebridge-broadlink-rm#81]
Why does air purifier come up as fan? In previous plug-in it was a air purifier

**Comment by Faisalthe01** [comment]
I think Cameron forked it from original plugin not from his old fork AlexanderBabel, that's why.

https://github.com/AlexanderBabel/homebridge-broadlink-rm/blob/master/accessories/air-purifier.js

**Comment by roberkane212** [comment]
@Faisalthe01 ahhh ok, hope this can be fixed soon. Makes me think I have fans on in the top view in homekit

**Comment by roberkane212** [comment]
@Faisalthe01 Can you help with this as you did in the original?

**Comment by Faisalthe01** [comment]
You can download the above file and replace it with your current air-purifier.js file.

**Comment by roberkane212** [comment]
@Faisalthe01 how do I download the file? And once I download how do I add it to the plug-in?

**Comment by roberkane212** [comment]
@Faisalthe01 im using config ui x

**Comment by Faisalthe01** [comment]
What OS are you using to run Homebridge? Can you see your file structure where Homebridge is installed?

**Comment by roberkane212** [comment]
No I cannot, only on the instance I have running straight on my rpi, every other instance is ruining through hb service through config ui x plug-in

**Comment by Faisalthe01** [comment]
Sorry I’m not familiar with raspberry pi setup. Can you google and see if how you find the file structure?

**Comment by roberkane212** [comment]
@Faisalthe01 thats ok I’ll just go back to the original plug-in. Thanks for your help

**Comment by kiwi-cam** [comment]
Nice catch. Looks like an easy fix.

I'll take a look this week.

**Comment by roberkane212** [comment]
@kiwi-cam thanks

**Comment by kiwi-cam** [comment]
Hi @roberkane212. Could I get you to come back to this fork and test that this now works correctly?  I've just pushed a new Beta version which should resolve this issue.

Sorry, I don't use config-ui-x so I'm not sure how to install beta versions - hopefully it's easy. From the command line it is: `npm install -g homebridge-broadlink-rm-pro@beta`

**Comment by roberkane212** [comment]
@kiwi-cam thanks!!! Yes I will try this and let you know the outcome. I appreciate the quick response

**Comment by roberkane212** [comment]
@kiwi-cam it worked, however I am getting some errors on start up. Hasn’t cause me any issues though

**Comment by kiwi-cam** [comment]
Can you share the errors? I'd like to make sure there's nothing broken in Beta before I release it.

**Comment by roberkane212** [comment]
![C84B8990-584C-4C2E-8450-17043C17C479](https://user-images.githubusercontent.com/44589993/95030071-e6a0b280-067a-11eb-8fdd-8e592c9e609c.jpeg)
Sorry it’s not the whole error I had to screen shot it since I’m not by my computer.

**Comment by kiwi-cam** [comment]
Ah, that error. There's a lot of discussion on it here: https://github.com/lprhodes/homebridge-broadlink-rm/issues/614 but no real conclusion on a fix. Installing hap-nodejs manually seems to be a workaround.

**Comment by masterfordev** [comment]
Just a reminder, in the last beta the humidity and temperature log appears again. The rest works perfectly. 👍

![Captura de Pantalla](https://user-images.githubusercontent.com/29960705/95125939-ebb14080-0712-11eb-8d90-b6544e0d8b60.png)
