### ISSUE TITLE
TV not showing up in Home App

### ISSUE THREAD

**Issue by enishoca** [kiwi-cam/homebridge-broadlink-rm#87]
plugin version 4.3.3
I can't see this TV in Home app - not sure when it disappeared - all other devices work fine
`
                {
                    "name": "Abby TV",
                    "type": "tv",
                    "host": "192.168.0.75",
                    "enableAutoOff": false,
                    "data": {
                        "on": [
                            {
                                "data": “0…”,
                                "pause": 0.1
                            },
                            {
                                "data": "2600…0”
                            }
                        ],
                        "off": [
                            {
                                "data": “00…”,
                                "pause": 0.1
                            },
                            {
                                "data": "2600…”
                            }
                        ],
                        "remote": {
                            "select": "0000 006B …”,
                            "arrowUp": "26005800…”,
                            "arrowDown": "260058…”,
                            "arrowLeft": "26005800…”,
                            "arrowRight": "2600600…”,
                            "back": “2…”,
                            "exit": "2600600",
                            "playPause": "260088…”,
                            "info": [
                                {
                                    "data": "0000 …”,
                                    "sendCount": 10
                                }
                            ]
                        },
                        "volume": {
                            "up": "260084031314…”,
                            "down": "260052035013…”
                        },
                        "inputs": [
                            {
                                "name": "Apple TV",

                                "type": "hdmi",
                                "data": [
                                    {
                                        "data": "0000 006d …”,
                                        "pause": 0.1
                                    },
                                    {
                                        "data": "26006000…”
                                    }
                                ]
                            },
                            {
                                "name": "Fire TV",
                                "type": "hdmi",
                                "data": [
                                    {
                                        "data": "0000 006d …,
                                        "pause": 0.1
                                    },
                                    {
                                        "data": "26006000000….”
                                    }
                                ]
                            }
                        ]
                    }
                },`

**Comment by masterfordev** [comment]
Hello. Did you do this?:

![Screenshot](https://user-images.githubusercontent.com/29960705/96360243-7feab280-10d8-11eb-8b85-380cf5f70ee7.jpeg)

**Comment by enishoca** [comment]
Thank you for pointing this out - no I didn't do this.
How do I add the TV in home kit?  What do I put in for device code?

**Comment by masterfordev** [comment]
The PIN code of your homebridge.

**Comment by enishoca** [comment]
So  I need to remove Hombridge and Homebridge again? not just the TV?  Because the has already disappeared.

**Comment by masterfordev** [comment]
So just add the tv. Add accesory / i have not a code or i cant scan / selec the tv / insert your PIN of homebridge.

**Comment by enishoca** [comment]
Thanks

**Comment by enishoca** [comment]
Now the next question is how do I get Alexa to see this - earlier I was able to control it in Alexa with Homebridge-Alexa plugin but its not visible there any more

**Comment by masterfordev** [comment]
I'm sorry. I don't have alexa and consequently I don't use that plugin. :/

**Comment by androolloyd** [comment]
@enishoca I followed @masterfordev 's instructions and was able to add my TV successfully just now.

**Comment by esttorhe** [comment]
Hi, sorry for reopening an old issue. I can create a new one if that's preferred.

I'm having the same issue. I can't add the TV because when I do the steps:

>Add accesory / i have not a code or i cant scan / selec the tv / insert your PIN of homebridge

I can't get to "select tv" as nothing shows. It just keeps showing a spinner and the TV never appears in the prompt to be added.
