### ISSUE TITLE
About TemperatureTempPath

### ISSUE THREAD

**Issue by burakcankose** [kiwi-cam/homebridge-broadlink-rm#88]
Hello,

I want to transfer data from a different temperature sensor to the air conditioning panel. I saw something about TemperatureTempPath but couldn't find any documentation. Can you help me how to do it?

**Comment by masterfordev** [comment]
Check the [Documentation](https://lprhodes.github.io/slate/#air-conditioner) there is the info about how to use that. Just have to create a file (e.g. temperature.txt), and in its contents place the temperature.
