### ISSUE TITLE
State of TV on/off button is not updating

### ISSUE THREAD

**Issue by CameronVIE** [kiwi-cam/homebridge-broadlink-rm#89]
Dear dev,

thanx for your work on that plugin - really nice!

My problem is, that the state of the ON/OFF button for TV does not update.

If i or my kids switch ON the TV with remote control the button stays OFF.

if i want to switch OFF the TV with Homekit it does not work because

LOG: [Broadlink RM 3 Mini] TV setSwitchState: already false (no data sent - B)

For swithing OFF the TV i would have to tell Siri to switch if ON :) But then, the button tells me ON instead of OFF....

The same situatiion is if i switch TV on by Siri with "pressing" a channel - TV switches on on that channel but button state of TV ON/OFF is still off.

My homebridge-samsungtv-2014 v1.2.3 plugin recognizes the state change! But this plugin is very basic in functions :)

It would be very nice if the button would get an STATE UPDATE.

Thank you very much
Cam

**Comment by kiwi-cam** [comment]
The usual way around this is to use `"pingIPAddress": "192.168.1.10",`. This works well **IF** your TV is connected to the network and only responds when it's turned on.

Personally, I've got a Chromecast connected to the USB port on my TV. This means that the Chromecast is only powered on when the TV is on and I know that if I can ping the chromecast the TV is on.

**Comment by sushenmathur** [comment]
@kiwi-cam 
having issues with the Ping since the update. I can ping the TV from the homebridge instace but the the TV switch state does not change 
![image](https://user-images.githubusercontent.com/21048866/100180202-646a9700-2f23-11eb-94dd-ce327d20c8ca.png)
![image](https://user-images.githubusercontent.com/21048866/100180229-72b8b300-2f23-11eb-8fb2-8fee1b262893.png)

running homebride in docker

**Comment by kiwi-cam** [comment]
I’ve just confirmed and I’m not having any issues with this in the latest BETA. What version are you running? Are there any permission errors when you first start Homebridge?

**Comment by sushenmathur** [comment]
4.3.7. Can’t see any errors in start up

**Comment by sushenmathur** [comment]
@kiwi-cam 
I am using a allowResend option, is that an issue.
please see my config 

`  {
                    "name": "Media-TV",
                    "type": "tv",
                    "host": "192.168.0.4",
                    "allowResend": true,
                    "pingIPAddress": "192.168.0.11",
                    "pingFrequency": 30,
                    "pingIPAddressStateOnly": true,
                    "pingGrace": 60,
                    "data": {
                        "on": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "off": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "volume": {
                            "up": "260058000001289313121312131213121213121213121312133713371337133713371312133712371337133713121337131213121337131213121312133712131237133713121336140005440001284a13000c560001284913000d05",
                            "down": "260050000001289413121213121213121312131213121312133713371337133712371312133713371337133713371337121213121337131213121312131213121337133712131237130005440001264b13000d050000000000000000"
                        },
                        "remote": {
                            "select": "260050000001279513121213121213121312131212131213123812381238123812381213123812381212133713371213121312131213121312381213121312381238133712371337150005430001284913000d050000000000000000",
                            "arrowUp": "260050000001279413121213121312131213121312131212133712381238123813371213123812371312133712131238123812131213121312381213123713121312123812381337120005450001274a12000d050000000000000000",
                            "arrowDown": "260050000001279413121213121312131213121312131213123812381337123812371312133712381213121312131238121312131238121312371337133712131337123812131238120005450001274a13000d050000000000000000",
                            "arrowLeft": "260050000001279413121312121312131213121312131213123812381237133713371213123813371238131212381213121312131213121213121337131212381337123812381337120005450001274a13000d050000000000000000",
                            "arrowRight": "260050000001279413121213121313121213121312131213123812371337133712381312123813371337121312131238121312131212131312121337123813121238123812381238120005450001274a13000d050000000000000000",
                            "back": "260050000001279413121213121312131213121312121312133712381238123812381312123812381411123713121337121312131213121312381213123812131238123812371337130005440001284a13000d050000000000000000",
                            "exit": "260050000001279413121213121312131213121312121312133712381238123812381312123812381411123713121337121312131213121312381213123812131238123812371337130005440001284a13000d050000000000000000",
                            "playPause": "260098000001289c111513371337133811141338113a13371139133812381313121311151312133713381238133713391139111413381213133711141313111411151213121410151100055000012b9a131212391238103b13121337113a11391239113a1337131213131312131213371339131213371115131213121312131311391313121313131312131213131015100005510001294a13000d05",
                            "info": "260050000001289413121213131113121312131212131312123812381337133712381312123713371337123812381213123812131213121312131213121312371312123812381337120005450001274b13000d050000000000000000"
                        },
                        "inputs": [
                            {
                                "name": "DTV",
                                "type": "s_video",
                                "data": [
                                    {
                                        "data": "260050000001269312141213111412131213111312131213113912371238123812371213113912381237123812381213113812131114111411141213111311391213113911381238110005420001254b12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269412131213121312131213111311141213123812371238123812371213113714381212123812381213111411131213121312381113121312381238123712381238110005410001264b11000d050000000000000000"
                                    }
                                ]
                            },
                            {
                                "name": "AppleTV",
                                "type": "hdmi",
                                "data": "260050000001279512121336123812371312133712371336123813361237131212131213131311371238113812121411131211151212131213361312121313121312111313121312130005980001274914000d050000000000000000"
                            }
                        ]
                    }
                },`

**Comment by kiwi-cam** [comment]
Does the behaviour change if you have `"allowResend": false`? If so I'll have to look into that.

**Comment by sushenmathur** [comment]
@kiwi-cam 
No change.. I am  not sure if it was caused by the update of the plugin or the docker container as both happened at the same time and one has caused it. Since then i have tried to blow the old docker container and create a new and reinstalled the plugin.

**Comment by sushenmathur** [comment]
Question on the side would be if there is any way I an update the state using HTTP

**Comment by kiwi-cam** [comment]
I wonder if it’s net permissions in node within docker. Does this solution help: https://github.com/AlexanderBabel/homebridge-broadlink-rm/issues/70#issue-557219736

**Comment by sushenmathur** [comment]
@kiwi-cam 
Having no issue discovering the rmpro’s. Nevertheless tried to solution in that comment. Still no Luck

**Comment by djrams10** [comment]
Hello, I also have the problem, I don't even have the status information of the plugin in the logs. The accessories are present but the change of status is no longer made. The TV switches work perfectly well too.

It is only the status that is problematic.

At the start of homebridge I have a successful configuration, but nothing in after the QR code homekit

Thank you for your help

![1D4D5BF5-9302-4534-AB44-40D6236D57D1](https://user-images.githubusercontent.com/28505910/204081644-435e3531-3dee-4803-ae66-ed224412ad10.png)

![FDBA2614-217F-4048-B7D0-E2796B338F8F](https://user-images.githubusercontent.com/28505910/204081666-e2940da9-84cd-466b-9ddb-1ab6d18058ea.png)
