### ISSUE TITLE
Add humidityFilePath support to the Dehumidifier accessory

### ISSUE THREAD

**Issue by kiwi-cam** [kiwi-cam/homebridge-broadlink-rm#92]
Request comes from @CyberMrProper in #90

**Comment by masterfordev** [comment]
And maybe you can add a pseudo-device option for humidity too... like on temperature.

**Comment by CyberMrProper** [comment]
This is working well in the beta, thanks!!

**Comment by kiwi-cam** [comment]
Fixed in 4.3.6
