### ISSUE TITLE
Can no longer see my device. 

### ISSUE THREAD

**Issue by barns102** [kiwi-cam/homebridge-broadlink-rm#94]
@kiwi-cam 

Hi

Since upgrading to 4.3.4 I get the following error:
Broadlink RM] [ERROR] Lounge Samsung sendData (no device found at 192.xxx.x.xxx)

I have two devices, both on fixed ip addresses. I have the ‘host’ section in the config so it can determine which device to send the code from, all worked perfectly before the upgrade. But now for both devices it’s say no device found at that ip, despite confirming that both devices are on those ip’s. 

Please help!!

**Comment by masterfordev** [comment]
What version are that devices?

**Comment by barns102** [comment]
@masterfordev 

Firmware - V57
Plugin version - 1.5.4

I got this information directly from the Broadlink App.

**Comment by masterfordev** [comment]
I mean what version are your Broadlink RM (2,3,4?)

And please, share your config.

**Comment by barns102** [comment]
@masterfordev RM Mini 3’s

**Comment by kiwi-cam** [comment]
How far through the setup did you go in the Broadlink app? If you set them up completely the Homebridge won’t be able to connect - and you’ll see what you’re describing. You need to abort the setup when prompted for a room. Otherwise they register in the cloud and can’t be used locally.

**Comment by barns102** [comment]
@kiwi-cam    If that’s is the case (which is difficult to understand, as they were working perfectly prior to the update) how do you reverse it?

**Comment by masterfordev** [comment]
> If that’s is the case (which is difficult to understand, as they were working perfectly prior to the update) how do you reverse it?

Try reset the devices (broadlink rm) and add it again but abort the setup process when ask you select a room. If that dont work, so try go to back version:

`npm install -g homebridge-broadlink-rm-pro@version.you.want`

e.g:

`npm install -g homebridge-broadlink-rm-pro@4.3.3`

**Comment by kiwi-cam** [comment]
I know where I went wrong... missed updating one of the dependencies.

@barns102  Could you try updating again now?

**Comment by sanychonline** [comment]
Just checked:

`[10/29/2020, 9:30:41 PM] [Broadlink RM] [INFO] Discovered Manual RM Pro Device (2223) at 172.16.1.6 

[10/29/2020, 9:31:06 PM] [Broadlink RM] Air Conditioner2 sendHex (172.16.1.9) 2600920000012793171115131536163615131512161215121513153616121537151215131512161215121711151216121612163516361512161216121512161215361612153616121612153616121600028f1512151315121612151216121512161215131611151316111513151216361513161115131512161215121612151216121513151215131512151315121636151315000d05000000000000`

Works fine after dependencies fix

**Comment by barns102** [comment]
I still have the same problem and don’t have an option to update in HOOBS I’m running version 4.3.4. @kiwi-cam

**Comment by masterfordev** [comment]
> I still have the same problem and don’t have an option to update in HOOBS I’m running version 4.3.4. @kiwi-cam 

Just use this command:
`npm install -g homebridge-broadlink-rm-pro`

If you have previously installed, will install again.
