### ISSUE TITLE
Updating from previous version

### ISSUE THREAD

**Issue by Spanishu** [kiwi-cam/homebridge-broadlink-rm#95]
I am running right now the lprhodes version of this plugin on my homebridge (v 3.6.22)I had to do a manual tweak in order to support my Broadlink RM Mini 3 D (5f36). Works all good now. 

Questions:
- can I install this version of the plugin over the current existing version? How?
- Will my config.json need adaption?
exerp here
`"platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "accessories": [
                {
                    "name": "Learn IR",
                    "host": "192.168.1.155",
                    "mac": "78:0f:77:87:f0:b8",
                    "type": "learn-code"
                },
                {
                    "name": "Aire Despacho",
                    "type": "air-conditioner",
                    "host": "xxx.xxx.xxx.xxx",
                    "mac": "78:0f:77:87:f0:b8",
                    "turnOnWhenOff": false,
                    "ignoreTemperatureWhenOff": true,
                    "replaceAutoMode": "cool",
                    "pseudoDeviceTemperature": 27,
                    "defaultCoolTemperature": 26,
                    "temperatureUpdateFrequency": 300,
                    "minTemperature": 10,
                    "maxTemperature": 28,
                    "disableLogs": true,
                    "data": {
                        "on": "26004c0271380e290d2a0e0e0e0d0d0f0d2a0d0e0e0e0e290e290e0d0f280e0e0e0e0e290e290e0d0f280e290e0e0e0e0e290d0e0f0d0f280e0d100c0f0c0e0e0e0d0f0d0e0d0f0d0e0d0f0d0e0d0e0e0e0d0f0d0e0d0f0d0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f0d0e0d0f0d0e290e290e0d0f0d0e0e0e290d0e0e290e0e0e0d0f0d0e0d0e0e0e0d0e290e290e0e0e290e290e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e290e0e0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d0f280d0f0e290e0e0e290e0001aa71380e290e290e0e0e0d0e0e0e290e0d0f0d0e290e290e0e0e290e0d0e0e0e290e290e0d0f280e2a0e0d0e0e0e290d0e0f0d0e290e0d0f0d0e0d0f0d0e0d0f0d0e0d0f0d0e0d100c100b100c0f0c100c0f0c0e0e0d0e0e0e0d0e0e0e0d0e0d0f0d0e0d0f0d0e0d0f0d2a0f28100c0f0c0e0e0d2a100c0c2a100c100b0d0f0d0e0d0f100c0c2b0f28100b10271027100c0f0d0f0c0f0c100c100b100c0f0d0f27100c100c0f0c0f0d0f0c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0c100c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0c100c0f0d0f0c0f0d0f0c0f0c100c100b100c100c0f0c100b100c0f0d0f0c0f0d0f0c0f0c100c0f0c100c100b100c0f0d0f0c100b100c0f0d0f0c0f0c10280f0c1027100c0f2810000d0500000000000000000000",
                        "off": "26004c0272360f280f290f0c0f0c100c0f280f0d0f0c0f280f28100c0f280f0c100c0f280f280f0d0f280f280f0c100c0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f290f0c0f0c100c0f0c100c0f280f280f0d0f0c0f0d0f0c0f0d0f280f280f0c10280f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f2810280f280f280f0c0f28100c0f280f0001a973360f2810280f0c0f0d0f0c0f280f0d0f0c0f280f28100c0f280f0d0f0c0f280f280f0d0f280f280f0d0f0c0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f2810280f0c0f0d0f0c0f0d0f0c0f280f280f0d0f0c0f0d0f0c0f0d0f280f280f0d0f280f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f280f0c0f0d0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c0f0d0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c10280f280f280f280f0c0f290f0c0f280f000d0500000000000000000000",
                        "temperature21": {
                            "pseudo-mode": "cool",
                            "data": "2600bc0170390e2b0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d0f0e2b0d0f0e2b0d2b0e0e0e2b0d2c0d2b0d2c0d2b0e0e0e0f0d2b0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d2b0e2b0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d2b0e0e0e0f0d0f0d0f0e0e0e0f0d0003cc71390d2c0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d2c0d0f0d2b0e2b0d0f0e2b0d2b0e2b0d2b0e2b0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d2c0d2b0e0e0e0f0d0f0d2b0e0f0d2b0e0f0d2b0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d0f0e2b0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e2b0d2b0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e2b0d0f0e2b0d2b0e2b0d0f0e2b0d2b0e000d0500000000000000000000"
                        },`

- I would like to add as well the heat mode to it and will have overlapping temperatures. Any chance to get a small indication on how to best tackle that?
Thanks best!

**Comment by kiwi-cam** [comment]
Hi @Spanishu. This version is built on the @lprhodes and @AlexanderBabel forks - trying to bring the best of all the features together. With this in mind, I've kept the same basic config.json structure. The options have been expanded but nothing removed so the exact same config will work the same.

To switch you need to remove to old one, and install the new one:
```
npm uninstall -g homebridge-broadlink-rm
npm install -g homebridge-broadlink-rm-pro
```
You can reverse those commands to go back if you need to.

Getting overlapping temperatues in the modes is a bit of work to learn all the codes. You really want to setup heatXX and coolXX codes in your config.json to get all temperatures and modes working.

**Comment by Spanishu** [comment]
Hi @kiwi-cam thanks a lot for the guide. Upgrade worked like a charm. 
On the coolXX and heatXX just to make sure I get this right or example for the Right now I have in the config.json 

`"temperature21": {
"pseudo-mode": "cool",
"data": "2600bc0170390e2b0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d0f0e2b0d0f0e2b0d2b0e0e0e2b0d2c0d2b0d2c0d2b0e0e0e0f0d2b0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d2b0e2b0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d2b0e0e0e0f0d0f0d0f0e0e0e0f0d0003cc71390d2c0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d2c0d0f0d2b0e2b0d0f0e2b0d2b0e2b0d2b0e2b0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d2c0d2b0e0e0e0f0d0f0d2b0e0f0d2b0e0f0d2b0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d0f0e2b0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e2b0d2b0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e2b0d0f0e2b0d2b0e2b0d0f0e2b0d2b0e000d0500000000000000000000"
                },`
I would replace if I understand your right Temperature21 with Cool21 and eliminate the pseudo-mode line? Thanks for the help and patience!

**Comment by kiwi-cam** [comment]
Check out the sample here: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/fa0c0ba2f600435299f09228237010232dacede6/config-sample.json#L154-L171

Basically you'd change (or leave that and add these as well) to:
`"cool21": { 
  "data": "2600bc0170390e2b0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d0f0e2b0d0f0e2b0d2b0e0e0e2b0d2c0d2b0d2c0d2b0e0e0e0f0d2b0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d2b0e2b0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d2b0e0e0e0f0d0f0d0f0e0e0e0f0d0003cc71390d2c0d0f0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d2c0d0f0d2b0e2b0d0f0e2b0d2b0e2b0d2b0e2b0d0f0e0e0e2b0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d2b0e0f0d0f0d0f0d2c0d2b0e0e0e0f0d0f0d2b0e0f0d2b0e0f0d2b0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d2b0e2b0d0f0e2b0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e2b0d2b0e0e0e0f0d0f0d0f0e0f0d0f0d0f0d0f0e0f0d0f0d0f0e0e0e0f0d0f0d0f0e0e0e2b0d0f0e2b0d2b0e2b0d0f0e2b0d2b0e000d0500000000000000000000" 
},`

**Comment by Spanishu** [comment]
Hi, 
many thanks. had to do some minor adoptions to the upper part of the config (replaceautomode out) but works like a charm. Thanks for the help glad to have this plugin and knowing there is support!
