### ISSUE TITLE
RM3 Devices does not work (not visible) after update to 4.3.4

### ISSUE THREAD

**Issue by sanychonline** [kiwi-cam/homebridge-broadlink-rm#96]
Devices does not respond. Plugin can't find RM3 Pro or RM3 Mini and work with them after update to 4.3.4
After switching back to 4.3.4-beta - issue was resolved.

**Comment by kiwi-cam** [comment]
Duplicate of #94 

I've just published a new version of one of the dependencies which should resolve this. Are you able to update the confirm for me?

**Comment by sanychonline** [comment]
Works fine as of now
