### ISSUE TITLE
swing toggle disappear in fan... 

### ISSUE THREAD

**Issue by beliy82** [kiwi-cam/homebridge-broadlink-rm#98]
swing toggle disappear in fan... used to work great, but now the button not shown in the fan
he was where i draw blue circle 
![image](https://user-images.githubusercontent.com/71979517/97671458-fc926f00-1a90-11eb-8eef-c2e22d9cd18f.png)

**Comment by masterfordev** [comment]
I think in ios 14 dont have the button for turn on the fan. But you can set the swing button. Read the documentation: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/README.md

**Comment by masterfordev** [comment]
You have installed this plugin or are you using the original version of @lprhodes ?

**Comment by beliy82** [comment]
homebridge-broadlink-rm-pro v4.3.4 
that what im using.... its worked, and been there a button, yesterday he disappeared

**Comment by masterfordev** [comment]
> homebridge-broadlink-rm-pro v4.3.4 
> 
> that what im using.... its worked, and been there a button, yesterday he disappeared 

Its true 🤔 my fan dont have the button 😥
![Screen](https://user-images.githubusercontent.com/29960705/97767720-38522680-1adb-11eb-847c-0405297b2f00.png)

**Comment by masterfordev** [comment]
Any idea why @kiwi-cam ?

**Comment by kiwi-cam** [comment]
I'm not sure why this has happened but I think I've got it going in a new BETA. Care to try out homebridge-broadlink-rm-pro@4.3.5-beta.1 ?

Something odd going on with the config variable scopes. I'll investigate at some stage.

**Comment by masterfordev** [comment]
In the new beta its working again kiwi-cam 👍

![Screen](https://user-images.githubusercontent.com/29960705/97775250-758ad880-1b1c-11eb-9c6a-b76ec0fd1040.png)

I hope this will also solve the problem I have with homepod, sometimes it says that the devices do not respond. But on my iPhone it works without problem, even in the app home appear working properly.

**Comment by masterfordev** [comment]
I forgot. The button for rotation direction doesn't appear.

**Comment by kiwi-cam** [comment]
Good point. The Rotation Direction probably has the same thing happening. I'll try to take a look tomorrow.

**Comment by kiwi-cam** [comment]
I've just pushed homebridge-broadlink-rm-pro@4.3.5-beta.2. I've fixed the Characteristics (Fanv2 uses Active instead of On) and tidied up showRotationDirection.

One question, should we be able to see both SwingSpeed and RotatonDirection? Each option works independently but setting showRotationDirection (or leaving default of true) means that Swing Speed doesn't show up.  Not sure if this is a HomeKit limitation.

**Comment by masterfordev** [comment]
I dont know. I dont have an "original" fan homekit 🙁
![Screen](https://user-images.githubusercontent.com/29960705/97787728-3fc40f00-1b71-11eb-8651-43dd5c252a06.png)

![image](https://user-images.githubusercontent.com/29960705/97787735-46eb1d00-1b71-11eb-9ef0-26a4595fa241.jpeg)

We should swipe to see the option to activate swing mode. @faisalthe01 you dont have and original fan compatible with homekit?

**Comment by Faisalthe01** [comment]
Hey, Nah don’t have it either. But see the screenshot from Homebridge dyson fan accessory, they have the SwingMode and RotationSpeed only. Maybe RotationDirection takes the SwingMode at bottom.

![66A96CE1-309B-42BA-B1D3-91C0C29B4784](https://user-images.githubusercontent.com/62862684/97792772-e2929100-1c36-11eb-96c5-7357db24ec58.jpeg)

Sorry @masterfordev, couldn’t be much help.

**Comment by beliy82** [comment]
nice, thanks! where can i find the beta installation?

**Comment by masterfordev** [comment]
> Hey, Nah don’t have it either. But see the screenshot from Homebridge dyson fan accessory, they have the SwingMode and RotationSpeed only. Maybe RotationDirection takes the SwingMode at bottom.
> 
> 
> 
> ![66A96CE1-309B-42BA-B1D3-91C0C29B4784](https://user-images.githubusercontent.com/62862684/97792772-e2929100-1c36-11eb-96c5-7357db24ec58.jpeg)
> 
> 
> 
> Sorry @masterfordev, couldn’t be much help.

No worries. That was help. 

@beliy82 use:

`npm install -g homebridge-broadlink-rm-pro@beta`

**Comment by kiwi-cam** [comment]
I've just pushed 4.3.5 with this bug fix.
